### ISSUE TITLE
Method Refactoring

### ISSUE THREAD

**Issue by gspeiliu** [tsantalis/RefactoringMiner#101]
Hi, I want to make sure that the method between two different commits is refactoring or not and I do not care about the refactoring details. Does the API has been provided? How can I implement that? Thank you. Nice work. 👍

**Comment by tsantalis** [comment]
I cannot understand the question. Do you mean you need the methods between two commits that were refactored with any kind of refactoring?

**Comment by gspeiliu** [comment]
Thanks for your quick response. Yes, part of. For example, there is one method called method_sample in commit1. The method_sample still exists in the next commit say commit2. If the method_sample's implementations are different between commit1 and commit2. I want to make sure that the implementation of method_sample in commit2 is actually refactoring or not. Can we achieve this requirement? Does it mean that the granularity is method rather than class? Thank you.

**Comment by tsantalis** [comment]
I think what you need is similar to issue https://github.com/tsantalis/RefactoringMiner/issues/99
You can get for every pair of methods between two commits, the statements that are common, and any deleted/added statements.
With this information you can infer if a method was modified or not.

**Comment by gspeiliu** [comment]
Thanks for your reply. I read your answer in issue #99 and tried to write code to complete my project. However, I have another concern.
For example, the method update diff result is as follow:
public int getDataStatus()
@@ -1,3 +1,3 @@
 {
-    return dataStatus;
+    return mDataStatus;
 }
The refactoring is change attribute dateStatus to mDataStatus.
However, when I call the method mapper.getRefactorings(), the number of refactoring of this method call is ZERO. Am I right? Thank you.

**Comment by tsantalis** [comment]
Attribute-related refactorings are class-level refactorings, and sometimes even project-level refactorings (for public fields).
You can call method `getAttributeReferences()` to get a set of `AbstractCodeMapping` objects, which correspond to the pairs of statements in which the refactored attribute is referenced.
