### ISSUE TITLE
Enum constant rename detection

### ISSUE THREAD

**Issue by bbrockbernd** [tsantalis/RefactoringMiner#104]
Hi @tsantalis,

RefactoringMiner doesn't seem to detect a rename of enum constants, but does detect renamed methods declared inside an enum body. Has this been a design choice? If so, why? And if not, are you planning on implementing this in the future?

Thanks!

**Comment by tsantalis** [comment]
Hi @bbrockbernd 
Could you please share a commit with such enum constant renames?
I will have to check if the enum constants are processed.

**Comment by bbrockbernd** [comment]
Hi @tsantalis 
An example of this rename is here: https://github.com/ioanasv/example-refactorings/commit/3259c5f90becad8bc8fee3f548ad68d23233cf6e

![image](https://user-images.githubusercontent.com/47760450/90777678-09aa1980-e2fc-11ea-87a5-9bebedc408f1.png)

**Comment by tsantalis** [comment]
Found some case studies from the refactoring oracle:
https://github.com/neo4j/neo4j/commit/74d2cc420e5590ba3bc0ffcc15b30b76a9cbef0b#diff-c64346425226d451a07f4f70f8ebd3eeR202
https://github.com/apache/hive/commit/92e98858e742bbb669ccbf790a71a618c581df21#diff-f6146aa9707218763ee51e8292721f37R35
https://github.com/facebook/facebook-android-sdk/commit/19d1936c3b07d97d88646aeae30de747715e3248#diff-cb12e10c60c53896f490680074ef74b5R31
