### ISSUE TITLE
./gradlew distZip error when trying to run RefactoringMiner from command line

### ISSUE THREAD

**Issue by AyanoIkegami** [tsantalis/RefactoringMiner#108]
Hi, 
I'm trying to run RefactoringMiner from command line using `./gradle distZip` , but I keepon getting an error.

`Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`
 
I tried this blog post, `gradle wrap`  but did not work. (Sorry, it is in Japanese...)
https://qiita.com/pg_mot/items/bf02f4f37382696f3898 

`FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/ext-hdd/vuln_refactor:2020:ayano-ik/analysis_code/RefactoringMiner/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating root project 'RefactoringMiner'.
> Could not find method java() for arguments [build_c2eq0ntex0s4nv3uhfitwtay4$_run_closure4@5edacf20] on root project 'RefactoringMiner'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.863 secs`

I'm currentlty running 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

thank you in advance.

Ayano & @raux

**Comment by tsantalis** [comment]
> tsantalis@tsantalis-XPS-13-9380:~/eclipse-workspace/RefactoringMiner$ ./gradlew distZip
> Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> 
> Task :compileJava
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD SUCCESSFUL in 9s
> 4 actionable tasks: 4 executed
> tsantalis@tsantalis-XPS-13-9380:~/eclipse-workspace/RefactoringMiner$ 

I just run it without a problem. Make sure you have gradle version 6 installed and the command is `./gradlew distZip`
The problem seems to be that it cannot find the gradle wrapper.
