### ISSUE TITLE
Missed Inline Method refactoring

### ISSUE THREAD

**Issue by onewhl** [tsantalis/RefactoringMiner#109]
Hello, @tsantalis!

I tested RefactoringMiner and noticed a missed Inline Method refactoring:

Code before a commit:
```
   public boolean isAgeMoreThanZero() {
        return age > 0;
    }

    public boolean isAgeValid() {
        return isAgeMoreThanZero() && age < 110;
    }
```

Code after the commit:
```
  public boolean isAgeValid() {
        return age > 0 && age < 110;
    }
```
And ` isAgeMoreThanZero()` was removed in the same commit.

**Comment by tsantalis** [comment]
Thank you @onewhl 
This is most probably due to not considering infix expressions for replacements.
I noticed the same problem in Extract Variable refactorings.
https://github.com/ioanasv/example-refactorings/commit/e0315579240f3f2f1544829db6d91f9e510bf2f9
I will have a look at this.

**Comment by tsantalis** [comment]
@onewhl Do you have this Inline Method in a commit to test it?
