### ISSUE TITLE
Project not able to build on mac.

### ISSUE THREAD

**Issue by sharmaankush8993** [tsantalis/RefactoringMiner#11]
I have downloaded this project on my mac and trying to build it using command ./gradlew distzip. But it is not building up completely and giving error 

`./gradlew distZip
:compileJava
Download https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/4.1.0.201509280440-r/org.eclipse.jgit-4.1.0.201509280440-r.jar
Download https://repo1.maven.org/maven2/com/jcabi/jcabi-github/0.17/jcabi-github-0.17.jar
Download https://repo1.maven.org/maven2/org/hibernate/hibernate-entitymanager/4.2.6.Final/hibernate-entitymanager-4.2.6.Final.jar
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.7/slf4j-log4j12-1.7.7.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4.jar
Download https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.53/jsch-0.1.53.jar
Download https://repo1.maven.org/maven2/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
Download https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.annotation/1.1.0/org.eclipse.jdt.annotation-1.1.0.jar
Download https://repo1.maven.org/maven2/com/jcabi/jcabi-aspects/0.18/jcabi-aspects-0.18.jar
Download https://repo1.maven.org/maven2/com/jcabi/jcabi-immutable/1.3/jcabi-immutable-1.3.jar
Download https://repo1.maven.org/maven2/com/jcabi/jcabi-xml/0.12.1/jcabi-xml-0.12.1.jar
Download https://repo1.maven.org/maven2/com/jcabi/jcabi-http/1.8.3/jcabi-http-1.8.3.jar
Download https://repo1.maven.org/maven2/com/jcabi/incubator/xembly/0.17/xembly-0.17.jar
Download https://repo1.maven.org/maven2/com/jcabi/jcabi-manifests/1.0.4/jcabi-manifests-1.0.4.jar
Download https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
Download https://repo1.maven.org/maven2/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
Download https://repo1.maven.org/maven2/org/aspectj/aspectjrt/1.8.2/aspectjrt-1.8.2.jar
Download https://repo1.maven.org/maven2/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar
Download https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.18.1/jersey-client-1.18.1.jar
Download https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.18.1/jersey-core-1.18.1.jar
Download https://repo1.maven.org/maven2/org/jboss/logging/jboss-logging/3.1.0.GA/jboss-logging-3.1.0.GA.jar
Download https://repo1.maven.org/maven2/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar
Download https://repo1.maven.org/maven2/org/jboss/spec/javax/transaction/jboss-transaction-api_1.1_spec/1.0.1.Final/jboss-transaction-api_1.1_spec-1.0.1.Final.jar
Download https://repo1.maven.org/maven2/org/hibernate/javax/persistence/hibernate-jpa-2.0-api/1.0.1.Final/hibernate-jpa-2.0-api-1.0.1.Final.jar
Download https://repo1.maven.org/maven2/org/hibernate/hibernate-core/4.2.6.Final/hibernate-core-4.2.6.Final.jar
Download https://repo1.maven.org/maven2/org/hibernate/common/hibernate-commons-annotations/4.0.2.Final/hibernate-commons-annotations-4.0.2.Final.jar
Download https://repo1.maven.org/maven2/org/javassist/javassist/3.15.0-GA/javassist-3.15.0-GA.jar
Download https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar
Download https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
Download https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
Download https://repo1.maven.org/maven2/com/jcabi/jcabi-log/0.15/jcabi-log-0.15.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:11: error: package org.refactoringminer.utils does not exist
import org.refactoringminer.utils.RefactoringRelationship;
                                 ^
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:45: error: cannot find symbol
    public List<RefactoringRelationship> parse(String refactoringDescription) {
                ^
  symbol:   class RefactoringRelationship
  location: class RefactoringDescriptionParser
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:46: error: cannot find symbol
        List<RefactoringRelationship> list = new ArrayList<>();
             ^
  symbol:   class RefactoringRelationship
  location: class RefactoringDescriptionParser
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:46: error: unexpected type
        List<RefactoringRelationship> list = new ArrayList<>();
                                                          ^
  required: class
  found:    <E>ArrayList<E>
  where E is a type-variable:
    E extends Object declared in class ArrayList
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:54: error: cannot find symbol
                        list.add(new RefactoringRelationship(parser.type, entityBefore.toString(), entityAfter.toString()));
                                     ^
  symbol:   class RefactoringRelationship
  location: class RefactoringDescriptionParser
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:80: error: local variable c is accessed from within inner class; needs to be declared final
                String key = normalizeType(matcher.group(c)) + "#" + normalizeAttribute(matcher.group(a));
                                                         ^
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:80: error: local variable a is accessed from within inner class; needs to be declared final
                String key = normalizeType(matcher.group(c)) + "#" + normalizeAttribute(matcher.group(a));
                                                                                                      ^
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:90: error: local variable c is accessed from within inner class; needs to be declared final
                String key = normalizeType(matcher.group(c));
                                                         ^
/Users/ankush/Personal/RefactoringMiner/src/org/refactoringminer/util/RefactoringDescriptionParser.java:100: error: local variable c is accessed from within inner class; needs to be declared final
                String typesString = matcher.group(c);
                                                   ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 1.284 secs`

**Comment by dmazinanian** [comment]
Thanks for reporting the problem. I got the same error.

The problem is, the package `org.refactoringminer.utils` is imported in `src/org/refactoringminer/util/RefactoringDescriptionParser.java`. This package in the `src-test` source folder, so we need to include it in the `build.gradle` file, in addition to the test source folders. As a consequence, we also need to have JUnit in the referenced libraries. I will commit the changes soon.
