### ISSUE TITLE
Always shows No Refactorings

### ISSUE THREAD

**Issue by s1mar** [tsantalis/RefactoringMiner#111]
I tried it from both the command line and the chrome extension. Both give 0 refactorings. The chrome extension says "No Refactorings" and the cmd line tool encounters a NullPointerException.

**Comment by tsantalis** [comment]
@s1mar Could you please report the stacktrace for the NullPointerException, and provide the repository you got the exception.
If the repository is private, the command line and chrome extension cannot analyze the commits.
