### ISSUE TITLE
Duplicate reports, one of them are false positive

### ISSUE THREAD

**Issue by boyang9602** [tsantalis/RefactoringMiner#112]
In commit https://github.com/apache/cassandra/commit/8704006bfa75a78cb904e35662e4c8bafc1f2330, I found there are 2 **Parameterize Variable** for the same variable being reported.   
38: Parameterize Variable fail : Throwable to accumulate : Throwable in method private replaceWithFinishedReaders(finished List<sstablereader>, accumulate Throwable) : Throwable in class org.apache.cassandra.io.sstable.SSTableRewriter  
39: Parameterize Variable fail : Throwable to  accumulate : Throwable in method protected doAbort(accumulate Throwable) : Throwable in class org.apache.cassandra.io.sstable.SSTableRewriter  
Seems 39 is correct but 38 is a false positive.

**Comment by tsantalis** [comment]
Thank you @boyang9602 
The method `private Throwable replaceWithFinishedReaders(List<SSTableReader> finished, Throwable accumulate)` is extracted from `public void abort()` and variable `fail` becomes parameter `accumulate` in renamed method `protected Throwable doAbort(Throwable accumulate)` and passed as an argument to method `replaceWithFinishedReaders()`
`accumulate = replaceWithFinishedReaders(Collections.<SSTableReader>emptyList(), accumulate);`

RefactoringMiner reports the parameterization of local variables even in methods extracted from the method originally declaring the parameterized variable.
As a result, 38 is not a false potive.
