### ISSUE TITLE
Missing a Change Variable Type Refactoring

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#113]
In [this](https://github.com/PhilJay/MPAndroidChart/commit/808a5b21f676638b5d09cc324fd8c048b240a3fa) commit at [line 652 of Chart.java](https://github.com/PhilJay/MPAndroidChart/commit/808a5b21f676638b5d09cc324fd8c048b240a3fa#diff-749ccb3904db1672bf00a3a8c40d59aac3cce1cd55afe8996e29d3171a11ac19L652), type of the variable is changed (Series[] values -> Entry[] values) , but this refactoring is not detected.

**Comment by tsantalis** [comment]
Maybe that's because it's an array type, but the replacement is on the element type. I will check it.

**Comment by jodavimehran** [comment]
Because these statements are completely different, they are not mapped, right?

Is that true to say that the first variable (Series[] values) is deleted and the second variable (Entry[] values) is added?

**Comment by tsantalis** [comment]
I will work on matching them. We could have a heuristic for class instance creations with different types but identical arguments.

**Comment by jodavimehran** [comment]
Ok, Thanks. By the way, the origin of almost all refactoring activity in this commit is a [rename class refactoring](https://github.com/PhilJay/MPAndroidChart/commit/808a5b21f676638b5d09cc324fd8c048b240a3fa#diff-4f1126c2ab2985cfc15405cb06f8974a32d577056cb473043c32cd1e70a80482L4). Maybe that would help match the statements.
