### ISSUE TITLE
Extract Method refactoring is not detected?

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#114]
**Summary:**
The input for RefactoringMiner was two versions of the below program, which contains the Extract Method refactoring. RefactoringMiner did not yield output.

Before Version
```java
Thread waitOnMonitorThread = new Thread(() -> {
			synchronized (monitor) {
				try {
					monitor.wait();
				}
				catch (InterruptedException ex) {
					Thread.currentThread().interrupt();
				}
			}
		}, "Waiting on monitor");
[...]

```

After Version
```java
Thread waitOnMonitorThread = new Thread(() -> {
			synchronized (monitor) extracted(monitor);
}, "Waiting on monitor");
[...]

private void extracted(Object monitor) {
		{
			try {
				monitor.wait();
			}
			catch (InterruptedException ex) {
				Thread.currentThread().interrupt();
			}
		}
	}
```

The refactoring was performed in this repository [osmarleandro/spring-boot](https://github.com/osmarleandro/spring-boot), by the selection of synchronized block from 62 to 69 lines of dumpThreadsAsText() method of ThreadDumpEndpointTests class. See the refactoring in [here](https://github.com/osmarleandro/spring-boot/commit/2de06b7c6e0a92bd8dad603b39b12c807a489ed2).

**Version:**
RefactoringMiner 2.0.2

**Steps to Reproduce:**
Run RefactoringMiner and pass as input [this commit](https://github.com/osmarleandro/spring-boot/commit/2de06b7c6e0a92bd8dad603b39b12c807a489ed2) of [osmarleandro/spring-boot](https://github.com/osmarleandro/spring-boot) GitHub repository.

**Actual results:**
RefactoringMiner does not report any refactoring.

**Expected results:**
A single Extract Method from synchronized block code in lines 62 to 69 of dumpThreadsAsText() method in ThreadDumpEndpointTests class.

**Comment by tsantalis** [comment]
Hi @osmarleandro 
I think the code after refactoring is not syntactically valid.
```java
synchronized (monitor) extracted(monitor);
```
A `synchronized` statement should have a Block AST node as a body according to the [Eclipse JDT documentation](https://help.eclipse.org/2020-09/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FSynchronizedStatement.html).
The proper syntax should be
```java
synchronized (monitor) {
    extracted(monitor);
}
```
The Eclipse JDT Parser, parsed the method until line [61](https://github.com/osmarleandro/spring-boot/commit/2de06b7c6e0a92bd8dad603b39b12c807a489ed2#diff-d039455f0089e77f3bd30293fae0c0a06491ab05fa81e0b88dc7f10a02a39d38R61) and then stopped.
Is it possible to make another commit with the same refactoring, but with the proper syntax?

**Comment by tsantalis** [comment]
I tested with the attached source files and the refactoring is properly detected.
**Extract Method** `private extracted(monitor Object) : void` extracted from `package dumpThreadsAsText() : void` in class `org.springframework.boot.actuate.management.ThreadDumpEndpointTests`
[dumpThreadsAsText.zip](https://github.com/tsantalis/RefactoringMiner/files/5647904/dumpThreadsAsText.zip)
