### ISSUE TITLE
LocationInfo of ExtractOperationRefactoring may not always producing accurate startOffset and length

### ISSUE THREAD

**Issue by diptopol** [tsantalis/RefactoringMiner#115]
LocationInfo of `sourceOperationAfterExtraction` may not always be producing accurate startOffset and length. I am providing a link to a project where I have reproduced the issue [https://github.com/diptopol/RefactoringMinerIssueReproduction](https://github.com/diptopol/RefactoringMinerIssueReproduction). The project which is investigated is [https://github.com/Guardsquare/proguard](https://github.com/Guardsquare/proguard) and the issue is found in below commits.

- 824e6abb1f524be726b1a207b7a2231aa9a4f95c
- 3fd802b3604e22f3d600cafab52e4491561583c8
- ec3d479d473c9d09d4278b1aa87bc943d40d4d10
- f63565a45b739f00a8518b234993337d22f54e27

**Comment by tsantalis** [comment]
[824e6abb1f524be726b1a207b7a2231aa9a4f95c](https://github.com/Guardsquare/proguard/commit/824e6abb1f524be726b1a207b7a2231aa9a4f95c#diff-d095763bbb4ff32ca3314b6cc926fa4066dcf604d079cbe6af1bc42747ffaa6aR89)
"filePath": "base/src/proguard/DataEntryReaderFactory.java",
"startLine": 89,
"endLine": 199,
"startColumn": 5,
"endColumn": 6,
"startOffset": 3300,
"endOffset": 8322

**Comment by tsantalis** [comment]
Further analysis revealed that the problem was due to encoding, giving wrong offsets to NodeFinder
