### ISSUE TITLE
The Extract Method refactoring is not detected?

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#119]
## Summary
The input for RefactoringMiner was two versions of the below program, which contains the Extract Method refactoring and the program still compile. RefactoringMiner did not yield output. The refactoring was performed in this repository osmarleandro/google-maps-services-java@8336ed8, by the selection of block from 92 to 93 lines of threadFactory() method of RateLimitExecutorService class.

#### Code example
Diff between the commit osmarleandro/google-maps-services-java@8336ed8 and their parent.
```diff
@@ -89,10 +89,15 @@ public class RateLimitExecutorService implements ExecutorService, Runnable {
     return new ThreadFactory() {
       @Override
       public Thread newThread(Runnable runnable) {
-        Thread result = new Thread(runnable, name);
-        result.setDaemon(daemon);
+        Thread result = extracted(name, daemon, runnable);
         return result;
       }
+
+       private Thread extracted(final String name, final boolean daemon, Runnable runnable) {
+               Thread result = new Thread(runnable, name);
+        result.setDaemon(daemon);
+               return result;
+       }
     };
   }
```

### Environment details
RefactoringMiner 2.0.2

## Steps to reproduce
1. Run RefactoringMiner and pass as input the commit osmarleandro/google-maps-services-java@8336ed8.

### Actual results
RefactoringMiner does not report any refactoring.

### Expected results
A single Extract Method from synchronized block code in threadFactory() method of RateLimitExecutorService class.

**Comment by tsantalis** [comment]
The fix supports the detection of extracted code from an anonymous class declaration to the parent type declaration, but not the detection of extracted code directly to the body of the anonymous class declaration, as shown in the example.
**Extract Method** `private extracted(name String, daemon boolean, runnable Runnable) : Thread` extracted from `private threadFactory(name String, daemon boolean) : ThreadFactory` in class `com.google.maps.internal.RateLimitExecutorService`
This modified code is available in [threadFactory.zip](https://github.com/tsantalis/RefactoringMiner/files/5720390/threadFactory.zip)
