### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/RefactoringMiner#12]
The method UMLOperationBodyMapper#performReplacement() throws a StringIndexOutOfBoundsException on the following case:

Project: [Ribbon](https://github.com/Netflix/ribbon)
Commit: [8cb17a20d16daa322ef59cf9da0e36394bd644d4](https://github.com/Netflix/ribbon/commit/8cb17a20d16daa322ef59cf9da0e36394bd644d4)

**Comment by tsantalis** [comment]
Unable to replicate. The process finished without any problem.
at https://github.com/Netflix/ribbon/commit/8cb17a20d16daa322ef59cf9da0e36394bd644d4
Inline Method private obtainServersViaEureka1() : List inlined to private obtainServersViaDiscovery() : List in class com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
