### ISSUE TITLE
Is it repeated refactorings? What about Rename Variable?

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#120]
## Summary
The input for RefactoringMiner was two versions of the below program, which it was applied a single Extract Method refactoring. The refactoring was applied in this repository osmarleandro/google-maps-services-java@48915a5, by the selection of 194 to 195 lines in threadFactory() method of RateLimitExecutorService class.

#### Code example
Diff between the commit osmarleandro/google-maps-services-java@48915a5 and their parent.
```diff
@@ -191,18 +191,21 @@ public class GeoApiContextTest {
   }
 
   private MockResponse createMockBadResponse() {
-    MockResponse response = new MockResponse();
-    response.setStatus("HTTP/1.1 500 Internal server error");
+    MockResponse response = extracted();
     response.setBody("Uh-oh. Server Error.");
 
     return response;
   }
 
+private MockResponse extracted() {
+       MockResponse response = new MockResponse();
+    response.setStatus("HTTP/1.1 500 Internal server error");
+       return response;
+}
+
   @Test(expected = IOException.class)
   public void testRetryCanBeDisabled() throws Exception {
-    // Set up 2 mock responses, an error that shouldn't be retried and a success
-    MockResponse errorResponse = new MockResponse();
-    errorResponse.setStatus("HTTP/1.1 500 Internal server error");
+    MockResponse errorResponse = extracted();
     errorResponse.setBody("Uh-oh. Server Error.");
     server.enqueue(errorResponse);
 
@@ -223,8 +226,7 @@ public class GeoApiContextTest {
 
   @Test
   public void testRetryEventuallyReturnsTheRightException() throws Exception {
-    MockResponse errorResponse = new MockResponse();
-    errorResponse.setStatus("HTTP/1.1 500 Internal server error");
+    MockResponse errorResponse = extracted();
     errorResponse.setBody("Uh-oh. Server Error.");

```

### Environment details
RefactoringMiner 2.0.2

## Steps to reproduce
1. Run RefactoringMiner and pass as input the commit osmarleandro/google-maps-services-java@48915a5.

### Actual results
RefactoringMiner yields the following output:

* Extract Method	private extracted() : MockResponse extracted from private createMockBadResponse() : MockResponse in class com.google.maps.GeoApiContextTest;
* Extract Method	private extracted() : MockResponse extracted from public testRetryCanBeDisabled() : void in class com.google.maps.GeoApiContextTest;
* Rename Variable	errorResponse : MockResponse to response : MockResponse in method private extracted() : MockResponse in class com.google.maps.GeoApiContextTest;
* Rename Variable	errorResponse : MockResponse to response : MockResponse in method private extracted() : MockResponse in class com.google.maps.GeoApiContextTest;
* Extract Method	private extracted() : MockResponse extracted from public testRetryEventuallyReturnsTheRightException() : void in class com.google.maps.GeoApiContextTest.

### Expected results
A single Extract Method from block code in createMockBadResponse() method of GeoApiContextTest class.

**Comment by tsantalis** [comment]
Hi @osmarleandro I would highly recommend to use our [Chrome extension](https://chrome.google.com/webstore/detail/refactoring-aware-commit/lnloiaibmonmmpnfibfjjlfcddoppmgd?hl=en) to visualize the refactorings in a commit directly in GitHub.
In this commit, we can see that code duplicated in three different methods has been extracted in a single method. This is the reason 3 `Extract Method` instances are reported.
In addition, the variables `errorResponse` in lines 204 and 226 are renamed to `response` in the extracted method.
RefactoringMiner 2.0 (and newer versions) reports nested refactorings, i.e., refactorings taking place on refactored code, such the extracted method.
![Screenshot from 2020-12-16 20-15-49](https://user-images.githubusercontent.com/1483516/102425702-da6e9500-3fdb-11eb-8e09-3dc732edc674.png)
