### ISSUE TITLE
Is Extract Variable refactoring a replication?

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#121]
## Summary
The input for RefactoringMiner was osmarleandro/google-maps-services-java@9d23ddb, which has applied a single Inline Method refactoring. The refactoring was applied by the inline of locationBias() method of FindPlaceFromTextRequest class in their references.

#### Code example
Diff between the commit and their parent is osmarleandro/google-maps-services-java@9d23ddb.

### Environment details
RefactoringMiner 2.0.2

## Steps to reproduce
1. Run RefactoringMiner and pass as input the commit osmarleandro/google-maps-services-java@9d23ddb.

### Actual results
RefactoringMiner yields the following output:

* Extract Variable	locationBias : LocationBias in method public testFindPlaceFromText() : void from class com.google.maps.PlacesApiTest;
* Extract Variable	locationBias : LocationBias in method public testFindPlaceFromTextPoint() : void from class com.google.maps.PlacesApiTest;
* Extract Variable	locationBias : LocationBias in method public testFindPlaceFromTextCircular() : void from class com.google.maps.PlacesApiTest;
* Extract Variable	locationBias : LocationBias in method public testFindPlaceFromTextRectangular() : void from class com.google.maps.PlacesApiTest.

### Expected results
A single Inline Method from block code in locationBias() method of FindPlaceFromTextRequest class.

**Comment by tsantalis** [comment]
**Move And Inline Method** `public locationBias(locationBias LocationBias) : FindPlaceFromTextRequest` moved from class `com.google.maps.FindPlaceFromTextRequest` to class `com.google.maps.PlacesApiTest` & inlined to `public testFindPlaceFromTextPoint() : void`
**Move And Inline Method** `public locationBias(locationBias LocationBias) : FindPlaceFromTextRequest` moved from class `com.google.maps.FindPlaceFromTextRequest` to class `com.google.maps.PlacesApiTest` & inlined to `public testFindPlaceFromTextRectangular() : void`
**Move And Inline Method** `public locationBias(locationBias LocationBias) : FindPlaceFromTextRequest` moved from class `com.google.maps.FindPlaceFromTextRequest` to class `com.google.maps.PlacesApiTest` & inlined to `public testFindPlaceFromTextCircular() : void`
**Move And Inline Method** `public locationBias(locationBias LocationBias) : FindPlaceFromTextRequest` moved from class `com.google.maps.FindPlaceFromTextRequest` to class `com.google.maps.PlacesApiTest` & inlined to `public testFindPlaceFromText() : void`

**Comment by tsantalis** [comment]
The fix will be released in version 2.0.3
