### ISSUE TITLE
Applying the Inline Method refactoring

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#122]
## Summary
The input for RefactoringMiner was osmarleandro/google-maps-services-java@643d5c1, which has applied a single Inline Method refactoring. The refactoring was applied by the inline of getOptimizationWaypoints() method of DirectionsApiTest class in their references. The variable inside of the inlined method was renamed because it has the same name as the other variable in the same block code.

#### Code example
Diff between the commit and their parent is osmarleandro/google-maps-services-java@643d5c1.

### Environment details
RefactoringMiner 2.0.2

## Steps to reproduce
1. Run RefactoringMiner and pass as input the commit osmarleandro/google-maps-services-java@643d5c1.

### Actual results
RefactoringMiner yields the following output:

* Inline Method	private getOptimizationWaypoints() : List<LatLng> inlined to public testOptimizeWaypointsBeforeWaypoints() : void in class com.google.maps.DirectionsApiTest;
* Rename Variable	waypoints : List<LatLng> to waypoints1 : List<LatLng> in method public testOptimizeWaypointsBeforeWaypoints() : void in class com.google.maps.DirectionsApiTest;
* Inline Method	private getOptimizationWaypoints() : List<LatLng> inlined to public testOptimizeWaypointsAfterWaypoints() : void in class com.google.maps.DirectionsApiTest;
* Rename Variable	waypoints : List<LatLng> to waypoints1 : List<LatLng> in method public testOptimizeWaypointsAfterWaypoints() : void in class com.google.maps.DirectionsApiTest.

### Expected results
A single Inline Method from block code in getOptimizationWaypoints() method of DirectionsApiTest class.

**Comment by tsantalis** [comment]
Again here method `getOptimizationWaypoints()` was inlined in two different methods, and this is the reason RefactoringMiner reports 2 `Inline Method` instances. There is no other way to show that the method has been inlined in two places.
Perhaps, there could be a description:
`private getOptimizationWaypoints() : List` inlined to `public testOptimizeWaypointsBeforeWaypoints() : void` and `public testOptimizeWaypointsAfterWaypoints() : void` in class `com.google.maps.DirectionsApiTest`
but this is clearly a matter of taste/preference. Indeed, there is one `Inline Method` refactoring triggered by the developer, but we decided to show multiple instances, if the method is inlined in multiple places.

![Screenshot from 2020-12-16 20-25-29](https://user-images.githubusercontent.com/1483516/102426296-10f8df80-3fdd-11eb-987c-c9d371e6b10a.png)
