### ISSUE TITLE
Move Method refactoring applied to Nested Classes

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#133]
## Summary

I applied a Move Method refactoring to move a method to a nested class in osmarleandro/spring-boot@21f4ef7 and RefactoringMiner detects it. But, I applied the same operation to osmarleandro/spring-boot@93a0c10 but RefactoringMiner yields an empty set of refactoring.

As seen in the code example below, there is a method with the same name but a different signature in the same class. This can affect the detection of the Move Method instance (osmarleandro/spring-boot@93a0c10) from RefactoringMiner? If not, why the instance was not detected?

#### Code example
Diff between the commit osmarleandro/spring-boot@93a0c10 and their parent.
```diff
@@ -71,20 +70,8 @@ public class ElasticsearchRestHealthIndicator extends AbstractHealthIndicator {
	      @Override
	      protected void doHealthCheck(Health.Builder builder) throws Exception {
	                      [...]
                        return;
                }
                try (InputStream inputStream = response.getEntity().getContent()) {
-                       doHealthCheck(builder, StreamUtils.copyToString(inputStream, StandardCharsets.UTF_8));
+                       builder.doHealthCheck(this, StreamUtils.copyToString(inputStream, StandardCharsets.UTF_8));
                }
        }
 
-       private void doHealthCheck(Health.Builder builder, String json) {
-               Map<String, Object> response = this.jsonParser.parseMap(json);
-               String status = (String) response.get("status");
-               if (RED_STATUS.equals(status)) {
-                       builder.outOfService();
-               }
-               else {
-                       builder.up();
-               }
-               builder.withDetails(response);
-       }
-

@@ -329,6 +330,18 @@ public final class Health extends HealthComponent {
                        return new Health(this);
                }
 
+               public void doHealthCheck(ElasticsearchRestHealthIndicator elasticsearchRestHealthIndicator, String json) {
+                       Map<String, Object> response = elasticsearchRestHealthIndicator.jsonParser.parseMap(json);
+                       String status = (String) response.get("status");
+                       if (ElasticsearchRestHealthIndicator.RED_STATUS.equals(status)) {
+                               outOfService();
+                       }
+                       else {
+                               up();
+                       }
+                       withDetails(response);
+               }
+
```

### Environment details
RefactoringMiner 2.0.2

## Steps to reproduce
1. Run RefactoringMiner and pass as input the commit osmarleandro/spring-boot@93a0c10.

### Actual results
RefactoringMiner yields and empty set of refactoring.

### Expected results
A single instance of Move Method refactoring applied to doHealthCheck(QHealth.Builder;QString) method of ElasticsearchRestHealthIndicator class.

**Comment by tsantalis** [comment]
Thank you @osmarleandro 
The issue has been fixed and will be included in release 2.0.4
