### ISSUE TITLE
Some Missed Add Annotation Refactoring Activities

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#135]
Below is the list of refactorings that I believe are performed but are missing on RefactoringMiner. The first four refactorings are the same as the second four samples but in different source folders.

1. Add Attribute Annotation	@Weak in attribute nextWrite : ReferenceEntry<K,V> from class com.google.common.cache.LocalCache.WriteQueue<K, V> at [line 3528](https://github.com/google/guava/commit/5e519d91d038636fa5f786908aa856ba5470846d#diff-66b145b2c74ddc7ef429a3b0b1551e217c7e6278d96c28fcb23d3a1da2cc18f6L3528) of android/guava/src/com/google/common/cache/LocalCache.java
2. Add Attribute Annotation	@Weak in attribute previousWrite : ReferenceEntry<K,V> from class com.google.common.cache.LocalCache.WriteQueue<K, V> at [line 3540](https://github.com/google/guava/commit/5e519d91d038636fa5f786908aa856ba5470846d#diff-66b145b2c74ddc7ef429a3b0b1551e217c7e6278d96c28fcb23d3a1da2cc18f6L3540) of android/guava/src/com/google/common/cache/LocalCache.java
3. Add Attribute Annotation	@Weak in attribute nextAccess : ReferenceEntry<K,V> from class com.google.common.cache.LocalCache.AccessQueue<K, V> at [line 3667](https://github.com/google/guava/commit/5e519d91d038636fa5f786908aa856ba5470846d#diff-66b145b2c74ddc7ef429a3b0b1551e217c7e6278d96c28fcb23d3a1da2cc18f6L3667) of android/guava/src/com/google/common/cache/LocalCache.java
4. Add Attribute Annotation	@Weak in attribute previousAccess : ReferenceEntry<K,V> from class com.google.common.cache.LocalCache.AccessQueue<K, V> at [line 3679](https://github.com/google/guava/commit/5e519d91d038636fa5f786908aa856ba5470846d#diff-66b145b2c74ddc7ef429a3b0b1551e217c7e6278d96c28fcb23d3a1da2cc18f6L3679) of android/guava/src/com/google/common/cache/LocalCache.java

5. Add Attribute Annotation	@Weak in attribute nextWrite : ReferenceEntry<K,V> from class com.google.common.cache.LocalCache.WriteQueue<K, V> at [line 3631](https://github.com/google/guava/commit/5e519d91d038636fa5f786908aa856ba5470846d#diff-98cf5b8d5ed981e94f4c745137a9b4ac3d0e896d0471cfb4e3baf85928c5053dL3631) of guava/src/com/google/common/cache/LocalCache.java
6. Add Attribute Annotation	@Weak in attribute previousWrite : ReferenceEntry<K,V> from class com.google.common.cache.LocalCache.WriteQueue<K, V> at [line 3643](https://github.com/google/guava/commit/5e519d91d038636fa5f786908aa856ba5470846d#diff-98cf5b8d5ed981e94f4c745137a9b4ac3d0e896d0471cfb4e3baf85928c5053dL3643) of guava/src/com/google/common/cache/LocalCache.java
7. Add Attribute Annotation	@Weak in attribute nextAccess : ReferenceEntry<K,V> from class com.google.common.cache.LocalCache.AccessQueue<K, V> at [line 3770](https://github.com/google/guava/commit/5e519d91d038636fa5f786908aa856ba5470846d#diff-98cf5b8d5ed981e94f4c745137a9b4ac3d0e896d0471cfb4e3baf85928c5053dL3770) of guava/src/com/google/common/cache/LocalCache.java
8. Add Attribute Annotation	@Weak in attribute previousAccess : ReferenceEntry<K,V> from class com.google.common.cache.LocalCache.AccessQueue<K, V> at [line 3782](https://github.com/google/guava/commit/5e519d91d038636fa5f786908aa856ba5470846d#diff-98cf5b8d5ed981e94f4c745137a9b4ac3d0e896d0471cfb4e3baf85928c5053dL3782) of guava/src/com/google/common/cache/LocalCache.java

**Comment by tsantalis** [comment]
@jodavimehran I need some help to understand the problem. For each attribute, I am getting 8 instances in the Chrome extension.
Do you mean there are 10 instances in total?
It seems all cases you report are inside anonymous class declarations.
Maybe that's the reason they are missed.

**Comment by jodavimehran** [comment]
Yes, there are more. All of the missing cases are attributes of AccessQueue and WriteQueue classes.

**Comment by jodavimehran** [comment]
To be precise, the attributes of the anonymous classes are defined as AccessQueue and WriteQueue classes' attributes.
