### ISSUE TITLE
Is there an option to compare two jar files?

### ISSUE THREAD

**Issue by zly123987** [tsantalis/RefactoringMiner#136]
I am conducting a study on state-of-art refactoring miners. I am curious if RMiner is able to compare two jar files or bytecode directories. I am aware compilation is not needed according to your ICSE paper, but does it support bytecode?

**Comment by tsantalis** [comment]
Bytecode is completely different from source code.
So, RefactoringMiner cannot work as it is on bytecode.
However, you can use a decompiler to generate the source code from the class files.
https://www.baeldung.com/java-decompiling-classes
http://java-decompiler.github.io/
