### ISSUE TITLE
Is it missing a Push Down Method refactoring?

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#137]
## Summary
In code present in osmarleandro/google-maps-services-java@1415e90 commit, I performed a single Push Down Method refactoring to awaitIgnoreError() method in PendingResultBase class and RefactoringMiner does not detect it.

The awaitIgnoreError() method is declared in the supertype PendingResult interface, which PendingResultBase class is implementing.

#### Code example
Diff between the commit osmarleandro/google-maps-services-java@1415e90 and their parent.
```diff
@@ -58,11 +58,6 @@ abstract class PendingResultBase<T, A extends PendingResultBase<T, A, R>, R exte
     return request.await();
   }
 
-  @Override
-  public final T awaitIgnoreError() {
-    return makeRequest().awaitIgnoreError();
-  }
-


@@ -202,4 +202,9 @@ public class DistanceMatrixApiRequest
   public DistanceMatrixApiRequest transitRoutingPreference(TransitRoutingPreference pref) {
     return param("transit_routing_preference", pref);
   }
+
+@Override
+public final DistanceMatrix awaitIgnoreError() {
+    return makeRequest().awaitIgnoreError();
+  }
 }

```

### Environment details
RefactoringMiner 2.0.2

## Steps to reproduce
1. Run RefactoringMiner and pass as input the osmarleandro/google-maps-services-java@1415e90 commit.

### Actual results
RefactoringMiner yields an empty set of refactorings.

### Expected results
An instance of Push Down Method refactoring applied to UMLTypeParameter class.

**Comment by tsantalis** [comment]
Return type `T` changes to the actual type corresponding to `T` in each subclass.

**Comment by tsantalis** [comment]
12 Push Down refactorings detected:
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : GeocodingResult[] from class com.google.maps.GeocodingApiRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : GeolocationResult from class com.google.maps.GeolocationApiRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : AutocompletePrediction[] from class com.google.maps.QueryAutocompleteRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : PlacesSearchResponse from class com.google.maps.NearbySearchRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : PlacesSearchResponse from class com.google.maps.TextSearchRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : PlaceDetails from class com.google.maps.PlaceDetailsRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : AutocompletePrediction[] from class com.google.maps.PlaceAutocompleteRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : FindPlaceFromText from class com.google.maps.FindPlaceFromTextRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : DistanceMatrix from class com.google.maps.DistanceMatrixApiRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : ImageResult from class com.google.maps.PhotoRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : DirectionsResult from class com.google.maps.DirectionsApiRequest
> Push Down Method public awaitIgnoreError() : T from class com.google.maps.PendingResultBase to public awaitIgnoreError() : ImageResult from class com.google.maps.StaticMapsRequest
