### ISSUE TITLE
Generic Type in the Push Down Method refactoring

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#138]
## Summary

In code present in osmarleandro/spring-boot@710ca16 commit, I performed a single Push Down Method refactoring to getProperties() method in InfoPropertiesInfoContributor class and RefactoringMiner does not detect it.

The original getProperties() method has a Generic Type as a return, which was changed after applying the Push Down Method refactoring.

#### Code example
Diff between the commit osmarleandro/spring-boot@710ca16 and their parent.
```diff
@@ -40,7 +40,7 @@ public abstract class InfoPropertiesInfoContributor<T extends InfoProperties> im
-       private final T properties;
+       protected final T properties;

@@ -49,14 +49,6 @@ 
-       /**
-        * Return the properties that this instance manages.
-        * @return the info properties
-        */
-       protected final T getProperties() {
-               return this.properties;
-       }
-

@@ -56,4 +56,12 @@ public class BuildInfoContributor extends InfoPropertiesInfoContributor<BuildPro
                replaceValue(content, "time", getProperties().getTime());
        }
 
+       /**
+        * Return the properties that this instance manages.
+        * @return the info properties
+        */
+       protected final BuildProperties getProperties() {
+               return this.properties;
+       }
+
 }
```

### Environment details
RefactoringMiner 2.0.2

## Steps to reproduce
1. Run RefactoringMiner and pass as input the osmarleandro/spring-boot@710ca16 commit.

### Actual results
RefactoringMiner yields an empty set of refactorings.

### Expected results
An instance of Push Down Method refactoring applied to getProperties() method in InfoPropertiesInfoContributor class.

**Comment by tsantalis** [comment]
Duplicate issue to #137

**Comment by tsantalis** [comment]
2 Push Down refactorings detected:
> Push Down Method protected getProperties() : T from class org.springframework.boot.actuate.info.InfoPropertiesInfoContributor to protected getProperties() : BuildProperties from class org.springframework.boot.actuate.info.BuildInfoContributor
> Push Down Method protected getProperties() : T from class org.springframework.boot.actuate.info.InfoPropertiesInfoContributor to protected getProperties() : GitProperties from class org.springframework.boot.actuate.info.GitInfoContributor
