### ISSUE TITLE
The detectAll method of GitHistoryRefactoringMinerImpl class does not call the handler method of RefactoringHandler

### ISSUE THREAD

**Issue by mirsaeedi** [tsantalis/RefactoringMiner#14]
In the following snippet of code (which I have taken from the ReadMe section), the _handle_ method will not get called:

```

GitService gitService = new GitServiceImpl();
GitHistoryRefactoringMiner miner = new GitHistoryRefactoringMinerImpl();

Repository repo = gitService.cloneIfNotExists(
    "tmp/refactoring-toy-example",
    "https://github.com/danilofes/refactoring-toy-example.git");

miner.detectAll(repo, "master", new RefactoringHandler() {
  @Override
  public void handle(RevCommit commitData, List<Refactoring> refactorings) {
    System.out.println("Refactorings at " + commitData.getId().getName());
    for (Refactoring ref : refactorings) {
      System.out.println(ref.toString());
    }
  }
```
It seems in the _detectRefactorings_ method of _GitHistoryRefactoringMinerImpl_ class, there is just one call to `handle(String commitId, List<Refactoring> refactorings)` method and nobody calls the other handle method `handle(RevCommit commitData, List<Refactoring> refactorings)`

**Comment by dmazinanian** [comment]
The overloads of the `RefactoringHandler#handle()` have default implementations (empty) and one is supposed to implement them with their own logic when implementing their own miner application. As you see, one accepts the SHA1 of the commit as `String`, while the other needs `JGit`'s `RevCommit`. Yes, `GitHistoryRefactoringMinerImpl` does not need the second overload since it works with SHA1s as String, while the other class `GitHistoryStructuralDiffAnalyzer` passes `RevCommit`s instead.

**Comment by mirsaeedi** [comment]
But I think when a user calls `miner#detectAll` and passes an implementation of `RefactoringHandler` to the method, he expects from the framework to call all of the methods of the `RefactoringHandler `interface. In fact, It seems the sole purpose of `RefactoringHandler` is to handle events, but as a user, I have no way to implement my desired behavior in case of the event. 

if that's not true, How should a user of the framework know which method of `RefactoringHandler ` will get called?

**Comment by dmazinanian** [comment]
You are right, I misunderstood the original problem. 

This is a regression. We have to change the README to use the other method. Of course, the design of this part can be improved as well.

Thanks for pointing this out. If you would like you can send a pull request for this part too. It will be highly appreciated.
