### ISSUE TITLE
False Rename Parameter Refactoring

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#142]
In [this](https://github.com/checkstyle/checkstyle/commit/ed76401d3bd039d684d6de21c4894d3ab62a3076) commit, an extract operation refactoring has been applied, and as a result of this refactoring, a new method is proposed. RefactoringMiner detects this refactoring correctly, but it reports another Rename Parameter refactoring related to the extracted method and the method it is extracted from that I think is not a real refactoring.

**Comment by tsantalis** [comment]
The refactoring is legit.
The parameter `DetailAST ast` from the original method `public void visitToken(DetailAST ast)` has been renamed to
`DetailAST ident` in the extracted method `private static void determineAssignmentConditions(DetailAST ident, FinalVariableCandidate candidate)`
