### ISSUE TITLE
Is the Move Method refactoring a true instance?

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#145]
## Summary

In code present in osmarleandro/RefactoringMiner@76626f3 commit, I applied a single Move Method refactoring to getTargetAttributeCodeRangeAfterMove() method in MoveAttributeRefactoring class. The method was moved to UMLAttribute class. RefactoringMiner did not detect the applied refactoring.

#### Code example
Diff fragment between the commit osmarleandro/RefactoringMiner@76626f3 and their parent.
```diff
@@ -171,4 +171,11 @@ public class UMLAttribute implements Comparable<UMLAttribute>, Serializable, Loc
                double normalized = (double)distance/(double)Math.max(s1.length(), s2.length());
                return normalized;
        }
+
+       /**
+        * @return the code range of the target attribute in the <b>child</b> commit
+        */
+       public CodeRange getTargetAttributeCodeRangeAfterMove() {
+               return codeRange();
+       }
 }

@@ -13,7 +13,7 @@ import gr.uom.java.xmi.UMLAttribute;
 
 public class MoveAttributeRefactoring implements Refactoring {
        protected UMLAttribute originalAttribute;
-       protected UMLAttribute movedAttribute;
+       public UMLAttribute movedAttribute;
        private volatile int hashCode = 0;
        
@@ -65,13 +65,6 @@ public class MoveAttributeRefactoring implements Refactoring {
                return originalAttribute.codeRange();
        }
 
-       /**
-        * @return the code range of the target attribute in the <b>child</b> commit
-        */
-       public CodeRange getTargetAttributeCodeRangeAfterMove() {
-               return movedAttribute.codeRange();
-       }
-
        public boolean equals(Object o) {
```

### Environment details
RefactoringMiner 2.0.3

## Steps to reproduce
1. Run RefactoringMiner and give as input the osmarleandro/RefactoringMiner@76626f3 commit.

### Actual results
RefactoringMiner yields an empty set as result.

### Expected results
A single instance of Move Method refactoring applied to getTargetAttributeCodeRangeAfterMove() method in MoveAttributeRefactoring class.

**Comment by tsantalis** [comment]
@osmarleandro 
This is not a valid refactoring transformation.
Technically, a delegate method should be left in the original class to preserve behaviour, as this refactoring breaks the public API of `MoveAttributeRefactoring`.
From the Feature Envy point of view, the refactoring is not well justified too, because the moved method, simply delegates to `codeRange()`.
Single line methods are in general tricky, because it is harder to assess similarity.
