### ISSUE TITLE
The GitHub API restriction could cause a problem in processing commits with more than 300 changed files

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#149]
Unfortunately, there is a restriction in the GitHub API that could negatively affect Refactoring Miner's accuracy since it uses it internally. The restriction is that this API will not give the complete list of changed files for the commits containing more than 300 files. It means that RefactoringMiner does not have enough information about the changed files in commits like [this](https://github.com/hibernate/hibernate-orm/commit/9caca0ce37d5a2763d476c6fa2471addcca710ca), which contains 1284 changed files, and could not be accurate enough in such cases. Although that is not the case for the other API that does not rely on the GitHub API, it is good to consider this problem, especially because the chrome extension uses it.

**Comment by tsantalis** [comment]
Thanks @jodavimehran 
Is there an alternative library that we could use (or a different way to call the current one), which can overcome this restriction.

https://github.community/t/the-maximum-number-of-files-in-a-single-diff-is-limited-to-3-000/14373
https://stackoverflow.com/questions/42545720/github-api-single-commit-dont-fetch-all-files

**Comment by jodavimehran** [comment]
Based on the GitHub Rest API documentation about [getting a commit](https://docs.github.com/en/rest/reference/repos#get-a-commit), the API response for the commits containing more than 300 changed files will include a pagination link for the other remaining files, up to a limit of 3000 files. So the GitHub rest API provides the information we need, and I think the limit of 3000 files is way better than 300 files. It seems the [Java API for GitHub](https://github-api.kohsuke.org/), which is a wrapper for the GitHub Rest API, does not implement this part, and it has the limitation of 300 files.
I found a way in which we can use the Java API to retrieve the remaining files. So I am going to finalize this solution and create a pull request.

**Comment by tsantalis** [comment]
In commit
https://github.com/spring-projects/spring-framework/commit/02a4473c62d8240837bec297f0a1f3cb67ef8a7b
we get
4762 java files with a locally cloned repository
2441 java files when fetching from GitHub.

**Comment by jodavimehran** [comment]
> In commit
> [spring-projects/spring-framework@02a4473](https://github.com/spring-projects/spring-framework/commit/02a4473c62d8240837bec297f0a1f3cb67ef8a7b)
> we get
> 4762 java files with a locally cloned repository
> 2441 java files when fetching from GitHub.

As mentioned in the GitHub API Documentation, unfortunately, the API returns the contents of a single commit up to a limit of 3000 files. So there is nothing we can do about this limitation.
