### ISSUE TITLE
Missing Rename Parameter and Change Parameter Type

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#155]
At [this](https://github.com/apache/commons-lang/commit/49e68a3f962c0b8e0ac80743db5eecb1b493c9e6#diff-04ccba1e21daf9419e555da657f2c7b571f5374370b4f53138871d18c55b5136L765) commit, a rename parameter refactoring and a change parameter type refactoring are performed, but the Refactoring Miner has missed them.

**Expected result:**
Change Parameter Type 	round:boolean to modType:int in method private static modify(val:Calendar, field:int , modType:ModifyType):void from class org.apache.commons.lang.time.DateUtils
Rename Parameter 	round:boolean to modType:int in method private static modify(val:Calendar, field:int , modType:ModifyType):void from class org.apache.commons.lang.time.DateUtils

**Actual result:**
No Refactoring

**Comment by tsantalis** [comment]
@jodavimehran 
`indexOf()` is using `equals()` and `UMLParameter.equals()` does include the parameter name
