### ISSUE TITLE
A Move Class Refactoring is missed

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#156]
In the changes performed on [this](https://github.com/apache/flink/commit/d56d48f1a1933f138f5d97f42b71aa64fad6bc6f#diff-0c9751e3c0d3a13bd1207784bf3cc0f2762c7817e77f9ad917e6b2afd54f2afb) commit, a move class refactoring is missed by Refactoring Miner.

**Expected Refactoring:**
Move Class: org.apache.flink.streaming.api.DataStream is moved to org.apache.flink.streaming.api.datastream.DataStream

**Comment by tsantalis** [comment]
Type parameter `<T>` changed to `<OUT>`

**Comment by tsantalis** [comment]
@jodavimehran 
The Move Class refactoring is properly detected now.
Along with the Move Class many Change Return/Parameter Type refactorings are reported.
Please check them.
