### ISSUE TITLE
Problem related to the string representation attribute of OperationBody class

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#157]
The string representation attribute of OperationBody class should also contain the close brace "}" because in some special cases like [this](https://github.com/apache/commons-lang/commit/050fe8e916507c9716983868284d64e58c1b56d2#diff-04ccba1e21daf9419e555da657f2c7b571f5374370b4f53138871d18c55b5136), despite the change in the body of a method, the body's string representation doesn't reflect the change.

**Comment by tsantalis** [comment]
@jodavimehran 
Do you mean only OperationBody should have a closing bracket, or all Composite statements?

**Comment by jodavimehran** [comment]
> @jodavimehran
> Do you mean only OperationBody should have a closing bracket, or all Composite statements within the body of the method?

I think all Composite statements because that is the only way we can find where a composite statement has ended.

**Comment by tsantalis** [comment]
So, basically Block type should have a closing bracket. Yes, we can do that.

**Comment by tsantalis** [comment]
@jodavimehran 
Can you please test the fix?

**Comment by jodavimehran** [comment]
> @jodavimehran
> Can you please test the fix?

That works fine.

The only problem I just found in this regard is related to an else block.
For example a statement like this:
`           if (i == 0) {
                parser = new SimpleDateFormat(parsePatterns[0]);
            } else {
                parser.applyPattern(parsePatterns[i]);
            }`
           
is representing like below list in the string representation.

1 = "if(i == 0)"
2 = "{"
3 = "parser=new SimpleDateFormat(parsePatterns[0]);\n"
4 = "}"
5 = "{"
6 = "parser.applyPattern(parsePatterns[i]);\n"
7 = "}"


Is this possible to add the else?

**Comment by tsantalis** [comment]
The change I did broke the tests. I will need more time on this issue.

**Comment by tsantalis** [comment]
@jodavimehran 
Can you give me a good example, about why adding the `else` is important?
Because it is highly unlikely that another block will follow the `if` block without being an `else` block

**Comment by jodavimehran** [comment]
> @jodavimehran
> Can you give me a good example, about why adding the `else` is important?
> Because it is highly unlikely that another block will follow the `if` block without being an `else` block

I don't have any. I just wanted to cover all possibilities, but as you mentioned, although it is possible, it is unlikely. So we can skip it.
