### ISSUE TITLE
Single line method and Inline Method refactoring

### ISSUE THREAD

**Issue by osmarleandro** [tsantalis/RefactoringMiner#158]
## Summary

In code present in osmarleandro/incubator-gobblin@959d461 commit, I applied an Inline Method refactoring to newJobLauncher() method in JobLauncherFactory class, but RefactoringMiner does not detect it.

#### Code example
Diff between the commit osmarleandro/incubator-gobblin@959d461 and their parent.
```diff
@@ -107,21 +107,6 @@ public class JobLauncherFactory {
     return newJobLauncher(sysProps, jobProps, launcherTypeValue, instanceBroker, metadataTags);
   }
 
-  /**
-   * Creates a new instance for a JobLauncher with a given type
-   * @param sysProps          the system/environment properties
-   * @param jobProps          the job properties
-   * @param launcherTypeValue the type of the launcher; either a {@link JobLauncherType} value or
-   *        the name of the class that extends {@link AbstractJobLauncher} and has a constructor
-   *        that has a single Properties parameter..
-   * @return the JobLauncher instance
-   * @throws RuntimeException if the instantiation fails
-   */
-  public static JobLauncher newJobLauncher(Properties sysProps, Properties jobProps,
-      String launcherTypeValue, SharedResourcesBroker<GobblinScopeTypes> instanceBroker) {
-    return newJobLauncher(sysProps, jobProps, launcherTypeValue, instanceBroker, ImmutableList.of());
-  }
-

@@ -35,6 +35,7 @@ import org.slf4j.LoggerFactory;
 import com.google.common.annotations.VisibleForTesting;
 import com.google.common.base.Optional;
 import com.google.common.base.Preconditions;
+import com.google.common.collect.ImmutableList;
 import com.google.common.io.Closer;
 import com.google.common.util.concurrent.ExecutionList;
 import com.typesafe.config.ConfigFactory;
@@ -170,8 +171,10 @@ public class JobLauncherExecutionDriver extends FutureTask<JobExecutionResult> i
   private static JobLauncher createLauncher(Configurable _sysConfig, JobSpec _jobSpec, Logger _log,
       Optional<String> jobLauncherType, SharedResourcesBroker<GobblinScopeTypes> instanceBroker) {
     if (jobLauncherType.isPresent()) {
-      return JobLauncherFactory.newJobLauncher(_sysConfig.getConfigAsProperties(),
-             _jobSpec.getConfigAsProperties(), jobLauncherType.get(), instanceBroker);
+      Properties sysProps = _sysConfig.getConfigAsProperties();
+               Properties jobProps = _jobSpec.getConfigAsProperties();
+               String launcherTypeValue = jobLauncherType.get();
+       return JobLauncherFactory.newJobLauncher(sysProps, jobProps, launcherTypeValue, instanceBroker, ImmutableList.of());
     }

```

### Environment details
RefactoringMiner 2.0.3

## Steps to reproduce
1. Run RefactoringMiner and give as input the osmarleandro/incubator-gobblin@959d461 commit.

### Actual results
```
Extract Variable	sysProps : Properties in method private createLauncher(_sysConfig Configurable, _jobSpec JobSpec, _log Logger, jobLauncherType Optional<String>, instanceBroker SharedResourcesBroker<GobblinScopeTypes>) : JobLauncher from class org.apache.gobblin.runtime.job_exec.JobLauncherExecutionDriver
Extract Variable	launcherTypeValue : String in method private createLauncher(_sysConfig Configurable, _jobSpec JobSpec, _log Logger, jobLauncherType Optional<String>, instanceBroker SharedResourcesBroker<GobblinScopeTypes>) : JobLauncher from class org.apache.gobblin.runtime.job_exec.JobLauncherExecutionDriver
```

### Expected results
The instance of Rename Method refactoring applied to newJobLauncher() abstract method in JobLauncherFactory interface.

**Comment by tsantalis** [comment]
@osmarleandro 
In the way you performed the Inline, the call site has not changed.
Before the call is `return JobLauncherFactory.newJobLauncher(...)` and after the call is
`return JobLauncherFactory.newJobLauncher(...)`
These are identical calls with the only difference that some arguments have been extracted as local variables.
The number of arguments increased from 4 to 5 by adding `ImmutableList.of()` as the fifth argument.

**Comment by osmarleandro** [comment]
Hi @tsantalis, thanks for your support and attention. 

This transformation is really tricky. When I apply to the overloaded method in osmarleandro/incubator-gobblin@a0db6c5 commit, the method's body has no changes, and RefactoringMiner detects the Inline Method.

**Comment by tsantalis** [comment]
The Inline Method refactorings in commit https://github.com/osmarleandro/spring-boot/commit/7f3f2d66a428bc69b9b038f78959213842d91f08
> Inline Method private format(lockInfo LockInfo) : String inlined to private writeMonitors(writer PrintWriter, lockedMonitorsAtCurrentDepth List<MonitorInfo>) : void in class org.springframework.boot.actuate.management.PlainTextThreadDumpFormatter
> Inline Method private format(lockInfo LockInfo) : String inlined to private writeLockedOwnableSynchronizers(writer PrintWriter, info ThreadInfo) : void in class org.springframework.boot.actuate.management.PlainTextThreadDumpFormatter
> Inline Method private format(lockInfo LockInfo) : String inlined to private writeStackTraceElement(writer PrintWriter, element StackTraceElement, info ThreadInfo, lockedMonitors List<MonitorInfo>, firstElement boolean) : void in class org.springframework.boot.actuate.management.PlainTextThreadDumpFormatter
