### ISSUE TITLE
Incorrectly reports a method rename

### ISSUE THREAD

**Issue by max-ellis** [tsantalis/RefactoringMiner#160]
**Summary**

I think RefactoringMiner incorrectly detected or reported a rename method refactoring. 

**Environtment**

RefactoringMiner 2.0

**Details**

Git Repository: 
https://github.com/MasDennis/Rajawali

The commits that I used: 
Start commit: 773d48939
End Commit: 3d9b713ba

Using `miner.detectBetweenCommits`

**Steps to reproduce** 

1. Use the detectBetweenCommits method with the above Git repository, start commit, and end commit. 

**Output**

**RenameOperationRefactoring:** 
`Rename Method	private update() : void renamed to public CameraVisibleFrustum(parent CameraFrustum, sides int, 
          radiusTop double, radiusBase double, height double) in class rajawali.bounds.CameraFrustum.CameraVisibleFrustum`

**Original Operation:** `private update() : void`

**Renamed Operation:** `public CameraVisibleFrustum(parent CameraFrustum, sides int, radiusTop double, radiusBase double, height double)`

I was using this code base to test some of my code and I noticed RefactoringMiner reported this refactoring. At first I thought it would be impossible for this to be a rename operation refactoring but I'm looking at the other refactoring operations that it detected and it detected several "add parameter" refactorings in CameraVisibleFrustum before it detected the rename operation refactoring. If we ignore the parameters that were added, we have `private update() : void renamed to public CameraVisibleFrustum()`. Since the method `update` is changed to a constructor, can we call this a rename method refactoring? Would it make sense to detect a remove parameter refactoring for the return type (void)?

**Comment by tsantalis** [comment]
The reported refactoring is in commit https://github.com/Rajawali/Rajawali/commit/1d1a2c5256e6da204b42c82a414dd078546591be

It seems the correct refactoring is `private void update()` becomes `private void update(boolean update)`
in agreement with the refactoring reported for the superclass `NPrism`
`Add Parameter update : boolean in method protected init(update boolean) : void from class rajawali.primitives.NPrism`

I will look into that.

**Comment by tsantalis** [comment]
The actual refactorings in this commit are:
> Add Parameter radiusBase : double in method public CameraVisibleFrustum(parent CameraFrustum, sides int, radiusTop double, radiusBase double, height double) from class rajawali.bounds.CameraFrustum.CameraVisibleFrustum
> Add Parameter update : boolean in method private update(update boolean) : void from class rajawali.bounds.CameraFrustum.CameraVisibleFrustum
> Add Parameter radiusTop : double in method public CameraVisibleFrustum(parent CameraFrustum, sides int, radiusTop double, radiusBase double, height double) from class rajawali.bounds.CameraFrustum.CameraVisibleFrustum
> Add Parameter height : double in method public CameraVisibleFrustum(parent CameraFrustum, sides int, radiusTop double, radiusBase double, height double) from class rajawali.bounds.CameraFrustum.CameraVisibleFrustum
> Add Parameter sides : int in method public CameraVisibleFrustum(parent CameraFrustum, sides int, radiusTop double, radiusBase double, height double) from class rajawali.bounds.CameraFrustum.CameraVisibleFrustum
> Add Parameter update : boolean in method protected init(update boolean) : void from class rajawali.primitives.NPrism
