### ISSUE TITLE
Repetitive Refactorings

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#163]
RefactoringMiner reports five extract-method refactorings after analyzing [this](https://github.com/hibernate/hibernate-orm/commit/b4bf58188c578927a238a791973975d23a92bfd9) commit, which I think are repetitive.

**Comment by tsantalis** [comment]
This is a great case for nested Extract Method refactorings.
`testStreamCloseOnTerminalOperation()` -> `runTerminalOperationTests()` -> `getMyEntityStream()` -> `getStream()`
`testStreamCloseOnTerminalOperation()` -> `runTerminalOperationTests()` -> `getLongStream()` -> `getStream()`

**Comment by tsantalis** [comment]
Refactorings detected in this commit:

> Modify Method Annotation @TestForIssue(jiraKey = "HHH-13872") to @TestForIssue(jiraKey = {"HHH-13872","HHH-14449"}) in method public testStreamCloseOnTerminalOperation() : void from class org.hibernate.test.stream.basic.JpaStreamTest
>   Extract Method private runTerminalOperationTests(prepare Runnable, onCloseCallbacks List<Runnable>, onCloseAssertion Runnable, flatMapBefore boolean, flatMapAfter boolean) : void extracted from public testStreamCloseOnTerminalOperation() : void in class org.hibernate.test.stream.basic.JpaStreamTest
>   Extract Method private getStream(prepare Runnable, session Session, queryString String, onCloseCallbacks List<Runnable>, flatMapBefore boolean, flatMapAfter boolean) : Stream<T> extracted from public testStreamCloseOnTerminalOperation() : void in class org.hibernate.test.stream.basic.JpaStreamTest
>   Change Variable Type stream : Stream<MyEntity> to stream : Stream<T> in method private getStream(prepare Runnable, session Session, queryString String, onCloseCallbacks List<Runnable>, flatMapBefore boolean, flatMapAfter boolean) : Stream<T> from class org.hibernate.test.stream.basic.JpaStreamTest
>   Change Variable Type stream : Stream<Long> to stream : Stream<T> in method private getStream(prepare Runnable, session Session, queryString String, onCloseCallbacks List<Runnable>, flatMapBefore boolean, flatMapAfter boolean) : Stream<T> from class org.hibernate.test.stream.basic.JpaStreamTest

Awesome screenshot showing the nested extracted method calls visualized in Chrome extension

![Screenshot from 2021-03-25 10-39-55](https://user-images.githubusercontent.com/1483516/112491352-9b787a00-8d56-11eb-843f-f4393343290d.png)
