### ISSUE TITLE
Add Parameters or Extract Method?

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#164]
In [this](https://github.com/Netflix/zuul/commit/1391276561ce4c1d35a1e721f9d319dedf8c9c1c) commit, the signature of the method (applyErrorEndpoint) is changed. RefactoringMiner reports it is extracted from another method. But I think it is not an extract method refactoring, and it should report two add-parameter refactorings instead. What do you think, @tsantalis?

**Comment by tsantalis** [comment]
The refactorings detected in this commit are:
> Add Parameter shouldSendErrorResponse : boolean in method public MockHttpSyncInboundFilter(filterName String, filterOrder int, shouldFilter boolean, error Throwable, shouldSendErrorResponse boolean) from class com.netflix.zuul.message.http.MockHttpSyncInboundFilter
> Add Parameter phase : String in method protected chainFilters(msg ZuulMessage, filterChainIterator Iterator<ZuulFilter>, phase String) : Observable<ZuulMessage> from class com.netflix.zuul.FilterProcessorImpl
> Add Parameter phase : String in method private applyErrorEndpoint(msg ZuulMessage, request HttpRequestMessage, filterChainIterator Iterator<ZuulFilter>, phase String) : Observable<ZuulMessage> from class com.netflix.zuul.FilterProcessorImpl
> Add Parameter filterChainIterator : Iterator<ZuulFilter> in method private applyErrorEndpoint(msg ZuulMessage, request HttpRequestMessage, filterChainIterator Iterator<ZuulFilter>, phase String) : Observable<ZuulMessage> from class com.netflix.zuul.FilterProcessorImpl
> Rename Method protected resetContextErrorFlags(msg ZuulMessage) : void renamed to protected flagErrorSent(msg ZuulMessage) : void in class com.netflix.zuul.FilterProcessorImpl
> Extract Variable inFilterIterator : Iterator<ZuulFilter> in method public applyFilterChain(msg ZuulMessage) : Observable<ZuulMessage> from class com.netflix.zuul.FilterProcessorImpl
