### ISSUE TITLE
Find all locations where renamed method was called

### ISSUE THREAD

**Issue by VladyslavBondarenko** [tsantalis/RefactoringMiner#165]
HI @tsantalis, thank you a lot for Refactoring Miner!

I have a question. 
With detected Rename Method refactoring I can know previous location of the method. But I would like to know all locations where the method was called, basically all other changes caused by the renaming (I would consider them as refactoring changes too). 

Is there a way to know the locations with Refactoring Miner?

**Comment by tsantalis** [comment]
Hi @VladyslavBondarenko 
I could provide easily the local (i.e., within the same class) statement mappings referring to the renamed method.

**Comment by Symbolk** [comment]
To rigorously infer the _uses_ of a _definition_, it requires building data and control graph. Specifically, for method declaration and invocations, it requires building the call graph.

Previously I have this done with symbol resolution of JDT, now I am trying Language Server Index Format.

**Comment by VladyslavBondarenko** [comment]
@tsantalis ok, within the same class would be already good

**Comment by tsantalis** [comment]
Hi @VladyslavBondarenko 
I implemented the feature.
Is it possible to provide some commits in which there are call references to renamed methods, in order to test the feature?
Thank you.

**Comment by VladyslavBondarenko** [comment]
@tsantalis 
Nice, it's working. But for example I use `detectAtCommit` for https://github.com/apache/oozie/commit/8df784b5fb15273af31d8c104f0f7c47c78e82a3, and `getCallReferences` of `RenameOperationRefactoring` for [this method](https://github.com/apache/oozie/commit/8df784b5fb15273af31d8c104f0f7c47c78e82a3#diff-31ed752fb02277849e7ef90796db4258056d13689c83c983afac759c7ca76a56L201) returns 2 call references - [1](https://github.com/apache/oozie/commit/8df784b5fb15273af31d8c104f0f7c47c78e82a3#diff-31ed752fb02277849e7ef90796db4258056d13689c83c983afac759c7ca76a56L573) and [2](https://github.com/apache/oozie/commit/8df784b5fb15273af31d8c104f0f7c47c78e82a3#diff-31ed752fb02277849e7ef90796db4258056d13689c83c983afac759c7ca76a56L620), but not [this reference](https://github.com/apache/oozie/commit/8df784b5fb15273af31d8c104f0f7c47c78e82a3#diff-31ed752fb02277849e7ef90796db4258056d13689c83c983afac759c7ca76a56L596) (should be because its diff is identical to 1).

**Comment by tsantalis** [comment]
@VladyslavBondarenko 
I changed the equals() and hashCode() in MethodInvocationReplacement, so that two replacements are considered equals when the locations of the method calls are equal.
