### ISSUE TITLE
MoveAndRename method refactoring is wrongly reported as Extract Method inside of Anonymous Class

### ISSUE THREAD

**Issue by mkshiblu** [tsantalis/RefactoringMiner#166]
#### Steps to Reproduce

1. Go to -
     https://github.com/mkshiblu/practice/commit/c5f4acfcceda4e4f72e695a4a4406b2adf4640a1
2.  Run the chrome extension 

#### Observed Behavior
The extension reported that method **setOptionSelectedStatus** has been extracted-

![image](https://user-images.githubusercontent.com/15908043/114091204-63108a00-9886-11eb-9d4a-5bd5a5913205.png)

#### Expected Behavior
The extension should have reported that the **setOptionAsSelected** has been **MoveAndRename** since there is no added method here.

Note that the code is a java re-creation of [this](https://github.com/angular/angular.js/commit/538f4606ff32e776b093243fed4af3460df74f2a#diff-c750f8f73d42041534b35a72022a51f2c298e06db5b8e0e4081ef60c3d30e173) javaScript code. 

#### Snippet Diff
![image](https://user-images.githubusercontent.com/15908043/114091768-137e8e00-9887-11eb-8f60-ab3882e27fa3.png)

**Refactoring Miner Version**
**Commit:** 9c6c1a2
**Commit Date:**  April 8, 2021

**Comment by tsantalis** [comment]
Move Method refactoring is reported only between different classes.
In this example, method `setOptionAsSelected` within an anonymous class is extracted as `setOptionSelectedStatus` to the outer class.
