### ISSUE TITLE
Would it possible to detect only certain refactoring types?

### ISSUE THREAD

**Issue by onewhl** [tsantalis/RefactoringMiner#168]
Hi, @tsantalis 

We use RefactoringMiner in several projects, and we are curious about the possibility to detect only certain types of refactorings. I know that the order the tool identifies refactorings is very important in the RefactoringMiner approach to minimize false-positive results. But anyway, how do you feel, is it possible to allow a user to specify the refactorings to detect?  At least for some of the refactoring types (for example, Rename and Move).

Thank you,
Zarina

**Comment by tsantalis** [comment]
@onewhl 
Hi Zarina,
Do you mean being able to disable completely the execution of some refactoring detection algorithms in order to improve performance?
Could you give a more concrete example about what you would like to be disabled or enabled?

**Comment by onewhl** [comment]
Yes, in my view, it would be very useful to have a possibility to run the detection only for certain refactorings.
Currently, we're developing a new feature in the RefactorInsight plugin, and for this feature, we need to detect only certain refactorings (Move/Extract/Inline/Pull Up/Push Down Method) in code changes in each commit. The performance is important because we need to update UI immediately.

For example, a user of RefactoringMiner could pass the list of refactorings they're interested in, and the tool detects only these certain refactorings.

**Comment by tsantalis** [comment]
@onewhl 
Some of the refactorings you mentioned, such as `Extract Method` and `Inline Method`, are local within a single class/file.
These refactorings are detected as pairs of classes are getting matched (first phase of the detection process).

In the second phase of the detection process, the unmatched methods from the first phase are examined as candidates
for `Move Method` and `Pull Up/Push Down Method` refactorings between different classes/files.
This phase is more computationally expensive, especially when the number of unmatched methods from the first phase is large.

The list of refactorings you are interested in cover both detection phases.
As a result, it is not possible to optimize something.
If you were interested only in refactorings detected in the first phase, the second phase could be disabled.
