### ISSUE TITLE
Support for Reporting Changes in Non-Access Modifiers

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#169]
Hi @tsantalis,

In addition to the access modifier, there are Non-Access Modifiers that we can use for code elements. Since RefactoringMiner already reports the change on access modifiers of attributes and methods, it would be useful to report the change of Non-Access Modifiers.

- [x] For classes, we can use either the **final** or **abstract** modifier.
_Update_: We also have **static**
- [x] For attributes, we can use **final**, **static**, **transient**, **volatile**.
- [x] For methods, we can use **final**, **static**, **abstract**, **synchronized**.
- [x] For parameters, we can use **final**
- [x] For local variables, we can use **final**

**Comment by jodavimehran** [comment]
some examples of removing the final modifier of methods
[apache/flink](https://github.com/apache/flink/commit/f5898a01e7877afa3df06223713db211708eaf9a)

**Comment by jodavimehran** [comment]
> some examples of removing the final modifier of methods
> [apache/flink](https://github.com/apache/flink/commit/f5898a01e7877afa3df06223713db211708eaf9a)

@tsantalis
In the mentioned commit, the final modifier was removed of private methods. Since private methods are final by default, is it a real change, or is it a code clean-up like removing the private access modifier of a method declaration of an Interface?

**Comment by tsantalis** [comment]
All non-access modifier changes are now supported.
