### ISSUE TITLE
The diff method metioned in README.md file doesn't work well.

### ISSUE THREAD

**Issue by lingmengfeng** [tsantalis/RefactoringMiner#17]
**File rootFolder1 = new File("C:\\Users\\ThinkPad\\Desktop\\base");
		File rootFolder2 = new File("C:\\Users\\ThinkPad\\Desktop\\base");
		List<String> filePaths1 = new ArrayList<String>();
		filePaths1.add("JimpleInvokeCall.java");
		List<String> filePaths2 = new ArrayList<String>();
		filePaths2.add("JimpleInvokeCall2.java");

		UMLModel model1 = new UMLModelASTReader(rootFolder1, filePaths1).getUmlModel();
		UMLModel model2 = new UMLModelASTReader(rootFolder2, filePaths2).getUmlModel();
		UMLModelDiff modelDiff = model1.diff(model2);
		List<Refactoring> refactorings = modelDiff.getRefactorings();**
When I try to call method **diff**, a mistake appears. It prompts me to add argument to match **diff(UMLModel, Map<String, String>)**. What frustrates me is to how to change the code. I tried different way, but it does not work. I hope to get help.

**Comment by tsantalis** [comment]
Method diff(UMLModel) was accidentally removed in commit [98494faab4ff4fc26b3ac264822bf9d2f85cab75](https://github.com/tsantalis/RefactoringMiner/commit/98494faab4ff4fc26b3ac264822bf9d2f85cab75)
