### ISSUE TITLE
Reports wrong file path in rename class

### ISSUE THREAD

**Issue by max-ellis** [tsantalis/RefactoringMiner#171]
**Summary**

RefactoringMiner reported the destination file path for the source file path. The source class is `modrian.rolap.LevelDateRangeConstraint`, but the file path is `src/main/mondrian/rolap/MemberRangeConstraint.java` when it should be `src/main/modrian/rolap/LevelDateRangeConstraint.java`.

**Environtment**

RefactoringMiner 2.1.0

**Details**

Git Repository: 
https://github.com/pentaho/mondrian

The commits that I used: 
Start commit: 8cfaafedb2
End Commit: 871f7747de

Using `miner.detectBetweenCommits`

**Steps to reproduce** 

1. Use the detectBetweenCommits method with the above Git repository, start commit, and end commit. 
2. Use the debugger and examine the source file for the original and renamed UML classes. 

**Output**

original: "mondrian.rolap.LevelDateRangeConstraint"
sourceFile: "src/main/mondrian/rolap/MemberRangeConstraint.java"

renamed:  "mondrian.rolap.MemberRangeConstraint"
sourceFile: "src/main/mondrian/rolap/MemberRangeConstraint.java"

**Comment by tsantalis** [comment]
Hi @max-ellis 
The refactoring took place in commit https://github.com/pentaho/mondrian/commit/871f7747deded94e721fa098561376ab304b24de
If you check the commit on GitHub, you will see that the source file is `src/main/mondrian/rolap/MemberRangeConstraint.java` for both the original and renamed classes.

There is no file path `src/main/modrian/rolap/LevelDateRangeConstraint.java` in the commit https://github.com/pentaho/mondrian/commit/871f7747deded94e721fa098561376ab304b24de

**Comment by max-ellis** [comment]
This was user error on my end.
