### ISSUE TITLE
Does not report Renames in refactorings `Change Variable Type` and `Replace Variable With Attribute`

### ISSUE THREAD

**Issue by ameyaKetkar** [tsantalis/RefactoringMiner#172]
[Example](https://github.com/neo4j/neo4j/commit/77a5e62f9d5a56a48f82b6bdd8519b18275bef1d)

PFA the reported JSON. [output.json.zip](https://github.com/tsantalis/RefactoringMiner/files/6424127/output.json.zip)

**Comment by tsantalis** [comment]
**Replace Variable With Attribute** `configPath : String` to `configDir : Path` in method `public execute(incomingArguments String[]) : void` from class `org.neo4j.restore.RestoreExistingClusterCli`
**Replace Variable With Attribute** `configPath : String` to `configDir : Path` in method `public execute(incomingArguments String[]) : void` from class `org.neo4j.restore.RestoreNewClusterCli`

are associated with
**Change Variable Type** `configPath : String` to `configDir : Path` in method `public execute(incomingArguments String[]) : void` from class `org.neo4j.restore.RestoreExistingClusterCli`
**Change Variable Type** `configPath : String` to `configDir : Path` in method `public execute(incomingArguments String[]) : void` from class `org.neo4j.restore.RestoreNewClusterCli`

There are no actual renames taking place in this commit, but only replacements of variables `configPath : String` with field `configDir : Path` and variables `homeDir : File` with field `homeDir : Path`
