### ISSUE TITLE
Missed variable reference 

### ISSUE THREAD

**Issue by ameyaKetkar** [tsantalis/RefactoringMiner#173]
When a variable is used inside of a `try-with-resource` statement , it is not reported as a variable reference in `Change Variable Type` refactoring 
[Example](https://github.com/junit-team/junit5/commit/403115a6d6026d5724e3d5323474aa56f1613944#diff-08ea91a262f1b996a66f07b62c82cea320ec244fa3a1e3ef57ecc8b4da8caf3eL92)

**Comment by tsantalis** [comment]
It is not reported in the references, because the try-with-resource statements were not matched
`try (Writer fileWriter = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(xmlFile), UTF_8)))`
`try (Writer fileWriter = Files.newBufferedWriter(xmlFile))`

**Comment by ameyaKetkar** [comment]
@tsantalis  I found a similar case : https://github.com/elastic/elasticsearch/commit/e7aa7e909a370a54613e86592d58219c7326faaf#diff-e1bf824829b65dfab6121aba238ff3a9c8c5cb29111f7b6c7bfa14c1992b34a4L270

We missed this type change too !

**Comment by tsantalis** [comment]
This kind of class instance creation replaced with static method call are not matched with the current heuristics.

**Comment by ameyaKetkar** [comment]
That sounds like a good idea. 
Maybe this can generalize too(not just `try`). If all statements are matched except like 1 or 2 statements, you could report them without replacements.
