### ISSUE TITLE
Missing a Rename Class Refactoring

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#175]
A refactoring with descriotion  **Rename Class org.junit.internal.runners.TestClassMethodsRunner renamed to org.junit.internal.runners.JUnit4ClassRunner** is missing in [this commit](https://github.com/junit-team/junit4/commit/521fdb5aae536bd5055f6d0e4f09c5a7bdb5799f#diff-b27ecfad86bf139be5cf6bd0d5966529d9e2d457a58dc8d3667af63628a563cd)

**Comment by tsantalis** [comment]
@jodavimehran 
This case is detected with the current version (most recent commit) of RefactoringMiner.
