### ISSUE TITLE
A refactoring case study

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#178]
In [this commit](https://github.com/junit-team/junit5/commit/805d4dad6d3893b8e973019b824167d7b6f2cb8c), some refactorings performed and the method `private void execute(TestDescriptor testDescriptor, C parentContext, ExecutionTracker tracker)` is moved to a newly extracted class.

**Comment by tsantalis** [comment]
This case is a method move to a newly extracted inner class, with nested `Extract Method` refactorings
