### ISSUE TITLE
Missing a Change Parameter Type Refactoring

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#179]
A change parameter type Refactoring is missing.

Commit: [spring-framework/d3b43e](https://github.com/spring-projects/spring-framework/commit/d3b43ebccb923c6d5825b10d4f4f305b54ee549d)

File: [GenericConversionService.java](https://github.com/spring-projects/spring-framework/commit/d3b43ebccb923c6d5825b10d4f4f305b54ee549d#diff-1137048ce8b11fb607a9505e227eb98dca0924b39b4a0b626527471a2c3a2451)

Class: GenericConversionService
Method Before: `protected GenericConverter getConverter(Class sourceType, TypeDescriptor targetType)`
Method After   : `protected GenericConverter getConverter(TypeDescriptor sourceType, TypeDescriptor targetType)`

**Comment by tsantalis** [comment]
Two additional refactorings detected after the fix:
**Change Parameter Type** `sourceType : Class` to `sourceType : TypeDescriptor` in method `protected getConverter(sourceType TypeDescriptor, targetType TypeDescriptor) : GenericConverter` from class `org.springframework.core.convert.support.GenericConversionService`

**Extract Method** `private matchConverterByClassPair(sourceType Class, targetType Class) : GenericConverter` extracted from `protected getConverter(sourceType Class, targetType TypeDescriptor) : GenericConverter` in class `org.springframework.core.convert.support.GenericConversionService`
