### ISSUE TITLE
long-running commits

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#180]
This commit is one of the long-running commits that I've found:

[hibernate-orm/commit/9caca0](https://github.com/hibernate/hibernate-orm/commit/9caca0ce37d5a2763d476c6fa2471addcca710ca)

**Comment by tsantalis** [comment]
[org.hibernate.cfg.AnnotationBinder](https://github.com/hibernate/hibernate-orm/commit/9caca0ce37d5a2763d476c6fa2471addcca710ca#diff-0389f3acd0df80c656b8d6033ec71f0fc063a49f037115d63dde321f46af5df1) **46 methods with changed signatures**
`UMLClassBaseDiff.checkForOperationSignatureChanges()` : 47 removedOperations x 46 addedOperations

`UMLModelDiff.checkForOperationMovesBetweenCommonClasses()` : 404 removedOpersions x 325 addedOperations
`UMLModelDiff.checkForOperationMovesIncludingRemovedAndAddedClasses()` : 548 removedOperations x 3254 addedOperations
`UMLModelDiff.checkForExtractedAndMovedOperations()` : 298 addedAndExtractedOperationsInCommonClasses
`UMLModelDiff.checkForExtractedAndMovedOperations()` : 27 addedOperationsInMovedAndRenamedClasses
`UMLModelDiff.checkForMovedAndInlinedOperations()` : 286 removedAndInlinedOperationsInCommonClasses

Log file with all 1200 refactorings detected in this commit
[hibernate-orm.log](https://github.com/tsantalis/RefactoringMiner/files/6522894/hibernate-orm.log)

**Comment by jodavimehran** [comment]
Another long-running sample:

[hibernate-orm/commit/8c806d](https://github.com/hibernate/hibernate-orm/commit/8c806d361d63764e8523006944dde52aff70532c)

**Comment by jodavimehran** [comment]
[spring-framework/02a447](https://github.com/spring-projects/spring-framework/commit/02a4473c62d8240837bec297f0a1f3cb67ef8a7b)

**Comment by jodavimehran** [comment]
[spring-framework/02a4473c](https://github.com/spring-projects/spring-framework/commit/02a4473c62d8240837bec297f0a1f3cb67ef8a7b)

**Comment by tsantalis** [comment]
@jodavimehran 
Is it possible to get directly from Git, if two files are identical?

**Comment by jodavimehran** [comment]
> @jodavimehran
> Is it possible to get directly from Git, if two files are identical?

I haven't found any direct solution yet.
What is the problem of comparing file contents or hash code of file contents? Is it also expensive?

**Comment by jodavimehran** [comment]
> [spring-framework/02a4473c](https://github.com/spring-projects/spring-framework/commit/02a4473c62d8240837bec297f0a1f3cb67ef8a7b)
> 
> 25 `Move Source Folder` refactorings are detected in this commit [**processing time**: ~6 minutes]
> 
> > Move Source Folder org.springframework.test to spring-test
> > Move Source Folder org.springframework.context to spring-context
> > Move Source Folder org.springframework.web.portlet to spring-webmvc-portlet
> > Move Source Folder org.springframework.core to spring-core
> > Move Source Folder org.springframework.web.servlet to spring-webmvc
> > Move Source Folder org.springframework.web.struts to spring-struts
> > Move Source Folder org.springframework.web.portlet to spring-webmvc
> > Move Source Folder org.springframework.web to spring-tx
> > Move Source Folder org.springframework.transaction to spring-tx
> > Move Source Folder org.springframework.asm to spring-asm
> > Move Source Folder org.springframework.jdbc to spring-jdbc
> > Move Source Folder org.springframework.oxm to spring-oxm
> > Move Source Folder org.springframework.web.portlet to spring-web
> > Move Source Folder org.springframework.expression to spring-expression
> > Move Source Folder org.springframework.beans to spring-beans
> > Move Source Folder org.springframework.web.servlet to spring-tx
> > Move Source Folder org.springframework.transaction to spring-webmvc-portlet
> > Move Source Folder org.springframework.instrument to spring-instrument
> > Move Source Folder org.springframework.aop to spring-aop
> > Move Source Folder org.springframework.orm to spring-orm
> > Move Source Folder org.springframework.aspects to spring-aspects
> > Move Source Folder org.springframework.web to spring-web
> > Move Source Folder org.springframework.context.support to spring-context-support
> > Move Source Folder org.springframework.instrument.tomcat to spring-instrument-tomcat
> > Move Source Folder org.springframework.jms to spring-jms
> 
> An interesting optimization would be to avoid the processing of files which are 100% textually identically.
> In this commit, all files are move to different source folders without any change in their source code.

Another sample of the textually identical files:
[apache/lucene-solr/778d9675](https://github.com/apache/lucene-solr/commit/778d96752fa94636a2136ea2b4d58a3fcbe283ec)

**Comment by jodavimehran** [comment]
Another long-running sample:
[elastic/elasticsearch/99f88f15](https://github.com/elastic/elasticsearch/commit/99f88f15c5febbca2d13b5b5fda27b844153bf1a)

**Comment by jodavimehran** [comment]
[jetty.project/41ed9f29](https://github.com/eclipse/jetty.project/commit/41ed9f29f41263c9facede20bddfaafa669b43c5)

**Comment by jodavimehran** [comment]
[jetty.project/fa4c7b0c](https://github.com/eclipse/jetty.project/commit/fa4c7b0ca9a98af85ed200440de9720cea29bb52)

**Comment by tsantalis** [comment]
Updated the entire codebase to change the year in the header of all Java files
https://github.com/eclipse/jetty.project/commit/ac24196b0d341534793308d585161381d5bca4ac
