### ISSUE TITLE
Misses "final" keyword in parameter

### ISSUE THREAD

**Issue by max-ellis** [tsantalis/RefactoringMiner#181]
**Context**

RefactoringMiner detects that `addListener(L listener, boolean allowDuplicates)` is extracted from `addListener(L listener)`. In the commit, the developer extracted `addListener(final L listener, boolean allowDuplicates)` from `addListener(final L listener)`. RefactoringMiner does not give any information that L is final.

Project: https://github.com/apache/commons-lang

Merge Commit: 19dace1b

Start Commit: 71d7c326

End Commit: 4ccfde2b

Refactoring Commit: a48071b0

**Steps to reproduce:**

1. Clone https://github.com/apache/commons-lang
2. Use the detectBetweenCommits method using the start and end commit.

Or

2. > RefactoringMiner -bc <project-folder>  71d7c326  4ccfde2b

**Output**

`Extract Method public addListener(listener L, allowDuplicate boolean) : void extracted from public addListener(listener L) : void in class org.apache.commons.lang3.event.EventListenerSupport`

**Comment by tsantalis** [comment]
Hi @max-ellis 
Thank you for trying out the new feature with final modifier addition/removal in variables and parameters.
In this case, there is no change to be reported, because `listener` is `final` in the original method and remains `final` in the extracted method.
The tool reports only changes from non-final to final and vice versa.

**Comment by max-ellis** [comment]
Hi @tsantalis, thank you for the quick response as always. If there is a final modifier in the parameter, will RefMiner detect that it exists? For example, if the method in the refactoring commit has the signature `addListener(final L listener)`,  the refactoring object will show that the parameter is `listener L` and even if I use the `UMLParameter.toString()`, it misses the final modifier . Does RefMiner ignore the final modifier in this case, or is there some way to get the final modifier from the refactoring object?

**Comment by max-ellis** [comment]
Nevermind, I was looking through the methods again and I stumbled across `UMLParameter.isFinal()` which should meet my needs.

**Comment by tsantalis** [comment]
@max-ellis The `final` modifier does not appear in the signature of the methods in refactoring descriptions, but you can get this information through `UMLParameter.isFinal()` as you correctly found.
