### ISSUE TITLE
A Complex Example to Improve the Method's Mapping Algorithm

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#183]
Consider [this](https://github.com/apache/commons-lang/commit/5111ae7db08a70323a51a21df0bbaf46f21e072e) commit:

It seems to me that the following changes happened :
- [x] [`format(long, String)`](https://github.com/apache/commons-lang/commit/5111ae7db08a70323a51a21df0bbaf46f21e072e#diff-ad3693552a9088880c9418f7db7847718c91c98f33ac15bfbcaf14c971333b19L115) is renamed to `formatDuration(long, String)` and one of its parameters is renamed.

- [x] [`format(long, String, boolean, TimeZone)`](https://github.com/apache/commons-lang/commit/5111ae7db08a70323a51a21df0bbaf46f21e072e#diff-ad3693552a9088880c9418f7db7847718c91c98f33ac15bfbcaf14c971333b19L129) is renamed to `formatDuration(long, String, boolean)` and one of its parameters is removed.

- [x] [`formatDuration(Token[], int, int, int, int, int, int, int, boolean)`](https://github.com/apache/commons-lang/commit/5111ae7db08a70323a51a21df0bbaf46f21e072e#diff-ad3693552a9088880c9418f7db7847718c91c98f33ac15bfbcaf14c971333b19L187) is renamed to [`format(Token[], int, int, int, int, int, int, int, boolean)`](https://github.com/apache/commons-lang/commit/5111ae7db08a70323a51a21df0bbaf46f21e072e#diff-ad3693552a9088880c9418f7db7847718c91c98f33ac15bfbcaf14c971333b19R370).

- [x] [`format(long, long, String)`](https://github.com/apache/commons-lang/commit/5111ae7db08a70323a51a21df0bbaf46f21e072e#diff-ad3693552a9088880c9418f7db7847718c91c98f33ac15bfbcaf14c971333b19L235) is renamed to `formatPeriod(long, long, String)`.

- [x] [`format(long, long, String, boolean, TimeZone)`](https://github.com/apache/commons-lang/commit/5111ae7db08a70323a51a21df0bbaf46f21e072e#diff-ad3693552a9088880c9418f7db7847718c91c98f33ac15bfbcaf14c971333b19L235) is renamed to `formatPeriod(long, long, String, boolean, TimeZone)`.

But the refactorings that RefactoringMiner can detect for this commit are different than the above changes.

**Comment by tsantalis** [comment]
Confirmed refactorings:
Rename Method `public format(startMillis long, endMillis long, format String, padWithZeros boolean, timezone TimeZone) : String` renamed to `public formatPeriod(startMillis long, endMillis long, format String, padWithZeros boolean, timezone TimeZone) : String` in class `org.apache.commons.lang.time.DurationFormatUtils`

Rename Method `public format(millis long, format String, padWithZeros boolean, timezone TimeZone) : String` renamed to `public formatDuration(durationMillis long, format String, padWithZeros boolean) : String` in class `org.apache.commons.lang.time.DurationFormatUtils`

Rename Method `public formatWords(millis long, suppressLeadingZeroElements boolean, suppressTrailingZeroElements boolean) : String` renamed to `public formatDurationWords(durationMillis long, suppressLeadingZeroElements boolean, suppressTrailingZeroElements boolean) : String` in class `org.apache.commons.lang.time.DurationFormatUtils`
