### ISSUE TITLE
Feature Request : Command line option to set timeout when mining a local repository

### ISSUE THREAD

**Issue by ameyaKetkar** [tsantalis/RefactoringMiner#184]
Command line option to set a time out when mining local repository can be useful. Something like:
`**-ct** <git-repo-folder> <commit-sha1> **<timeout>** -json <path-to-json-file>`

**Comment by tsantalis** [comment]
@ameyaKetkar 
Sure, I can add this feature.
Do you have any commits that took too long to analyze. It would be interesting to examine the reasons it takes so long.
We recently did an improvement. I would like to check if this improvement works for other commits.

**Comment by ameyaKetkar** [comment]
Until now: 
`a0b004acb5965508782f5430c240f71580478832,elasticsearch
d84c643f5880a88d2e5c38b487123161f3e01fe0,elasticsearch
7cd128b372b0011814df76247bafbbf55709ae3f,elasticsearch
773876caee2e7e123094b9f2d0539e925cf0c13a,elasticsearch
28164ccf2e2d05c40f7a7f9bea4d3e9c9bae191e,elasticsearch
f055ad641ade5683a2b350d2bc61dd403d2daca3,elasticsearch
f74a78940cadf3c809bc0e23fb6fd71b55bec6f1,elasticsearch
b69e8aadbdab0902d989e2a52d63acf055a25b9c,elasticsearch
ff5527f0375b788a6562af96360fc34d0a083043,elasticsearch
5d5a9afb571e0a14e092cc19075385e3dee9e533,elasticsearch
f5f2149ff2c66cbe1d09c57d34fd56ae6d298272,elasticsearch
18a2cf23d4c0b08820ba01ccdc19689fd7207c26,elasticsearch
20ab4be59f072e21c3cb5877d4aebfae43e98680,elasticsearch
47c0e13a3b0f4c64e0fa36c5706c0260a777d68b,elasticsearch
75b4f408e05fc19de6fce775132239f1e22c99ac,elasticsearch
e5ee80c2924b97cab68e0daa3297a554071e8a88,elasticsearch
34bd72e69b4f0ff68b28fda99adcb3971bb94784,elasticsearch
220aa734ee19fe114376c764e2fbf41eee93e5c7,elasticsearch
99f88f15c5febbca2d13b5b5fda27b844153bf1a,elasticsearch
cec90f452a6d9763ae7d9f233747d86df722f192,elasticsearch
f3ec4a5208febeeca53a145861807a2dc43dac7f,elasticsearch
d63cd8c9c3c09f50fdef1ef607e0a27e4e0f6148,elasticsearch
9cc33f4e292309368ea871de802bf8a1da3cfbf5,elasticsearch
2efd22454a62e7387c51eb0cd973e5ff7a3fb09f,elasticsearch
8e1ef0cff93d30a130a106cbd4838fc68231f509,elasticsearch
8fc213f237ccffc12870a7a0d845c91d8ecbab3b,elasticsearch
5bc7822562a6eefa4a64743233160cdc9f431adf,elasticsearch
96d279ed83e25f427db86b831333ca6772202a91,elasticsearch
ec0dc2c0e900e1703dea29ddb56e4916618fc49e,elasticsearch
e294056bbf3ce579c41847d0bbe4a407f9f3f1cd,elasticsearch
5db7ed22a0aab6e630a89952ec94327d205fc3a3,elasticsearch
fe36861ada3e75259ff601a9f6b0e1cd5fbb8afe,elasticsearch
7ca5495d86093cd4673f7a96f6752406ac82cfda,elasticsearch
3b71a31557e2a9a2a5a7ab6aa77609b03eb3be7e,elasticsearch
a15f1ee4f64b19670b15a9c1526c7b0b0204ea60,elasticsearch
5fa36dad0b8503bef3d91173bb342da555445c26,elasticsearch
34675caef44577a96f984614a8c05c21dfb2b825,elasticsearch
c64f80b1f7149ee00e79f345c0edc6e2b605b515,elasticsearch
21a09be994653f358c28c900dfa0b0a072172a93,elasticsearch
a0513217dba5d964bf176c8f409baccfbd25359b,elasticsearch
70729f37d47e62c404c965d61da2ddbcaf29f18e,elasticsearch
cffee0e000b4164e0614ce6369ca1e0ac3e06659,elasticsearch
627d853f18c65a3ae7d23dd455db8b061eaad104,elasticsearch
a90c1de8745681356a6516f4f22a8c40f71f6b12,elasticsearch
95a7eed9aa35f47b228e402508709b5bd6703cf4,elasticsearch
f6feb6c2c845aaab31cec4b4047c77c2caf85b89,elasticsearch
78fcd0581d2981b48dfac5c63047e7fd14a248e8,elasticsearch
3b696828ada5953bb1669b972a353736383edf08,elasticsearch
dd99bef666dd02714c09f5c56bea49395a34c680,elasticsearch
1a3efc43292a23cb697108f294de3dfbe7ed8a0e,elasticsearch
ec3388ddbe9f7e69e1476749d780b47cb7dd8cce,elasticsearch
af179ab2f57066a69d110f89bb14ebcba60a08dc,elasticsearch
a92a647b9f17d1bddf5c707490a19482c273eda3,elasticsearch
71a9cfec79f7ecd0bdd3c85bcb919ae77449a24b,elasticsearch
c31cd981ebabc0747cabcc07a8c8797619ed2c53,hadoop
0afc036deb35df7e86ede3dcebc430c8f05ed368,hadoop
f4617c62395e65a4b0b42339208be05f6e93e2fd,hadoop
1e3a6efcef2924a7966c44ca63476c853956691d,hadoop
d1475ee86fb58ab70a6dc785d08f190189ede43d,flink
d5770fe8dd1486d457c87c17a7df8dba276e9bcd,flink
eb3a1741032795ab8db76b40c3614820a2529166,flink
228a3da1b974640c477d61b5390805b54e9610f9,flink
dcc1330375826b779e4902176bb2473704dabb11,flink
0af48012ec621f429b3abcfc4ca6e0d13ad44316,flink
e72a5a7ea41b307a0b6393d1988a5ebf90720e23,flink
e0afec8a7654334e3e9992433f5a0424d2ed51b8,flink
aa38468ff520f850eafadb463c696d105292f420,flink
c6997c97c575d334679915c328792b8a3067cfb5,flink
4881d9c308ccd6b5ca70925bf6ebedb70e7705fc,cassandra
af3fe39dcabd9ef77a00309ce6741268423206df,cassandra
356dc3c253224751cbf80b32cfce4e3c1640de11,cassandra
59b5b6bef0fa76bf5740b688fcd4d9cf525760d0,cassandra
207c80c1fd63dfbd8ca7e615ec8002ee8983c5d6,cassandra
f7431b432875e334170ccdb19934d05545d2cebd,cassandra
310a48efcfdc0fb77fbd5fd6e734bf17667f617d,cassandra
ccab496d2d37c86341d364dea6c27513fda27331,cassandra
a7c4ba9eeecb365e7c4753d8eaab747edd9a632a,cassandra
4213a2257429b6a0803ab1b52c39a6a35fbde889,graylog2-server
4e9d68fdf435de0b55a6852078ef557611bcaaef,graylog2-server
e496f28af4686e439e5fb7cf5455ff1ab13b0a1e,smile
78e01038b081e28c688bbd4744e8032025db5fc4,smile
f37298a37282c41f2675d42b812d7df2899fbe66,smile
4559a914111cb32b5998ee57bcfb2ea5fe718fdc,smile
d9918ced9edec03caab1c1700ebe51d8e3cabd1f,smile
17de173cb5334d866f1886d3e057f49a6c987bad,hibernate-orm
87e3f0fd28d7229b0a35032292ff32f542c22010,hibernate-orm
ac4f4ff4ad3c260c5ec996ba668a7760c8c429bf,hibernate-orm
`

**Comment by ameyaKetkar** [comment]
One more command line option would be very helpful 
**-xt** <git-url> <clone-To-Folder> <commit-sha1> **<timeout>** -json <path-to-json-file>

**Comment by tsantalis** [comment]
@ameyaKetkar 
How many seconds did you set for the timeout?

**Comment by ameyaKetkar** [comment]
200 seconds!

**Comment by tsantalis** [comment]
[a0b004acb5965508782f5430c240f71580478832.log](https://github.com/tsantalis/RefactoringMiner/files/6593286/a0b004acb5965508782f5430c240f71580478832.log) [processing time: ~6 minutes]

**Comment by tsantalis** [comment]
@ameyaKetkar 
Could you please process the commits in the [timeout.txt](https://github.com/tsantalis/RefactoringMiner/files/6580420/timeout.txt) with a longer `timeout` ?
It seems these commits just needed a bit more time, because they are large commits.
Please let me know about the results.
