### ISSUE TITLE
Refactored or Removed, that is the question!

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#186]
Is the following method refactored or Removed?

Commit: [junit-team/junit5/cbf97077](https://github.com/junit-team/junit5/commit/cbf97077bae0db71dc3a7cade28c3b00587a8699)

file: [junit-launcher/src/main/java/org/junit/gen5/launcher/Launcher.java](https://github.com/junit-team/junit5/commit/cbf97077bae0db71dc3a7cade28c3b00587a8699#diff-debee5bcc60ae015e17aa8ddf07a4c04cf4df2b353d8b3b5f0139cc62bee2f4c)

Class: **org.junit.gen5.launcher.Launcher**

Before: [`public void execute(TestExecutionPlan testPlan) throws Throwable`](https://github.com/junit-team/junit5/commit/cbf97077bae0db71dc3a7cade28c3b00587a8699#diff-debee5bcc60ae015e17aa8ddf07a4c04cf4df2b353d8b3b5f0139cc62bee2f4cL40)
After: [`public void execute(TestPlan testPlan)`](https://github.com/junit-team/junit5/commit/cbf97077bae0db71dc3a7cade28c3b00587a8699#diff-debee5bcc60ae015e17aa8ddf07a4c04cf4df2b353d8b3b5f0139cc62bee2f4cR21)

**Comment by tsantalis** [comment]
There are only two statements mapped between these two methods:
```java
engine.execute(testDescriptions); -> testEngine.execute(tests);
for(engine: discoverEngines()) -> for(testEngine: lookupAllTestEngines())
```

**NonMappedLeavesT1**:
```java
Map<TestIdentifier,TestDescriptor> engineTestDescriptions=testDescriptionsByEngine.get(engine.getId());
List<TestIdentifier> testIdentifiers=testPlan.getTestIdentifiers();
List<TestIdentifier> filtered=engineTestDescriptions.keySet().stream().filter(testIdentifier -> testIdentifiers.contains(testIdentifier)).collect(Collectors.toList());
List<TestDescriptor> testDescriptions=new ArrayList<>();
testDescriptions.add(lookup(engine,testIdentifier));
```
**NonMappedLeavesT2**:
```java
List<TestDescriptor> tests=testPlan.getAllTestsForTestEngine(testEngine);
```
**NonMappedInnerNodesT1**:
```java
for(testIdentifier: filtered)
```

These two methods cannot be matched due to  a large number of unmatched statements.
The implementation has completely changed.
