### ISSUE TITLE
Missing refactorings related to duplicate annotations 

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#187]
In [this commit](https://github.com/javaparser/javaparser/commit/c9f2a4fe27453e09a268730cd0ab76a42016475f), some duplicate annotations are removed, but it seems since they are identical, RefactoringMiner doesn't report the removals as refactoring.

**Comment by tsantalis** [comment]
@jodavimehran 
This is due to the way equals and hashCode is implemented for annotations. Lexically identical annotations are considered equal.
This is a very weird case. The code is generated, and probably the generation caused duplicate annotations.

**Comment by jodavimehran** [comment]
> @jodavimehran
> This is due to the way equals and hashCode is implemented for annotations. Lexically identical annotations are considered equal.
> This is a very weird case. The code is generated, and probably the generation caused duplicate annotations.
> 
> I don't think it's really worth to add location in equals and hashCode, but that's the only way to solve this issue.

I found another way to handle this kind of situation.

Thanks.
