### ISSUE TITLE
Can we do refactoring in our source code? 

### ISSUE THREAD

**Issue by masoudnep** [tsantalis/RefactoringMiner#188]
hello , im beginer in your source code and As I understand , this library just detect refactorings, but dont do refactoring in any source code if im wrong please please give me example.

**Comment by masoudnep** [comment]
im sorry the other question is the source code must be in github that refactoring miner detect refactorings? or we can use our source code without github like Jdeodrant

**Comment by tsantalis** [comment]
@masoudnep 
For the first question, the tool does not apply refactorings.
For the second question, you can run the tool on two directories containing two versions of the same source code
https://github.com/tsantalis/RefactoringMiner#with-two-directories-containing-java-source-code
