### ISSUE TITLE
Missing Refactorings

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#189]
The following refactorings are missing:

**Change Parameter Type** _system : boolean_ to _caseSensitivity : IOCase_ in method `public wildcardMatch(filename String, wildcardMatcher String, caseSensitivity IOCase) : boolean` from class org.apache.commons.io.FilenameUtils

**Rename Parameter** _system : boolean_ to _caseSensitivity : IOCase_ in method `public wildcardMatch(filename String, wildcardMatcher String, caseSensitivity IOCase) : boolean` from class org.apache.commons.io.FilenameUtils

**Change Method Access Modifier** _private_ to _public_ in method `public equals(filename1 String, filename2 String, normalized boolean,  caseSensitivity IOCase) : boolean` from class org.apache.commons.io.FilenameUtils

**Remove Parameter** _system : boolean_  in method `public equals(filename1 String, filename2 String, normalized boolean,  caseSensitivity IOCase) : boolean` from class org.apache.commons.io.FilenameUtils

**Add Parameter** _caseSensitivity : IOCase_  in method `public equals(filename1 String, filename2 String, normalized boolean,  caseSensitivity IOCase) : boolean` from class org.apache.commons.io.FilenameUtils

commit: [apache/commons-io/07751ea9](https://github.com/apache/commons-io/commit/07751ea95c575cb95a310a23a78dc8cbe85b27a9#diff-9a379719584375caea037e4c1621ba38231695f8300700a7e4a3110dbeef00e0R1114)

**Comment by tsantalis** [comment]
@jodavimehran 
The tool internally matches the `wildcardMatch` methods
This the `toString` outcome of the corresponding `UMLOperationDiff` object
> private wildcardMatch(filename String, wildcardMatcher String, system boolean) : boolean
> 	visibility changed from private to public
> 		parameter system boolean:
> 		type changed from boolean to IOCase
> 		name changed from system to caseSensitivity

but in the code changes inside the method, there is no replacement of
`system` with `caseSensitivity`, and thus it is not reported as a refactoring.
To me it seems like new parameter enables new functionality in the method.

The `equals` methods are not matched because the

**Comment by tsantalis** [comment]
The parameter changes in `wildcardMatch` methods are reported as:
> Remove Parameter system : boolean in method private wildcardMatch(filename String, wildcardMatcher String, system boolean) : boolean from class org.apache.commons.io.FilenameUtils
> Add Parameter caseSensitivity : IOCase in method public wildcardMatch(filename String, wildcardMatcher String, caseSensitivity IOCase) : boolean from class org.apache.commons.io.FilenameUtils
