### ISSUE TITLE
Should this be a move and rename class refactoring?

### ISSUE THREAD

**Issue by max-ellis** [tsantalis/RefactoringMiner#190]
**Context**

There is a case that appears to just be a rename class refactoring but is detected as a move and rename class refactoring. 

**Environtment**

RefactoringMiner 2.0

**Details**

Git Repository: https://github.com/google/error-prone
Refactoring Commit: 5a13bac8

**Output**
Refactoring Detail: "Move And Rename Class	Poo moved and renamed to Poo1.Poo2"
File Location: core/src/test/resources/com/google/errorprone/MultipleTopLevelClassesWithErrors.java

In the Git history, the class Poo is renamed to Poo1, then Poo2 and Poo3 is added to the same file. I do not believe a move ever happens.

**Comment by tsantalis** [comment]
There is a lot of ambiguity in `MultipleTopLevelClassesWithErrors` as all `poo()` methods have an identical body.
As a matching problem, there are many possible solutions.
a) `Poo` is renamed to `Poo3`, then `Poo1` with its nested `Poo2` are added
b) `Poo` is renamed to `Poo1`, then nested `Poo2` and `Poo3` are added

I agree both of these solutions are better than the `Move and Rename Class`
