### ISSUE TITLE
Misses change package refactoring

### ISSUE THREAD

**Issue by max-ellis** [tsantalis/RefactoringMiner#191]
**Context**

RefMiner detects three move and rename refactorings. The packages that these classes are in are renamed and in the process, the classes are renamed too. Is this something that should be reported as change package refactorings as well as move + rename refactorings?

**Environment**

RefactoringMiner 2.0

**Details**

Git Repository: https://github.com/CamelCookbook/camel-cookbook-examples
Refactoring Commit: fb613175

**Output**

Move + Rename Class 1: "Move And Rename Class	org.camelcookbook.error.dlq.DlqRouteBuilder moved and renamed to org.camelcookbook.error.dlc.DlcRouteBuilder"

Move + Rename Class 2: "Move And Rename Class	org.camelcookbook.error.dlq.DlqSpringTest moved and renamed to org.camelcookbook.error.dlc.DlcSpringTest"

Move + Rename Class 3: "Move And Rename Class	org.camelcookbook.error.dlq.DlqTest moved and renamed to org.camelcookbook.error.dlc.DlcTest"

**Additional Details**

`git show fb613175` results in:

 `-package org.camelcookbook.error.dlq;`
 `+package org.camelcookbook.error.dlc;`

**Comment by tsantalis** [comment]
@max-ellis 
Thank you for reporting this issue.
I check the code, and package changes are inferred from `Move Class` refactorings, but not from `Move And Rename Class` refactorings. This needs to be fixed.
