### ISSUE TITLE
Is it possible to get details about other methods in the original method's class?

### ISSUE THREAD

**Issue by max-ellis** [tsantalis/RefactoringMiner#192]
I am trying to programmatically undo a move method refactoring using the information stored in the RefMiner objects. Unfortunately, moving a method from one class to another does not necessarily put it in the original location within the class. If I have the information about which method came before it, I could just move it back to the original class then move it under that method. I noticed that classDiff stores that information but it's private and there's no way to access it. 

Is there currently any way to retrieve this information from the UMLOperation object that I haven't noticed? If not, would it be possible to add a getter to UMLOperation for this information?

**Comment by tsantalis** [comment]
@max-ellis 
All program elements reported in refactorings (including `UMLOperation`) have a `LocationInfo` object that has the exact location of the program element inside its source file.
Isn't that enough to place the moved method back to its original location?

What library are you using for undoing the refactorings?
I have some experience with Eclipse JDT `ASTRewrite` API.

**Comment by max-ellis** [comment]
@tsantalis 
Thank you for the quick response. I'm actually using the text offset inside of `LocationInfo` right now and it is working. I'm concerned that if the developer adds several lines of code before the original method location in a future commit, then using the text offset will move the method to the wrong position. For example, if method `foo()` comes before method `bar()`, and method `bar()` is moved, then if the developer adds several lines to a method before `foo()`, I think `bar()` would be moved to a location before `foo()`. I haven't run into a situation where this happens yet but I'm pretty sure this will be a case that I run into.

I'm using the IntelliJ refactoring engine. I'm using their move method processor to move the method to the original class. After I perform the move, I find the method that comes before the moved method's original text offset and modify the PSI tree using that. If I have the information about the methods that come before the originally moved method, then I could use the method signature to find the correct position in the PSI tree and I think that would be more accurate than using the text offset.

**Comment by tsantalis** [comment]
@max-ellis 
The easiest solution is to call from `UMLModelDiff` object, the method
`public UMLAbstractClass findClassInParentModel(String className)`
or
`public UMLAbstractClass findClassInChildModel(String className)`
and then call though the returned `UMLAbstractClass` object
the method
`public List<UMLOperation> getOperations()`
This gives you the methods of the class in order.
Doing a simple `indexOf(UMLOperation)` will give you the position of the method.
and then using `get(int)` you can get the methods before and after.

**Comment by max-ellis** [comment]
Thank you @tsantalis, that's incredibly helpful.
