### ISSUE TITLE
Missed a Type Change

### ISSUE THREAD

**Issue by ameyaKetkar** [tsantalis/RefactoringMiner#193]
https://github.com/vaadin/framework/commit/d36d63fefa3ab9f4908f97772bcc6499e4f52532#diff-aacde06a1d4007d12aeacdc9ca0ca5f616b772435a1aad01b61f9f4e9d4359ffL144

**FIXED** in commit https://github.com/tsantalis/RefactoringMiner/commit/cd681e54355eaf22a2233a41ef3fe9f57c3f78e1

**Comment by ameyaKetkar** [comment]
Missed reporting the mapping for return statement 
https://github.com/javaparser/javaparser/commit/ee729dcafee513#diff-21c398ea2bcb58f93aab7bcf4d7803ac9cda27173547b622dde34e9751cf8a36L37

**Comment by ameyaKetkar** [comment]
Missed reporting references of for this parameter
https://github.com/javaparser/javaparser/commit/ee729dcafee513#diff-a1646f984a7cdfbf5fb5a49d4e76a58867ca4c21b65bbccc832165f54b687dd7R181
and this parameter
https://github.com/javaparser/javaparser/commit/ee729dcafee513#diff-a1646f984a7cdfbf5fb5a49d4e76a58867ca4c21b65bbccc832165f54b687dd7R199

**Comment by tsantalis** [comment]
@ameyaKetkar 
Parameter `path` is only used on the right side
`File file = path.toFile();` to convert path` to `file`
As a result, there is no mapping.
Should we add the non-mapped statements referencing the variables?

**Comment by ameyaKetkar** [comment]
@tsantalis  I see what you are saying. I don't think there is any need to report the non-mapped statements referencing the variables. 
Actually, now that I remember why pasted this link here. 
If you look at this line: https://github.com/javaparser/javaparser/commit/ee729dcafee513#diff-a1646f984a7cdfbf5fb5a49d4e76a58867ca4c21b65bbccc832165f54b687dd7L201 

I feel this is easy scenario (`solveMethodCalls` is a recursive method) to capture updated argument when a change parameter type is performed.

**Comment by tsantalis** [comment]
@ameyaKetkar If I understand correctly you would like the mappings of recursive method calls to be added in the variable references?

**Comment by ameyaKetkar** [comment]
yes! thats the correct requirement.

**Comment by tsantalis** [comment]
Technically speaking, the variables referenced in the recursive calls are local variables `File f` whose type has not changed, and have nothing to do with the method parameters `File file` and `Path path`.

**Comment by ameyaKetkar** [comment]
As far as I understood the change, the adaptation `f` -> `f.toPath()` was performed because the parameter type was changed from `File` to `Path`.
