### ISSUE TITLE
The reported line numbers should account for the comments

### ISSUE THREAD

**Issue by ameyaKetkar** [tsantalis/RefactoringMiner#195]
I observed that when RMiner reports line numbers for UMLOperations it reports the line at which the associated comments begins. It would be convenient if it could find where the method actually starts at. 
I don't know if this is an intended behavior. 

for instance 
1: /* 
2: * abc
3: * /
4: void getFoo();

For the above example, RMiner will report 1 not 4.

**Comment by tsantalis** [comment]
@ameyaKetkar 
When a method declaration has Javadoc, Eclipse JDT Parser considers the Javadoc as part of the method, and returns the start offest of the Javadoc as the start offset of the method declaration.

**Comment by ameyaKetkar** [comment]
ok ok .  I ll mark this closed then!
