### ISSUE TITLE
Not Matched Variable, Reported as removed and added

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#199]
A variable that supposes to be matched is reported as added and removed variable.

commit: [checkstyle/fbf3f95c](https://github.com/checkstyle/checkstyle/commit/fbf3f95c2273be23b966cba6e6ef89390a6fb020)

Class: [JavadocMethodCheck](https://github.com/checkstyle/checkstyle/commit/fbf3f95c2273be23b966cba6e6ef89390a6fb020#diff-0018a9fb4a27ce36af7b7b6825e71398036d8191d048258a79f4abecfa6995e8)

Method: checkThrowsTags(List, List, boolean)
Variable: `final Token token = exceptionInfo.getName();` Line: 919

In this method, there is another variable with the same name and type but different scope. Maybe that is the problem.
The other variable: `final Token token = new Token(tag.getFirstArg(), tag.getLineNo(), tag.getColumnNo());` Line: 892

**Comment by tsantalis** [comment]
The statement in the scope of `final Token token = exceptionInfo.getName();` is
`log(token.getLineNo(), token.getColumnNo(), MSG_EXPECTED_TAG, JavadocTagInfo.THROWS.getText(), token.getText());`
but the mapping is the parent statements including the lambda expression.
```java
throwsList.stream().filter(exceptionInfo -> !exceptionInfo.isFound())
                .forEach(exceptionInfo -> {
                    final Token token = exceptionInfo.getName();
                    log(token.getLineNo(), token.getColumnNo(),
                        MSG_EXPECTED_TAG,
                        JavadocTagInfo.THROWS.getText(), token.getText());
});
```
