### ISSUE TITLE
Not Matched Parameter (Variable)

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#200]
Parameter `aErrors : LocalizedMessage[]` in method `public fireErrors(aFileName String, aErrors LocalizedMessage[]) : void` from class `com.puppycrawl.tools.checkstyle.Checker` is not listed in the matched variable set in this [commit](https://github.com/checkstyle/checkstyle/commit/e50e1fcd1c17ba1f73d11df38382907cc163a1d1#diff-b48cc2ff38026f94180847550cd260a0ebefb4a9cb9635e39f5fa2046311d72bL468).

The reason is that all statements using the parameter are changed in this commit and couldn't be matched.

**FIXED** in commit https://github.com/tsantalis/RefactoringMiner/commit/f0d29e62b026686445deb05c32c911476d721854

**Comment by jodavimehran** [comment]
Similar problem:
Commit: [checkstyle/3a20dbe8](https://github.com/checkstyle/checkstyle/commit/3a20dbe8edafe0cca300b7b9dfa48effa9a36a06#diff-650e834bca871d6bf6c1b3800ff4116b2d7ab4fe5de6489a042652c2f72e024dL524)

parameter: `fileName : String`
method: `protected fireErrors(aFileName String, aErrors LocalizedMessage[]) : void` 
class: `com.puppycrawl.tools.checkstyle.Checker`

**Comment by jodavimehran** [comment]
Commit: [checkstyle/82b2ba52](https://github.com/checkstyle/checkstyle/commit/82b2ba526976588d550cac698e512f8de6c1ffc6#diff-b48cc2ff38026f94180847550cd260a0ebefb4a9cb9635e39f5fa2046311d72bL255)

parameter: `aFileName : String`
method: `protected fireErrors(aFileName String, aErrors LocalizedMessage[]) : void`
class: `com.puppycrawl.tools.checkstyle.Checker`

**Comment by jodavimehran** [comment]
Commit: [checkstyle/d46c2cf0](https://github.com/checkstyle/checkstyle/commit/d46c2cf0e9df06bb5f424dbd7645574f082f7609#diff-650e834bca871d6bf6c1b3800ff4116b2d7ab4fe5de6489a042652c2f72e024dL250)

parameter: `files : List<File>`
method: `public process(files List<File>) : int`
class: `com.puppycrawl.tools.checkstyle.Checker`

**Comment by tsantalis** [comment]
All cases fixed in this issue.
