### ISSUE TITLE
Miss Matched Variable and Parameter

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#202]
In [this](https://github.com/apache/flink/commit/536675b03a5050fda9c3e1fd403818cb50dcc6ff#diff-a1603ed1cd2ebca94e14e1ab0d09f6c71ab1730b45d384673fdb6db61b947e21) commit, parameter `uri : URI` is renamed to `fsUri : URI` in method `public getUnguardedFileSystem(fsUri URI) : FileSystem` from class `org.apache.flink.core.fs.FileSystem`.

At the same time, a variable is added with the same name of the parameter before rename. As a result, the newly added variable is matched with the parameter, and the renamed parameter is reported as an added variable which I think is not true.

**Comment by tsantalis** [comment]
There are 3 identical mappings that give us confidence that parameter `uri` became local variable `uri`
`String supposedUri="file:///" + uri.getAuthority() + uri.getPath();`
`String supposedUri="file:///" + uri.getAuthority() + uri.getPath();`

`throw new IOException("Found local file path with authority '" + uri.getAuthority() + "' in path '"+ uri.toString()+ "'. Hint: Did you forget a slash? (correct path would be '"+ supposedUri+ "')");`
`throw new IOException("Found local file path with authority '" + uri.getAuthority() + "' in path '"+ uri.toString()+ "'. Hint: Did you forget a slash? (correct path would be '"+ supposedUri+ "')");`

`final FSKey key=new FSKey(uri.getScheme(),uri.getAuthority());`
`final FSKey key=new FSKey(uri.getScheme(),uri.getAuthority());`
