### ISSUE TITLE
Missing Rename Parameter

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#210]
commit [jetty.project/e35c51eb](https://github.com/eclipse/jetty.project/commit/e35c51eb7d91d099e7e84e308d30010ecaa6a0c5#diff-3d992a4ede3043ab7665b3fb1dc744b4e03c5a9782aed423c397058633a3e229L69)

method before `public void send(MetaData.Response info, boolean head, ByteBuffer content, boolean lastContent, Callback callback)`
method after `public void send(MetaData.Response info, boolean isHeadRequest, ByteBuffer content, boolean lastContent, Callback callback)`

file [HttpTransportOverHTTP2.java](https://github.com/eclipse/jetty.project/commit/e35c51eb7d91d099e7e84e308d30010ecaa6a0c5#diff-3d992a4ede3043ab7665b3fb1dc744b4e03c5a9782aed423c397058633a3e229)

**Comment by tsantalis** [comment]
local variable `boolean isHeadRequest = head;` becomes parameter `boolean isHeadRequest`

**Comment by jodavimehran** [comment]
> local variable `boolean isHeadRequest = head;` becomes parameter `boolean isHeadRequest`

So, we just need to have a Remove Parameter Refactoring for `boolean head`

**Comment by tsantalis** [comment]
`Remove Parameter head : boolean in method public send(info MetaData.Response, head boolean, content ByteBuffer, lastContent boolean, callback Callback) : void from class org.eclipse.jetty.http2.server.HttpTransportOverHTTP2`
`Parameterize Variable isHeadRequest : boolean to isHeadRequest : boolean in method public send(info MetaData.Response, isHeadRequest boolean, content ByteBuffer, lastContent boolean, callback Callback) : void from class org.eclipse.jetty.http2.server.HttpTransportOverHTTP2`
