### ISSUE TITLE
Extra Change Parameter Type and Rename Parameter Refactoring

### ISSUE THREAD

**Issue by jodavimehran** [tsantalis/RefactoringMiner#211]
I [this](https://github.com/checkstyle/checkstyle/commit/822384a711290170148b43b5ae390dd4e8cfaf4f#diff-b48cc2ff38026f94180847550cd260a0ebefb4a9cb9635e39f5fa2046311d72bL184) commit, two refactorings (one parameterize variable and one localize parameter) have been performed on a method.
method before: `private int process(String aFileName)`
method after: `private int process(File aFile)`

There are two other refactrings also related to this method which are extra: 
_Change Parameter Type_ `aFileName : String` to `aFile : File`  in method `private process(aFile File) : int`  from class `com.puppycrawl.tools.checkstyle.Checker`

_Rename Parameter_ `aFileName : String` to `aFile : File`  in method `private process(aFile File) : int`  from class `com.puppycrawl.tools.checkstyle.Checker`

**Comment by jodavimehran** [comment]
For this case, we also miss two possible rename variable refactoring

variable `final File f = new File(aFileName);` became to parameter `File aFile`
parameter `String aFileName` became to local variable `final String fileName = aFile.getPath();`

**Comment by tsantalis** [comment]
The renames are implied in the `Parameterize Variable` and `Localize Parameter` refactorings.
