### ISSUE TITLE
Missing "Move Method" refactoring

### ISSUE THREAD

**Issue by egor-bogomolov** [tsantalis/RefactoringMiner#212]
Hello, thanks for a great tool! I'm analyzing [a commit from Git repo](https://github.com/greenrobot/EventBus/commit/794096aa09bb854dae45e662711454f7b1570cc8) and getting the refactorings listed below. If we look at the change list in the commit, we can see that both `testSubscribeUnSubscribeAndPostMixedEventType` method and `SubscribeUnsubscribeThread` class were moved to another file without changes. RefactoringMiner finds move for all methods from the class but fails to detect move of `testSubscribeUnSubscribeAndPostMixedEventType`. What is the reason for it, am I missing something?

> Refactorings at 794096aa09bb854dae45e662711454f7b1570cc8:
> 
> * Move Source Folder	EventBusTest/src to EventBusTestJava/src/main/java
> * Change Method Access Modifier	private to package in method package runThreadsMixedEventType(count int, threadCount int) : void from class org.greenrobot.eventbus.EventBusMultithreadedTest
> * Move Method	public shutdown() : void from class org.greenrobot.eventbus.EventBusMultithreadedTest.SubscribeUnsubscribeThread to public shutdown() : void from class org.greenrobot.eventbus.EventBusAndroidMultithreadedTest.SubscribeUnsubscribeThread
> * Move Method	public run() : void from class org.greenrobot.eventbus.EventBusMultithreadedTest.SubscribeUnsubscribeThread to public run() : void from class org.greenrobot.eventbus.EventBusAndroidMultithreadedTest.SubscribeUnsubscribeThread
> * Move Method	public onEventMainThread(event String) : void from class org.greenrobot.eventbus.EventBusMultithreadedTest.SubscribeUnsubscribeThread to public onEventMainThread(event String) : void from class org.greenrobot.eventbus.EventBusAndroidMultithreadedTest.SubscribeUnsubscribeThread
> * Move Method	public onEventBackgroundThread(event Integer) : void from class org.greenrobot.eventbus.EventBusMultithreadedTest.SubscribeUnsubscribeThread to public onEventBackgroundThread(event Integer) : void from class org.greenrobot.eventbus.EventBusAndroidMultithreadedTest.SubscribeUnsubscribeThread
> * Move Method	public onEvent(event Object) : void from class org.greenrobot.eventbus.EventBusMultithreadedTest.SubscribeUnsubscribeThread to public onEvent(event Object) : void from class org.greenrobot.eventbus.EventBusAndroidMultithreadedTest.SubscribeUnsubscribeThread
> * Move Method	public onEventAsync(event Object) : void from class org.greenrobot.eventbus.EventBusMultithreadedTest.SubscribeUnsubscribeThread to public onEventAsync(event Object) : void from class org.greenrobot.eventbus.EventBusAndroidMultithreadedTest.SubscribeUnsubscribeThread

**Comment by tsantalis** [comment]
@egor-bogomolov 
Thank you for reporting this issue. I will look into it as soon as possible

**Comment by tsantalis** [comment]
One new refactoring is detected after the fix:
> Push Down Method public testSubscribeUnSubscribeAndPostMixedEventType() : void from class org.greenrobot.eventbus.EventBusMultithreadedTest to public testSubscribeUnSubscribeAndPostMixedEventType() : void from class org.greenrobot.eventbus.EventBusAndroidMultithreadedTest
