### ISSUE TITLE
gradlew - Required Java Version?

### ISSUE THREAD

**Issue by TahLoow** [tsantalis/RefactoringMiner#215]
Hello! When I run gradlew to build, I get a failed build with this output standing out:
**class file has wrong version 55.0, should be 52.0**

In the past, I fixed this by dropping my java version, but I can't remember which. Is there a particular version that this software is restricted to? Or one that you are using currently?

OS: Windows 10
Jre: 1.8.0_301
Jdk: 1.8.0_301
Gradle: 7.2

**Comment by tsantalis** [comment]
Dear @TahLoow 
Please use Java 11.
Although the source code of RefactoringMiner is still compatible with Java 8, its dependencies require Java 11.
