### ISSUE TITLE
Work with bare repos

### ISSUE THREAD

**Issue by ErikBrendel** [tsantalis/RefactoringMiner#222]
In order to operate on a bare git repo, when opening it, the user wants to directly provide the path to the git directory. Adding "/.git" to it breaks the program. Relevant line:

https://github.com/tsantalis/RefactoringMiner/blob/d15b2932b1811ee1afd39a8cab9fbda1655f2081/src/org/refactoringminer/util/GitServiceImpl.java#L109

For working with the command line, it would be awesome to have a flag (e.g. `--bare`) to indicate this.

**Comment by tsantalis** [comment]
@ErikBrendel 
I think you will like my fix even more.

**Comment by ErikBrendel** [comment]
Beautiful, thank you very much :+1:
