### ISSUE TITLE
Get file before and after refactoring. 

### ISSUE THREAD

**Issue by rdurelli** [tsantalis/RefactoringMiner#224]
Does anyone know how to get the source code before and after a refactoring? Is it possible? Thanks.

**Comment by tsantalis** [comment]
Hi @rdurelli 
RefactoringMiner does not store the actual source code snippets related to a refactoring to avoid redundant memory consumption.
Instead, it provides a lightweight `CodeRange` object including the following properties:
```java
String filePath
int startLine
int endLine
int startColumn
int endColumn
```
You can find more info in the following link
https://github.com/tsantalis/RefactoringMiner#location-information-for-the-detected-refactorings

If you have the corresponding file blobs, you can easily extract the refactored source code snippets.

**Comment by rdurelli** [comment]
@tsantalis Thanks. It helps me. However, as I need to access the source code "before" and "after".. i went straight to the source code and I have investigated the method detectRefactorings in GitHistoryRefactoringMinerImpl.. then I could find the following: 

`Map<String, String> fileContentsBefore = new ConcurrentHashMap<String, String>();
 Map<String, String> fileContentsCurrent = new ConcurrentHashMap<String, String>();`

I dunno if this is the best way.. but it help me. Thanks

**Comment by tsantalis** [comment]
Hi @rdurelli 
Yes, you are right.
`fileContentsBefore` and `fileContentsCurrent` are two maps where the keys are file paths and the values are file contents for the parent and child commit, respectively.

So, you can use the `filePath` from the `CodeRange` object to get the corresponding file contents from the map.
