### ISSUE TITLE
RefactoringMiner API's -JSON flag outputs empty "leftSideLocation" and "rightSideLocation"

### ISSUE THREAD

**Issue by djaekim** [tsantalis/RefactoringMiner#226]
Expected output:
https://github.com/apache/commons-collections/commit/adac97557392145d360644f3c97a44ad991642b6
![image](https://user-images.githubusercontent.com/26092570/151097060-aed860b6-8bb7-4c12-affa-44cab0643752.png)

Real output:
https://github.com/apache/commons-collections/commit/8ffb78ec50a5d3a79dbd0e76c36c50f3263594aa
![image](https://user-images.githubusercontent.com/26092570/151097106-49bff935-5538-4e26-8734-e89b5c88be9d.png)

**Comment by tsantalis** [comment]
@djaekim 
This is due to a performance improvement. RefactoringMiner is skipping the parsing and processing of files that are **identical** have **trivial changes**, such as changes in comments and/or import statements.
`TestSplitMapUtils.java` has only changes in the Javadoc of the class.
