### ISSUE TITLE
Silent Hanging in 2.2

### ISSUE THREAD

**Issue by TahLoow** [tsantalis/RefactoringMiner#234]
Hello,

I've been trying to run pre-compiled Refactoring Miner 2.2 on a local install of the Beam repository (github.com/apache/beam). I've had output grow between 100,000KB and 120,000KB before hanging on some random commit for over twelve hours with no file changes, no exit from the refactoring miner process, and the last logged commit being several years from the target. To put into context, Refactoring Miner 2.1 usually analyzes Beam's entirety within two hours. The other three projects I analyzed with 2.2 had no difficulties. 

This is the command I used:

RefactoringMiner.bat -a path\to\beam master -json beam_out.json

I tried to skip over potentially offending commits with little success. The following command generated only 10KB of data before hanging for several hours. Hopefully this issue reproduces on your end. 

RefactoringMiner.bat -bc path\to\beam 94a8f294176bed869cf4c88ebdae11f4bb482df2 f7d9e6ac93e1e9e9ed4aa9047c1b432c429f13bc -json beam_temp.json

Thank you for efforts

**Comment by tsantalis** [comment]
The problematic commit is https://github.com/apache/beam/commit/916e0393e7301d6682d1f1d5a6589231d7892cb2

**Comment by tsantalis** [comment]
Dear @TahLoow 
The issue has been fixed and the commit is processed in 3 seconds after the fix.
If you want to use the fix, please build RefactoringMiner from the latest commit.
