### ISSUE TITLE
The program doesn't finish with commit: https://github.com/apache/derby/commit/a6026ca86d4175d28351a45ddd8affe18270f26f

### ISSUE THREAD

**Issue by victor0624** [tsantalis/RefactoringMiner#236]
I ran from the command line, for the commit: https://github.com/apache/derby/commit/a6026ca86d4175d28351a45ddd8affe18270f26f. The program has run for 4 hours, and it is still running. What happend?

**Comment by tsantalis** [comment]
Possibly some kind of combinatorial explosion when matching statements. I will look into it.
