### ISSUE TITLE
Extract Method is wrongly reported as Rename Method (Mock Java Test case)

### ISSUE THREAD

**Issue by mkshiblu** [tsantalis/RefactoringMiner#237]
##### Problem

Simplified Java recreation of a chart js extract method is wrongly reported as Rename method.

#### Steps to Reproduce

1. Go to -
       https://github.com/mkshiblu/practice/commit/cd0b49426b9d02a236f518a652f5737ea33fc400
2.  Run the chrome extension 

#### Observed Behavior
The extension reported that method *drawCaret()* has been renamed to *getCaretPosition()*

#### Expected Behavior
The extension should have reported that the **getCaretPosition** has been **Extracted** from *drawCaret()*.

Note that the code is a java re-creation of [this](https://github.com/chartjs/Chart.js/commit/f97cab12b1c4db4d5782d92f95e362093ad31860) javaScript code. 

#### Snippet Diff
![image](https://user-images.githubusercontent.com/15908043/159382486-c44a84c9-56fd-4b84-8965-aa62b8326164.png)

**Refactoring Miner Version**
**Commit:** 2d41d67
**Commit Date:**  March 19, 2022

**NB:** In the JS version, 43 unmapped statements were reported from T1 between old and new versions of **drawCaret** and thus not mapped. A similar reason has been observed for java as well.

**Comment by tsantalis** [comment]
**Refactorings detected after the fix**:
> Extract Method public getCaretPosition(vm int[], size int) : CaretPosition extracted from package drawCaret(vm int[], size int, opacity int) : void in class chartjs.ToolTip
> Remove Parameter opacity : int in method package drawCaret(vm int[], size int, opacity int) : void from class chartjs.ToolTip
