### ISSUE TITLE
error when running ./gradlew distZip

### ISSUE THREAD

**Issue by anwarghammam** [tsantalis/RefactoringMiner#239]
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

any help please ?

**Comment by victor0624** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
> 
> any help please ?

Did you try higher version JDKs?

**Comment by tsantalis** [comment]
@anwarghammam @victor0624 
My setup is Gradle 7 and JDK 11.
