### ISSUE TITLE
explanation of refactoring types

### ISSUE THREAD

**Issue by victor0624** [tsantalis/RefactoringMiner#241]
Hi, do you have explanations for each kind of refactorings? I am confused by some types, for example, "rename class" VS "Move and Rename class". So, I wondered where I can find some definitions for each refactoring name?

**Comment by tsantalis** [comment]
We have the detection rules in the papers, and most of the refactoring types can be found in [Fowler's catalogue](https://refactoring.com/catalog/).

`Move And Rename Class` means that both the package and the name of the class changed.
`Rename Class` means only the name of the class changed.
