### ISSUE TITLE
Error in https://github.com/weld/core.git  da6358580511659a0759920d6cc64757693d0d8e

### ISSUE THREAD

**Issue by victor0624** [tsantalis/RefactoringMiner#242]
![image](https://user-images.githubusercontent.com/20552618/161042402-01b37333-98f1-4192-b42b-d6dd20d4a230.png)

**Comment by tsantalis** [comment]
There are many `Add Parameter` refactorings missed in https://github.com/weld/core/commit/da6358580511659a0759920d6cc64757693d0d8e#diff-ec454e08ad1a42c3c9f3799cdb5b18d6a1e25f1726de9ce91a1dbe7b67989ccf

A potential future improvement is to use updated in method references to infer from the addition of arguments, the addition of parameters.
