### ISSUE TITLE
A quetion

### ISSUE THREAD

**Issue by victor0624** [tsantalis/RefactoringMiner#244]
Hello, RefactoringMiner is a very good tool. But at the moment, I don't want some refactoring types, is there any solution that would allow me to customize my own needs? Thanks a lot.

**Comment by tsantalis** [comment]
Hi @victor0624 
You can comment out the refactoring types you don't want in
https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/api/RefactoringType.java#L107-L196

The refactoring types to be considered is set in the `GitHistoryRefactoringMinerImpl` constructor
https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L83
By default, `ALL` refactoring types are considered.

**Comment by victor0624** [comment]
> Hi @victor0624 You can comment out the refactoring types you don't want in https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/api/RefactoringType.java#L107-L196
> 
> The refactoring types to be considered is set in the `GitHistoryRefactoringMinerImpl` constructor https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L83 By default, `ALL` refactoring types are considered.

Thanks for your reply!
