### ISSUE TITLE
maybe an error?

### ISSUE THREAD

**Issue by victor0624** [tsantalis/RefactoringMiner#249]
![image](https://user-images.githubusercontent.com/20552618/166974429-579a24bb-50d7-42b5-a0fc-9f6c84ef7df3.png)
Hi, for this commit: https://github.com/hornetq/hornetq/commit/664146363dc6ad39bb29b7c108eed6236457d189, from the output of command line, I got a "change parameter type" refactoring. For the second leftSideLocation, the codeElement is "package MessageEntry(message MessageImpl)" . I don't understand why the modifier of a method can be a package?

**Comment by tsantalis** [comment]
When there is no access modifier specified the access level is **package-private** (no explicit modifier).
https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html
