### ISSUE TITLE
lines extracted from a function are outside the function itself - is this a bug or expected behaviour ?

### ISSUE THREAD

**Issue by alan-barzilay** [tsantalis/RefactoringMiner#251]
In this [commit](https://github.com/GluuFederation/oxd/commit/d75078bd7468d87ac47a3cf612ea41c480205b37) I get a weird function extraction, the function where the extraction occurs is only 3 lines(from 96 to 98) but the extracted lines are only outside this function (102,104,128). 

Is this normal? I'm trying to understand how is it possible to have lines extracted from a function that are outside the function itself.

Am I misunderstanding something?

here is the refactoring miner output for this refactoring:
<details>
    <summary> </summary>

```
{
	"type": "Extract Method",
	"description": "Extract Method public validateAudience(idToken Jwt, clientId String) : void extracted from public validateIdToken(clientId String) : void in class org.gluu.oxd.server.op.Validator",
	"leftSideLocations": [{
		"filePath": "oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java",
		"startLine": 96,
		"endLine": 98,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "source method declaration before extraction",
		"codeElement": "public validateIdToken(clientId String) : void"
}, {
		"filePath": "oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java",
		"startLine": 104,
		"endLine": 104,
		"startColumn": 13,
		"endColumn": 106,
		"codeElementType": "VARIABLE_DECLARATION_STATEMENT",
		"description": "extracted code from source method declaration",
		"codeElement": null
}, {
		"filePath": "oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java",
		"startLine": 102,
		"endLine": 102,
		"startColumn": 13,
		"endColumn": 93,
		"codeElementType": "VARIABLE_DECLARATION_STATEMENT",
		"description": "extracted code from source method declaration",
		"codeElement": null
}, {
		"filePath": "oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java",
		"startLine": 128,
		"endLine": 128,
		"startColumn": 13,
		"endColumn": 101,
		"codeElementType": "VARIABLE_DECLARATION_STATEMENT",
		"description": "extracted code from source method declaration",
		"codeElement": null
}],


``` 
</details>

**Comment by tsantalis** [comment]
Hi @alan-barzilay 
I tried to replicate the problem, but I am not getting this refactoring with the latest commit of RefactoringMiner.

Currently, there is only one Extract Method refactoring
`Extract Method public validateIdToken() : void extracted from public isIdTokenValid(clientId String) : boolean in class org.gluu.oxd.server.op.Validator`

Could you please let me know what version of RefactoringMiner you are using?

>  Remove Parameter jwt : Jwt in method public createRSASigner(jwt Jwt, discoveryResponse OpenIdConfigurationResponse, keyService PublicOpKeyService) : RSASigner from class org.gluu.oxd.server.op.Validator
>   Move Attribute private idToken : Jwt from class org.gluu.oxd.server.op.Validator to private idToken : Jwt from class org.gluu.oxd.server.op.JwsSignerObject
>   Rename Parameter clientId : String to nonce : String in method public validateIdToken(nonce String) : void from class org.gluu.oxd.server.op.Validator
>   Move Attribute private opClientFactory : OpClientFactory from class org.gluu.oxd.server.op.Validator to private opClientFactory : OpClientFactory from class org.gluu.oxd.server.op.JwsSignerObject
>   Merge Parameter [idToken : Jwt, keyService : PublicOpKeyService, opClientFactory : OpClientFactory] to jwsSignerObject : JwsSignerObject in method public Validator(jwsSignerObject JwsSignerObject, discoveryResponse OpenIdConfigurationResponse) from class org.gluu.oxd.server.op.Validator
>   Add Method Modifier static in method public validateAudience(idToken Jwt, clientId String) : void from class org.gluu.oxd.server.op.Validator
>   Rename Method public createRSASigner(jwt Jwt, discoveryResponse OpenIdConfigurationResponse, keyService PublicOpKeyService) : RSASigner renamed to public createJwsSigner(jwsSignerObject JwsSignerObject, discoveryResponse OpenIdConfigurationResponse) : AbstractJwsSigner in class org.gluu.oxd.server.op.Validator
>   Change Return Type RSASigner to AbstractJwsSigner in method public createJwsSigner(jwsSignerObject JwsSignerObject, discoveryResponse OpenIdConfigurationResponse) : AbstractJwsSigner from class org.gluu.oxd.server.op.Validator
>   Extract Variable jwsSigner : JwsSignerObject in method public execute(params GetTokensByCodeParams) : IOpResponse from class org.gluu.oxd.server.op.GetTokensByCodeOperation
>   Remove Variable Modifier final in variable nonceFromToken : String in method public validateIdToken(nonce String, clientId String) : void from class org.gluu.oxd.server.op.Validator
>   Remove Attribute Modifier static in attribute private opClientFactory : OpClientFactory from class org.gluu.oxd.server.op.Validator
>   Add Parameter idToken : Jwt in method public validateAudience(idToken Jwt, clientId String) : void from class org.gluu.oxd.server.op.Validator
>   Extract Method public validateIdToken() : void extracted from public isIdTokenValid(clientId String) : boolean in class org.gluu.oxd.server.op.Validator
>   Remove Parameter clientId : String in method public isIdTokenValid(clientId String) : boolean from class org.gluu.oxd.server.op.Validator
>   Extract Variable jwsSigner : JwsSignerObject in method public execute(params CheckIdTokenParams) : IOpResponse from class org.gluu.oxd.server.op.CheckIdTokenOperation
>   Merge Attribute [idToken : Jwt, opClientFactory : OpClientFactory, keyService : PublicOpKeyService] to jwsSignerObject : JwsSignerObject in class org.gluu.oxd.server.op.Validator
>   Add Parameter jwsSignerObject : JwsSignerObject in method public createJwsSigner(jwsSignerObject JwsSignerObject, discoveryResponse OpenIdConfigurationResponse) : AbstractJwsSigner from class org.gluu.oxd.server.op.Validator
>   Extract Class org.gluu.oxd.server.op.JwsSignerObject from class org.gluu.oxd.server.op.Validator
>   Rename Attribute rsaSigner : RSASigner to jwsSigner : AbstractJwsSigner in class org.gluu.oxd.server.op.Validator
>   Change Attribute Type rsaSigner : RSASigner to jwsSigner : AbstractJwsSigner in class org.gluu.oxd.server.op.Validator
>   Extract Variable jwsSigner : JwsSignerObject in method public execute(params ValidateParams) : IOpResponse from class org.gluu.oxd.server.op.ValidateOperation
>   Rename Method public validateIdToken(nonce String, clientId String) : void renamed to public validateAudience(idToken Jwt, clientId String) : void in class org.gluu.oxd.server.op.Validator
>   Move Attribute private keyService : PublicOpKeyService from class org.gluu.oxd.server.op.Validator to private keyService : PublicOpKeyService from class org.gluu.oxd.server.op.JwsSignerObject
>   Remove Parameter nonce : String in method public validateIdToken(nonce String, clientId String) : void from class org.gluu.oxd.server.op.Validator
>   Remove Parameter keyService : PublicOpKeyService in method public createRSASigner(jwt Jwt, discoveryResponse OpenIdConfigurationResponse, keyService PublicOpKeyService) : RSASigner from class org.gluu.oxd.server.op.Validator
>   Rename Variable nonceFromToken : String to azpFromToken : String in method public validateAudience(idToken Jwt, clientId String) : void from class org.gluu.oxd.server.op.Validator

**Comment by alan-barzilay** [comment]
> Could you please let me know what version of RefactoringMiner you are using?

RefactoringMiner-2.1.0

>  The refactoring you report seems valid. I would like to investigate it in more detail.


So it is normal to have this situation? I dont understand how extracting a line outside the function should be valid, could you explain to me the logic behind this?

**Comment by alan-barzilay** [comment]
So this was really a bug?

**Comment by tsantalis** [comment]
In the previous reported refactoring the extraction is from method `public void validateIdToken(String clientId)` which is declared between lines 96-98.
I guess back then RefactoringMiner was detecting a nested Extract Method refactoring.
`validateIdToken(String nonce, String clientId)` extracted from `validateIdToken(String clientId)`
and then another extraction from the extracted method
`public static void validateAudience(Jwt idToken, String clientId)` extracted from `validateIdToken(String nonce, String clientId)`

With the last commit method `validateIdToken(String nonce, String clientId)` is matched with `validateIdToken(String nonce)`
and thus 
`validateAudience(Jwt idToken, String clientId)` is extracted **directly** (not nested) from `validateIdToken(String nonce, String clientId)`
