### ISSUE TITLE
'Replace loop with pipeline' combined with 'Extract Method'

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#252]
**Problem**

Neither "Extract Method" nor "Replace loop with pipeline" are reported.

**Commit**

[pedramnoori/TestcasesForRM](https://github.com/pedramnoori/TestCases-for-RefactoringMiner/commit/e0051179a3fe55d04f35bc209ebb3bc7db2e398d)

**Observation**

I compared the _OperationBodyMapperList_ (mappings) object in two scenarios. First, when there is no Extract Method with Replace loop with pipeline. Second, when we have both together. In the second case (which is the case provided at the aforementioned commit,) the number of mappings is decreased by two (map between `System.out.println()` in two versions and between `for {}` and the stream equivalent are missing).

**Comment by tsantalis** [comment]
Refactorings detected after the fix:
**Extract Method** `public printList(movies List<String>) : void` extracted from `public main(args String[]) : void` in class `TestStream`
**Replace Loop With Pipeline** `for(int i=0; i < movies.size(); i++)` with `movies.stream().forEach(System.out::println);` in method `public printList(movies List<String>) : void` from class `TestStream`
