### ISSUE TITLE
Sub-expression matching

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#253]
**Title**

Sub-expression matching

**Commit**

[giraph/87f3c4d](https://github.com/apache/giraph/commit/87f3c4d8572ee8f7244af8a92dc3312ce24260e3)

**Refactroing**

Extract method **private getWorkerCommunications()** at the very end of the commit. 

**Observation**

This refactoring is **correctly reported by RefactroingMiner**. 

Through this extract method operation, there is one mappings reported by RefactroingMiner: 
from `getGraphState().getWorkerCommunications().sendMessageRequest(id,message);` in parent commit to `return getGraphState().getWorkerCommunications();` in the child commit with one replacement of type _METHOD_INVOCATION_.

Although the proper mapping in this case is probably from `getGraphState().getWorkerCommunications()` to `return getGraphState().getWorkerCommunications();`, RefactoringMiner cannot report it because I think it works in statement level and cannot capture sub-expression mappings. 

Even though RefactoringMiner works perfectly without this functionality, I think this is a potential spot for RefactoringMiner to improve and support this.

**Comment by pouryafard75** [comment]
Similar to mockito-10

**Comment by tsantalis** [comment]
```java
return mockSettings.serializable()
                .defaultAnswer(returnsDeepStubsAnswerUsing(returnTypeGenericMetadata));
```
AFTER Extract Method
```java
return propagateSerializationSettings(mockSettings, parentMockSettings)
                .defaultAnswer(returnsDeepStubsAnswerUsing(returnTypeGenericMetadata));
```
