### ISSUE TITLE
Wrong mapping

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#254]
**Problem**

Wrong mapping reported - Extract method

**Commit**

[pedramnoori/TestCases-for-RefactoringMiner/225816b](https://github.com/pedramnoori/TestCases-for-RefactoringMiner/commit/225816b37491e1c1cd5ab48a7b3ba89da0ee0348)

Extract Method **private connectToLogfile()**

**Observation**

There is a wrong mapping in within this extract method operation. RefactoringMiner maps `preferences=Preferences.userNodeForPackage(logger);` from parent commit to `return logger;` from child commit. 

The proper way I think should be reporting the `return logger;` in the child commit as a non-mapped leave.

**Comment by tsantalis** [comment]
@pedramnoori 
This issue has been fixed.
The wrong mapping is removed from the corresponding mapper, but `return logger;` is not added back to the non-mapped leaves.
Is that a problem?

**Comment by pedramnoori** [comment]
I think this is a problem with this example that needs to be solved.

According to the below example, RefactoringMiner reports these kind of `return` statements as non-mapped leaves, and these two examples are aiming a similar concept  (adding return statement within the Extract Method refactoring mechanics).

**Example**
[pedramnoori/TestCases-for-RefactoringMiner/661d1ce](https://github.com/pedramnoori/TestCases-for-RefactoringMiner/commit/661d1cee4cfeb521dacbc991abf31842caed8b62)

**Comment by tsantalis** [comment]
`return t3;` is correctly reported as non-mapped statement.
We should ignore such `return` non-mapped statements, as they are introduced by the Extract Method refactoring mechanics.
