### ISSUE TITLE
error in "rename class"

### ISSUE THREAD

**Issue by victor0624** [tsantalis/RefactoringMiner#256]
https://github.com/apache/derby/commit/6da924f1c3fcd4358dbde3f628356261647ee632
There are some errors in this commit, 
"Rename Class org.apache.derbyTesting.functionTests.tests.lang.DummyReader renamed to org.apache.derbyTesting.functionTests.tests.lang.DummyBinary",
"Rename Class org.apache.derbyTesting.functionTests.tests.lang.DummyBinary renamed to org.apache.derbyTesting.functionTests.tests.lang.DummyReader"
DummyBinary and DummyReader have almost the same code, so I think that's why the RefactoringMiner made mistake.

**Comment by tsantalis** [comment]
@victor0624 
Are you sure this is the right commit?
There are no such files in this commit. The refactorings detected are:

>  Remove Method Modifier static in method private insertLongBinary(ps PreparedStatement, kbytes int) : int from class org.apache.derbyTesting.functionTests.tests.lang.streams
>  Rename Class org.apache.derbyTesting.functionTests.tests.lang.streams renamed to org.apache.derbyTesting.functionTests.tests.lang.StreamsTest
>  Remove Attribute Modifier static in attribute private pkCount : int from class org.apache.derbyTesting.functionTests.tests.lang.streams
>  Remove Method Modifier static in method private insertLongString(ps PreparedStatement, kchars int, isInsert boolean) : int from class org.apache.derbyTesting.functionTests.tests.lang.streams
>  Change Attribute Access Modifier public to package in attribute package lines : int from class org.apache.derbyTesting.functionTests.tests.lang.DummyPrintStream
