### ISSUE TITLE
duplicate Move Source Folder

### ISSUE THREAD

**Issue by feifeiniu-se** [tsantalis/RefactoringMiner#258]
https://github.com/izpack/izpack/commit/284fc6b71ccd0f3b1494fecab45eb72c1c477e1f
For this commit, the refactoringMiner output two "Move Source Folder src/lib to izpack-compiler/src/main/java", while the second one is empty:
"{
	"type": "Move Source Folder",
	"description": "Move Source Folder src/lib to izpack-compiler/src/main/java",
	"leftSideLocations": [],
	"rightSideLocations": []
}", 
is this ok?

**Comment by tsantalis** [comment]
@feifeiniu-se 
With the latest RefactoringMiner commit there is a single `Move Source Folder	src/lib to izpack-compiler/src/main/java`
which includes 324 `MovedClassToAnotherSourceFolder` instances

I consider this issue as fixed.
