### ISSUE TITLE
reorder parameter missing

### ISSUE THREAD

**Issue by feifeiniu-se** [tsantalis/RefactoringMiner#259]
https://github.com/izpack/izpack/commit/a7b381847d9b8296a459d65de4da7bd1f9995477
For this commit, I think there is also reoder parameter, apart from remove parameter:
---public InstallerFrame(String title, InstallData installdata, RulesEngine rules, IconsDatabase icons, IPanelComponent panelComponent, UninstallDataWriter uninstallDataWriter, PanelManager panelManager)
+++public InstallerFrame(String title, InstallData installdata, RulesEngine rules, IconsDatabase icons, PanelManager panelManager, UninstallDataWriter uninstallDataWriter). 
But according to refactoringMiner, there is only remove parameter.

**Comment by tsantalis** [comment]
The current implementation of Reorder Parameter refactorings supports method signatures with an equal number of parameters.
But this case is useful to extend our solution to support method signatures with a different number of parameters.
I will work on it.
