### ISSUE TITLE
Request for RefactoringMiner API to detect between directories

### ISSUE THREAD

**Issue by ketkarameya** [tsantalis/RefactoringMiner#260]
@tsantalis I was wondering if you plan on (or open to ) add another RMiner API (like `detectAtCommit` we could have `detectBetweenDirectories`) that mines Refactorings between 2 versions of a project stored in separate directories. I can contribute this, if this is something you are okay to add to RMiner.

**Comment by tsantalis** [comment]
The functionality is already there
https://github.com/tsantalis/RefactoringMiner#with-two-directories-containing-java-source-code
We just need an API for it. Go ahead with the feature and I will merge it.
