### ISSUE TITLE
Statement Mapping inside the lambda Expression + some other mapping problems

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#266]
Problem:  Some mappings are missing from the body mappers.
You can find the commit [here](https://github.com/pouryafard75/TestCases/commit/d01dfd14c0f8cae6ad4f78171011cd839b980e00).
File: LambdaExample.java

Method **read**: _```public int read()```_
Following mappings are missing from the bodyMapper:

* Line 21 parent commit ```String containsStr = (String) contains.elementAt(i) ``` ->   Line 5 child commit ```String containsStr = (String) contains.elementAt(i);```
(inside Lambda)

* Line 22 parent commit ```matches = line.indexOf(containsStr) >= 0;``` -> Line 6 child commit ```return line.indexOf(containsStr) >= 0;```
(inside Lambda)

Method **read2**: _```public int read2()```_
Following mappings are missing from the bodyMapper:
* Line 55 parent commit ```RegularExpression regexp = (RegularExpression) regexps.elementAt(i);``` -> Line 13 child commit ```RegularExpression regexp = (RegularExpression) regexps.elementAt(i);```
(inside Lambda)

* Line 56 parent commit ```Regexp re = regexp.getRegexp(getProject());``` -> Line 14 child commit ```Regexp re = regexp.getRegexp(getProject());```
(inside Lambda)

* Line 57 parent commit ```matches = re.matches(line);``` -> Line 15 child commit ```return re.matches(line);```
(inside Lambda)

Extract Method Refactoring (**read**):
_Extract Method	protected extracted(vector Vector, matcher Function<Integer,Boolean>) : int extracted from public read() : int_ 

The following mapping is missing from the bodyMapper:

* Line-range 20-23 parent commit  ```{ }``` -> Line range 40-42 child commit ```{ }``` 
(reported as nonMappedInnerNode)

Extract Method Refactoring (**read2**):
_Extract Method	protected extracted(vector Vector, matcher Function<Integer,Boolean>) : int extracted from public read2() : int_ 

The following mappings are missing from the bodyMapper:
* Line 53 parent commit  ```for (int i = 0; matches && i < regexpsSize; i++) ``` -> Line 39 child commit ```for (int i = 0; matches && i < containsSize; i++)```
(For the other extract method, this problem does not exist)

* Line-range 54-58  parent commit  ```{ }``` -> Line range 40-42 child commit ```{ }``` 
(reported as nonMappedInnerNode)

**Comment by tsantalis** [comment]
This issue was accidentally fixed with commit https://github.com/tsantalis/RefactoringMiner/commit/48bb4cfd773ac2363019daf4b38456d91cdc1fb1

**Comment by pouryafard75** [comment]
@tsantalis  Statements which are inside the lambda, are fixed with commit 48bb4cfd773ac2363019daf4b38456d91cdc1fb1. There are still some incorrect mappings.
