### ISSUE TITLE
No refactoring identified

### ISSUE THREAD

**Issue by mashalahmad** [tsantalis/RefactoringMiner#27]
hi

Im trying to implement the low level Api to detect the refactoring before and after but I always get the empty array. here is snippet of code im working 

File rootFolder1 = new File(System.getProperty("user.dir")+"/src/refactoring_before/");
	File rootFolder2 = new File(System.getProperty("user.dir")+"/src/refactoring_after/");
	System.out.println(rootFolder2);
	ArrayList<String> filePaths1 = new ArrayList<String>();
	filePaths1.add(System.getProperty("user.dir")+"/src/refactoring_before/Customer.java");
	
	//System.out.print(filePaths1);
	List<String> filePaths2 = new ArrayList<String>();
	filePaths2.add(System.getProperty("user.dir")+"/src/refactoring_after/Customer.java");

	UMLModel model1 = new UMLModelASTReader(rootFolder1, filePaths1).getUmlModel();
	UMLModel model2 = new UMLModelASTReader(rootFolder2, filePaths2).getUmlModel();
	UMLModelDiff modelDiff = model1.diff(model2);
	//System.out.print(modelDiff);
	
	List<Refactoring> refactorings = modelDiff.getRefactorings();
	System.out.println(refactorings.toString());	
	for (Refactoring ref : refactorings) {
		
		System.out.println(ref.toString());	
	
	}

**Comment by tsantalis** [comment]
file paths should be relative to the source folder
```
File rootFolder1 = new File(System.getProperty("user.dir"));
File rootFolder2 = new File(System.getProperty("user.dir"));
filepaths1.add("/src/refactoring_before/Customer.java")
filepaths2.add("/src/refactoring_after/Customer.java")
```
