### ISSUE TITLE
Wrong Argumentization

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#274]
**Observation**

The parameter of the Extract Method has been wrongly argumentized.

**Commit**

[Here](https://github.com/spring-projects/spring-boot/commit/b47634176fa48ad925f79886c6aaca225cb9af64)

**Extracted Method**

findAll(Predicate<String> predicate) which is extracted two times

**Explanation**

The parameter of the aforementioned method has been argumentized with `this.all` in both cases, which is wrong.

**Comment by tsantalis** [comment]
@pedramnoori 
`Map<String, String> parameterToArgumentMap` is introduced in `ExtractOperationRefactoring`
I checked that the map contains different values (the correct ones) for each Extract Method refactoring instance in this commit.
