### ISSUE TITLE
Cannot detect extract method inside of static blocks anonymous class' 

### ISSUE THREAD

**Issue by mkshiblu** [tsantalis/RefactoringMiner#276]
**Problem**

Refactoring Miner was not able to detect that **stringFilter** function was extracted from **valid**

**Steps to Reproduce**

1. Go to https://github.com/mkshiblu/practice/commit/75acb3d75b95e6fb4dfd44ac06b4c8a11f34120a

2. Run refactoring miner to get the list of refactoring or use the Chrome extension once it is up and running.

**Observed Behavior**

No refactorings are reported by RefactoringMiner.

**Expected Behavior**

1. `````StringFilter````` extracted from `````valid````` 
2.  ``````moduleChainIdMatch`````` extraced from `````valid````` (Possibly?)

**Quick Diff**

![image](https://user-images.githubusercontent.com/15908043/186276427-379d9d3c-79be-4d00-bd26-11e56acdc7aa.png)

**Notes**

-  The Above Java Example Test Code is a close recreation to [this](https://github.com/jquery/jquery/commit/ecd8ddea33dc40ae2a57e4340be03faf2ba2f99b#diff-2f4c7e11d8d3cd864e3d706b27d42169ddd5d06b9292dbe446a3a45b9572b68d) javaScript code.  `external\qunit\qunit.js Line 1136`

-  Source code is compilable because of the addition of mock classes.

**Environment:**

RefactoringMiner Commit Version : 263366d

**Comment by tsantalis** [comment]
@mkshiblu 
The refactoring was actually detected, but not reported.
