### ISSUE TITLE
Wrong Argumentization

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#278]
**Observation**

The parameter of the extracted method has been wrongly argumentized.

**Commit**

[Here](https://github.com/robovm/robovm/commit/bf5ee44b3b576e01ab09cae9f50300417b01dc07)

**Extracted method which has been wrongly argumentized**

"Extract Method public **set(key CGImageProperty8BIM, value NativeObject)** : CGImageProperty8BIMData extracted from public **set(property CGImageProperty8BIM, value String) : CGImageProperty8BIMData** in class org.robovm.apple.imageio.**CGImageProperty8BIMData**"

**Description**

The "NativeObject value" parameter should be argumentized with "new CFString(value)" for this extracted method, but according to the RefactoringMiner, it has been argumentized with "CFNumber.valueOf(value)", which is the argument of the another method.

**Comment by tsantalis** [comment]
Duplicate with issue #274
Fixed in https://github.com/tsantalis/RefactoringMiner/commit/d54b266f92d4edcb7cda929c9b24dfd1e47caf15
