### ISSUE TITLE
Missing Extract Class Refactoring

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#279]
**-Problem**

Unable to detect Extract Class Refactoring

**-Commit**

[Here](https://github.com/robovm/robovm/commit/bf5ee44b3b576e01ab09cae9f50300417b01dc07)

In **CGImageMetadataEnumerationOptions.java** file

**-Expected Behavior**

There should be an Extract Class refactoring: Extract Class CGImageMetadataEnumerationOptions.Keys from CGImageMetadataEnumerationOptions. Method "EnumerateRecursivelyKey" has been transferred to the aforementioned class with the new name: "EnumerateRecursively".

Note that multiple similar Extract Class refactorings have been reported by RefactoringMiner in this commit but this one is missing.

**Comment by tsantalis** [comment]
@pedramnoori 
The issue is fixed. Thanks for reporting it.
