### ISSUE TITLE
Detect All refactoring of all branches?

### ISSUE THREAD

**Issue by mashalahmad** [tsantalis/RefactoringMiner#28]
Is there any feature of Rminer that will iterate through each branch of Github repository and detect all refactoring? For example we don't need to mention branch "master".

**Comment by tsantalis** [comment]
If branch X is merged into the master, then every refactoring taking place in X can be detected just by analyzing the master branch.
As a result, analyzing all branches of a repository will result in duplicate refactoring reports.
One approach to overcome this problem would be to clean up duplicates after analyzing all branches,
or analyze only the branches not merged to the master.
