### ISSUE TITLE
‘type’ may raise a nullpointer exception, when i run detectAll in open-source project iluwatar/java-design-patterns

### ISSUE THREAD

**Issue by liuborepo** [tsantalis/RefactoringMiner#280]
https://github.com/tsantalis/RefactoringMiner/blob/c83921af18b8728d49e048d9e3ed6c6a78f3b8dd/src/gr/uom/java/xmi/diff/UMLModelDiff.java#L2735

**Comment by liuborepo** [comment]
if(type !=null && !addedOperation.getNonQualifiedClassName().equals(type.getClassType()) && !superclassRelationship) {

**Comment by tsantalis** [comment]
Hi @liuborepo 
Do you have the exact commit the NullPointerException happened?

**Comment by tsantalis** [comment]
@liuborepo 
I fixed the issue as you suggested.
I also run for all commit of this project, and attache the [log.txt](https://github.com/tsantalis/RefactoringMiner/files/9531590/log.txt)
Please report any other issues you might find.
RefactoringMiner, recently added support for lambda expression parameters, and in some cases they don't have a type.
This caused the NullPointerException.
