### ISSUE TITLE
Strange behavior on mapping the statements inside lambda

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#286]
The following commits explain strange behavior regarding lambda expression:

Commit : [here](https://github.com/pouryafard75/TestCases/commit/0952454d3921dec199d55017562065308fcc0ed9)
None of the statements inside lambda are reported as mapped.

Commit: [here](https://github.com/pouryafard75/TestCases/commit/01e3ae2ac0c052f155426003685a0cb3031e3743)
Statements inside lambda are reported correctly.

It seems like when the body of the lambdas are identical, inner statements are not reported.

**Comment by tsantalis** [comment]
Fixed in commit https://github.com/tsantalis/RefactoringMiner/commit/6e50d8a39498588205ac6e5b3de1048ac6fdef09
