### ISSUE TITLE
Clean install: 

### ISSUE THREAD

**Issue by ElmarFrerichs** [tsantalis/RefactoringMiner#297]
Hello,

I'm trying to get RefactoringMiner to work, but I can't get Gradle to actually build the project. The output is appended below.

System: Windows 10

```
# .\gradlew.bat jar
> Task :compileJava FAILED
C:\Users\e\git\RefactoringMiner\src\gr\uom\java\xmi\AnonymousClassDeclarationVisitor.java:6: error: cannot access org.eclipse.jdt.core.dom.ASTVisitor
import org.eclipse.jdt.core.dom.ASTVisitor;
                               ^
  bad class file: C:\Users\e\.gradle\caches\modules-2\files-2.1\org.eclipse.jdt\org.eclipse.jdt.core\3.30.0\2d6102201beb98b3c9a8ca36dbf82f9f8b71bc4c\org.eclipse.jdt.core-3.30.0.jar(org/eclipse/jdt/core/dom/ASTVisitor.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed
```
A similar messages appears when using WSL with Debian 9.

It looks a bit like a dependency problem to me, but I haven't worked with gradle before so I wont speculate. Any help would be appreciated.

Greetings,
Elmar Frerichs

**Comment by tsantalis** [comment]
Hi @ElmarFrerichs 
Thank you for reporting this issue.

Please try the following solution:
In `build.gradle` uncomment lines 32-34 and 42-43
```
maven {
    url 'https://raw.githubusercontent.com/jmini/ecentral/HEAD/repo'
}
```
```
implementation platform('fr.jmini.ecentral:eclipse-platform-dependencies:4.24')
implementation 'org.eclipse.jdt:org.eclipse.jdt.core'
```

and comment out line 44
```
//implementation 'org.eclipse.jdt:org.eclipse.jdt.core:3.30.0'
```

and then re-build.

Please let me know if this workaround solved the problem.

**Comment by ElmarFrerichs** [comment]
Hello,

thanks for the answer.

I made the modifications to the build.gradle and rerun the command, but got the exact same failure message. It seems as if gradle is still using the cached version... is there a command to clear that cache?

Greetings

**Comment by ElmarFrerichs** [comment]
Update: Deleted the .gradle Folder in the Repository and .gradle in my Home (including the cache), same result. Workaround does not work.

**Comment by tsantalis** [comment]
@ElmarFrerichs 
Just to make sure, you should build with JDK 11 and Gradle 7 (or newer versions)

**Comment by ElmarFrerichs** [comment]
Good call on that, forgot to mention my Java version - I was still stuck with Java 8. Changed to JDK 11, build success!

Thanks for the help.
