### ISSUE TITLE
Convert the output in a CSV file

### ISSUE THREAD

**Issue by broke31** [tsantalis/RefactoringMiner#300]
I'm trying to use the tool to conduct some experiments; however, in many cases, the output generated is quite difficult to manipulate, this is because the tool produces output as a JSON file. Would it be possible to obtain the output in CSV format?

**Comment by tsantalis** [comment]
Hi @broke31 
JSON allows to have nested properties and fits very well with the structure of the output.
CSV is a better fit for row/column based output.

JSON can be easily deserialized in every programming language.
What is exactly the difficulty you are facing?

**Comment by broke31** [comment]
The output structure of JSON could be difficult to deserialize due to the output being a nested file. The current python library to deserialize  JSON does not perfectly deserialize it.
In particular, when applying the function "json_normalize", to deserialize the file, the output is not completely correct (e.g., the output of this function inserts in one field the entire content of leftSideLocations).
In any case, the answer of this StackOverflow post resolves this conversion issue:
https://stackoverflow.com/questions/74363880/how-to-convert-a-complex-nested-json-file-to-csv-in-python

Thank you for the tool!

**Comment by tsantalis** [comment]
@broke31 
I am glad you found a solution for your problem.
I will now close the issue.
