### ISSUE TITLE
Missing statement mappings and inaccurate replacement

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#305]
**Problem**

Two missing statement mappings in an Extract Method refactoring, and inaccurate replacement in one statement mapping

**Commit**

[Here](https://github.com/apache/hive/commit/f664789737d516ac664462732664121acc111a1e)

**File**

[AppConfig.java](https://github.com/apache/hive/commit/f664789737d516ac664462732664121acc111a1e#diff-c9cd5e5535527595c5aa1d4942b682218de3cb93d41acac8dfaa83623600451d)

**Refactoring**

**Extract Method** **private** **dumpConfig(conf Configuration, sb StringBuilder)** : void extracted **from private dumpEnvironent()** : String in class org.apache.hive.hcatalog.templeton.**AppConfig**

**Problem description (Mapping problem)**

There are two non-mapped leaves (StatementObject) in both versions, which have to be mapped. In the following, I have mentioned the details.

**1-**

- `Iterator<Map.Entry<String,String>> configIter=this.iterator();` Line **242** from the parent commit

Should be mapped with:

- `Iterator<Map.Entry<String,String>> configIter=conf.iterator();` Line **258** from the child commit

**2-** 

- `List<Map.Entry<String,String>> configVals=new ArrayList<Map.Entry<String,String>>();` Line **242** from the parent commit

Should be mapped with:

- `List<Map.Entry<String,String>> configVals=new ArrayList<>();` Line **259** from the child commit

**Problem description (Replacement problem)**

Also, in the leafMapping object , in which the two following statements have been mapped:

- `sb.append(entry.getKey()).append('=').append(get(entry.getKey())).append('\n');`

Mapped with:

- `sb.append(entry.getKey()).append('=').append(conf.get(entry.getKey())).append('\n');`

There is one replacement reported by RefactoringMiner, "**get(entry.getKey()) -> this**", which is wrong I think. The ideal replacement in my opinion would be a MethodInvocationReplacement (METHOD_INVOCATION_ARGUMENT) replacement, because the argument of the `append` method has been changed within this mapping.

**Comment by tsantalis** [comment]
@pedramnoori 
I fixed the unmapped statements.
You can ignore this replacement `get(entry.getKey())` -> `this`,
because from `parameterToArguments`, we know that `this` becomes `conf`.
All differences in the mapped statements can be explained from `parameterToArguments`

![Screenshot from 2022-12-16 14-30-03](https://user-images.githubusercontent.com/1483516/208174849-3c48ce0f-a4ed-442f-9af0-fc9469438896.png)
