### ISSUE TITLE
Wrong statement mapping and replacement

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#306]
**Problem**

Wrong statement mapping and replacement within two Extract Method refactorings

**Commit**

[Here](https://github.com/google/auto/commit/8fc60d81fe0e46e7e5c96e71d4a93fcadc6bde4f)

**File**

[BasicAnnotationProcessor.java](https://github.com/google/auto/commit/8fc60d81fe0e46e7e5c96e71d4a93fcadc6bde4f#diff-2167c24df95e48cbafc17aecb37391dc766ac4f0f521eac28527c66d507dba23)

**Refactoring and explanation (wrong mapping)**

**Extract Method** private **deferredElements()** : ImmutableMap<String,Optional<? extends Element>> extracted **from public process**(annotations Set<? extends TypeElement>, roundEnv RoundEnvironment) : boolean in class com.google.auto.common.**BasicAnnotationProcessor**

There is a mapping within the above Extract Method refactoring, which is totally wrong:

- `deferredElements.entrySet()` Line **163** in the parent commit

with

- `return deferredElements.build();` Line **170** in the child commit

Instead, the return statement in the child commit have to be reported as a non-mapped leaf in the extracted method.

**Refactoring and explanation (wrong replacement)**

**Extract Method** private **process**(validElements ImmutableSetMultimap<Class<? extends Annotation>,Element>) : void extracted **from public proces**s(annotations Set<? extends TypeElement>, roundEnv RoundEnvironment) : boolean in class com.google.auto.common.**BasicAnnotationProcessor**

There is a mapping within this extract method refactoring:

- from `SetMultimap<Class<? extends Annotation>,Element> filteredMap=Multimaps.filterKeys(elementsByAnnotation,Predicates.in(step.annotations()));`

- to `SetMultimap<Class<? extends Annotation>,Element> filteredMap=Multimaps.filterKeys(validElements,Predicates.in(step.annotations()));`

The only difference between two aforementioned statements is the first passed argument in the `filterKeys` method. The correct replacement in this case would be a VARIABLE_NAME replacement: **"elementsByAnnotation -> validElements"** , but the reported replacement by RefactoringMiner is a VARIABLE_NAME replacement: **"elementsByAnnotation -> validElements(deferredElements,roundEnv)"**, which is wrong.

**Comment by tsantalis** [comment]
@pedramnoori 
The replacement is like that, because of the argumentization process
`process(validElements(deferredElements, roundEnv))`

`validElements` was replaced with `validElements(deferredElements, roundEnv)` when the statement was argumentized.

**Comment by tsantalis** [comment]
@pedramnoori 
Two additional mappings were added:

`ImmutableMap<String, Optional<? extends Element>> deferredElements =
        deferredElementsBuilder.build();`
mapped to
`return deferredElements.build();`

`ImmutableSetMultimap<Class<? extends Annotation>, Element> elementsByAnnotation =
        elementsByAnnotationBuilder.build();`
mapped to
`return validElements.build();`

which are both correct.
