### ISSUE TITLE
Wrong statement mapping and replacement in an Extract Method case

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#308]
**Problem**

Inaccurate statement mapping and missing expected replacement

**Commit**

[Here](https://github.com/Alluxio/alluxio/commit/9aeefcd8120bb3b89cdb437d8c32d2ed84b8a825)

**File**

[MaxFreeAllocator.java](https://github.com/Alluxio/alluxio/commit/9aeefcd8120bb3b89cdb437d8c32d2ed84b8a825#diff-f852df32cee1d52f4c32b3cb376214c9e2ffa88a2890ec2430839c6aac33828f)

**Refactoring**

Extract Method private **getCandidateDirInTier(tier StorageTier, blockSize long)** : StorageDir **extracted from** public **allocateBlock(userId long, blockId long, blockSize long, location BlockStoreLocation)** : TempBlockMeta in class tachyon.worker.block.allocator.MaxFreeAllocator

Note that there are **two same Extract Methods** with the aforementioned information - i.e., code duplication has been extracted to a new method.

**Problem description**

Within the first extracted method (with respect to the order of appearance in the child commit), the statement `StorageDir candidateDir = null;` at line 74 in the child commit has been mapped with `candidateDir = dir;` at line 50 in the parent commit, which is wrong.
The former has to be reported either as a non-mapped leaf or being mapped with `StorageDir candidateDir = null;` at line 42 in the parent commit. (I believe the first scenario would make more sense)

Furthermore, in the statement mapping between `long maxFreeBytes=blockSize;` in the parent commit and `long maxFreeBytes=blockSize - 1;` in the child commit, the replacement is empty, which is wrong. Number Literal replacement has to be reported I guess.

**Comment by tsantalis** [comment]
![Screenshot from 2022-12-26 23-19-41](https://user-images.githubusercontent.com/1483516/209610671-8df564cf-6a9e-4aae-9398-3ab4d64b3b4d.png)
