### ISSUE TITLE
Missing statement

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#309]
**Problem**

Missing a statement in the bodyMapper of an Extract Method

**Commit** 

[Here](https://github.com/skylot/jadx/commit/2d8d4164830631d3125575f055b417c5addaa22f)

**File**

[JavaClass.java](https://github.com/skylot/jadx/commit/2d8d4164830631d3125575f055b417c5addaa22f#diff-569ef7c336deb17468c64425f018df7d27747dee1844305703f01d33ae51d5dc)

**Refactoring**

Extract Method **public getJavaNodeAtPosition(line int, offset int)** : JavaNode extracted **from** **public getDefinitionPosition(line int, offset int)** : CodePosition in class jadx.api.JavaClass

**Problem description**

There is one missing statement inside the bodyMapper of the aforementioned extract method:

- `if (obj == null)` at **line 175** in the child commit

Which is neither reported as a non-mapped-inner node, nor presented in mappings. According to my analysis, this if condition has to be mapped as a non-mapped-inner node.

**Comment by tsantalis** [comment]
The mapping of statements has been improved as shown in the screenshot.
There are two directly extracted methods and one nested extracted method.

![Screenshot from 2022-12-10 20-22-26](https://user-images.githubusercontent.com/1483516/206882492-0bbb0179-1b9b-4ec5-9687-0ebd7ed30982.png)
