### ISSUE TITLE
 org.kohsuke.github.GitHubClient retryConnectionError

### ISSUE THREAD

**Issue by RebeWu** [tsantalis/RefactoringMiner#310]
Even though I have added the github-oauth.properties, I got the error org.kohsuke.github.GitHubClient retryConnectionError.
![image](https://user-images.githubusercontent.com/20625749/206917866-f13c79d0-2e2c-4f94-8127-23d636f77dc4.png)

**Comment by RebeWu** [comment]
Can you tell me how to pass this?  I  can make sure that my github profile is correct.

**Comment by RebeWu** [comment]
@tsantalis

**Comment by tsantalis** [comment]
![Screenshot from 2022-12-11 14-46-38](https://user-images.githubusercontent.com/1483516/206925360-c456c2b9-f82d-445b-ac43-44507e7787ac.png)

I run the same without any problem.
Based on the exception log, your OAuth token does not have the appropriate access rights.

**Comment by RebeWu** [comment]
OK. thanks. I have opened all the rights of my  OAuth token, but it doesn't work, and my GitHub setting shows this token (including previous ones) has never been used. 
By the way, your work is so excellent and try this six months ago in java. I can also not pass the commands about gitURL. Maybe it's the configuration of the certification of GitHub.
