### ISSUE TITLE
If-else-if to switch case

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/RefactoringMiner#315]
https://github.com/checkstyle/checkstyle/commit/ab2f93f9bf61816d84154e636d32c81c05854e24?diff=split#diff-accfc31827d56d36dbbe87ecc685803523f314e63ebd262f8207e346b60262a6R228-R239

![Screenshot from 2022-12-28 22-41-17](https://user-images.githubusercontent.com/1483516/209900517-cb5a57d2-e04b-4b14-a8e6-008c0cccf58f.png)

**Comment by pouryafard75** [comment]
Another case is: https://github.com/checkstyle/checkstyle/commit/5a9b7249e3d092a78ac8e7d48aeeb62bf1c44e20

![image](https://user-images.githubusercontent.com/28820932/215908437-b8e8d0fe-132d-4fcc-ba7c-25c379bb4bdc.png)

**Comment by pouryafard75** [comment]
@tsantalis Another case can be found here:
https://github.com/open-keychain/open-keychain/commit/c11fef6e7c80681ce69e5fdc7f4796b0b7a18e2b#diff-4d4436d415b26cfa599819885f9510c2da0cd152fcd5e1898a135b29ca90bce8R80

File: [DecryptFilesActivity.java](https://github.com/open-keychain/open-keychain/commit/c11fef6e7c80681ce69e5fdc7f4796b0b7a18e2b#diff-4d4436d415b26cfa599819885f9510c2da0cd152fcd5e1898a135b29ca90bce8)
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/28820932/224626392-0ac800f3-6f15-48da-9e21-b7fed9dcef4b.png">

**Comment by pouryafard75** [comment]
Similar problem: https://github.com/VoltDB/voltdb/commit/deb8e5ca64fcf633edbd89523af472da813b6772
[SetFunction.java](https://github.com/VoltDB/voltdb/commit/deb8e5ca64fcf633edbd89523af472da813b6772#diff-78a761f74394c576cdc5eb536467acaad78abec5786fd0d54be30fdebecde3bc)

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/28820932/229313815-ed3e4130-2911-4400-816b-92d4e3bde027.png">

**Comment by tsantalis** [comment]
Switch to if-else-if case:
https://github.com/facebook/facebook-android-sdk/commit/e813a0be86c87366157a0201e6c61662cadee586#diff-d304dfc38233877c7e9430d61c785187dc53079164b49a745bea30984cc80a02

**Comment by pouryafard75** [comment]
@tsantalis 
The revert of these commits:

case1: https://github.com/pouryafard75/TestCases/commit/f0c9e8ed17cc485555756c6af49297b46f99087d
case2:  https://github.com/pouryafard75/TestCases/commit/de98d2123ec51da850ea75797c7053f5faa6dd73
case3: https://github.com/pouryafard75/TestCases/commit/d5f7f3787b1d2b182fe7fd2820893ae0099adb8f

I believe we do have some inconsistency for the case2.

**Comment by tsantalis** [comment]
https://github.com/pouryafard75/TestCases/commit/f0c9e8ed17cc485555756c6af49297b46f99087d

![Screenshot from 2023-04-05 06-31-37](https://user-images.githubusercontent.com/1483516/230055800-a48527fd-e756-4d73-8819-9d14c8ad8931.png)

**Comment by tsantalis** [comment]
@pouryafard75 

I checked case2
https://github.com/pouryafard75/TestCases/commit/de98d2123ec51da850ea75797c7053f5faa6dd73

and all mappings are properly contained in the bodyMapper.

There must be something happening on the AST diff side. Could you please have a look?
