### ISSUE TITLE
RefactoringMiner cannot finish processing a commit from project Nutch

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/RefactoringMiner#32]
https://github.com/apache/nutch/commit/c93d908bb635d3c5b59f8c8a22e0584ebf588794

**Comment by Ivan-Veselov** [comment]
On my machine it's finished in 1 hour and 5 minutes according to `System.currentTimeMillis()`. According to visualvm profiler one of overloads of `editDistance` consumed a lot of CPU time.

https://github.com/tsantalis/RefactoringMiner/blob/cb82a94d553c668bed969dd42ecbdaefbf3ae497/src/gr/uom/java/xmi/diff/StringDistance.java#L11
