### ISSUE TITLE
Moved method doesn't have to have the same name

### ISSUE THREAD

**Issue by Ivan-Veselov** [tsantalis/RefactoringMiner#34]
Hi!

Appreciate your work, it's great!

In article _"Accurate and Efficient Refactoring Detection in Commit History"_ you give a set of "Refactoring detection rules" that are used to detect a refactoring. I'm interested in Move Method refactorings, so the following is about them. There is no restriction on method name in detection rules for Move Method refactoring (according to the article). And it sounds logical: it is possible to move method and immediately in the same commit rename it (for example if old name doesn't fit the new class well). But according to source code in this repository and my experience with RMiner you do require moved method to have the same name:

https://github.com/tsantalis/RefactoringMiner/blob/cb82a94d553c668bed969dd42ecbdaefbf3ae497/src/gr/uom/java/xmi/diff/UMLModelDiff.java#L1244

Are there any specific reasons for this to be? Is it OK to just remove this particular line? Are there any pitfalls that may follow?

**Comment by tsantalis** [comment]
Hi Ivan,

The case you refer to is actually a Move & Rename Method (i.e., two refactoring operations in sequence).
Recently, RefactoringMiner supported the detection of Move & Rename Class.
Therefore, I think we gained enough knowledge to add support for Move & Rename Method.

If you just comment out the aforementioned line, there will be two implications:
1. **Performance**: The number of method combinations to be compared will increase significantly.
2. **Accuracy**: The chances of having false positives/negatives will increase, in the case where a removed method can be matched with multiple added methods and vice versa.

RefactoringMiner follows a round-based detection approach, where in each round the matching conditions get more relaxed.
For example, in the detection of Move/Rename Class refactorings,
in the first round it will match all classes with the same name, but different package
in the second round it will match all classes with different name, but same package and
in the final round it will match all remaining classes with both different name and package.

A similar approach can be applied for Move/Rename Method refactorings.
I will add your issue as a feature request.

**Comment by tsantalis** [comment]
The added feature still needs more validation.
We have [46 True Positives](http://refactoring.encs.concordia.ca/oracle/tool-refactorings/RefactoringMiner/TP/Move%20And%20Rename%20Method) in our oracle with the current detection rule.
