### ISSUE TITLE
Sub-expression mapping is missing while ExtractMethod Refactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#340]
Commit: https://github.com/rstudio/rstudio/commit/cb49e436b9d7ee55f2531ebc2ef1863f5c9ba9fe
File: [ScrollableToolbarPopupMenu.java](https://github.com/rstudio/rstudio/commit/cb49e436b9d7ee55f2531ebc2ef1863f5c9ba9fe#diff-b562f901b3f3ec54de4d27326e16031eebe612a2388d4c296d4c8cf04ae86401)

In the following refactoring:
```Extract Method	protected setMaxHeight(maxHeight int) : void extracted from protected wrapMenuBar(menuBar ToolbarMenuBar) : Widget in class org.rstudio.core.client.widget.ScrollableToolbarPopupMenu```

all the statements are mapped correctly. There is one expression mapping that is missing:

```getMaxHeight()``` line **72** parent commit => ```getMaxHeight()```Line **71** child commit 
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/28820932/215986045-ad1857e4-934f-41db-98ed-5212329c286d.png">

**Comment by pouryafard75** [comment]
Fixed after the introduction of **argumentMappings**,  in c626986.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28820932/220481337-0dcd2728-9b2e-48ab-9c6d-fc41c67a92ea.png">

@tsantalis You can close this issue.

**Comment by tsantalis** [comment]
Fix is confirmed

![Screenshot from 2023-03-05 18-10-11](https://user-images.githubusercontent.com/1483516/222991324-b6bec596-8941-4178-95de-d96380ded1d5.png)
