### ISSUE TITLE
ExtractVariable on top of another ExtractVariableRefactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#342]
Commit: https://github.com/JetBrains/intellij-community/commit/7ed3f273ab0caf0337c22f0b721d51829bb0c877
File: [EduStepicConnector.java](https://github.com/JetBrains/intellij-community/commit/7ed3f273ab0caf0337c22f0b721d51829bb0c877#diff-15f0bf20887653b9aeb199ba1dde2617bf79c857885fd21fadbacc20a1fc7ea0)

There is a case of ExtractVariable on top of another ExtractVariableRefactoring inside an ExtractMethodRefactoring.

Inside the following extract method refactoring:
```Extract Method	private addCoursesFromStepic(result List<CourseInfo>, pageNumber int) : boolean extracted from public getCourses() : List<CourseInfo> in class com.jetbrains.edu.stepic.EduStepicConnector```

The following refactoring was detected:
```Extract Variable coursesContainer : CoursesContainer in method private addCoursesFromStepic(result List<CourseInfo>, pageNumber int) : boolean from class com.jetbrains.edu.stepic.EduStepicConnector```

There is also another ExtractVariableRefactoring which can be reported for the ```final String url``` in line **160** child commit.
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/28820932/215986417-069c5239-4ea1-448c-978c-26ab8c71c024.png">

**Comment by tsantalis** [comment]
After supporting overlapping Extract Variable refactorings:

![Screenshot from 2023-02-04 13-48-35](https://user-images.githubusercontent.com/1483516/216784417-36f8ff7e-517a-44c2-83e1-b98d81f35c0a.png)

**Comment by pouryafard75** [comment]
👍
