### ISSUE TITLE
Ternary operator replaced by a newly introduced if condition

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#344]
Commit: https://github.com/Athou/commafeed/commit/18a7bd1fd1a83b3b8d1b245e32f78c0b4443b7a7\
File: [DefaultFaviconFetcher.java](https://github.com/Athou/commafeed/commit/18a7bd1fd1a83b3b8d1b245e32f78c0b4443b7a7#diff-ff3cf2009ccf915adff9467bada9f8428d924af84675188f7191554eeca95968)
Inside method ```public byte[] fetch(Feed feed)```:

Ternary operator replaced by if condition:
Line **32** parent commit => Line **34** child commit
The goal is to find the subexpression mapping for ```feed.getUrl()```. However, the entire statements can be mapped as well.

Also the If statement ```if (icon == null) {..}``` Line **52** child commit has been multimapped with:
- Line **33** child commit
- Line **58** child commit

The first one does not seem to be correct.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28820932/215987024-12b26927-9555-4686-b119-d8bd512f5b17.png">

**Comment by pouryafard75** [comment]
@tsantalis 
- MultiMapping must be removed. The only mapping for the `if` is inside the extract method. 
- `url` and `icon` declaration should be not matched.
- Imrpove ArgumentMappings to support unmatched statements.

**Comment by pouryafard75** [comment]
@tsantalis 
This case is also similar:
https://github.com/JetBrains/intellij-community/commit/8d7a26edd1fedb9505b4f2b4fe57b2d2958b4dd9

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/28820932/225793141-711cec93-0d6f-4d8a-9e63-0f2a46260e2d.png">

**Comment by tsantalis** [comment]
The multi-mapping issue for https://github.com/Athou/commafeed/commit/18a7bd1fd1a83b3b8d1b245e32f78c0b4443b7a7 is resolved

![Screenshot from 2023-04-08 12-24-31](https://user-images.githubusercontent.com/1483516/230732239-c4332e66-a188-4e53-b4fe-8abe79b19a41.png)

**Comment by tsantalis** [comment]
In both cases, the condition checked in the conditional expression is different from the condition checked in the `if` statement. This makes quite challenging to detect the migration

**Comment by tsantalis** [comment]
![Screenshot from 2023-04-19 22-01-43](https://user-images.githubusercontent.com/1483516/233239608-6308c622-68e1-4382-95f5-ce277f5c2a02.png)
