### ISSUE TITLE
Replacement inaccuracy within an Extract Method refactoring

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#345]
**Problem**

The replacement set reported for a statement mapping is empty, which is incorrect

**Commit**

[Here](https://github.com/apache/cassandra/commit/f797bfa4da53315b49f8d97b784047f33ba1bf5f)

**File**

[UUIDGen.java](https://github.com/apache/cassandra/commit/f797bfa4da53315b49f8d97b784047f33ba1bf5f#diff-4e5ec70c0ffd2fa0921be0ef79325bfb1e01fa8ec53985bc5a42fdce531dcb13)

**Refactoring object**

Extract Method **private fromUnixTimestamp(timestamp long, nanos long)** : long extracted **from private fromUnixTimestamp(timestamp long)** : long in class org.apache.cassandra.utils.UUIDGen

**Description**

There is only one statement mapping within the aforementioned Extract Method refactoring, which is:

- `return (timestamp - START_EPOCH) * 10000;` Line **172** in the **parent** version
To
- `return ((timestamp - START_EPOCH) * 10000) + nanos;` Line **182** in the **child** version

**The replacement set for this statement mapping object is empty, which is obviously wrong**. Since PurityChecker uses the replacements information as one of it's reasoning parts, these two statement are exact the same in PurityChecker's point of view, which is incorrect.

**Comment by tsantalis** [comment]
@pedramnoori 

A Concatenation replacement is now reported.
