### ISSUE TITLE
Missing Replacement within an Extract Method refactoring

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#346]
**Problem**

Replacement set is empty although there is a change within the statement mapping

**Commit**

[Here](https://github.com/Alluxio/alluxio/commit/ed966510ccf8441115614e2258aea61df0ea55f5)

**File**

[StorageDir.java](https://github.com/Alluxio/alluxio/commit/ed966510ccf8441115614e2258aea61df0ea55f5#diff-3cdf86aa9fb4676e7fd2a12b5210fc5952aeaf944b925ef44e971a2dd13dcafa)

**Refactoring**

Extract Method private **reclaimSpace(size long)** : void extracted **from public removeTempBlockMeta(tempBlockMeta TempBlockMeta)** : boolean in class tachyon.worker.block.meta.StorageDir

**Problem description**

Within the following statement mapping, **the replacement is empty**"

- `Preconditions.checkState(mCapacityBytes >= mAvailableBytes,"Available bytes should always be less than total capacity bytes");`

mapped with

- `Preconditions.checkState(mCapacityBytes >= mAvailableBytes + size,"Available bytes should always be less than total capacity bytes");`

**although the right hand side of the check has been changed.**

**Comment by tsantalis** [comment]
@pedramnoori 

A Concatenation replacement is reported for this case.
