### ISSUE TITLE
Mapping not reported: Statement Moved out of the if statement while enclosing try-finally block was removed.

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#349]
Commit: https://github.com/Netflix/eureka/commit/f6212a7e474f812f31ddbce6d4f7a7a0d498b751
File: [DiscoveryClient.java](https://github.com/Netflix/eureka/commit/f6212a7e474f812f31ddbce6d4f7a7a0d498b751#diff-fc1737bdfb41c9dc55bd09357b48c080bd563e6677adf78fc24c2066a1f3ef86)

**Problem:**
The following mapping is missing from the ```void updateInstanceRemoteStatus()``` bodyMapper:
- Line **890** parent commit ```lastRemoteInstanceStatus = currentRemoteInstanceStatus;``` =>  Line **888** child commit ```lastRemoteInstanceStatus = currentRemoteInstanceStatus;```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28820932/216078018-2357b780-b82b-4f20-b1bc-1caff736496d.png">

**Comment by tsantalis** [comment]
![Screenshot from 2023-02-04 23-05-13](https://user-images.githubusercontent.com/1483516/216801014-6448222e-aa05-4184-bb82-66e395e48023.png)
