### ISSUE TITLE
Wrong statement mapping

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#350]
**Problem**

Wrong statement mapping within an Extract Method

**Commit**

[Here](https://github.com/wordpress-mobile/WordPress-Android/commit/f8d5cf01f123a1d0a65857aa2db0571fe9cd1911)

**File**

[Blog.java](https://github.com/wordpress-mobile/WordPress-Android/commit/f8d5cf01f123a1d0a65857aa2db0571fe9cd1911#diff-b95b612f972466fcc6f236bd930d07373df498d62e5ed3ba0d59589952839956)

**Refactoring case**

Extract Method **private getIconImageURL(size int, iconUrl String, blogUrl String)** : String extracted **from public getIconImageURL(size int)** : String in class org.wordpress.android.models.Blog

**Problem description**

There is a nonMappedInnerNodeT2 within the aforementioned Extract Method refactoring: `if(iconUrl == null)` Line 489. This composite statement should be mapped with `if (iconURL == null)` Line 478 in the parent commit. The latter has been mapped with another composite statement, which I believe is wrong.

**Comment by tsantalis** [comment]
![Screenshot from 2023-02-07 15-55-51](https://user-images.githubusercontent.com/1483516/217363641-acd0c6e9-f3e0-45bb-a6e3-17b668ed6d25.png)
