### ISSUE TITLE
Inaccurate mapping for the ExtractMethodRefactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#352]
Commit: https://github.com/wordpress-mobile/WordPress-Android/commit/f8d5cf01f123a1d0a65857aa2db0571fe9cd1911
File: [Blog.java](https://github.com/wordpress-mobile/WordPress-Android/commit/f8d5cf01f123a1d0a65857aa2db0571fe9cd1911#diff-b95b612f972466fcc6f236bd930d07373df498d62e5ed3ba0d59589952839956)

```Extract Method	private getIconImageURL(size int, iconUrl String, blogUrl String) : String extracted from public getIconImageURL(size int) : String in class org.wordpress.android.models.Blog```

The following mappings are missing:

- Line range **478-480** parent commit ```if (iconURL == null) {...}``` => Line range ~~479-481~~ **489-491** child commit ```if (iconUrl == null) {...}```

- Line **479** parent commit ```return blavatarUrl;``` => Line ~~480~~ **490** ```return blavatarUrl;```

![image](https://user-images.githubusercontent.com/28820932/215944382-a234ab57-e878-40a9-b963-ed70a94ce149.png)

**Comment by pouryafard75** [comment]
And what is the proper mapping for ```this.getUrl()``` in parent version line 477? @tsantalis

**Comment by pouryafard75** [comment]
This is a duplicate of https://github.com/tsantalis/RefactoringMiner/issues/350.

**Comment by tsantalis** [comment]
![Screenshot from 2023-02-07 15-55-51](https://user-images.githubusercontent.com/1483516/217363719-93dd788d-c788-4cce-9aea-093390e62b0a.png)

**Comment by tsantalis** [comment]
![Screenshot from 2023-02-09 02-46-53](https://user-images.githubusercontent.com/1483516/217749489-0465c71f-c03f-4157-8d34-277502becd9c.png)
