### ISSUE TITLE
ExtractVariable Refactoring with more than one subExpressionMappings but only one was reported

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#353]
Commit: https://github.com/signalapp/Signal-Android/commit/c4a37e38aba926c2bef27e4fc00e3a4848ce46bd
File:[src/org/thoughtcrime/securesms/ConversationActivity.java](https://github.com/signalapp/Signal-Android/commit/c4a37e38aba926c2bef27e4fc00e3a4848ce46bd#diff-c8b054d138c679f6453d2cd3afbeab77387a0fba6037f03b970f1af66591318e)

Method: ```private Drafts getDraftsForCurrentState()```
ExtractVariableRefactoring was reported but only one of the subExpressionMappings has been reported.
The other two LeafMappings which were not reported, are expected to be as:
- Line **1022** parent  ```Draft.VIDEO``` =>  Line **1070** child ```Draft.VIDEO```
- Line **1023** parent  ```Draft.IMAGE``` =>  Line **1071** child ```Draft.IMAGE```

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/28820932/215979690-830e4b4a-3099-43c0-bee0-bcca0fc7ab53.png">

**Comment by tsantalis** [comment]
The number of `leaves1` is less than the number of `leaves2`.
This has a single mapping as a result.

if the number of `leaves2` was less than the number of `leaves1`
then we would get a 1-to-3 multi-mapping between statements:

`drafts.add(new Draft(draftType, slide.getUri().toString()));`
and
`drafts.add(new Draft(Draft.AUDIO, slide.getUri().toString()));`
`drafts.add(new Draft(Draft.VIDEO, slide.getUri().toString()));`
`drafts.add(new Draft(Draft.IMAGE, slide.getUri().toString()));`

**Comment by tsantalis** [comment]
![Screenshot from 2023-03-30 08-05-58](https://user-images.githubusercontent.com/1483516/229230558-bb294e21-4cc2-42cc-a7bd-920e826358f2.png)
