### ISSUE TITLE
Extract Variable Refactorings are not detected due to the use of Parenthesis

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#354]
Commit: https://github.com/pouryafard75/TestCases/commit/025a71a6a23a16a0708f9e7fa0101dfda13023e2
File: [ExVar/1/Run.java](https://github.com/pouryafard75/TestCases/commit/025a71a6a23a16a0708f9e7fa0101dfda13023e2#diff-8753fce52924d4212e8901241265818ed02a85c6ee474d4eb9e1d9d10d739ec9)

This example is generated by **_ChatGPT_** to demonstrate the Extract Variable Refactoring technique.
However, due to the parenthesis, none of the three refactorings are detected.

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28820932/215982059-ddde4f32-b8e6-4d9d-851f-fd4520da540c.png">

**Comment by tsantalis** [comment]
@pouryafard75 
![Screenshot from 2023-04-21 14-23-01](https://user-images.githubusercontent.com/1483516/233708484-ae015ba5-21c5-44ca-9725-8ace52c58401.png)
