### ISSUE TITLE
Common Exception Types reported inaccurately because of the Identical Exception local name (type of the exception ignoring the qualifier)

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#355]
Commit: https://github.com/JetBrains/intellij-community/commit/6ff3fe00d7ffe04dbe0904b8bad98285b6988d6d
File: [src/org/jetbrains/idea/maven/server/Maven32ServerEmbedderImpl.java](https://github.com/JetBrains/intellij-community/commit/6ff3fe00d7ffe04dbe0904b8bad98285b6988d6d#diff-91b7a77ae75a383fc78e2ae300f83c19a93b9c491770004e41ac4a8c967bf6d0)
Method: ```private Artifact resolve```
CommonExceptionTypes:
- ArtifactResolutionException => **ArtifactResolutionException**
- org.eclipse.aether.resolution.ArtifactResolutionException => ~~ArtifactResolutionException~~  **org.eclipse.aether.resolution.ArtifactResolutionException**
As a result of this, a multiMapping has occurred:
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/28820932/215984099-58b13924-12e0-4c0d-a013-62151d414c0b.png">

**Comment by tsantalis** [comment]
![Screenshot from 2023-03-05 21-36-24](https://user-images.githubusercontent.com/1483516/223007515-8c339602-ac15-44f1-84cd-4ccad3ca2cf5.png)

**Comment by tsantalis** [comment]
Works even the qualified type is before the non-qualified type:

![Screenshot from 2023-03-06 06-30-49](https://user-images.githubusercontent.com/1483516/223098491-6bb2790e-0b36-49fe-b5f7-c3239340f76a.png)
