### ISSUE TITLE
False Inline Method refactoring

### ISSUE THREAD

**Issue by onewhl** [tsantalis/RefactoringMiner#356]
Hi! False positive Inline Method refactoring was detected by the tool.
Project: https://github.com/JetBrains/Arend
Commit: 71a7665708963ee2bb53dce6da3c78c1075873ae
Class: ExpressionResolveNameVisitor
Method: visitPatterns()
RefactoringMiner version: 2.3.2

**Comment by tsantalis** [comment]
Hi @onewhl 

Inline Method is no longer detected when running RefactoringMiner built from the latest commit.

Here is the current list of detected refactorings in this commit:

**Remove Parameter** resolvePatterns : boolean in method public visitPatterns(patterns List<Concrete.Pattern>, usedNames Map<String,Referable>, resolvePatterns boolean) : void from class org.arend.naming.resolving.visitor.ExpressionResolveNameVisitor

**Add Parameter** newRef : Referable in method public patternResolved(originalRef Referable, newRef Referable, pattern Concrete.Pattern, resolvedRefs List<Referable>) : void from class org.arend.naming.resolving.ResolverListener

**Change Parameter Type** pattern : Concrete.ConstructorPattern to pattern : Concrete.Pattern in method public patternResolved(originalRef Referable, newRef Referable, pattern Concrete.Pattern, resolvedRefs List<Referable>) : void from class org.arend.naming.resolving.ResolverListener

**Add Parameter** resolvedRefs : List<Referable> in method public tryResolve(referable Referable, scope Scope, resolvedRefs List<Referable>) : Referable from class org.arend.naming.resolving.visitor.ExpressionResolveNameVisitor
