### ISSUE TITLE
Extract Attribute Refactoring not reported

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#359]
Commit: https://github.com/HdrHistogram/HdrHistogram/commit/0e65ac4da70c6ca5c67bb8418e67db914218042f
File: [HistogramLogProcessor.java](https://github.com/HdrHistogram/HdrHistogram/commit/0e65ac4da70c6ca5c67bb8418e67db914218042f#diff-45b7dd122af2043b8813e1090d626acdf82a7f4abe85d839bc6623e05d24ba5e)

Local variable  ```int lineNumber = 0;``` line 160 parent -> Attribute ``` int lineNumber = 0;``` line 151 child.

![image](https://user-images.githubusercontent.com/28820932/217340061-a7406ce8-c4e2-4ef6-8980-f980989abcf8.png)

In this case, the Extract Attribute Refactoring is not detected.

**Comment by tsantalis** [comment]
@pouryafard75 
There is a new refactoring reported `Replace Variable with Attribute`. The actual refactoring type is `RenameVariable`.
Both VariableDeclaration objects for the variable and attribute are included in this refactoring.
You can create a mapping between the two declarations.
