### ISSUE TITLE
AnonymousClass inside the bodyMapper of ExtractOperationRefactoring is missing

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#361]
Commit: https://github.com/JetBrains/intellij-community/commit/98ecc4cfd927f388645f6a6bc492c80868b1a11d
File: [CreateResourceBundleDialogComponent.java](https://github.com/JetBrains/intellij-community/commit/98ecc4cfd927f388645f6a6bc492c80868b1a11d#diff-8e0aaf5916e4d82e11ef55f6f18e065c6fbcf161581933055b61279cad8e399f)

There is an ExtractMethodRefactoring.
The return statement inside the newly introduced method contains an anonymous class but the bodyMapper of the extract method doesn't have it as anonymousClassDiffs.
As a result, the method is not mapped:
![image](https://user-images.githubusercontent.com/28820932/217409861-67bdd38e-0737-4f90-8789-9e1afb6a39f0.png)

**Comment by tsantalis** [comment]
![Screenshot from 2023-02-10 14-35-40](https://user-images.githubusercontent.com/1483516/218182290-9bc099db-cfc9-4aee-9d6f-ad3ab229aa0e.png)
