### ISSUE TITLE
Statement mapping problem

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#362]
**Problem**

One statement reported as a non-mapped leaves as well as within a statement mapping in a Move Method refactoring bodyMapper

**Commit**

[Here](https://github.com/eucalyptus/eucalyptus/commit/5a38d0bca0e48853c3f7c00a0f098bada64797df)

**Refactoring object**

**Move Method** protected **dealWithAbsoluteMetrics**(dataBatch List<MetricQueueItem>) : List<MetricQueueItem> from class com.eucalyptus.cloudwatch.domain.metricdata.**MetricDataQueue** to protected dealWithAbsoluteMetrics(dataBatch List<AbsoluteMetricQueueItem>) : List<AbsoluteMetricQueueItem> from class com.eucalyptus.cluster.callback.cloudwatch.**AbsoluteMetricQueue**

**Problem description**

Within the bodyMapper of the aforementioned refactoring, the following statement reported as a nonMappedLeave in parent version:

`dataToInsert.add(createVolumeThroughputMetric(accountId,nameSpace,metricType,datum)); ` Line **227** in **MetricDataQueue.java**

The problem is that the same statement has been reported within a statement mapping in the same Move Method stated above.
I want to emphasize that this statement should be reported in the corresponding statement mapping. In other words, the expected behavior is that the statement needs to be removed from nonMappedLeavesT1.

**Comment by tsantalis** [comment]
@pedramnoori 
Statement `dataToInsert.add(createVolumeThroughputMetric(accountId,nameSpace,metricType,datum));`
is no longer reported in nonMappedLeaves.
