### ISSUE TITLE
Feature Request: Support for moved statements between functions that are not necessary relevant

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#363]
Commit: https://github.com/MovingBlocks/Terasology/commit/8f63cc5c8edb8e740026447bc4827f8e8e6c34b1
File: [PreviewWorldScreen.java](https://github.com/MovingBlocks/Terasology/commit/8f63cc5c8edb8e740026447bc4827f8e8e6c34b1#diff-4b14a1fe1d90de983cf982262e99da463cfb7a480153c7eb0bb704ec3c77d7f8)

Sta

- Line **127** parent commit: 
```EnvironmentSwitchHandler environmentSwitchHandler = context.get(EnvironmentSwitchHandler.class);```
is identical to
Line **148** child commit:
```EnvironmentSwitchHandler environmentSwitchHandler = context.get(EnvironmentSwitchHandler.class);```

- Line **128** parent commit:
```environmentSwitchHandler.handleSwitchToPreviewEnivronment(context, environment);```
is identical to
Line **149** child commit:
```environmentSwitchHandler.handleSwitchToPreviewEnivronment(context, environment);```

- Line **129** parent commit:
```genTexture();```
is identical to
Line **150** child commit:
```genTexture();```

- Line **132** child commit:
```previewGen = new FacetLayerPreview(environment, worldGenerator);```
is identical to
Line **151** parent commit:
```previewGen = new FacetLayerPreview(environment, worldGenerator);```

However, these moved statements cannot be easily justified by the refactoring mechanisms.

![image](https://user-images.githubusercontent.com/28820932/217430678-e30f5965-67d8-4abf-84fd-10e3186f6ed5.png)

**Comment by tsantalis** [comment]
![Screenshot from 2023-02-10 10-51-14](https://user-images.githubusercontent.com/1483516/218135516-cfffcf37-4ff0-48fd-9e69-3299dbca38fc.png)
