### ISSUE TITLE
Missing Statement mapping for the case of nested anonymous classes

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#364]
Commit: https://github.com/JetBrains/intellij-community/commit/619a6012da868d0d42d9628460f2264effe9bdba
File: [ChooseByNameBase.java](https://github.com/JetBrains/intellij-community/commit/619a6012da868d0d42d9628460f2264effe9bdba#diff-348dd8cbf908ea3192aa5106509f912d72a36a1f5f4dded21b13a410e4774fef)

Problem 
- Missing Statement Mapping for the case of nested anonymous classes
- anonymousClassDiffList returns as an empty list

Inside ```public run(indicator ProgressIndicator) : void -> public run(indicator ProgressIndicator) : void``` bodyMapper:

Line Range **1708-1718** parent commit:
```
myCalcUsagesThread = new CalcElementsThread(text, everywhere, null, ModalityState.NON_MODAL, false) {
              @Override
              protected boolean isOverflow(@NotNull Set<Object> elementsArray) {
                tooManyUsagesStatus.pauseProcessingIfTooManyUsages();
                if (elementsArray.size() > UsageLimitUtil.USAGES_LIMIT - myMaximumListSizeLimit && tooManyUsagesStatus.switchTooManyUsagesStatus()) {
                  int usageCount = elementsArray.size() + myMaximumListSizeLimit;
                  UsageViewManagerImpl.showTooManyUsagesWarning(getProject(), tooManyUsagesStatus, indicator, presentation, usageCount, null);
                }
                return false;
              }
            };
```
can be mapped with:
Line range **1711-1721** child commit:
```
myCalcUsagesThread = new CalcElementsThread(text, everywhere, null, ModalityState.NON_MODAL) {
              @Override
              protected boolean isOverflow(@NotNull Set<Object> elementsArray) {
                tooManyUsagesStatus.pauseProcessingIfTooManyUsages();
                if (elementsArray.size() > UsageLimitUtil.USAGES_LIMIT - myMaximumListSizeLimit && tooManyUsagesStatus.switchTooManyUsagesStatus()) {
                  int usageCount = elementsArray.size() + myMaximumListSizeLimit;
                  UsageViewManagerImpl.showTooManyUsagesWarning(getProject(), tooManyUsagesStatus, indicator, presentation, usageCount, null);
                }
                return false;
              }
            };
```

The statements are not identical, (**_false_** literal at the end of the first line).

Also, the anonymousClassDiff returns empty, and the ```isOverflow``` method declared inside this statement is not mapped. 

![image](https://user-images.githubusercontent.com/28820932/217433774-ebd1932e-c2e3-41a0-a7f7-e68458f590d7.png)

Regarding the ```@NotNull Set<Object> elementsArray``` the mappings for diff are created from the ```umlOperationBodyMapper.getMatchedVariables()``` executed from the ```public void run(@NotNull final ProgressIndicator indicator)```.

**Comment by tsantalis** [comment]
![Screenshot from 2023-02-10 12-59-33](https://user-images.githubusercontent.com/1483516/218162972-9ab0015d-b38c-415f-8b9c-13be795ab5d8.png)
