### ISSUE TITLE
Additional ArgumentMappings reported

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#367]
Commit: https://github.com/crashub/crash/commit/2801269c7e47bd6e243612654a74cee809d20959
[FilePublicKeyProvider.java](https://github.com/crashub/crash/commit/2801269c7e47bd6e243612654a74cee809d20959#diff-9c518f5d6b3f51141ed56c777776030bf0b055c80694d845f925b0c31f00e795)

**Refactoring**: `Extract Method	private convertPemKeyPair(pemKeyPair PEMKeyPair) : KeyPair extracted from public loadKeys() : Iterable<KeyPair> in class org.crsh.auth.FilePublicKeyProvider`

**Problem:** Two argument mappings are reported. However only one seems to be enough for this case.

- `keyPair` Line **68** -> `keyPair` Line **69** (Correct)
- `keyPair` Line **68** -> `keyPair` Line **72** (Unnecessary)

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/28820932/218831381-e88163c5-14df-4fb2-a366-8277698c9b52.png">

**Comment by tsantalis** [comment]
@pouryafard75 
The method is called two times.
So, it seems the developer extracted the method and then re-used it for a new case ` instanceof SubjectPublicKeyInfo`.

We should report only the first one, if we want to be 100% correct.
It is doable, if we check if the variable `keyPair` is declared in a mapped statement or not.
Thankfully, the variable declarations have scopes, and it is easy to check which statements are within their scope.

**Comment by pouryafard75** [comment]
Thanks for the clarification.

**Comment by tsantalis** [comment]
@pouryafard75 
I will fix it in RefactoringMiner core.

**Comment by tsantalis** [comment]
@pouryafard75 
Please test it with previous cases. The fix checks if the statement containing the call, or its parent have a mapping in the parentMapper. In this way, we can exclude code that is newly added to the method.

![Screenshot from 2023-02-15 07-20-34](https://user-images.githubusercontent.com/1483516/219026317-6521400f-390b-4289-9877-c9e3ec752f9e.png)

**Comment by tsantalis** [comment]
@pouryafard75 
Shouldn't we have something like `keyPair` matched + renamed to `pemKeyPair` in the extracted method, instead of having `pemKeyPair` as added?
