### ISSUE TITLE
Fix Pull Up Method

### ISSUE THREAD

**Issue by Ivan-Veselov** [tsantalis/RefactoringMiner#37]
I have two instances of weird behaviour. Both of them relate to Pull Up Method.

**The first one:**
Commit: https://github.com/netty/netty/commit/bfbef036a8c1121083b485a98b9cb04a84e7dfea
Part of output:
```
Pull Up Method	public continueReading() : boolean from class io.netty.channel.epoll.EpollRecvByteAllocatorMessageHandle to package maybeMoreDataToRead() : boolean from class io.netty.channel.epoll.EpollRecvByteAllocatorHandle
Pull Up Method	public continueReading() : boolean from class io.netty.channel.epoll.EpollRecvByteAllocatorMessageHandle to public continueReading() : boolean from class io.netty.channel.epoll.EpollRecvByteAllocatorHandle
```
If the second refactoring looks  fine (though I'm not 100% it is a method pull up), the first one is strange.
1. It's a move of the same method.
1. It's said that method is moved to package.
1. Bodies of original method and moved are not similar. Though they have something in common, and their bodies are too small to make significant difference.

**The second one:**
Commit: https://github.com/PhilJay/MPAndroidChart/commit/c22b47ce59db34160e336c0c2edbd81506ee8811
Part of output:
```
Pull Up Method	public setRotation(angle float) : void from class com.github.mikephil.charting.charts.RadarChart to private calcFormats() : void from class com.github.mikephil.charting.charts.PieRadarChartBase
```
Strange thing here is that bodies of two methods are completely different:
```
public void setRotation(float angle) {
        
        angle = Math.abs(angle % 360f);
        mOffsetAngle = angle;
}
```

```
private void calcFormats() {
    // -1 means calculate digits
    if (mValueDigitsToUse == -1) {
        if (mOriginalData.getXValCount() <= 1)
            mValueFormatDigits = 0;
        else
            mValueFormatDigits = Utils.getPieFormatDigits(mDeltaY);
    }
    else
        mValueFormatDigits = mValueDigitsToUse;
}
```
Also:
1.  `setRotation` was actually pulled up to `setRotationAngle`.
1. `calcFormats` also was pulled up and it saved its name, but there also were some extractions.

**Comment by tsantalis** [comment]
The first case is actually a case of nested refactorings, which RefactoringMiner does not handle (discussed in Section 3.4 of the paper "Accurate and Efficient Refactoring Detection in Commit History").

Method `continueReading()` is first pulled up to the superclass, and then method `maybeMoreDataToRead()` is extracted from `continueReading()`

**BEFORE REFACTORING**
```java
public boolean continueReading() {
    return isEdgeTriggered() || isRdHup() ? true : super.continueReading();
}
```
**AFTER REFACTORING**
```java
public final boolean continueReading() {
    return receivedRdHup ||  maybeMoreDataToRead() && config.isAutoRead() || super.continueReading();
}
boolean maybeMoreDataToRead() {
    return isEdgeTriggered && lastBytesRead() > 0;
}
```

Furthermore, we have the following changes on top of the refactorings:
1. The call to `isRdHup()` is replaced with field access `receivedRdHup`
2. In the extracted method `maybeMoreDataToRead()` the call to `isEdgeTriggered()` is replaced with field access `isEdgeTriggered` and a new condition is added `&& lastBytesRead() > 0`
3. In the original method `continueReading()` a new condition is added `&& config.isAutoRead()`

**Comment by tsantalis** [comment]
The second case is indeed a false positive.
The correct refactoring is

```
Pull Up Method public setRotation(angle float) : void from class com.github.mikephil.charting.charts.RadarChart to public setRotationAngle(angle int) : void from class com.github.mikephil.charting.charts.PieRadarChartBase
```
and is fixed in the last commit.
