### ISSUE TITLE
Inaccurate Mappings

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#372]
https://github.com/spring-projects/spring-boot/commit/20d39f7af2165c67d5221f556f58820c992d2cc6
File: [VcapApplicationListener.java](https://github.com/spring-projects/spring-boot/commit/20d39f7af2165c67d5221f556f58820c992d2cc6#diff-20c0e93c9cdc48e5daf515f3d0b15d4b3480911e5ccf54c5379ff24b8a3703bf)
Problem: **Inaccurate mappings**

`private void flatten` operationBodyMapper:
- [x] Identical if-else statements are mapped incorrectly:
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/28820932/220486190-9e14ec63-be39-4bd0-8d16-d12107ac67cf.png">

- [ ] It would be a nice improvement if we have the refactoring/mappings for `@SuppressWarnings("unchecked")`
such as Moved Annotation from method body to method signature.
Currently, the reported refactoring is Add Method Annotation which is correct but can be improved. 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/28820932/220486778-6f9b4636-9d90-42fa-98aa-9e89b6eb2958.png">

**Comment by tsantalis** [comment]
@pouryafard75 
I think we are going too far by supporting `Move Annotation` from a variable declaration to its parent method declaration.
I don't think it is wrong to show it as deleted/added.
Is this annotation matched by GumTree?

![Screenshot from 2023-03-05 09-49-49](https://user-images.githubusercontent.com/1483516/222967837-99b87f42-cbd3-4dee-ab12-843bddf14264.png)

**Comment by pouryafard75** [comment]
@tsantalis Yes, the annotation is matched by GumTree.
Line **208** parent `SuppressWarnings("unchecked")` -> Line **179** Child `SuppressWarnings("unchecked")`
However, there must be a multi mapping for this annotation because it also exists in Line **202** parent. They miss this one.
This is GumTree's diff. 👇 
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/28820932/223580306-33fe1fc9-5865-4657-b458-3524c8a6c150.png">

**Comment by pouryafard75** [comment]
@tsantalis I am going to add this to our test cases #395 . If ever we introduce the new refactoring, the test must be updated.

**Comment by tsantalis** [comment]
@pouryafard75 
`SuppressWarnings` is matched with `flatten` method invocation name !!!!

Can you do some research to check if it is a common practice to move `@SuppressWarnings` to the parent container (method declaration) ?

**Comment by pouryafard75** [comment]
@tsantalis The first one is matched correctly. But the second one is matched incorrectly.
So far, This was the first related to moving the annotation to the method declaration.
