### ISSUE TITLE
Feature Request: Complex sub-expression mappings

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#373]
https://github.com/spring-projects/spring-boot/commit/cb98ee25ff52bf97faebe3f45cdef0ced9b4416e
File: [WebMvcAutoConfigurationTests.java](https://github.com/spring-projects/spring-boot/commit/cb98ee25ff52bf97faebe3f45cdef0ced9b4416e#diff-c0191699ffddda3119feb211eefa1105f84d6932fa7f50f7a7d5602137da4af0)
The multi-mappings are correct. The question is only regarding the red(deleted) and green(added) parts.
Statement mappings are reported correctly. Can we have sub-expression mappings for `Config.class`, `WebMvcAutoConfiguration.class`, `HttpMessageConvertersAutoConfiguration.class` and `PropertyPlaceholderAutoConfiguration.class`
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/28820932/220490044-2ffb6c94-4189-46d0-9de7-7486aeba8aa3.png">

**Comment by tsantalis** [comment]
[Diff](https://users.encs.concordia.ca/~nikolaos/diffGallery/WebMvcAutoConfigurationTests.html)
