### ISSUE TITLE
Inaccurate Mappings + debatable multiMappings

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#374]
https://github.com/facebook/buck/commit/f26d234e8d3458f34454583c22e3bd5f4b2a5da8
File: [AdbHelper.java](https://github.com/facebook/buck/commit/f26d234e8d3458f34454583c22e3bd5f4b2a5da8#diff-8b1672ed0167e6b7a425fbf4a33be8fc18c01a3a79d830495e4835a41797de14)

Problem: Inaccurate mappings
- [x] Line range **269-271** parent `if (devices == null) {...}`-> Line range **272-274** child `if (devices == null) {...}`
- [x] Line  **270** parent `return false;`-> Line **273** child `return false;`
- [x] The last problem is caused due to the following mappings:
  - Line **261** child `devices = filterDevices(adb.getDevices());`  is mapped to Line **245** child `List<IDevice> devices = filterDevices(adb.getDevices());`
  - Line **261** child  is mapped to Line **271** child `devices = getDevices();`
This one should be discussed. 

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/28820932/220494502-13722958-d77f-44a3-a4a8-d474bc9607ba.png">

**Comment by tsantalis** [comment]
@pouryafard75 
I am fine with the multi-mapping of L261
Clearly the declaration of `devices` is duplicated between the original and the extracted method.

**Comment by tsantalis** [comment]
@pouryafard75 
`return false;` is properly matched now

Still we can improve the mapping of the other `return false;` **L257** with `return null;` **R241**

![Screenshot from 2023-04-08 18-17-10](https://user-images.githubusercontent.com/1483516/230744912-0adf8d6c-6cdd-4719-88bc-afe8431fb8fc.png)

**Comment by tsantalis** [comment]
Diff after the last fix:

![Screenshot from 2023-04-08 20-29-50](https://user-images.githubusercontent.com/1483516/230748147-f93af786-93df-4237-8fe1-8d9d9315d504.png)
