### ISSUE TITLE
1 of 2 Inline Operation Refactorings reported

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#375]
https://github.com/netty/netty/commit/303cb535239a6f07cbe24a033ef965e2f55758eb
File: [OpenSslEngine.java](https://github.com/netty/netty/commit/303cb535239a6f07cbe24a033ef965e2f55758eb#diff-0b07dfa3c28036ef062f7860b9e87a971bb82cac9f427fceac817d0fdc02af50)

Problem: **Inline Operation Refactoring only reported once while performed two times**
Inline Method	private principal(certs Certificate[]) : Principal inlined to public getLocalPrincipal() : Principal in class io.netty.handler.ssl.OpenSslEngine.OpenSslSession

It is reported once, but it must be reported two times.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28820932/220495979-94f6bef6-ad73-4760-9b49-381b6274689e.png">
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/28820932/220496322-aadb91ac-200f-4fc1-8637-75fd2373ca69.png">

**Comment by pouryafard75** [comment]
@tsantalis It can be closed

**Comment by tsantalis** [comment]
`getIssuerX500Prinicipal()` is replaced with `getSubjectX500Prinicipal()` in `getPeerPrinicipal()`
If we consider it as Inline Method, the functionality has changed.

On the other hand, the Inline Method that is reported is pure.

The second Inline Method refactoring is detected by RefDiff according to the oracle:
http://refactoring.encs.concordia.ca/oracle/commit-refactorings/1117922
