### ISSUE TITLE
SubExpression Mappings for the InlineVariableRefactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#376]
Similar to ExtractVariableRefactoring, the subExpression mappings are required for the Inline Variable Refactoring as well.
Two inline variable refactorings were performed here:
https://github.com/processing/processing/commit/8707194f003444a9fb8e00bffa2893ef0c2492c6
File: [PSurfaceJOGL.java](https://github.com/processing/processing/commit/8707194f003444a9fb8e00bffa2893ef0c2492c6#diff-c4bbc86e757b1654763ba06e0f617c553a1a456fa8d8ad603e634721624c33f5)
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28820932/220502455-7a622cdc-ad3e-4442-8283-42b33f4e5c02.png">

**Comment by tsantalis** [comment]
![Screenshot from 2023-03-02 16-26-06](https://user-images.githubusercontent.com/1483516/222557956-8345afe0-1c5d-40d3-a7e1-2c44f74a5612.png)
