### ISSUE TITLE
Inaccurate mappings for break statements

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#377]
https://github.com/osmandapp/Osmand/commit/c45b9e6615181b7d8f4d7b5b1cc141169081c02c
File: [RouteLayer.java](https://github.com/osmandapp/Osmand/commit/c45b9e6615181b7d8f4d7b5b1cc141169081c02c#diff-639f343a2565efee47c93b12b8b83d9bfbc271839810a3d7ad6cf0eaf0c897af)
Problem: Inaccurate mappings for `break` statements:
- [ ] Line **434** parent commit `break` -> Line ~452~ **462** child commit `break`
- [ ] Line **441** parent commit `break` -> Line ~462~ **452** child commit `break`

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28820932/220504611-df6d3d19-2065-46ff-b5e5-fa7e300c06d3.png">

**Comment by tsantalis** [comment]
![Screenshot from 2023-03-01 15-29-28](https://user-images.githubusercontent.com/1483516/222258218-3dff5b93-caac-4f98-8eb1-52bce6374867.png)

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-03-17 19-48-10](https://user-images.githubusercontent.com/1483516/226070729-f22cb8df-00c1-47cd-be3a-eb365de222f9.png)
