### ISSUE TITLE
Doesn't run on java 10

### ISSUE THREAD

**Issue by Arthurlpgc** [tsantalis/RefactoringMiner#38]
Gradlew won't build with java 10
Error:
` error: incompatible types: Enumeration<TreeNode> cannot be converted to Enumeration<DefaultMutableTreeNode>
        Enumeration<DefaultMutableTreeNode> enumeration = root.preorderEnumeration();`
looks similar to [this issue](https://github.com/chatty/chatty/issues/241)

**Comment by Arthurlpgc** [comment]
Follow up: the fix on their version works, will send a PR if you want to merge it (:

**Comment by tsantalis** [comment]
@Arthurlpgc Could you please try to build after this fix?
I don't have Java 10 installed to try it.
