### ISSUE TITLE
Project Strcuture: test files

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#382]
Currently, `src-test` has been added to both `main` and `test` sourceSets in the `build.gradle`.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/28820932/221975330-a47a9ce4-516e-45e0-b4d1-95807ccb0b43.png">
With this declaration, `src-test` will not be considered as the test source.
As a result, a couple of problems occur:

- First of all, the test data will be available inside the artifact. Here you can find two snapshots of the 2.3.2-SNAPSHOT.jar contents:
<img width="1428" alt="Screenshot 2023-02-28 at 3 50 47 PM" src="https://user-images.githubusercontent.com/28820932/221976538-cef3c614-9e52-4270-8b5d-c80adb4fd8d6.png">

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/28820932/221977595-de6bd28b-1f0d-4459-ae36-16c9757bfe24.png">

- Secondly, in order to use a library inside the test files, we must use the `implementation` keyword. As a result, the test library will be also included in the artifact which is not needed. By having the `src-test` as the test root, we can use `testImplementation` and introduce a couple of useful assertation libraries such as `AssertJ`.

**Comment by pouryafard75** [comment]
I have addressed and fix the issue in my latest PR https://github.com/tsantalis/RefactoringMiner/pull/383.

**Comment by tsantalis** [comment]
File sizes reduced
`refactoring-miner-2.3.2-SNAPSHOT.jar`                 1.1MB -> 975KB
`refactoring-miner-2.3.2-SNAPSHOT-javadoc.jar`  1.5MB -> 1.4MB
`refactoring-miner-2.3.2-SNAPSHOT-sources.jar`  3.4MB -> 458KB
