### ISSUE TITLE
Missing statement mappings (Statement using builder pattern separated to several statement)

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#384]
Commit: https://github.com/SonarSource/sonarqube/commit/0d9fcaa4415ee996e423a97cfe0d965586ca59a5
File: [Batch.java](https://github.com/SonarSource/sonarqube/commit/0d9fcaa4415ee996e423a97cfe0d965586ca59a5#diff-c12d919cbb75911ec586889ce4f1305d33aae9810727a233306de7eb285e650d)

Method: `public execute() : Batch -> public execute() : Batch`

- Parent line **71** `start().executeTask(bootstrapProperties).stop();` -> Child version line **71** `start();`
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/28820932/222032809-f351394d-b18f-450a-90f6-afa79edd6a42.png">

**Comment by pouryafard75** [comment]
@tsantalis 
There is no CompositeReplacement for this one

<img width="1047" alt="Screenshot 2023-03-16 at 6 07 01 PM" src="https://user-images.githubusercontent.com/28820932/225763403-495de3b3-bc3c-4eb5-9fd7-42465602f8de.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-04-04 20-37-51](https://user-images.githubusercontent.com/1483516/229954281-d064c099-af78-4a97-91ad-8e7d8a1896c1.png)
