### ISSUE TITLE
Incorrect Argument Mapping reported

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#385]
Commit: https://github.com/SonarSource/sonarqube/commit/0d9fcaa4415ee996e423a97cfe0d965586ca59a5
File: [Batch.java](https://github.com/SonarSource/sonarqube/commit/0d9fcaa4415ee996e423a97cfe0d965586ca59a5#diff-c12d919cbb75911ec586889ce4f1305d33aae9810727a233306de7eb285e650d)

Extract Method:	`private doStop(swallowException boolean) : void extracted from public stop() : void in class org.sonar.batch.bootstrapper.Batch`

Reported ArgumentMappings:
`false` -> `false`
However, this mapping is not correct
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/28820932/222034953-3ac031ba-6251-4fbf-a324-b704efd2c66d.png">

**Comment by pouryafard75** [comment]
This also happens in https://github.com/nutzam/nutz/commit/de7efe40dad0f4bb900c4fffa80ed377745532b3.
File: [Daos.java](https://github.com/nutzam/nutz/commit/de7efe40dad0f4bb900c4fffa80ed377745532b3#diff-a2180a86079d6a5635c8280b4206aa0483a548c5597a1bbcc43a752d91f4e32d)

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28820932/222065106-17269bd4-7d6d-47eb-b987-a880180877ff.png">

**Comment by pouryafard75** [comment]
The same issue happened here: https://github.com/thymeleaf/thymeleaf/commit/aed371dac5e1248880e869930c636994c3d0f8dc
File: [ThymeleafMarkupTemplateReader.java](https://github.com/thymeleaf/thymeleaf/commit/aed371dac5e1248880e869930c636994c3d0f8dc#diff-a9209028a831c46bac606306c22696bac34b388fb0e95c8845413ab544794ad7)

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/28820932/222078155-335784f9-fdeb-4004-b366-a76312591d9c.png">
<img width="708" alt="image" src="https://user-images.githubusercontent.com/28820932/222078272-cdbd90d6-705a-4021-876f-34549a6f7e52.png">

**Comment by tsantalis** [comment]
The old cases still match correctly after the fix:

![Screenshot from 2023-03-02 06-47-16](https://user-images.githubusercontent.com/1483516/222420422-4c050135-26b1-48a4-9a5d-9cadbab1838b.png)
![Screenshot from 2023-03-02 06-48-29](https://user-images.githubusercontent.com/1483516/222420440-0eb1aeac-0ba3-4dcd-9431-426827d4d377.png)

The new cases are fixed as follows:

![Screenshot from 2023-03-02 06-50-51](https://user-images.githubusercontent.com/1483516/222420900-f793c6f5-6547-4fcc-999b-f2e12ea3b543.png)
![Screenshot from 2023-03-02 06-53-22](https://user-images.githubusercontent.com/1483516/222421388-047c68ca-3760-4330-b08f-5cdc12c31190.png)
![Screenshot from 2023-03-02 06-59-18](https://user-images.githubusercontent.com/1483516/222422716-1992ad00-a53a-4280-8abf-b9382b21cda7.png)

**Comment by tsantalis** [comment]
Tested for Inline Method too:

![Screenshot from 2023-03-02 09-26-46](https://user-images.githubusercontent.com/1483516/222474790-08fc301a-e039-469f-86fa-f3321490a137.png)
