### ISSUE TITLE
Inaccurate Mappings for Blocks within an Extract Method Refactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#386]
Commit: https://github.com/fabric8io/fabric8/commit/e068eb7f484f24dee285d29b8a910d9019592020
File: [JsonMojo.java](https://github.com/fabric8io/fabric8/commit/e068eb7f484f24dee285d29b8a910d9019592020#diff-42797294f9ff44f04620e9d61c1854325203a9880cdf363030d91483479230ff)

Reported Mapping:
-  Parent version  Line range **912-922** `{ }` -> Child version  Line range **917-920** `{ }`
However The correct mapping is Line range **912-922** `{ }` -> Child version `{ }` Line range **940-948**
Both blocks belong to identical if statements
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28820932/222036220-73e64b01-ee3f-4677-a300-4eb8b507002b.png">

**Comment by tsantalis** [comment]
@pouryafard75 

This is no longer happening, but we can improve the mapping of `HTTPGetAction action = null;`

![Screenshot from 2023-03-09 09-18-06](https://user-images.githubusercontent.com/1483516/224052646-b9f4d1e9-5e38-42f0-ab71-219a88d9906d.png)

**Comment by tsantalis** [comment]
@pouryafard75 

Final optimal diff after supporting Variable declaration Split to Variable declaration (with default value) + Assignment with initializer

![Screenshot from 2023-03-09 13-55-51](https://user-images.githubusercontent.com/1483516/224126792-3159e8a0-cebf-421d-95b1-14d98b933d2e.png)
