### ISSUE TITLE
Four Incorrect Rename Parameters Refactoring for the case of Extract Method Refactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#387]
Commit: https://github.com/FasterXML/jackson-databind/commit/cfe88fe3fbcc6b02ca55cee7b1f4ab13e249edea
File: [TypeFactory.java](https://github.com/FasterXML/jackson-databind/commit/cfe88fe3fbcc6b02ca55cee7b1f4ab13e249edea#diff-d533fdf77cd40a01e6a613580c7a3351b6428109a2b64384d8ad9ea756ce2842)

Two correct ExtractMethod Refactoring reported:
- Extract Method	`protected classForName(name String, initialize boolean, loader ClassLoader) : Class<?> extracted from public findClass(className String) : Class<?> in class com.fasterxml.jackson.databind.type.TypeFactory`
- Extract Method	`protected classForName(name String) : Class<?> extracted from public findClass(className String) : Class<?> in class com.fasterxml.jackson.databind.type.TypeFactory`

**But** in addition to those, 4 Rename Parameters Refactoring also reported.
The parameters of the newly introduced method are mapped with the original method parameters.
Also, two more Rename Parameters Refactoring reported but the original variable which supposed to be the parent version, shows the child version.

Incorrect Refactorings:

- Rename Parameter	`className : String to name : String in method protected classForName(name String, initialize boolean, loader ClassLoader) : Class<?> from class com.fasterxml.jackson.databind.type.TypeFactory`

- Rename Parameter	`className : String to name : String in method protected classForName(name String, initialize boolean, loader ClassLoader) : Class<?> from class com.fasterxml.jackson.databind.type.TypeFactory`
  - Identical to the previous one but the original variable is referring to the variable in the child version.

- Rename Parameter	`className : String to name : String in method protected classForName(name String) : Class<?> from class com.fasterxml.jackson.databind.type.TypeFactory`

- Rename Parameter	`className : String to name : String in method protected classForName(name String) : Class<?> from class com.fasterxml.jackson.databind.type.TypeFactory`
  - Identical to the previous one but the original variable is referring to the variable in the child version.
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/28820932/222041116-740c9fb9-13c0-4772-8094-1183a8ab59ca.png">

As a result, the diff is showing multi mapping for the parameters.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28820932/222041059-a590fcaf-6e55-4f9b-ac08-8299c0126fa7.png">

**Comment by pouryafard75** [comment]
The same issue happened here: https://github.com/thymeleaf/thymeleaf/commit/aed371dac5e1248880e869930c636994c3d0f8dc

[src/main/java/org/thymeleaf/templateparser/markup/ThymeleafMarkupTemplateReader.java](https://github.com/thymeleaf/thymeleaf/commit/aed371dac5e1248880e869930c636994c3d0f8dc#diff-a9209028a831c46bac606306c22696bac34b388fb0e95c8845413ab544794ad7)

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/28820932/222077357-398f2c72-a1d7-4ec6-9770-9070a07b23dc.png">


<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28820932/222077104-afb2a00c-8d13-4e5e-ba4f-6d3392f16ad3.png">


<img width="1407" alt="image" src="https://user-images.githubusercontent.com/28820932/222077014-c9b59c2a-d56f-4609-a0ba-0d5bd71f072c.png">

**Comment by tsantalis** [comment]
@pouryafard75 
The fix removes the referring to the variable in the child version.
The Rename parameter refactoring will remain.
You can filter-out on your side (if `renameParameter.operationAfter` == `extractMethod.extractedOperation`).
