### ISSUE TITLE
Incorrect Statement mapping reported 

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#388]
Commit: https://github.com/abarisain/dmix/commit/885771d57c97bd2dd48951e8aeaaa87ceb87532b
File: [WidgetHelperService.java](https://github.com/abarisain/dmix/commit/885771d57c97bd2dd48951e8aeaaa87ceb87532b#diff-85673775aed77ae91efe521e0dcb504c63a75bf1d2a306ada342c51ea0c6658c)

Incorrect mappings reported:
- Parent version Line **48** `mApp.addConnectionLock(this);` -> Parent version Line **65** `mApp.removeConnectionLock(token);`
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/28820932/222043352-9cb33418-10ac-4da7-ab51-2eea4fed7262.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-04-09 16-20-57](https://user-images.githubusercontent.com/1483516/230795219-a2de9ce7-0535-43c5-ab2e-4524e3496342.png)

**Comment by pouryafard75** [comment]
@tsantalis Should we improve the mapping for the `.getStatus` method invocation? If you believe it's unnecessary, I will add it to the benchmark.

**Comment by tsantalis** [comment]
@pouryafard75 
The mapping for `.getStatus()` looks fine to me.
There is a kind of Extract Variable `status` + Merge with previous variable declaration `mpd`
