### ISSUE TITLE
Inaccurate mappings in case of having identical statements within different if statements

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#389]
Commit: https://github.com/nutzam/nutz/commit/de7efe40dad0f4bb900c4fffa80ed377745532b3
File: src/org/nutz/dao/util/Daos.java

Reported Mapping:
- Parent version Line **577** `sql.vars().set("table", en.getTableName());` ->  Child version Line **735** `sql.vars().set("table", en.getTableName());`
However, the identical statement exists in the if statement `if(de) {...}` in both versions.
Thus, the correct mapping is
Parent version Line **587** `sql.vars().set("table", en.getTableName());` ->  Child version Line **735** `sql.vars().set("table", en.getTableName());`

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/28820932/222066827-bccf43f4-68fb-4971-a1fd-f39733209099.png">

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/28820932/222066330-33bb1db5-006e-4470-8ac8-97443254b766.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-04-10 05-51-14](https://user-images.githubusercontent.com/1483516/230878964-26f6b875-f95e-40f4-979b-5c71c5282bd2.png)
