### ISSUE TITLE
Incorrect statement mapping for the case of Variable Declaration with different initializer

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#390]
Commit: https://github.com/JetBrains/intellij-community/commit/e1625136ba12907696ef4c6e922ce073293f3a2c
File: [MavenProject.java](https://github.com/JetBrains/intellij-community/commit/e1625136ba12907696ef4c6e922ce073293f3a2c#diff-8334049f0b43b102cf1204f26e5c62e8e886f5e341d066990f46c9867b0e46de)

Reported mapping: 
- Parent version line **488** `res = new LinkedHashMap<String, String>();` -> Child version line **457** `Map<String, String> res = new LinkedHashMap<String, String>();`
However, the correct mapping seems to be:
Parent version line **457** `Map<String, String> res = null;` -> Child version line **457** `Map<String, String> res = new LinkedHashMap<String, String>();`

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/28820932/222072070-9963f74a-4872-4977-8295-c43fffacd725.png">

**Comment by tsantalis** [comment]
@pouryafard75 
I think the right diff is to have a multi-mapping
L488 + L469 -> R457

The initializer is moved to the declaration
