### ISSUE TITLE
Parameter to Argument Mapping not reported

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#392]
Commit: https://github.com/wordpress-mobile/WordPress-Android/commit/f8d5cf01f123a1d0a65857aa2db0571fe9cd1911
File: [Blog.java](https://github.com/wordpress-mobile/WordPress-Android/commit/f8d5cf01f123a1d0a65857aa2db0571fe9cd1911#diff-b95b612f972466fcc6f236bd930d07373df498d62e5ed3ba0d59589952839956)

After fa0c8f26, one of the argument mappings is not getting reported. The missed mapping is highlighted in the following image. As a result, the corresponding test is not getting passed. If this diff is more desirable, the test cases must be updated. But if this was not intentional, the argument mappings need to be updated.

(I checked out the commit before the aforementioned one, to capture this image. The highlighted one **doesn't** exist at the moment)
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/28820932/222625934-bcd5d80b-e0ed-4ab5-aea2-c27a4e19d1e6.png">

 Before the commit:
<img width="1123" alt="Screenshot 2023-03-02 at 10 47 41 PM" src="https://user-images.githubusercontent.com/28820932/222626643-d2abb13a-3c8c-42b1-8114-2b58e5a23888.png">

After the commit:
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/28820932/222626776-8d1c304c-af8a-4490-a485-397843cae267.png">

**Comment by tsantalis** [comment]
@pouryafard75 
I fixed the issue, but now we get additional argument mappings with `iconURL`, which are correct

Can you please update the test, so that we can go for a release?

![Screenshot from 2023-03-03 03-48-39](https://user-images.githubusercontent.com/1483516/222675349-2f671787-4fd9-4694-99d0-f1108930a82d.png)
