### ISSUE TITLE
 Variable Declaration Split to Declaration + Assignment statement

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#397]
https://github.com/FasterXML/jackson-databind/commit/cfe88fe3fbcc6b02ca55cee7b1f4ab13e249edea
File: [TestTypeFactoryWithClassLoader.java](https://github.com/FasterXML/jackson-databind/commit/cfe88fe3fbcc6b02ca55cee7b1f4ab13e249edea#diff-452336e3aaf8da5168dff67483d368e786da44bb77d9f737879172091582a2d4)

- [ ] Variable Declaration Split to Declaration + Assignment statement. `ClassLoader loader`
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28820932/224398504-d5bfc7f3-d5bf-46e7-8518-8dfe83a33f1b.png">

- [ ] Please confirm that the `return` statements are mapped correctly.  Both statements inside the original method in the child version are reported as non-mapped. In my opinion, there is no problem regarding those.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/28820932/224399803-c20b032b-6656-4358-a470-5ccd1e76a48a.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-03-11 08-37-27](https://user-images.githubusercontent.com/1483516/224511134-1c33cb5b-9bbe-4a55-9f06-77343ee28e56.png)

**Comment by pouryafard75** [comment]
@tsantalis Fixed

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28820932/225513542-91c68580-62b3-4c63-aa43-1d2d53b98103.png">

**Comment by pedramnoori** [comment]
@tsantalis 

I found the problem. The mapping is perfectly reported but the problem is that the above mentioned statement also reported as a non-mapped leave.

**Comment by tsantalis** [comment]
@pedramnoori 
It is a bit challenging to remove it from the non-mapped leaves, because it is not possible to remove elements from a list, while you perform an iteration over the elements of the list.

**Comment by tsantalis** [comment]
@pedramnoori 
The issue if fixed with the commit above.
