### ISSUE TITLE
Multi-mapping while having anonymous class inside

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#398]
https://github.com/JetBrains/intellij-community/commit/e1f0dbc2f09541fc64ce88ee22d8f8f4648004fe

Seems like the correct mapping must be:
- `result.set(new NewLibraryConfiguration(coord, RepositoryLibraryType.getInstance(), new RepositoryLibraryProperties(coord)) {
              @Override
              public void addRoots(@NotNull LibraryEditor editor) {
                editor.addRoots(roots);
              }
            });
`
-->
`return new NewLibraryConfiguration(coord, RepositoryLibraryType.getInstance(), new RepositoryLibraryProperties(coord)) {
      @Override
      public void addRoots(@NotNull LibraryEditor editor) {
        editor.addRoots(roots);
      }
    };
`

And 
- `result.set(new NewLibraryConfiguration(coord, RepositoryLibraryType.getInstance(), new RepositoryLibraryProperties(coord)) {
              @Override
              public void addRoots(@NotNull LibraryEditor editor) {
                editor.addRoots(roots);
              }
            });
`
-->
`result.set(roots);`
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28820932/224403586-e40789c7-b96a-4126-95eb-8035632dae4f.png">

**Comment by tsantalis** [comment]
The statement we are looking for is nested within another anonymous

```java
resolveLibrary(project, coord, extraTypes, repositories, new Processor<List<MavenArtifact>>() {
      public boolean process(final List<MavenArtifact> artifacts) {
        if (!artifacts.isEmpty()) {
          AccessToken accessToken = WriteAction.start();
          try {
            final List<OrderRoot> roots = createRoots(artifacts, copyTo);
            result.set(new NewLibraryConfiguration(coord, RepositoryLibraryType.getInstance(), new RepositoryLibraryProperties(coord)) {
              @Override
              public void addRoots(@NotNull LibraryEditor editor) {
                editor.addRoots(roots);
              }
            });
          }
          finally {
            accessToken.finish();
          }
          notifyArtifactsDownloaded(project, artifacts);
        }
        return true;
      }
});
```

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-03-11 06-56-15](https://user-images.githubusercontent.com/1483516/224483185-72541b7b-771b-4899-b517-7cd1bc93a94b.png)
