### ISSUE TITLE
System.out.println replaced with Formatter.format

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#401]
https://github.com/phishman3579/java-algorithms-implementation/commit/f2385a56e6aa040ea4ff18a23ce5b63a4eeacf29#diff-c05682e2df89f5bb4f016f35a2b9a0d53853b2eeb1c5074efd84596313ce0526R640
The developer decided to use `Formatter.format` instead of `System.out.println`.
As a result, these statements are not getting mapped and the existing statements related to`System.out.println` are inaccurately mappaed.
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28820932/224520395-3a85d26a-09ef-4bc1-8f04-2d8c62840fb7.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-03-20 06-45-04](https://user-images.githubusercontent.com/1483516/226318588-b8567525-3d74-451c-9b35-192dce69bc5a.png)
