### ISSUE TITLE
Methods with empty body inside anonymous class + Duplicated Statements

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#402]
https://github.com/languagetool-org/languagetool/commit/01cddc5afb590b4d36cb784637a8ea8aa31d3561

- [x] Overridden methods with empty bodies are not getting matched properly.
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28820932/224520601-a51f0683-66dd-4fbd-9f4c-3937a0bc665c.png">

- [x] Duplicated statements are getting mapped incorrectly:
- Line **334** parent `cons = new GridBagConstraints();` -> Line ~~182~~ **163** child `cons = new GridBagConstraints();`
- Line **336** parent `cons.gridx = 0;` -> Line ~~280~~ **165** child `cons.gridx = 0;`
- Line **337** parent `cons.gridy = 0;` -> Line ~~405~~ **166** child `cons.gridy= 0;`
- Line **273** parent `cons.gridx = 0;` -> Line ~~165~~ **404** child `cons.gridx = 0;`
- Line **274** parent `cons.gridy = 0;` -> Line ~~166~~ **405** child `cons.gridy= 0;`
There are also other inaccuracies related to duplicated statements but I assume they will be fixed after resolving the mentioned ones.

**Comment by tsantalis** [comment]
![Screenshot from 2023-03-13 10-37-19](https://user-images.githubusercontent.com/1483516/224733946-b91d5661-6f1c-4853-8ea2-d5da57cf42ff.png)
