### ISSUE TITLE
Extract constructor refactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#404]
Commit: https://github.com/FasterXML/jackson-databind/commit/cfe88fe3fbcc6b02ca55cee7b1f4ab13e249edea
File: [TypeFactory.java](https://github.com/FasterXML/jackson-databind/commit/cfe88fe3fbcc6b02ca55cee7b1f4ab13e249edea#diff-d533fdf77cd40a01e6a613580c7a3351b6428109a2b64384d8ad9ea756ce2842)
**Problem:** A new constructor has been introduced and the previous one now contains the invocation to the newly introduced one, while the statements in the original one have been moved to the new constructor.

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/28820932/225514578-46ec28b6-16ee-460a-a2d2-64af7caedce3.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-03-21 22-16-41](https://user-images.githubusercontent.com/1483516/226784697-195a9d2c-9d86-4fc7-882f-e7db5224a917.png)
