### ISSUE TITLE
Missing Statement mappings within extract method

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#405]
Commit: https://github.com/google/auto/commit/8fc60d81fe0e46e7e5c96e71d4a93fcadc6bde4f
File: [BasicAnnotationProcessor.java](https://github.com/google/auto/commit/8fc60d81fe0e46e7e5c96e71d4a93fcadc6bde4f#diff-2167c24df95e48cbafc17aecb37391dc766ac4f0f521eac28527c66d507dba23)
As can be seen in the image, the following statement mapping is missing

- Line **146** parent ` ImmutableMap<String, Optional<? extends Element>> deferredElements =
        deferredElementsBuilder.build(); ` -> Line **135** child `ImmutableMap<String, Optional<? extends Element>> deferredElements = deferredElements();`

Although this is the invocation of the extracted method but looks reasonable to map the statement in my opinion.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28820932/225515864-ed4b561a-86a3-40af-b2d7-e2a2c0f25576.png">

Worth mentioning, after this fix, the diff is not going to be perfect out of the box, however, this fix is required to proceed.

**Comment by pouryafard75** [comment]
Another example of this problem can be seen here:
https://github.com/structr/structr/commit/6c59050b8b03adf6d8043f3fb7add0496f447edf#diff-63e49f3df333e92d1637eccbc53e6356a3feb3a8e05d09ffae2e16f5b2f9cfd3R226

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28820932/225760057-1b7e7d7c-614d-4a01-a9ff-ce9e6d89f211.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28820932/225760080-b8e77a1a-84ac-4b5d-9883-986cafc56994.png">

**Comment by tsantalis** [comment]
@pouryafard75 

The first case is working fine
![Screenshot from 2023-04-05 09-20-01](https://user-images.githubusercontent.com/1483516/230092928-6fa6c6ea-d83b-4106-b4d2-0a119c2a3f0a.png)

**Comment by tsantalis** [comment]
After the fix for case https://github.com/structr/structr/commit/6c59050b8b03adf6d8043f3fb7add0496f447edf#diff-63e49f3df333e92d1637eccbc53e6356a3feb3a8e05d09ffae2e16f5b2f9cfd3R226

![Screenshot from 2023-04-05 09-50-21](https://user-images.githubusercontent.com/1483516/230100924-058f1fdb-471b-40ac-bfd3-f321ba9dd4c6.png)
