### ISSUE TITLE
Incorrect statement mappings + Missed statement mappings which contains the invocation to renamed method

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#411]
https://github.com/pockethub/PocketHub/commit/a7401e5091c06c68fae499ea1972b40143c66fa9

- [x] Statement (inside the extracted method) containing renamed method invocation not mapped:
`endAccess(token.access_token, token.scope);` -> `endAuth(token.access_token, token.scope);`
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28820932/225771507-408bc3bc-939c-4a48-9ac7-36c3d438ed62.png">

The method has been renamed which is detected correctly: 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28820932/225771411-3396af63-aeee-4241-97b2-17e634113bfb.png">

- [ ] Two unnecessary mappings reported:
- `final Intent newIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(url.build().toString()));` -> `Intent intent = new Intent(this, LoginWebViewActivity.class);` 
- `chooser.putExtra(Intent.EXTRA_INITIAL_INTENTS, extraIntents);` -> `intent.putExtra(INTENT_EXTRA_URL, url.toString());`
None of these mappings looks correct (in my opinion)

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28820932/225771791-c7edb5c2-8371-4252-9d36-93cbffdfc9c2.png">

**Comment by tsantalis** [comment]
@pouryafard75 
![Screenshot from 2023-03-23 12-50-57](https://user-images.githubusercontent.com/1483516/227279603-73a0e13f-1646-4a8d-9981-3b53c2c6393b.png)
