### ISSUE TITLE
Incorrect anonymousClassDiffs

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#417]
https://github.com/wicketstuff/core/commit/8ea46f48063c38473c12ca7c114106ca910b6e74
File: [FoundationTabTest.java](https://github.com/wicketstuff/core/commit/8ea46f48063c38473c12ca7c114106ca910b6e74#diff-8a97677317be826cbdde9841b5801c2b01b8c518bb89f3587e0b93b285ed4479)

**Problem:** 6 items were reported in anonymousClassDiffs, however, 3 items are expected.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/28820932/227079235-500bbd99-5571-4e46-bdc4-abba0685733a.png">
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/28820932/227079306-ef2b43cf-9d2b-4c66-8a98-c835c6f314ab.png">

**Comment by tsantalis** [comment]
@pouryafard75 
![Screenshot from 2023-03-23 14-17-08](https://user-images.githubusercontent.com/1483516/227316941-29afaff4-b6e7-47a3-90cc-676d166b1347.png)
