### ISSUE TITLE
Inaccurate Extract Attribute Refactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#418]
Commit: https://github.com/pouryafard75/TestCases/commit/be5ea951b76ac9c4caed2d72bce118174a454670

This is a replication of https://github.com/infinispan/infinispan/commit/8f446b6ddf540e1b1fefca34dd10f45ba7256095 and the file is:
server/integration/jgroups/src/main/java/org/jboss/as/clustering/jgroups/subsystem/RemoteSiteResourceDefinition.java -> server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/RemoteSiteResourceDefinition.java

**Problem**: The extract attribute refactoring does not seem to be correct.
Reported refactoring: `Extract Attribute WILDCARD_PATH : PathElement in class org.infinispan.server.jgroups.subsystem.RemoteSiteResourceDefinition`

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/28820932/227084564-9d13e9dc-0591-4470-87ac-1ea9735f737a.png">

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28820932/227084875-2409907e-384b-4f98-a742-391e2cd41a6c.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28820932/227084894-a4b0a860-7fd8-4287-b380-791c146cabeb.png">

**Comment by tsantalis** [comment]
@pouryafard75 

The super constructor call before was
`super(PathElement.pathElement(ModelKeys.REMOTE_SITE)` ...

This code exists now into newly added method `pathElement(String name)` and has an additional argument `name`

```java
static PathElement pathElement(String name) {
    return PathElement.pathElement(ModelKeys.REMOTE_SITE, name);
}
```

The extracted field `WILDCARD_PATH` is initialized by calling the newly added method `pathElement(String name)` and passing `PathElement.WILDCARD_VALUE` as the `name` argument.

If you inline the `pathElement(String name)` call the initialization of `WILDCARD_PATH` becomes

`PathElement.pathElement(ModelKeys.REMOTE_SITE, PathElement.WILDCARD_VALUE)`
which is very close to
the first argument of the super constructor call
`PathElement.pathElement(ModelKeys.REMOTE_SITE)`
with the only difference of an additional argument.
