### ISSUE TITLE
Improvement for Argument mappings

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#419]
https://github.com/facebook/buck/commit/a1525ac9a0bb8f727167a8be94c81a3415128ef4
File: [DebugPathSanitizer.java](https://github.com/facebook/buck/commit/a1525ac9a0bb8f727167a8be94c81a3415128ef4#diff-b48f96c1d353605e83e8e52233d102d44bf6e73b3c696b22d04db8302b8ac35a)

**Problem**: `workingDir.get()` was passed as the argument in Line **107** child version ` return getAllPathsWork(workingDir.get());`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28820932/225783891-866a1a49-f185-44c6-9f5d-7a4795c753b0.png">

<img width="1106" alt="Screenshot 2023-03-22 at 10 40 15 PM" src="https://user-images.githubusercontent.com/28820932/227086270-005bd0da-1ded-46df-837d-d7164d2bde2e.png">

**Comment by tsantalis** [comment]
@pouryafard75 

Please re-run all tests you have involving argument mappings.

![Screenshot from 2023-03-23 15-15-59](https://user-images.githubusercontent.com/1483516/227324332-497a5611-b606-4ebb-8944-b711ca24a136.png)
