### ISSUE TITLE
Duplicate refactoring reports

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/RefactoringMiner#42]
Duplicate refactoring `Move Attribute private digest : MessageDigest from class org.bitcoinj.core.Utils to class org.bitcoinj.core.Sha256Hash`
is reported 3 times in commit
https://github.com/bitcoinj/bitcoinj/commit/a6601066ddc72ef8e71c46c5a51e1252ea0a1af5

Issue reported by
Flávia Coelho
Doctoral Student in Computer Science
Software Productivity Lab (SPLAB)
Federal University of Campina Grande

**Comment by klerisson** [comment]
I'm running RMiner against https://github.com/danilofes/refactoring-toy-example with the last improvements to detect Move Attribute refactorings. But apparently I'm still getting duplicates: 

2018-11-07 10:51:56 INFO  Checking out tmp/refactoring-toy-example 9a5c33b16d07d62651ea80552e8782974c96bb8a ...
Refactorings at 9a5c33b16d07d62651ea80552e8782974c96bb8a
Move Attribute	public magicNumber : int from class org.DogManager to class org.animals.Dog
Move Attribute	public magicNumber : int from class org.DogManager to class org.animals.Dog
Move Attribute	public magicNumber : int from class org.DogManager to class org.animals.Dog

Is it the same problem?

**Comment by klerisson** [comment]
My bad. Merge problems from my side. It's working!
