### ISSUE TITLE
Inaccurate Argument Mappings for boolean literal (false) in ExtractMethodRefactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#420]
https://github.com/VoltDB/voltdb/commit/669e0722324965e3c99f29685517ac24d4ff2848
File: [AdHocPlannerWork.java](https://github.com/VoltDB/voltdb/commit/669e0722324965e3c99f29685517ac24d4ff2848#diff-5aaee1666d033ddf6f0116221430df2cb6c6c0ced92c6c19e7e8078ff7df5a8c)

**Problem:** `false` was passed to the newly extracted method as `isAdmin` argument, however, in addition to the correct argument mappings, all the `false` literals in the method are mapped to the argument. All of these occurrences are in the same statement, this might be the reason behind this inaccuracy.
**Refactoring:** `Extract Method	public makeStoredProcAdHocPlannerWork(replySiteId long, sql String, userParams Object[], singlePartition boolean, context CatalogContext, completionHandler AsyncCompilerWorkCompletionHandler, isAdmin boolean) : AdHocPlannerWork extracted from public makeStoredProcAdHocPlannerWork(replySiteId long, sql String, userParams Object[], singlePartition boolean, context CatalogContext, completionHandler AsyncCompilerWorkCompletionHandler) : AdHocPlannerWork in class org.voltdb.compiler.AdHocPlannerWork`

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/28820932/227087772-efc8a372-e62e-44e2-8593-009dc540dc8d.png">

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/28820932/227087897-3fe74925-e710-419f-a9fe-82411d03ade0.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-03-26 13-48-00](https://user-images.githubusercontent.com/1483516/227794353-19f87eae-cfe9-4dcd-91b8-29c0919473de.png)
