### ISSUE TITLE
Inaccurate Argument Mappings for integer literal (1) in ExtractMethodRefactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#422]
This issue is similar to issue #420.

https://github.com/apache/cassandra/commit/9a3fa887cfa03c082f249d1d4003d87c14ba5d24
File: [BootStrapperTest.java](https://github.com/apache/cassandra/commit/9a3fa887cfa03c082f249d1d4003d87c14ba5d24#diff-f5b9166806ca2abc3a27cec8176c76da78eab8701c8d17966df960b4700074f2)

**Problem**: Integer literal `1` is passed as the argument `numVNodes` but no argument mapping is expected to be reported for this case. 
**Refactoring**: `Extract Method private generateFakeEndpoints(tmd TokenMetadata, numOldNodes int, numVNodes int) : void extracted from private generateFakeEndpoints(numOldNodes int) : void in class org.apache.cassandra.dht.BootStrapperTest`

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28820932/227131252-76c246f0-840b-4d14-b9ac-73c065306509.png">
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/28820932/227132017-582b2cb4-5f84-44be-8ae9-1a5597bd222b.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-03-26 14-53-32](https://user-images.githubusercontent.com/1483516/227797658-069f9132-54c7-44ee-8170-c2fe0f164544.png)
