### ISSUE TITLE
Variable Replaced with the attribute and initializer moved to the Method with @Before annotation in Test code

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#424]
https://github.com/facebook/buck/commit/7e104c3ed4b80ec8e9b72356396f879d1067cc40
File: [ResolverIntegrationTest.java](https://github.com/facebook/buck/commit/7e104c3ed4b80ec8e9b72356396f879d1067cc40#diff-8bb9e7418e883de1b671cf16b6dec4be46036b08d2596d2e7108ba622938335f)
**Problem**: Intializer moved to the method with the `@Before` annotation

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/28820932/227142314-577218a9-a3de-4350-b7da-a922f935513b.png">

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28820932/227143352-97e35e79-d61d-4ed8-8157-bec0c5708ffc.png">

@victorgveloso This might be interesting for you also.

**Comment by victorgveloso** [comment]
That's an interesting case of extracting test setup, especially because the developer moved some duplicated code to an existing setup method.

**Comment by tsantalis** [comment]
@pouryafard75 @victorgveloso 

We support a new refactoring named `Move Code` for code that is moved between existing methods.
Currently, we handle only statement moves to `setUp` and `tearDown` methods.

I guess the opposite scenario is also possible, statement moves from `setUp` and `tearDown` methods to `Test` methods.

![Screenshot from 2023-03-25 23-00-29](https://user-images.githubusercontent.com/1483516/227752877-94405562-5402-405f-965e-0e44ba72869d.png)

**Comment by pouryafard75** [comment]
@tsantalis Interesting! I checked the Refactoring Oracle. Seems like we do not have other instances of this refactoring and all four reported `Move Code` refactorings have occurred in this exact commit.

**Comment by tsantalis** [comment]
@pouryafard75 
As I said, the current implementation is focused only on moves to `setUp` and `tearDown` methods.
In the future, we can extend it to support move code scenarios in production code.
If you have some commits with code move between previously existing production methods, please make an issue.
