### ISSUE TITLE
Error with invoking "gr.uom.java.xmi.UMLType.getClassType()"

### ISSUE THREAD

**Issue by kavehshahedi** [tsantalis/RefactoringMiner#431]
During the analysis of [panda-lang/panda](https://github.com/panda-lang/panda), the mentioned commits will throw an exception:
https://github.com/panda-lang/panda/commit/dee3009ba59b8ff5bf3468386a16efee38a949a7
https://github.com/panda-lang/panda/commit/91e53c60d62e34c57a49bcb03b93472e8e3cc746

Stack trace for **dee3009ba59b8ff5bf3468386a16efee38a949a7**:
```
java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.UMLType.getClassType()" because the return value of "gr.uom.java.xmi.decomposition.VariableDeclaration.getType()" is null
	at gr.uom.java.xmi.decomposition.OperationInvocation.matchesOperation(OperationInvocation.java:320)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForExtractedAndMovedOperations(UMLModelDiff.java:2786)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:2213)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:159)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:684)
```

Stack trace for **91e53c60d62e34c57a49bcb03b93472e8e3cc746**:
```
java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.UMLType.getClassType()" because the return value of "gr.uom.java.xmi.decomposition.VariableDeclaration.getType()" is null
	at gr.uom.java.xmi.decomposition.OperationInvocation.matchesOperation(OperationInvocation.java:320)
	at gr.uom.java.xmi.diff.InlineOperationDetection.matchingInvocations(InlineOperationDetection.java:175)
	at gr.uom.java.xmi.diff.InlineOperationDetection.getRemovedOperationsSortedByCalls(InlineOperationDetection.java:41)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForInlinedOperations(UMLClassBaseDiff.java:1699)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:102)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:158)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:684)
```

**Comment by tsantalis** [comment]
@kavehshahedi 

https://github.com/panda-lang/panda/commit/dee3009ba59b8ff5bf3468386a16efee38a949a7

>   Add Method Annotation @SuppressWarnings("unchecked") in method public generate(requestedType Class, strategy GenerationStrategy) : Object from class org.panda_lang.panda.utilities.autodata.defaults.virtual.InMemoryDataHandler
>   Rename Variable foundUser : Optional<User> to foundByUser : Optional<User> in method public test() : void from class org.panda_lang.panda.utilities.autodata.AutomatedDataSpaceTest
>   Rename Parameter values : Object[] to constructorArguments : Object[] in method public create(constructorArguments Object[]) : ENTITY from class org.panda_lang.panda.utilities.autodata.data.repository.DataHandler
>   Change Return Type Class<?> to Class<TYPE> in method public getExpectedReturnType() : Class<TYPE> from class org.panda_lang.panda.utilities.autodata.data.query.DataQuery
>   Change Return Type Map<String,EntitySchemeProperty> to Map<String,EntityProperty> in method public getProperties() : Map<String,EntityProperty> from class org.panda_lang.panda.utilities.autodata.data.entity.EntityScheme
>   Change Variable Type property : EntitySchemeProperty to property : EntityProperty in method protected load(method Method) : EntityMethodScheme from class org.panda_lang.panda.utilities.autodata.data.entity.EntityMethodSchemeLoader
>   Change Parameter Type properties : Map<String,EntitySchemeProperty> to properties : Map<String,EntityProperty> in method package EntityScheme(rootClass Class<?>, properties Map<String,EntityProperty>, methods Collection<EntityMethodScheme>) from class org.panda_lang.panda.utilities.autodata.data.entity.EntityScheme
>   Change Variable Type property : EntitySchemeProperty to property : EntityProperty in method private generateFields(scheme EntityScheme, entityClass CtClass) : void from class org.panda_lang.panda.utilities.autodata.data.entity.EntityGenerator
>   Change Attribute Type properties : Map<String,EntitySchemeProperty> to properties : Map<String,EntityProperty> in class org.panda_lang.panda.utilities.autodata.data.entity.EntityScheme
>   Change Parameter Type type : Class<?> to requestedType : Class in method public generate(requestedType Class, strategy GenerationStrategy) : Object from class org.panda_lang.panda.utilities.autodata.defaults.virtual.InMemoryDataHandler
>   Rename Parameter values : Object[] to constructorArguments : Object[] in method public create(constructorArguments Object[]) : T from class org.panda_lang.panda.utilities.autodata.defaults.virtual.InMemoryDataHandler
>   Change Attribute Type property : EntitySchemeProperty to property : EntityProperty in class org.panda_lang.panda.utilities.autodata.data.entity.EntityMethodScheme
>   Change Variable Type property : EntitySchemeProperty to property : EntityProperty in method private generateDefaultConstructor(scheme EntityScheme, entityClass CtClass) : void from class org.panda_lang.panda.utilities.autodata.data.entity.EntityGenerator
>   Change Variable Type propertyValue : Optional<EntitySchemeProperty> to propertyValue : Optional<EntityProperty> in method private toRule(scheme EntityScheme, rules List<String>, index AtomicInteger) : ProxyQueryRuleScheme from class org.panda_lang.panda.utilities.autodata.data.query.ProxyQueryParser
>   Change Variable Type properties : Map<String,EntitySchemeProperty> to properties : Map<String,EntityProperty> in method protected load(entityClass Class<?>) : EntityScheme from class org.panda_lang.panda.utilities.autodata.data.entity.EntitySchemeLoader
>   Change Variable Type property : EntitySchemeProperty to property : EntityProperty in method private load(properties Map<String,EntityProperty>, methods Collection<EntityMethodScheme>, method Method) : void from class org.panda_lang.panda.utilities.autodata.data.entity.EntitySchemeLoader
>   Change Return Type Optional<EntitySchemeProperty> to Optional<EntityProperty> in method public getProperty(name String) : Optional<EntityProperty> from class org.panda_lang.panda.utilities.autodata.data.entity.EntityScheme
>   Change Variable Type cachedProperty : EntitySchemeProperty to cachedProperty : EntityProperty in method private load(properties Map<String,EntityProperty>, methods Collection<EntityMethodScheme>, method Method) : void from class org.panda_lang.panda.utilities.autodata.data.entity.EntitySchemeLoader
>   Rename Parameter type : Class<?> to requestedType : Class in method public generate(requestedType Class, strategy GenerationStrategy) : Object from class org.panda_lang.panda.utilities.autodata.defaults.virtual.InMemoryDataHandler
>   Remove Parameter entityScheme : EntityScheme in method private createFunction(handler DataHandler, entityScheme EntityScheme) : MethodFunction from class org.panda_lang.panda.utilities.autodata.data.repository.RepositoryProxyMethodGenerator
>   Add Method Annotation @SuppressWarnings("unchecked") in method public find(query DataQuery, values Object[]) : Object from class org.panda_lang.panda.utilities.autodata.defaults.virtual.InMemoryDataHandler
>   Change Return Type EntitySchemeProperty to EntityProperty in method public getProperty() : EntityProperty from class org.panda_lang.panda.utilities.autodata.data.entity.EntityMethodScheme
>   Change Parameter Type property : EntitySchemeProperty to property : EntityProperty in method package EntityMethodScheme(method Method, property EntityProperty, type EntityMethodType) from class org.panda_lang.panda.utilities.autodata.data.entity.EntityMethodScheme
>   Change Variable Type schemeProperty : EntitySchemeProperty to schemeProperty : EntityProperty in method public find(query DataQuery, values Object[]) : Object from class org.panda_lang.panda.utilities.autodata.defaults.virtual.InMemoryDataHandler
>   Change Parameter Type properties : Map<String,EntitySchemeProperty> to properties : Map<String,EntityProperty> in method private load(properties Map<String,EntityProperty>, methods Collection<EntityMethodScheme>, method Method) : void from class org.panda_lang.panda.utilities.autodata.data.entity.EntitySchemeLoader
>   Rename Parameter changes : Object to modifications : DataModification[] in method public save(t T, modifications DataModification[]) : void from class org.panda_lang.panda.utilities.autodata.defaults.virtual.InMemoryDataHandler
>   Add Method Annotation @SuppressWarnings("unchecked") in method private updateFunction(handler DataHandler) : MethodFunction from class org.panda_lang.panda.utilities.autodata.data.repository.RepositoryProxyMethodGenerator
>   Change Parameter Type changes : Object to modifications : DataModification[] in method public save(t T, modifications DataModification[]) : void from class org.panda_lang.panda.utilities.autodata.defaults.virtual.InMemoryDataHandler
>   Rename Class org.panda_lang.panda.utilities.autodata.data.entity.EntitySchemeProperty renamed to org.panda_lang.panda.utilities.autodata.data.entity.EntityProperty

**Comment by tsantalis** [comment]
@kavehshahedi 

https://github.com/panda-lang/panda/commit/91e53c60d62e34c57a49bcb03b93472e8e3cc746

>   Rename Parameter source : Source to packageSource : Package in method public interpret(packageSource Package) : Result<Application,Throwable> from class org.panda_lang.framework.interpreter.Interpreter
>   Move Method protected getPandaModules() : File from class org.panda_lang.panda.manager.PackageDocument to public getPandaModules() : File from class org.panda_lang.panda.manager.PackageInfo
>   Add Parameter module : Module in method public unknownLocation(module Module, id String) : Location from class org.panda_lang.framework.interpreter.token.PandaLocation
>   Change Parameter Type modulePath : ModulePath to packages : Packages in method public load(packages Packages, typeGenerator TypeGenerator, typeLoader TypeLoader, mappings Object[]) : void from class org.panda_lang.panda.language.std.StdLoader
>   Rename Attribute manager : PackageManager to packageManager : PackageManager in class org.panda_lang.panda.manager.goals.Install
>   Add Class Annotation @Mappings(pkg = "java", module = "collections", commonPackage = "java.util", classes = {"Collection","Comparator","Deque","Iterator","List","Map","Map$Entry","ArrayDeque","ArrayList","HashMap","HashSet","Hashtable","IdentityHashMap","LinkedHashMap","LinkedHashSet","LinkedList","Stack","TreeMap","TreeSet","Vector","WeakHashMap"}) in class org.panda_lang.panda.language.std.java.JavaCollectionsModule
>   Extract And Move Method public forModule(qualifier String) : Option<Module> extracted from private forPathType(type String) : Option<Type> in class org.panda_lang.framework.architecture.module.PandaTypeLoader & moved to class org.panda_lang.framework.architecture.packages.Packages
>   Change Method Access Modifier protected to public in method public getWorkingDirectory() : File from class org.panda_lang.panda.manager.PackageManager
>   Remove Parameter controller : FrameworkController in method protected run(controller FrameworkController) : Option<Object> from class org.panda_lang.panda.manager.Run
>   Remove Method Annotation @Override in method public hasRequired() : boolean from class org.panda_lang.framework.interpreter.source.PandaSourceService
>   Add Thrown Exception Type Exception in method public run(manager PackageManager, packageInfo PackageInfo) : Option<Object> from class org.panda_lang.panda.manager.goals.Run
>   Add Parameter manager : PackageManager in method public run(manager PackageManager, packageInfo PackageInfo) : Option<Object> from class org.panda_lang.panda.manager.goals.Run
>   Add Parameter packageManager : PackageManager in method package GitHubInstall(packageManager PackageManager, dependency Dependency) from class org.panda_lang.panda.manager.goals.GitHubInstall
>   Add Class Annotation @Mappings(pkg = "panda", module = Package.DEFAULT_MODULE, commonPackage = "java.lang", classes = {"Iterable"}) in class org.panda_lang.framework.resource.mappings.java.JavaModule
>   Inline Method private parseFile(context Context<?>, requiredFile TokenInfo) : void inlined to public parse(context Context<?>) : Option<Completable<Boolean>> in class org.panda_lang.panda.language.syntax.head.RequireParser
>   Change Class Access Modifier package to public in class org.panda_lang.panda.manager.Dependency
>   Move Method protected getVersion() : String from class org.panda_lang.panda.manager.PackageDocument to public getVersion() : String from class org.panda_lang.framework.architecture.packages.Package
>   Change Method Access Modifier protected to public in method public getDependencies() : List<Dependency> from class org.panda_lang.panda.manager.PackageInfo
>   Add Parameter packageInfo : PackageInfo in method public run(manager PackageManager, packageInfo PackageInfo) : Option<Object> from class org.panda_lang.panda.manager.goals.Run
>   Extract Variable context : Context<?> in method package ReplCreator(console ReplConsole) from class org.panda_lang.panda.shell.repl.ReplCreator
>   Add Parameter moduleName : String in method public importModule(packageName String, moduleName String) : void from class org.panda_lang.framework.architecture.module.Imports
>   Move Class org.panda_lang.framework.architecture.PandaScript moved to org.panda_lang.framework.architecture.packages.PandaScript
>   Remove Parameter name : String in method public importModule(name String) : void from class org.panda_lang.framework.architecture.module.Imports
>   Change Type Declaration Kind interface to class in type org.panda_lang.framework.interpreter.source.SourceService
>   Rename Parameter modulePath : ModulePath to packages : Packages in method private loadClass(packages Packages, typeGenerator TypeGenerator, typeLoader TypeLoader, mappings Object) : void from class org.panda_lang.panda.language.std.StdLoader
>   Add Class Modifier final in class org.panda_lang.framework.architecture.packages.Packages
>   Move Class org.panda_lang.panda.manager.InstallStatus moved to org.panda_lang.panda.manager.goals.InstallStatus
>   Remove Class Modifier final in class org.panda_lang.panda.manager.PackageDocument
>   Change Method Access Modifier protected to public in method public hasHigherVersion(anotherVersion String) : boolean from class org.panda_lang.panda.manager.Dependency
>   Remove Method Annotation @Override in method public countUsedTypes() : long from class org.panda_lang.framework.architecture.module.PandaModule
>   Change Variable Type fileQualifier : Option<TokenInfo> to packageName : TokenInfo in method public parse(context Context<?>) : Option<Completable<Boolean>> from class org.panda_lang.panda.language.syntax.head.RequireParser
>   Change Variable Type environment : Environment to packages : Packages in method public parse(context Context<?>) : Option<Completable<Boolean>> from class org.panda_lang.panda.language.syntax.head.RequireParser
>   Change Return Type Completable<Module> to Module in method public getModule() : Module from class org.panda_lang.framework.architecture.packages.Script
>   Rename Parameter manager : PackageManager to packageManager : PackageManager in method public Install(packageManager PackageManager, document PackageInfo) from class org.panda_lang.panda.manager.goals.Install
>   Add Parameter packages : Packages in method public Imports(packages Packages, typeLoader TypeLoader) from class org.panda_lang.framework.architecture.module.Imports
>   Move Method public getPackage() : Package from class org.panda_lang.framework.architecture.ModuleSource to public getPackage() : Package from class org.panda_lang.framework.architecture.module.Module
>   Add Parameter result : Completable<Script> in method private parse(lexer Lexer, application PandaApplication, context Context<Object>, headPool ParserPool<Object>, source Source, result Completable<Script>) : boolean from class org.panda_lang.panda.language.PandaInterpreter
>   Change Attribute Type scriptName : String to source : Source in class org.panda_lang.framework.architecture.packages.PandaScript
>   Add Thrown Exception Type Exception in method public currentTest() : Option<Object> from class org.panda_lang.panda.examples.tests.performance.CurrentTestBenchmark
>   Move Method public fromFile(file File) : PandaURLSource from class org.panda_lang.framework.interpreter.source.PandaURLSource to public fromFile(module Module, file File) : URLSource from class org.panda_lang.framework.interpreter.source.URLSource
>   Rename Parameter file : File to script : File in method public load(workingDirectory File, script File) : Result<Application,Throwable> from class org.panda_lang.panda.utils.PandaUtils
>   Move Class org.panda_lang.panda.manager.Install moved to org.panda_lang.panda.manager.goals.Install
>   Change Class Access Modifier package to public in class org.panda_lang.panda.manager.goals.Run
>   Change Parameter Type modulePath : ModulePath to packages : Packages in method public load(packages Packages, typeGenerator TypeGenerator, typeLoader TypeLoader) : void from class org.panda_lang.panda.language.std.StdLoader
>   Change Method Access Modifier protected to public in method public getVersion() : String from class org.panda_lang.framework.architecture.packages.Package
>   Change Variable Type packageInfo : PackageDocument to packageInfo : PackageInfo in method public install(resultConsumer BiConsumer<InstallStatus,Dependency>, ownerDirectory File, packageInfoFile File) : List<Dependency> from class org.panda_lang.panda.manager.goals.GitHubInstall
>   Rename Attribute modulePath : ModulePath to packages : Packages in class org.panda_lang.framework.architecture.module.PandaTypeLoader
>   Change Parameter Type codeSource : PandaURLSource to codeSource : URLSource in method public PandaSource(module Module, codeSource URLSource) from class org.panda_lang.framework.interpreter.source.PandaSource
>   Remove Class Annotation @InternalModuleInfo(module = "java:collections", pkg = "java.util", classes = {"Collection","Comparator","Deque","Iterator","List","Map","Map$Entry","ArrayDeque","ArrayList","HashMap","HashSet","Hashtable","IdentityHashMap","LinkedHashMap","LinkedHashSet","LinkedList","Stack","TreeMap","TreeSet","Vector","WeakHashMap"}) in class org.panda_lang.panda.language.std.java.JavaCollectionsModule
>   Pull Up Method public hasStandard() : boolean from class org.panda_lang.framework.interpreter.source.PandaSourceService to public hasUnloadedSources() : boolean from class org.panda_lang.framework.interpreter.source.SourceService
>   Change Return Type Completable<Module> to Module in method public getModule() : Module from class org.panda_lang.framework.architecture.packages.PandaScript
>   Change Thrown Exception Type IOException to Exception in method public install(resultConsumer BiConsumer<InstallStatus,Dependency>, ownerDirectory File, packageInfoFile File) : List<Dependency> from class org.panda_lang.panda.manager.goals.CustomInstall
>   Remove Parameter interrupted : Stack<Runnable> in method private parse(lexer Lexer, application PandaApplication, context Context<Object>, headPool ParserPool<Object>, interrupted Stack<Runnable>, sourceEntry Pair<Source,Completable<Script>>) : boolean from class org.panda_lang.panda.language.PandaInterpreter
>   Remove Parameter script : Source in method public load(script Source, workingDirectory File) : Result<Application,Throwable> from class org.panda_lang.panda.utils.PandaFileLoader
>   Add Thrown Exception Type Exception in method package testMatmul() : void from class org.panda_lang.panda.examples.tests.performance.matmul.MatmulTest
>   Change Parameter Type scriptName : String to source : Source in method public PandaScript(source Source) from class org.panda_lang.framework.architecture.packages.PandaScript
>   Change Method Access Modifier protected to public in method public run(manager PackageManager, packageInfo PackageInfo) : Option<Object> from class org.panda_lang.panda.manager.goals.Run
>   Extract Class org.panda_lang.panda.manager.PackageInfo from class org.panda_lang.panda.manager.PackageDocument
>   Move Class org.panda_lang.panda.manager.CustomInstall moved to org.panda_lang.panda.manager.goals.CustomInstall
>   Change Parameter Type source : Source to packageSource : Package in method public interpret(packageSource Package) : Result<Application,Throwable> from class org.panda_lang.panda.language.PandaInterpreter
>   Move Method protected toDependency() : Dependency from class org.panda_lang.panda.manager.PackageDocument to public toDependency() : Dependency from class org.panda_lang.panda.manager.PackageInfo
>   Add Parameter module : Module in method public PandaSource(module Module, id Object, content String, virtual boolean) from class org.panda_lang.framework.interpreter.source.PandaSource
>   Change Type Declaration Kind interface to class in type org.panda_lang.framework.architecture.packages.Packages
>   Move Class org.panda_lang.panda.utils.PandaFileLoader moved to org.panda_lang.panda.PandaFileLoader
>   Change Attribute Type modulePath : ModulePath to packages : Packages in class org.panda_lang.panda.language.PandaEnvironment
>   Change Method Access Modifier package to public in method public Install(packageManager PackageManager, document PackageInfo) from class org.panda_lang.panda.manager.goals.Install
>   Move And Rename Class org.panda_lang.framework.architecture.module.ModulePath moved and renamed to org.panda_lang.framework.architecture.packages.Packages
>   Add Class Annotation @Mappings(pkg = "java", module = Package.DEFAULT_MODULE, commonPackage = "java.util", classes = {"Arrays","Objects","Optional","Random","UUID"}) in class org.panda_lang.panda.language.std.java.JavaUtilsModule
>   Rename Variable moduleDirectory : File to packageDirectory : File in method public run(manager PackageManager, packageInfo PackageInfo) : Option<Object> from class org.panda_lang.panda.manager.goals.Run
>   Change Parameter Type document : PackageDocument to document : PackageInfo in method public Install(packageManager PackageManager, document PackageInfo) from class org.panda_lang.panda.manager.goals.Install
>   Change Return Type PandaURLSource to URLSource in method public fromFile(module Module, file File) : URLSource from class org.panda_lang.framework.interpreter.source.URLSource
>   Change Method Access Modifier protected to public in method public getName() : String from class org.panda_lang.panda.manager.Dependency
>   Add Parameter module : Module in method public PandaSource(module Module, codeSource URLSource) from class org.panda_lang.framework.interpreter.source.PandaSource
>   Rename Parameter manager : PackageManager to packageManager : PackageManager in method public createCustomInstall(packageManager PackageManager, document PackageInfo, dependency Dependency) : CustomInstall from class org.panda_lang.panda.manager.goals.CustomInstallFactory
>   Remove Class Annotation @InternalModuleInfo(module = "java", pkg = "java.lang", classes = {"Class","Exception","Runtime","RuntimeException","Runnable","StringBuilder","System","Throwable"}) in class org.panda_lang.panda.language.std.java.JavaExtensionModule
>   Rename Package org.panda_lang.framework.resource.internal to org.panda_lang.framework.resource.mappings
>   Move Method protected getName() : String from class org.panda_lang.panda.manager.PackageDocument to public getName() : String from class org.panda_lang.framework.architecture.packages.Package
>   Rename Parameter modulePath : ModulePath to packages : Packages in method public PandaTypeLoader(packages Packages, parents TypeLoader...) from class org.panda_lang.framework.architecture.module.PandaTypeLoader
>   Move Class org.panda_lang.framework.resource.internal.java.Java moved to org.panda_lang.framework.resource.mappings.java.Java
>   Pull Up Method public hasRequired() : boolean from class org.panda_lang.framework.interpreter.source.PandaSourceService to public hasUnloadedSources() : boolean from class org.panda_lang.framework.interpreter.source.SourceService
>   Rename Variable fileQualifier : Option<TokenInfo> to packageName : TokenInfo in method public parse(context Context<?>) : Option<Completable<Boolean>> from class org.panda_lang.panda.language.syntax.head.RequireParser
>   Extract Variable headParser : PoolParser<Object> in method private parse(lexer Lexer, application PandaApplication, context Context<Object>, headPool ParserPool<Object>, source Source, result Completable<Script>) : boolean from class org.panda_lang.panda.language.PandaInterpreter
>   Change Thrown Exception Type IOException to Exception in method public run() : void from class org.panda_lang.panda.manager.goals.Install
>   Rename Parameter source : Source to packageSource : Package in method public interpret(packageSource Package) : Result<Application,Throwable> from class org.panda_lang.panda.language.PandaInterpreter
>   Remove Parameter name : String in method private getDependencies(name String) : List<Dependency> from class org.panda_lang.panda.manager.PackageDocument
>   Inline Method private parse(result Completable<Script>, script Script, interrupted Stack<Runnable>, context Context<PoolParser<Object>>, stream SourceStream) : boolean inlined to private parse(lexer Lexer, application PandaApplication, context Context<Object>, headPool ParserPool<Object>, source Source, result Completable<Script>) : boolean in class org.panda_lang.panda.language.PandaInterpreter
>   Rename Variable moduleInfo : InternalModuleInfo to mappingsInfo : Mappings in method private loadClass(packages Packages, typeGenerator TypeGenerator, typeLoader TypeLoader, mappings Object) : void from class org.panda_lang.panda.language.std.StdLoader
>   Move Method private getDependencies(name String) : List<Dependency> from class org.panda_lang.panda.manager.PackageDocument to public getDependencies() : List<Dependency> from class org.panda_lang.panda.manager.PackageInfo
>   Change Parameter Type source : Source to packageSource : Package in method public interpret(packageSource Package) : Result<Application,Throwable> from class org.panda_lang.framework.interpreter.Interpreter
>   Add Class Annotation @Mappings(pkg = "java", module = Package.DEFAULT_MODULE, commonPackage = "java.lang", classes = {"Class","Exception","Runtime","RuntimeException","Runnable","StringBuilder","System","Throwable"}) in class org.panda_lang.panda.language.std.java.JavaExtensionModule
>   Move Class org.panda_lang.framework.resource.internal.java.JavaModule moved to org.panda_lang.framework.resource.mappings.java.JavaModule
>   Change Variable Type packageInfo : PackageDocument to packageInfo : PackageInfo in method private install(pandaModules File, dependency Dependency, dependenciesToLoad Collection<Dependency>) : void from class org.panda_lang.panda.manager.goals.Install
>   Move Method protected getDependencies() : List<Dependency> from class org.panda_lang.panda.manager.PackageDocument to public getDependencies() : List<Dependency> from class org.panda_lang.panda.manager.PackageInfo
>   Add Parameter packageName : String in method public importModule(packageName String, moduleName String) : void from class org.panda_lang.framework.architecture.module.Imports
>   Change Thrown Exception Type IOException to Exception in method public install(documentFile File) : void from class org.panda_lang.panda.manager.PackageManager
>   Rename Class org.panda_lang.framework.interpreter.source.PandaURLSource renamed to org.panda_lang.framework.interpreter.source.URLSource
>   Change Attribute Type document : PackageDocument to document : PackageInfo in class org.panda_lang.panda.manager.goals.MavenInstall
>   Remove Parameter sourceEntry : Pair<Source,Completable<Script>> in method private parse(lexer Lexer, application PandaApplication, context Context<Object>, headPool ParserPool<Object>, interrupted Stack<Runnable>, sourceEntry Pair<Source,Completable<Script>>) : boolean from class org.panda_lang.panda.language.PandaInterpreter
>   Move Class org.panda_lang.panda.manager.Run moved to org.panda_lang.panda.manager.goals.Run
>   Add Thrown Exception Type Exception in method public load(workingDirectory File, script File) : Result<Application,Throwable> from class org.panda_lang.panda.utils.PandaUtils
>   Change Method Access Modifier protected to public in method public getPandaModules() : File from class org.panda_lang.panda.manager.PackageInfo
>   Move Class org.panda_lang.panda.manager.CustomInstallFactory moved to org.panda_lang.panda.manager.goals.CustomInstallFactory
>   Remove Class Annotation @InternalModuleInfo(module = "java", pkg = "java.util", classes = {"Arrays","Objects","Optional","Random","UUID"}) in class org.panda_lang.panda.language.std.java.JavaUtilsModule
>   Change Attribute Type document : PackageDocument to document : PackageInfo in class org.panda_lang.panda.manager.goals.Install
>   Extract Class org.panda_lang.framework.architecture.packages.Package from class org.panda_lang.panda.manager.PackageDocument
>   Change Parameter Type modulePath : ModulePath to packages : Packages in method public PandaTypeLoader(packages Packages, parents TypeLoader...) from class org.panda_lang.framework.architecture.module.PandaTypeLoader
>   Change Method Access Modifier protected to public in method public Dependency(type String, owner String, name String, version String) from class org.panda_lang.panda.manager.Dependency
>   Remove Method Annotation @Override in method public countTypes() : long from class org.panda_lang.framework.architecture.module.PandaModule
>   Rename Parameter scriptName : String to source : Source in method public PandaScript(source Source) from class org.panda_lang.framework.architecture.packages.PandaScript
>   Add Thrown Exception Type Exception in method public setup() : void from class org.panda_lang.panda.examples.tests.performance.matmul.MatmulPerformanceTest
>   Parameterize Variable current : Source to source : Source in method private parse(lexer Lexer, application PandaApplication, context Context<Object>, headPool ParserPool<Object>, source Source, result Completable<Script>) : boolean from class org.panda_lang.panda.language.PandaInterpreter
>   Add Parameter module : Module in method public ClassSource(module Module, clazz Class<?>) from class org.panda_lang.framework.interpreter.source.ClassSource
>   Move Class org.panda_lang.panda.manager.MavenInstall moved to org.panda_lang.panda.manager.goals.MavenInstall
>   Rename Attribute modulePath : ModulePath to packages : Packages in class org.panda_lang.panda.language.PandaEnvironment
>   Change Thrown Exception Type IOException to Exception in method public run(documentFile File) : Option<Object> from class org.panda_lang.panda.manager.PackageManager
>   Rename Attribute scriptName : String to source : Source in class org.panda_lang.framework.architecture.packages.PandaScript
>   Change Thrown Exception Type IOException to Exception in method private install(pandaModules File, dependency Dependency, dependenciesToLoad Collection<Dependency>) : void from class org.panda_lang.panda.manager.goals.Install
>   Change Attribute Type modulePath : ModulePath to packages : Packages in class org.panda_lang.framework.architecture.module.PandaTypeLoader
>   Change Method Access Modifier private to public in method public getDependencies() : List<Dependency> from class org.panda_lang.panda.manager.PackageInfo
>   Change Method Access Modifier protected to public in method public getOwner() : String from class org.panda_lang.panda.manager.Dependency
>   Add Parameter pkg : Package in method public load(workingDirectory File, pkg Package) : Result<Application,Throwable> from class org.panda_lang.panda.PandaFileLoader
>   Rename Variable environment : Environment to packages : Packages in method public parse(context Context<?>) : Option<Completable<Boolean>> from class org.panda_lang.panda.language.syntax.head.RequireParser
>   Add Parameter module : Module in method public fromFile(module Module, file File) : URLSource from class org.panda_lang.framework.interpreter.source.URLSource
>   Change Class Access Modifier package to public in class org.panda_lang.panda.manager.PackageManagerConstants
>   Rename Class org.panda_lang.framework.interpreter.source.PandaClassSource renamed to org.panda_lang.framework.interpreter.source.ClassSource
>   Change Method Access Modifier protected to public in method public getName() : String from class org.panda_lang.framework.architecture.packages.Package
>   Rename Variable mainScript : File to dependencyPackageInfo : File in method public run(manager PackageManager, packageInfo PackageInfo) : Option<Object> from class org.panda_lang.panda.manager.goals.Run
>   Change Parameter Type document : PackageDocument to document : PackageInfo in method public MavenInstall(manager PackageManager, document PackageInfo, dependency Dependency) from class org.panda_lang.panda.manager.goals.MavenInstall
>   Rename Parameter modulePath : ModulePath to packages : Packages in method public load(packages Packages, typeGenerator TypeGenerator, typeLoader TypeLoader) : void from class org.panda_lang.panda.language.std.StdLoader
>   Change Thrown Exception Type IOException to Exception in method public install(resultConsumer BiConsumer<InstallStatus,Dependency>, ownerDirectory File, packageInfoFile File) : List<Dependency> from class org.panda_lang.panda.manager.goals.GitHubInstall
>   Rename Parameter modulePath : ModulePath to packages : Packages in method public load(packages Packages, typeGenerator TypeGenerator, typeLoader TypeLoader, mappings Object[]) : void from class org.panda_lang.panda.language.std.StdLoader
>   Add Parameter module : Module in method public PandaSource(module Module, id Object, content String) from class org.panda_lang.framework.interpreter.source.PandaSource
>   Move Class org.panda_lang.framework.architecture.Script moved to org.panda_lang.framework.architecture.packages.Script
>   Change Method Access Modifier protected to public in method public toDependency() : Dependency from class org.panda_lang.panda.manager.PackageInfo
>   Remove Class Annotation @InternalModuleInfo(module = "panda", pkg = "java.lang", classes = {"Iterable"}) in class org.panda_lang.framework.resource.internal.java.JavaModule
>   Change Class Access Modifier package to public in class org.panda_lang.panda.manager.goals.Install
>   Move Class org.panda_lang.panda.manager.GitHubInstall moved to org.panda_lang.panda.manager.goals.GitHubInstall
>   Change Method Access Modifier protected to public in method public getVersion() : String from class org.panda_lang.panda.manager.Dependency
>   Change Variable Type moduleInfo : InternalModuleInfo to mappingsInfo : Mappings in method private loadClass(packages Packages, typeGenerator TypeGenerator, typeLoader TypeLoader, mappings Object) : void from class org.panda_lang.panda.language.std.StdLoader
>   Change Parameter Type modulePath : ModulePath to packages : Packages in method private loadClass(packages Packages, typeGenerator TypeGenerator, typeLoader TypeLoader, mappings Object) : void from class org.panda_lang.panda.language.std.StdLoader
>   Change Parameter Type document : PackageDocument to document : PackageInfo in method public createCustomInstall(packageManager PackageManager, document PackageInfo, dependency Dependency) : CustomInstall from class org.panda_lang.panda.manager.goals.CustomInstallFactory
>   Collapse Hierarchy org.panda_lang.framework.architecture.module.PandaModulePath to org.panda_lang.framework.architecture.packages.Packages
>   Add Thrown Exception Type Exception in method public load(workingDirectory String, sourceFile String) : Result<Application,Throwable> from class org.panda_lang.panda.utils.PandaUtils
>   Move And Inline Method public equals(to Object) : boolean moved from class org.panda_lang.framework.architecture.module.PandaModule to class org.panda_lang.panda.manager.Dependency & inlined to public equals(o Object) : boolean
>   Inline Variable module : Module in method protected fetchType(context Context<?>, javaTypeSource Snippet) : Type from class org.panda_lang.panda.language.syntax.head.ConveyanceUtils
>   Change Class Access Modifier package to public in class org.panda_lang.panda.manager.PackageDocument
>   Parameterize Attribute document : PackageDocument to packageInfo : PackageInfo in method public run(manager PackageManager, packageInfo PackageInfo) : Option<Object> from class org.panda_lang.panda.manager.goals.Run
