### ISSUE TITLE
Unmapped Statement Move: field initialization moved from @Before method to just one of the @Test methods

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#432]
At commit https://github.com/jenkinsci/acceptance-test-harness/pull/338/commits/0661e8b8be3a986c624caca3a54a45b927ba23d0  

The field initialization

```Java
private StageView stageView
``` 

moved from the `@Before` method

```Java
    @Before
    public void before() {
        stageView = new StageView(context, path);
    }
```

to one of the `@Test` methods

```Java
    @Test
    public void jobShouldContainStageview() throws Exception {
        WorkflowJob job = this.saveWorkflowJobWithFile(SINGLE_JOB);
        Build build = job.startBuild().shouldSucceed();
        stageView = new StageView(job, path);  // HERE
        job.open();
        assertThat(stageView.getRootElementName().getText(),containsString("Stage View"));
    }
```

Leading to the deletion of the `@Before` method.

Yet, RefactoringMiner's latest version (8baafe35146fcec01de41dba80614460bea2ebea)

<img width="606" alt="Screenshot 2023-03-28 at 9 35 30 PM" src="https://user-images.githubusercontent.com/11022419/228403714-0676cb3f-8ee3-42c0-94c9-4de51535d287.png">

Could not detect it

<img width="1470" alt="Screenshot 2023-03-28 at 9 30 26 PM" src="https://user-images.githubusercontent.com/11022419/228403163-22101c0f-a156-4725-9f0e-7e02a5e83505.png">

**Comment by victorgveloso** [comment]
@tsantalis that's the case you asked me to look for.

**Comment by tsantalis** [comment]
@pouryafard75 @victorgveloso 

![Screenshot from 2023-04-17 06-54-05](https://user-images.githubusercontent.com/1483516/232464552-7736c36e-5a66-482e-ad4b-140ed0104e82.png)

**Comment by tsantalis** [comment]
https://github.com/apache/drill/commit/c1b847acdc8cb90a1498b236b3bb5c81ca75c044

![Screenshot from 2023-04-17 08-00-08](https://user-images.githubusercontent.com/1483516/232478350-8af6ebb6-3634-424b-bbe1-26b007382add.png)

This is a diff of the pulled up method, showing that `Map<String, WorkspaceConfig> workspaces = Maps.newHashMap();` has been removed, and eventually moved to `createTestWorkspaces()`

![Screenshot from 2023-04-17 07-58-16](https://user-images.githubusercontent.com/1483516/232478375-f4001d9f-6eb5-4f40-a781-e56d178153c0.png)

**Comment by tsantalis** [comment]
https://github.com/apache/cassandra/commit/f797bfa4da53315b49f8d97b784047f33ba1bf5f#diff-822707a68576bd683b72fde39e19ab8a78ed5a1816d95f5d8a00b3f46ac78d03

Code moved from `setUpClass()` with `@BeforeClass` annotation to newly added `beforeTest()` method with `@Before` annotation

![Screenshot from 2023-04-17 11-48-30](https://user-images.githubusercontent.com/1483516/232540811-fd2deaf5-8cbd-42f1-bb24-f24269f5341c.png)

**Comment by tsantalis** [comment]
https://github.com/JetBrains/intellij-community/commit/7a4dab88185553bd09e827839fdf52e870ef7088#diff-7cd02727f221d361433f3b29e20a261660ccb9d7a508023713c1112f8bf5ed38

![Screenshot from 2023-04-17 12-01-36](https://user-images.githubusercontent.com/1483516/232543693-abf2f31a-7acf-47a2-9fba-1a1d439d7758.png)

**Comment by tsantalis** [comment]
https://github.com/pentaho/mondrian/commit/871f7747deded94e721fa098561376ab304b24de

Statement `propSaver.set(MondrianProperties.instance().GenerateFormattedSql, true);` moved from two test method to `setUp()`

![Screenshot from 2023-04-17 17-03-58](https://user-images.githubusercontent.com/1483516/232610515-8a3550f1-bc7a-4877-8332-0f50ca6ecf35.png)

**Comment by tsantalis** [comment]
https://github.com/apache/drill/commit/2800c57981f27d04b97e5994c3f6325ca301f110#diff-c22c219bea381ab31a7366e15734515f08e1a627145bdc60725ce8751139a13e

Another nice case with multi-mappings. Duplicated statements moved from tests to `setupForAllTests()` with `@BeforeClass` annotation and `setupForEachTest()` with `@Before` annotation.

![Screenshot from 2023-04-17 19-00-47](https://user-images.githubusercontent.com/1483516/232628634-7b4afcde-ad34-4b35-b385-9d6fece07410.png)
