### ISSUE TITLE
Incorrect Argument Mapping for ExtractMethod Refactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#434]
https://github.com/JetBrains/MPS/commit/ce4b0e22659c16ae83d421f9621fd3e922750764
[AbstractModule.java](https://github.com/JetBrains/MPS/commit/ce4b0e22659c16ae83d421f9621fd3e922750764#diff-6f80e193263b69de84cc29bb0eb8bbcef6e2e1d1c0bee54568fc10623a13f1b0)

**Problem:** The second argument mappings is incorrect since the passed argument is not used and the developer is calling the `getModuleName` again instead of using the `oldname` parameter

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28820932/229313509-2abe84d3-9b75-4872-891d-1f65d4999c91.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-04-04 22-00-54](https://user-images.githubusercontent.com/1483516/229961836-3edb9d29-7353-48a3-bbce-d6e5181beb41.png)
