### ISSUE TITLE
Operations with different signatures and slightly different method body not reported as mapped

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#435]
https://github.com/netty/netty/commit/9d347ffb91f34933edb7b1124f6b70c3fc52e220
[HttpObjectDecoder.java](https://github.com/netty/netty/commit/9d347ffb91f34933edb7b1124f6b70c3fc52e220#diff-e26989b9171ef22c27c9f7d80689cfb059d568c9bd10e75970d96c02d0654878)

**Problem:** 
1-  `private static int findNonWhitespace(CharSequence sb, int offset)` -> 
`private static int findNonWhitespace(AppendableCharSequence sb, int offset)`  **not reported**

2-  `private static int findWhitespace(CharSequence sb, int offset)` -> 
`private static int findWhitespace(AppendableCharSequence sb, int offset)` **not reported**

3- `private static int findEndOfString(CharSequence sb)` -> 
`private static int findEndOfString(AppendableCharSequence sb)` **not reported**

**Description:**
For all three operations:
- The method name hasn't been modified. 
- The first parameter has been updated from `CharSequence` to `AppendableCharSequence`.
- The declaration of the variable `result` has been moved inside the for loop expressions.
- Instead of breaking from the loop and returning the `result` afterward, `result` is returned since it is not accessible outside of the loop anymore.

However, there are some other changes as well, but these methods seem to be good candidates to get mapped.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28820932/229313952-6fa4a1fb-ca0f-4d82-823a-06dd5b13c3d9.png">

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/28820932/229314081-18a6f159-10fc-44c4-a08b-744484b2e878.png">

**Comment by tsantalis** [comment]
@pouryafard75 

I added a LeafMapping between the variable declaration and the first expression of the for loop,
but it seems it overwrites the for-loop mapping, instead of making a multi-mapping.

![Screenshot from 2023-08-18 08-59-57](https://github.com/tsantalis/RefactoringMiner/assets/1483516/d527fbe7-5bc9-4587-88c6-248225f549ed)

**Comment by pouryafard75** [comment]
@tsantalis 
Proof of fix:
<img width="1430" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/fe6986df-83f7-41c6-9e00-a81b1f6b8b8e">

**Comment by pouryafard75** [comment]
@tsantalis 
The last method doesn't contain the newly added mapping (Please check the screenshots).
<img width="961" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/20432e00-2946-4051-b89a-51c815e8f0db">
