### ISSUE TITLE
Anonymous class replaced with a concrete class and the methods moved to the new concrete class

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#436]
https://github.com/clojure/clojure/commit/309c03055b06525c275b278542c881019424760e
[PersistentList.java](https://github.com/clojure/clojure/commit/309c03055b06525c275b278542c881019424760e#diff-4cdae3e30330302978691a557029db391f6e29e0a86852d20d6fde3899298b72)

Problem: The initializer of `IFn creator` was an anonymous class in the parent version. In the child version, a concrete class corresponding to the anonymous one is created beforehand, and the initializer is replaced with the object creation from the concrete class which is `new Preordinal`.

**Note:** I am not sure whether this information is reported by RefactoringMiner or not, but it is already reported, where should I look for it?

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/28820932/229315724-4860d053-dfdc-435f-ad43-9d0216cdda86.png">

**Comment by tsantalis** [comment]
@pouryafard75 

You should process `ReplaceAnonymousWithClassRefactoring` and call getDiff()
