### ISSUE TITLE
Incorrect statement mapping in ExtractOperationRefactoring

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#437]
https://github.com/eclipse/jetty.project/commit/837d1a74bb7d694220644a2539c4440ce55462cf
[ProxyServletTest.java](https://github.com/eclipse/jetty.project/commit/837d1a74bb7d694220644a2539c4440ce55462cf#diff-04867100f23ddcd87a0c9f7adfbdc18cffd550c75e52ea4e46d2ab2033529bec)

Problem: Inaccurate statement mappings for `Extract Method	private testTransparentProxyWithQuery(proxyToContext String, prefix String, target String) : void extracted from public testTransparentProxyWithQuery() : void in class org.eclipse.jetty.proxy.ProxyServletTest` Refactoring.

**L674** -> **R686** has been reported but **L674** -> **R700** looks correct:
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28820932/229317968-99e52bb6-b705-425d-bc4d-2dcd48e73956.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/28820932/229316891-473268ef-dd07-41c2-b9d5-cad605702527.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-04-22 07-16-18](https://user-images.githubusercontent.com/1483516/233781487-feadeafd-3c24-430d-aeca-818e82dac3a6.png)
