### ISSUE TITLE
Missing statement mapping (Method with single return statement)

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#438]
https://github.com/hibernate/hibernate-orm/commit/0b6ea757e34a63b1421b77ed5fbb61398377aab1
[CallbacksTest.java](https://github.com/hibernate/hibernate-orm/commit/0b6ea757e34a63b1421b77ed5fbb61398377aab1#diff-9dd92d5bd5e5ac97a396dfe0f558a7efb63154e0a27809524c1e4ab1a908a86f)

**Problem**: Statement mapping missing in `public getAnnotatedClasses() : Class[] -> public getAnnotatedClasses() : Class[]`
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28820932/229319146-a51eea28-ac9d-4b38-8b52-17b1367226fe.png">

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/28820932/229319276-cb2e8574-170e-45f6-abd1-235e73583b24.png">

**Comment by tsantalis** [comment]
@pouryafard75 
![Screenshot from 2023-04-23 14-27-23](https://user-images.githubusercontent.com/1483516/233858537-ccaea3c1-35cc-42a1-9213-5c6f04615462.png)
