### ISSUE TITLE
Statements moved to anonymous class within the same method

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#440]
https://github.com/gradle/gradle/commit/3a7ccf5a252077332b9505acb22f190745f726f7
[PlayApplicationPlugin.java](https://github.com/gradle/gradle/commit/3a7ccf5a252077332b9505acb22f190745f726f7#diff-0d659811effa0fcf0be4efc92260a119ebc0a1bef76a2795045bf60cfebfc667)
Problem: Inside Method `void createPlayRunTask(ModelMap<Task> tasks, BinaryContainer binaryContainer, final ServiceRegistry serviceRegistry, final PlayPluginConfigurations configurations, ProjectIdentifier projectIdentifier, final PlayToolChainInternal playToolChain)` 3 statements moved from the method body into the anonymous class method body:
- L**398** `DeploymentRegistry deploymentRegistry = serviceRegistry.get(DeploymentRegistry.class);` -> R**409** `DeploymentRegistry deploymentRegistry = serviceRegistry.get(DeploymentRegistry.class);`

- L**399** `final PlayApplicationDeploymentHandle deploymentHandle = registerOrFindDeploymentHandle(deploymentRegistry, deploymentId);` -> R**410** `PlayApplicationDeploymentHandle deploymentHandle = deploymentRegistry.get(PlayApplicationDeploymentHandle.class, playRun.getPath());`

- L**400** `deploymentHandle.registerBuildListener(serviceRegistry.get(Gradle.class));` -> R**411** `deploymentHandle.registerBuildListener(serviceRegistry.get(Gradle.class));`

**Note:** I am not sure whether these mappings are reported by RM or not. In case they already exist, please let me know where can I find them.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28820932/229331862-654349ae-9cf8-4bdf-b8c3-08e9f8e7c16c.png">

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/28820932/229332110-a7fa9c5d-5de6-433a-bebc-e201ca9d1ed6.png">

**Comment by tsantalis** [comment]
@pouryafard75 

There is a Move Code refactoring generated for this case, but the mappings are not shown in the AST diff.

The same happens for this case
https://github.com/JetBrains/intellij-community/commit/619a6012da868d0d42d9628460f2264effe9bdba
`Move Code from public computeInReadAction(indicator ProgressIndicator) : void to public run() : void in class com.intellij.ide.util.gotoByName.ChooseByNameBase.CalcElementsThread.computeInReadAction.invokeLater.new Runnable`
