### ISSUE TITLE
Variable Declaration statement not mapped when the initializer extracted to a new method

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#441]
https://github.com/JetBrains/intellij-plugins/commit/83b3092c1ee11b70489732f9e69b8e01c2a966f0
[DartAnalysisServerService.java](https://github.com/JetBrains/intellij-plugins/commit/83b3092c1ee11b70489732f9e69b8e01c2a966f0#diff-b2fa6867f6081548120831a6768ae898e285bd94ed032f3fc9a5713ab524251f)
Problem: The following statement mapping is not reported:
L**1196** `final String message = "Error from " + methodName +
                           (filePath == null ? "" : (", file = " + filePath)) +
                           ", SDK version = " + mySdkVersion +
                           ", server version = " + myServerVersion +
                           ", error code = " + error.getCode() + ": " + error.getMessage() +
                           "\n" + partialTrace + "...";` 
-> R**1214** `final String message = getShortErrorMessage(methodName, filePath, error) + "\n" + partialTrace + "...";`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28820932/229332262-d084f1d6-2099-44a2-b80a-e9b4165adf6a.png">
<img width="1106" alt="Screenshot 2023-04-02 at 1 04 51 AM" src="https://user-images.githubusercontent.com/28820932/229332455-f6b52831-1435-462f-b424-90c6d1803b63.png">

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-04-05 14-10-24](https://user-images.githubusercontent.com/1483516/230167705-5738c411-d06f-4b86-b200-025c7e2e6562.png)
