### ISSUE TITLE
Variable Declaration statement not mapped when the initializer extracted to a new method (Similar to #441)

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#442]
Similar to #441 
https://github.com/JetBrains/intellij-plugins/commit/0df7cb00757fe0d4fac8d8b0d5fc46af95feb238
[DartResolver.java](https://github.com/JetBrains/intellij-plugins/commit/0df7cb00757fe0d4fac8d8b0d5fc46af95feb238#diff-310f7e6ba67848d847f389dc29c6c1684861c24c2443883c73a81e7322e1c840)
**Problem:** The following statement mapping is not reported:
L**140** `PsiFile file = PsiManager.getInstance(project).findFile(virtualFile);` 
-> R**138** `PsiFile file = findPsiFile(project, targetPath);`
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/28820932/229332984-4d708d34-4b5b-419d-9526-2dbe374e0c88.png">
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/28820932/229333154-f92c8863-62e9-4345-9f50-3e66d1018f50.png">

**Comment by tsantalis** [comment]
@pouryafard75 

We should leave this case as is, based on issue https://github.com/pouryafard75/RM-ASTDiff/issues/58

The extracted method could be equivalently coded as follows:

```java
public static PsiFile findPsiFile(@NotNull Project project, @NotNull String path) {
    PsiFile file = null;
    VirtualFile virtualFile = LocalFileSystem.getInstance().findFileByPath(path);
    if (virtualFile != null) {
      file = PsiManager.getInstance(project).findFile(virtualFile);
    }
    return file;
}
```

In that case we would consider that the original variable declaration is split into
Variable Declaration + Assignment statement.

As a result, the statement
```java
PsiFile file = findPsiFile(project, targetPath);
```

is a newly added statement.

To further support my argument, it is not right to match variable declarations that are in different nesting levels before and after the refactoring, as in this case.
