### ISSUE TITLE
Publish the library on Maven

### ISSUE THREAD

**Issue by mauricioaniche** [tsantalis/RefactoringMiner#45]
It'd be nice to have refactoringminer available on Maven central.

Right now, I have the jar in my tool folder, which is not ideal! :)

**Comment by tsantalis** [comment]
@mauricioaniche Thank you for your suggestion!
This is in my immediate plans for RefactoringMiner.
There are still some improvements to be made until the next stable release.

**Comment by nashid** [comment]
@tsantalis it would be awesome to have it published in the maven central.

**Comment by jazzmuesli** [comment]
> It'd be nice to have refactoringminer available on Maven central.
> 
> Right now, I have the jar in my tool folder, which is not ideal! :)

I run ./gradlew install and it puts the jar into my local mvn repository, so I can use it as 
   <dependency>
      <groupId>org.refactoringminer</groupId>
      <artifactId>RefactoringMiner</artifactId>
      <version>1.0</version>
      </dependency>
in another project.

**Comment by mauricioaniche** [comment]
Shall we discuss this issue again? I am updating RMiner frequently, copying the JAR that I build locally to my project, but I'm afraid I'm not updating all its dependencies. Having it in Maven Central would remove all this manual work.

I have some experience in deploying to Maven central. I can give you detailed instructions, so that it'll take little time :)

**Comment by tsantalis** [comment]
@mauricioaniche What about the new GitHub packages feature? Have you tried it? It seems much easier than deploying to Maven central.

**Comment by mauricioaniche** [comment]
I never used it, but if I understand correctly, this GitHub packages feature only works mostly with GitHub actions. Or you have the 1GB limit for data out of actions. Maybe that's enough for RMiner users?
