### ISSUE TITLE
TestCommandLine is flaky and brittle

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#450]
TestCommandLine has two problems that lead to flakiness:

1. Invokes `RefactoringMiner` class's API (e.g., detectAll and detectAtGitHubCommit) that creates a temporary json file, which is never purged 
   1. We can solve this issue by replacing the `jsonPath` variable with a field and adding a tearDown method that cleans the temporary file located at `jsonPath`
2. `RefactoringMiner` class's API also runs concurrently, so the main thread proceeds to run the following statements instantly, and that means `IOUtils.readLines` may be executed before the json file is generated (possibly testing an old version of the same file or throwing `FileNotFoundException` because no file with that name exists)
   1. We can solve this issue by leveraging the timeout parameter to explicitly put the main thread to sleep for 100s using `Thread.sleep(100_000L)`

In addition, it has a problem that makes it brittle:

1. The resulting json of the `RefactoringMiner` class's API includes a "list of commits," which contains a "repository" field whose value depends on the URL of the `git remote origin` of the cloned repository.
   1. This is particularly harmful because the automated test does not clone the repository automatically. So that the `assertEquals` fails whenever you cloned the required repos without anticipating the adopted format of the origin URL.
   2. For example, `TestCommandLine.testAll` will fail if you cloned "refactoring-toy-example" into the `tmp1` dir using either `git clone https://github.com/danilofes/refactoring-toy-example` or `git@github.com:danilofes/refactoring-toy-example.git`
      1. Instead, you are expected to clone it using `git clone https://github.com/danilofes/refactoring-toy-example.git` (a subtle difference that is easily overlooked)
   4. There are two alternative solutions for this problem:
      1. Discard the repository field before comparing the expected and obtained json files
      2. Make those tests clone the repositories automatically (enforcing the implicitly adopted format of the origin URL)

**Comment by tsantalis** [comment]
@victorgveloso 
Can you make a PR with your commit?

**Comment by victorgveloso** [comment]
Unfortunately, the commit just partially solve the aforementioned problems. I've tried many alternative implementations in the last 5 days and will make a PR based on the best version.

In my experiment, some tests in TestCommandLine can be very slow and it gets stuck (possibly due to a deadlock) when executed concurrently. 

The `@ResouceLock` annotation alleviate the issue but using `@Isolated` in the class seems to be the most consistent solution. [JUnit 5's define isolated tests run sequentially even when concurrency is enabled] (https://junit.org/junit5/docs/5.7.1/api/org.junit.jupiter.api/org/junit/jupiter/api/parallel/Isolated.html)

**Comment by tsantalis** [comment]
@victorgveloso 
The only tests that are a bit slow are the GitHub tests, because some commits are big and the files need to be downloaded using the GitHub API.
I have no problem running these tests.

**Comment by victorgveloso** [comment]
I agree, those are the slow ones. And the problem only shows up when I added the tearDown method to delete the generated files. 

If I keep the generated files, the tests run quickly and flawlessly. However, that's not what we want. We want the tests to fail when we break the code. 

Currently, these tests aren't testing anything except the cached files. I'll work on it and make a PR by tomorrow.
