### ISSUE TITLE
MoveCode Refactoring not detected

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#469]
https://github.com/pouryafard75/RM-ASTDiff/commit/37b7de20c219c3ebffbca586cfd50c71e54c4aea
<img width="1437" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/9ee43cc2-f5db-4df3-b158-b351af859bf0">

As the author of the commit, I moved one statement to another method.

**Comment by tsantalis** [comment]
`private ASTDiff process(UMLAbstractClassDiff classDiff, Pair<TreeContext, TreeContext> treeContextPair,boolean mergeFlag)`
calls
`private void processClassDeclarationMapping(Tree srcTree, Tree dstTree, UMLClassBaseDiff classDiff, ExtendedMultiMappingStore mappingStore)`
which contains statement
`processClassAttributes(srcTree,dstTree,classDiff,mappingStore);`

Essentially the statement is moved 1-level back in the call chain (moved to caller method `process`).
This could be implemented with a rule

**Comment by tsantalis** [comment]
This issue is fixed in the AST diff, matching the remaining unique unmatched stattements
