### ISSUE TITLE
detection between tags

### ISSUE THREAD

**Issue by mashalahmad** [tsantalis/RefactoringMiner#47]
Hi im trying to detect the refactoring between the tags  of the [this](https://github.com/wumpz/jhotdraw.git) repository but im nt getting any refactoring between all the tags
here is the code

		```
               GitService gitService = new GitServiceImpl();
		GitHistoryRefactoringMiner miner = new GitHistoryRefactoringMinerImpl(); 

		Repository repo = 
           gitService.cloneIfNotExists("tmp/jhtdraw4","https://github.com/wumpz/jhotdraw.git");
		
		miner.detectBetweenTags(repo, "7.8", "7.9", new RefactoringHandler() {
			  @Override
			  public void handle(RevCommit commitData, List<Refactoring> refactorings) {
			    System.out.println("Refactorings at " + commitData.getId().getName());
			    for (Refactoring ref : refactorings) {
			      System.out.println(ref.toString());
			    }
			  }
			});
```

**Comment by tsantalis** [comment]
The fixed version includes merge commits. Some refactorings may appear twice.

> 2019-02-08 22:02:12 INFO  Processing tmp\jhotdraw 4f9b1e296547cc4f5723d2b59e1c6bf586b801e3 ...
> 2019-02-08 22:02:13 INFO  Processing tmp\jhotdraw 9f4398b5a769bdf921ea55d4a7baf72497fab131 ...
> Refactorings at 9f4398b5a769bdf921ea55d4a7baf72497fab131
> Extract Method	protected constrainPoint(p Point2D.Double, figure Figure[]) : Point2D.Double extracted from protected constrainPoint(p Point) : Point2D.Double in class org.jhotdraw.draw.tool.AbstractTool
> Refactorings at 791995bdeeddb26a065a68cfac956af9d2136477
> 2019-02-08 22:02:14 INFO  Processing tmp\jhotdraw 8bedbbc8fc87bab34b943bdc32389d8fb31a95ae ...
> 2019-02-08 22:02:14 INFO  Processing tmp\jhotdraw a18029af70be5ddd07b1beb4f616e6f24fcd1bfe ...
> Refactorings at a18029af70be5ddd07b1beb4f616e6f24fcd1bfe
> 2019-02-08 22:02:14 INFO  Processing tmp\jhotdraw f93493be9a2db4619875da93d4f2e32415279da5 ...
> 2019-02-08 22:02:14 INFO  Processing tmp\jhotdraw 8bedbbc8fc87bab34b943bdc32389d8fb31a95ae ...
> Refactorings at 8bedbbc8fc87bab34b943bdc32389d8fb31a95ae
> Extract Method	protected constrainPoint(p Point2D.Double, figure Figure[]) : Point2D.Double extracted from protected constrainPoint(p Point) : Point2D.Double in class org.jhotdraw.draw.tool.AbstractTool
> Refactorings at f93493be9a2db4619875da93d4f2e32415279da5
> Refactorings at c5acae70085ac2ae825810d4ea50448bed000f46
> Refactorings at ef5566c02030c4a494b18191b05fe31b51050ff4
> Refactorings at 059450c04230dc19e28eb640ecca0cd0d88faf50
> 2019-02-08 22:02:15 INFO  Analyzed jhotdraw [Commits: 8, Errors: 0, Refactorings: 2]
