### ISSUE TITLE
Wrong reported Extract Method

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#471]
**Problem:**

Wrong reported Extract Method refactoring (statement mappings)

**Commit:**

https://github.com/spring-projects/spring-data-neo4j/commit/f85cb537d2abe6bc73ae5b037a3e517a9aa8bcf1

**Wrong reported Refactoring:**

Extract Method private **defaultStartClause**(entity Neo4jPersistentEntity<?>) : String extracted from public **toString()** : String in class org.springframework.data.neo4j.repository.query.**CypherQueryBuilder**.**CypherQuery**

**Description**

Within the above mentioned commit, the reported statement mapping in the aforementioned Extract Method is wrong. Instead, there is one method in the parent version with the following information, which I believe should be mapped with the newly added method (I think it's already mapped, so the problem here is just the wrong reported Extract Method):

`private String defaultStartClause()` Line 63 to 66

The statement inside this method is very similar to the one in the newly added method.

**Comment by tsantalis** [comment]
`defaultStartClause()` is moved from `CypherQueryBuilder` to inner class `CypherQueryBuilder.CypherQuery`
