### ISSUE TITLE
Wrong reported Extract Method refactorings

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#472]
**Problem:**

Two wrong reported Extract Method refactorings (statement mappings)

**Commit:**

https://github.com/Direwolf20-MC/BuildingGadgets/commit/949d89f4d7847be694f2f082da5ab5814327d1fa

**Wrong reported refactorings:**

**1-** Extract Method package **itemPropertiesWithGroup()** : Item.Properties extracted from package **init()** : void in class com.direwolf20.buildinggadgets.common.registry.objects.**BGItems**

**2-** Extract Method package **itemPropertiesWithGroup()** : Item.Properties extracted from package **unstackableItemProperties()** : Item.Properties in class com.direwolf20.buildinggadgets.common.registry.objects.**BGItems** 

**Description**

Statement mappings within the above mentioned Extract Method refactorings is completely wrong. **Instead, RMiner should report two Rename Method refactorings**:

- `static Item.Properties itemPropertiesWithoutGroup()` has been renamed to `static Item.Properties itemProperties()`
- `static Item.Properties itemProperties()` has been renamed to `static Item.Properties itemPropertiesWithGroup()`

**Comment by tsantalis** [comment]
**Rename Method** package itemPropertiesWithoutGroup() : Item.Properties renamed to package itemProperties() : Item.Properties in class com.direwolf20.buildinggadgets.common.registry.objects.BGItems

**Rename Method** package itemProperties() : Item.Properties renamed to package itemPropertiesWithGroup() : Item.Properties in class com.direwolf20.buildinggadgets.common.registry.objects.BGItems
