### ISSUE TITLE
Wrong reported statement mappings (Extract Method)

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#473]
**Problem**

Wrong reported statement mappings, and consequently, Extract Method refactoring

**Commit**

https://github.com/linkedin/pygradle/commit/e1ad18b5ddb9bd49ac4823e41b5d4ebb8c800caf

**Target Refactoring**

Extract Method private **fromFile(file File)** : Optional<PythonWheelDetails> extracted **from** public **findWheel**(library String, version String, pythonVersion PythonVersion) : Optional<File> in class com.linkedin.gradle.python.wheel.**WheelCache**

**Description**

Within the above mentioned refactoring, the reported statement mapping is as follows:

- List<File> collect=Arrays.stream(files).filter(file -> pythonAbi.stream().anyMatch(it -> file.getName().contains(it))).filter(file -> platformTagList.stream().anyMatch(it -> file.getName().endsWith(it))).collect(Collectors.toList());

**Mapped with:**

- Matcher matcher=wheelPattern.matcher(file.getName());

This mapping, which is the main mapping within this refactoring, does not make sense. If we consider this mapping as a wrong one, the Extract Method refactoring itself would be wrong. Furthermore, from the invocation of the reported Extract Method, we can further make sure that this refactoring is invalid.

**Comment by tsantalis** [comment]
@pedramnoori 
`file.getName()` is matched between the two statements.
The Extract Method seems valid given the other two statements matched.

![Screenshot from 2023-05-20 20-04-00](https://github.com/tsantalis/RefactoringMiner/assets/1483516/97036224-8e6b-4e37-9837-bda3210ca792)

**Comment by tsantalis** [comment]
@pedramnoori 
`wheelMatches()` also seems to be an extracted method, which is not detected.
Both cases are rather challenging, as there are extensive changes in the code.
I think both extracted methods are non-pure.
