### ISSUE TITLE
Wrong reported Rename Method and statement mapping

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#474]
**Problem**

Invalid reported Rename Method and one mapping inaccuracy within an Extract Method

**Commit**

https://github.com/antlr/intellij-plugin-v4/commit/76ba9bd26316f0d8fbd213df8e2f32e1ca6957ab

**Target refactorings**

- (Wrong Rename Method): Rename Method public **releaseEditors()** : void renamed to public **setEditor**(editor Editor) : void in class org.antlr.intellij.plugin.preview.**PreviewState**   

- (Extract Method with a mapping inaccuracy): Extract Method public **releaseEditor()** : void extracted **from** public **releaseEditors()** : void in class org.antlr.intellij.plugin.preview.**PreviewState**

**Description**

From the statements involved in the aforementioned Rename Method refactoring, we can safely say that this Rename Method is wrong. Furthermore, the statement mapping within this invalid Rename Method causes one **non-mapped leave** within the aforementioned Extract Method:

- `editor=null;` Line **54**, child version

Instead, this statement should be mapped with `editor = null;` Line **78**, parent version.

**Comment by tsantalis** [comment]
![Screenshot from 2023-05-21 21-02-25](https://github.com/tsantalis/RefactoringMiner/assets/1483516/d33babd2-5e7b-4d2c-ae65-69e62881216c)
