### ISSUE TITLE
Replacement inaccuracy (inconsistency)

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#481]
**Problem**

Replacement inaccuracy within a Move Method refactoring

**Commit**

https://github.com/liquibase/liquibase/commit/48cde78cda7948b79d109f128c34c11f8b9ff9bd

**Involved refactorings**

**1-** Move Method public **getProperty**(propertyName String) : ContextProperty from class liquibase.context.**Context** to public getProperty(propertyName String) : ConfigurationProperty from class liquibase.configuration.**AbstractConfiguration**

**2-** Move Method public **getValue**(propertyName String, returnType Class<T>) : T from class liquibase.context.**Context** to public getValue(propertyName String, returnType Class<T>) : T from class liquibase.configuration.**AbstractConfiguration**

**3-** Move Method protected **init**(valueContainers ContextValueContainer...) : void from class liquibase.context.**Context** to protected init(valueContainers ConfigurationProvider...) : void from class liquibase.configuration.**AbstractConfiguration**

**Description**

There are three similar statement mapping (exact the same change happened within those) within the three aforementioned Move Method refactorings. The replacement reported for matching these mappings are not consistent (is not accurate for the last refactoring)

The first two screenshots show the correct reported replacement (for the first two refactorings), and the last one contains the wrong reported replacement:

<img width="707" alt="Screen Shot 2023-06-01 at 11 49 34 AM" src="https://github.com/tsantalis/RefactoringMiner/assets/37044356/dac1f9f5-89f9-414f-8edf-c42fe0d6917e">

-------------------------------------------------------------------------------------------------------------------------

<img width="724" alt="Screen Shot 2023-06-01 at 11 50 21 AM" src="https://github.com/tsantalis/RefactoringMiner/assets/37044356/5a3d1351-cc30-4e26-9729-a12de11619b6">

-------------------------------------------------------------------------------------------------------------------------

<img width="779" alt="Screen Shot 2023-06-01 at 11 51 16 AM" src="https://github.com/tsantalis/RefactoringMiner/assets/37044356/e25f7971-10d6-451b-8d86-ed1c5ab2d34f">

**Comment by tsantalis** [comment]
Related to #484
Fixed in commit https://github.com/tsantalis/RefactoringMiner/commit/a791ab588fa8d938ca442526741ee9bd2a4ccf83
