### ISSUE TITLE
Missing Move and Rename Attribute refactoring

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#483]
**Problem**

Missing -Move and Rename Attribute- refactoring

**Commit**

https://github.com/antlr/intellij-plugin-v4/commit/5e3f0034618d73f7873da654fde245e9a5365967

**Expected (missing) refactoring**

The `editorConsole` attribute from [PreviewPanel.java](https://github.com/antlr/intellij-plugin-v4/commit/5e3f0034618d73f7873da654fde245e9a5365967#diff-9fe1729f1da3fe67b6be965460c40c4cf1b53450dd73f70277053c4351a305c0) has been renamed to `errorConsole` and moved to [InputPanel.java ](https://github.com/antlr/intellij-plugin-v4/commit/5e3f0034618d73f7873da654fde245e9a5365967#diff-59e281191b7ef0adad499bdd2eb20e8c0f36f1d60a4ef9417683faaf23768995) file. 

As references for supporting my argument, you can check the `clearErrorConsole` and `displayErrorInParseErrorConsole` methods.

**Comment by tsantalis** [comment]
Related to issue #498
Fixed by commit https://github.com/tsantalis/RefactoringMiner/commit/22eec0ad5b22ebec2e83da927170747937e71719
