### ISSUE TITLE
Move and rename class

### ISSUE THREAD

**Issue by feifeiniu-se** [tsantalis/RefactoringMiner#488]
https://github.com/apache/commons-bcel/commit/7ca3d8ec6278548833e5ce6d41ae2040b1d41f7a
Hi, I wonder if there is a real "Move and Rename Class" refactoring, just cause class InnerClass and ElementNameValuePairGen look like each other, but is there move and rename happend?

**Comment by feifeiniu-se** [comment]
And once you say ElementNameValuePairGen is moved and renamed from class InnerClass, then you will also detect Change Class Access Modifier. But if it's not, then the second refactoring shouldn't exist.

**Comment by tsantalis** [comment]
@feifeiniu-se 

Thank you for reporting this issue.
Both classes are empty (no methods and no attributes).
So, it is very risky to match them.
I will fix the issue asap.

**Comment by tsantalis** [comment]
@feifeiniu-se 

The only refactorings detected after the fix are:
Extract Superclass org.apache.bcel.AbstractTestCase from class org.apache.bcel.AbstractCounterVisitorTestCase
Add Class Modifier abstract in class org.apache.bcel.classfile.ElementValue
