### ISSUE TITLE
Wrong Move and Inline refactoring

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#491]
**Problem**

Wrong reported Move and Inline Method refactoring

**Commit**

https://github.com/mixpanel/mixpanel-android/commit/ea7583935e9bfaeaa9edcf1ca27ce64b5c8e3eae#diff-c3f2b011f16276a661954cb03b75d15014288443e570342832bea933b3fe69a8

**Target Refactoring**

**Move And Inline** Method public **flush()** : void moved from class com.mixpanel.android.mpmetrics.**MPMetrics**.**PeopleImpl** to class com.mixpanel.android.mpmetrics.**MPMetrics** & inlined to public **flush()** : void

**Description**

Based on the manual validation I did for this specific refactoring, the flush() method in the parent version has been simply moved to the flush() method in the child version.

The flushAll() method, which is the targetOperationBeforeInline according to the RefactoringMiner, has been removed within this commit.

**Comment by tsantalis** [comment]
**BEFORE** Refactoring
`flushAll()` method calls `mPeople.flush();`

```java
public void flushAll() {
        if (MPConfig.DEBUG) Log.d(LOGTAG, "flushAll");
        flushEvents();
        mPeople.flush();
}
```

```java
private class PeopleImpl implements People {
       @Override
        public void flush() {
            if (MPConfig.DEBUG) Log.d(LOGTAG, "People.flush");
            mMessages.submitPeople();
        }
}
```

**AFTER** Refactoring
`flushAll()` method is renamed to `flush()` and `flushEvents()` is inlined to `flush()`
```java
public void flush() {
        if (MPConfig.DEBUG) Log.d(LOGTAG, "flushEvents");

        mMessages.submitEvents();
        mMessages.submitPeople();
}
```

The statement `mMessages.submitPeople();`
can only come from Move and Inline Method `flush()` from class `com.mixpanel.android.mpmetrics.MPMetrics.PeopleImpl`
Therefore, the reported refactoring is correct.
