### ISSUE TITLE
Missed the mapping for method when abstract keyword removed 

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#494]
https://github.com/JetBrains/MPS/commit/61b5decd4a4e5e6bbdea99eb76f136ca10915b73

**Problem**: The abstract method became concrete but it is not reported.

```  protected abstract void doInsertNode(SNode nodeToInsert, SNode anchorNode, boolean insertBefore);``` 
-> ```  protected void doInsertNode(SNode nodeToInsert, SNode anchorNode, boolean insertBefore) ```

<img width="1438" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/9471f8e9-5c7e-44a2-b30e-46fb42ce83ec">

<img width="1078" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/e6eda615-9305-463e-b59d-b4c507a05397">

**Comment by tsantalis** [comment]
@pouryafard75 
![Screenshot from 2023-06-24 17-50-54](https://github.com/tsantalis/RefactoringMiner/assets/1483516/fe9e5242-5e29-4882-8a57-2fb0d1a44ea6)
