### ISSUE TITLE
Missing Move and Rename Attribute refactoring

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#498]
**Problem**

Missing Move and Rename Attribute refactoring happened within an Extract Superclass refactoring

**Commit**

https://github.com/openMF/android-client/commit/4a66dec4cab77fcb68593b31dc8416d87ee85c21

**Refactorings**

- Extract Superclass Refactoring (**reported by RMiner**): 
**Extract Superclass** com.mifos.mifosxdroid.core.**MifosBaseFragment** from classes [com.mifos.mifosxdroid.online.LoanRepaymentFragment, com.mifos.mifosxdroid.online.ClientDetailsFragment, com.mifos.mifosxdroid.online.SavingsAccountSummaryFragment, com.mifos.mifosxdroid.online.GenerateCollectionSheetFragment, com.mifos.mifosxdroid.online.SavingsAccountTransactionFragment, com.mifos.mifosxdroid.online.ClientIdentifiersFragment, com.mifos.mifosxdroid.fragments.CenterListFragment, com.mifos.mifosxdroid.online.CenterListFragment, com.mifos.mifosxdroid.fragments.GroupFragment, com.mifos.mifosxdroid.online.LoanTransactionsFragment, com.mifos.mifosxdroid.online.GroupListFragment, com.mifos.mifosxdroid.fragments.LoanFragment, com.mifos.mifosxdroid.online.DataTableDataFragment, com.mifos.mifosxdroid.online.ClientSearchFragment, com.mifos.mifosxdroid.online.ClientListFragment, com.mifos.mifosxdroid.fragments.ClientFragment, com.mifos.mifosxdroid.online.DocumentListFragment, com.mifos.mifosxdroid.online.LoanRepaymentScheduleFragment, com.mifos.mifosxdroid.online.LoanAccountSummaryFragment, com.mifos.mifosxdroid.online.CollectionSheetFragment]

- Missing Move and Rename Attribute Refactoring (**has not been reported by RMiner**):

Attribute `InputMethodManager inputMethodManager` from [ClientSearchFragment.java](https://github.com/openMF/android-client/commit/4a66dec4cab77fcb68593b31dc8416d87ee85c21#diff-39ba741c86abd9cb260b207f372cca346f21e4a675fb0903356b294c0d1b840a) has been moved to `private InputMethodManager inputManager` in [MifosBaseFragment.java](https://github.com/openMF/android-client/commit/4a66dec4cab77fcb68593b31dc8416d87ee85c21#diff-843551aaa6c03c76d091ed1189d7c50d2146f0d61c1e2e5f232a98579ba97475) 

**Description**

Based on the manual validation I did on this commit, the aforementioned Move and Rename Attribute refactoring is missing. As one reference, within the `public void onCreate(Bundle savedInstanceState)` **Pull Up Method refactoring**, this attribute has been used. Reporting this refactoring will help PurityChecker to report the above mentioned Pull Up Method as a pure case.

**Comment by tsantalis** [comment]
Newly reported refactorings:

`Change Attribute Access Modifier`	package to private in attribute private inputManager : InputMethodManager from class com.mifos.mifosxdroid.core.MifosBaseFragment

`Move And Rename Attribute`	package inputMethodManager : InputMethodManager renamed to private inputManager : InputMethodManager and moved from class com.mifos.mifosxdroid.online.ClientSearchFragment to class com.mifos.mifosxdroid.core.MifosBaseFragment
