### ISSUE TITLE
Out of memory error while computing longest common substring

### ISSUE THREAD

**Issue by dharanikumarp** [tsantalis/RefactoringMiner#5]
When executed on https://github.com/google/guava.git, the RefactoringMiner fails with an out of memory error while computing the common substring.

Observed the similar error while analysing the project https://github.com/stanfordnlp/CoreNLP.git

The RefactoringMiner is modified to analyse only the extract method refactoring.

[Google_Guava_OOM_Error.txt](https://github.com/tsantalis/RefactoringMiner/files/401999/Google_Guava_OOM_Error.txt)

**Comment by tsantalis** [comment]
Longer common sub-sequence algorithm is no longer used.
