### ISSUE TITLE
Empty SubExpressionMappings for the AssertThrowsRefactroing 

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#500]
**Commit:** https://github.com/pouryafard75/TestCases/commit/562c4447a566170ac28872a88b323669a82db5c9
**Problem:** SubExpressionMappings for the AssertThrowsRefactroing is empty.
<img width="933" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/8bdf9420-7d35-4e7d-95a6-86ff7bff1f8a">

Based on my experiments, the problem occurred after https://github.com/tsantalis/RefactoringMiner/commit/8a8bfb6 

**After** the problematic commit:
<img width="1412" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/6cb8178f-937b-4b2f-955c-5ff5c6d27363">

**Before** the problematic commit:
<img width="1437" alt="Screenshot 2023-07-13 at 8 47 44 PM" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/0c45bd94-bf99-4ae9-b096-46dd5cf4687a">
Notice the difference in ```CorruptRecordException.class```

**Comment by tsantalis** [comment]
@pouryafard75 

![Screenshot from 2023-07-24 20-58-11](https://github.com/tsantalis/RefactoringMiner/assets/1483516/7c4b45c4-ca20-40f7-a79a-dada348ea474)
