### ISSUE TITLE
Wrong merge parameter

### ISSUE THREAD

**Issue by feifeiniu-se** [tsantalis/RefactoringMiner#501]
https://github.com/apache/ant-ivy/commit/23e7c3b44ddb18eecaed97ef68aa26220a085a37, in this commit, refactoringminer identified "Merge Parameter [rootModuleConf : String, resolved : Collection] to evictionData : EvictionData in method public markEvicted(evictionData EvictionData) : void from class fr.jayasoft.ivy.IvyNode".
If you look into the source code, you will see there is no merge parameter.

**Comment by tsantalis** [comment]
@feifeiniu-se 

The reported refactoring is correct.

First, we have an Extract Method refactoring, as `public void markEvicted(EvictionData evictionData)` is extracted from `public void markEvicted(String rootModuleConf, IvyNode node, ConflictManager conflictManager, Collection resolved)`

The four parameters of the original method are "merged" into object `evictionData`
`EvictionData evictionData = new EvictionData(rootModuleConf, node, conflictManager, resolved);`
which is then passed to the extracted method.

In the extracted method, we have the following consistent replacements
`resolved` -> `evictionData.getSelected()`
`rootModuleConf` -> `evictionData.getRootModuleConf()`

which show that the original variables are now accessed through getter calls over the `evictionData` object.
This is a typical Introduce Parameter Object refactoring, which is done to eliminate Long Parameter List code smell.

RefactoringMiner reports this case as `Merge Parameter` in the extracted method,
as the original parameters have been replaced with `evictionData` in the extracted method.

RefactoringMiner has the ability to report nested refactorings, i.e., refactorings happening on top of other refactorings, e.g., Merge Parameter over Extract Method refactoring in this case.
