### ISSUE TITLE
Wrong parameterize variable

### ISSUE THREAD

**Issue by feifeiniu-se** [tsantalis/RefactoringMiner#502]
In commit, https://github.com/apache/ant-ivy/commit/64d6303154b1c85181c686d0a6e7c0437e5da770, I don't think there exists "Parameterize Variable fos : FileOutputStream to outStream : OutputStream in method public update(ivy Ivy, inStream InputStream, outStream OutputStream, resolvedRevisions Map, status String, revision String, pubdate Date, ns Namespace, replaceInclude boolean) : void from class fr.jayasoft.ivy.xml.XmlModuleDescriptorUpdater", since the original method declaration wasn't changed at all.

**Comment by tsantalis** [comment]
@feifeiniu-se 

Similar to #501 we have an Extract Method refactoring
`update(final Ivy ivy, InputStream inStream, OutputStream outStream, final Map resolvedRevisions, final String status, 
            final String revision, final Date pubdate, final Namespace ns, final boolean replaceInclude) `
extracted from
`update(final Ivy ivy, URL srcURL, File destFile, final Map resolvedRevisions, final String status, 
final String revision, final Date pubdate, final Namespace ns, final boolean replaceInclude)`

In the extracted method the local variable `fos` becomes the parameter `outStream`
as shown from the call to the extracted method
`update(ivy, in, fos, resolvedRevisions, status, revision, pubdate, ns, replaceInclude);`

So, a local variable in the original method becomes a parameter in the extracted method and thus RefactoringMiner reports a Parameterize Variable refactoring.

If you want to ignore such nested refactorings, you can call method `isInsideExtractedOrInlinedMethod()` on variable related refactorings. If this method returns `true`, then the corresponding refactorings is applied on top of an Extract or Inline Method refactoring.
