### ISSUE TITLE
Extract class rightSideLocation

### ISSUE THREAD

**Issue by feifeiniu-se** [tsantalis/RefactoringMiner#503]
https://github.com/apache/ant-ivy/commit/da7350551914ccbc9c1c652f979faf9a48d6012a, there is "Extract Class org.apache.ivy.plugins.report.XmlReportWriter from class org.apache.ivy.plugins.report.XmlReportOutputter" identified. But the rightSideLocalizations include "extracted method declaration", whose localization is still the old file. According to my understanding, these localization should be the new file path where the extracted method exists after commit, right?

**Comment by tsantalis** [comment]
@feifeiniu-se 

This is the json for this refactoring.
All rightSideLocations for the extracted method have `src/java/org/apache/ivy/plugins/report/XmlReportWriter.java' as filePath, which is the extracted class.
I don't see something wrong.

{
	"type": "Extract Class",
	"description": "Extract Class org.apache.ivy.plugins.report.XmlReportWriter from class org.apache.ivy.plugins.report.XmlReportOutputter",
	"leftSideLocations": [{
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportOutputter.java",
		"startLine": 52,
		"endLine": 309,
		"startColumn": 0,
		"endColumn": 2,
		"codeElementType": "TYPE_DECLARATION",
		"description": "original type declaration",
		"codeElement": "org.apache.ivy.plugins.report.XmlReportOutputter"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportOutputter.java",
		"startLine": 98,
		"endLine": 100,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "original method declaration",
		"codeElement": "public output(report ConfigurationResolveReport, stream OutputStream) : void"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportOutputter.java",
		"startLine": 102,
		"endLine": 147,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "original method declaration",
		"codeElement": "public output(report ConfigurationResolveReport, confs String[], stream OutputStream) : void"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportOutputter.java",
		"startLine": 149,
		"endLine": 297,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "original method declaration",
		"codeElement": "private ouputRevision(report ConfigurationResolveReport, out PrintWriter, dependencies List, dep IvyNode) : void"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportOutputter.java",
		"startLine": 299,
		"endLine": 308,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "original method declaration",
		"codeElement": "private toString(strs String[]) : String"
}],
	"rightSideLocations": [{
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportOutputter.java",
		"startLine": 31,
		"endLine": 74,
		"startColumn": 0,
		"endColumn": 2,
		"codeElementType": "TYPE_DECLARATION",
		"description": "type declaration after extraction",
		"codeElement": "org.apache.ivy.plugins.report.XmlReportOutputter"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportWriter.java",
		"startLine": 44,
		"endLine": 260,
		"startColumn": 0,
		"endColumn": 2,
		"codeElementType": "TYPE_DECLARATION",
		"description": "extracted type declaration",
		"codeElement": "org.apache.ivy.plugins.report.XmlReportWriter"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportWriter.java",
		"startLine": 49,
		"endLine": 51,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "extracted method declaration",
		"codeElement": "public output(report ConfigurationResolveReport, stream OutputStream) : void"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportWriter.java",
		"startLine": 53,
		"endLine": 98,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "extracted method declaration",
		"codeElement": "public output(report ConfigurationResolveReport, confs String[], stream OutputStream) : void"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportWriter.java",
		"startLine": 100,
		"endLine": 248,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "extracted method declaration",
		"codeElement": "private ouputRevision(report ConfigurationResolveReport, out PrintWriter, dependencies List, dep IvyNode) : void"
}, {
		"filePath": "src/java/org/apache/ivy/plugins/report/XmlReportWriter.java",
		"startLine": 250,
		"endLine": 259,
		"startColumn": 5,
		"endColumn": 6,
		"codeElementType": "METHOD_DECLARATION",
		"description": "extracted method declaration",
		"codeElement": "private toString(strs String[]) : String"
}]
}
