### ISSUE TITLE
Updated Interface method not matched inside the anonymous class

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#508]
**Commit**: https://github.com/luontola/retrolambda/commit/46b0d84de9c309bca48a99e572e6611693ed5236
**File**:[Retrolambda.java](https://github.com/luontola/retrolambda/commit/46b0d84de9c309bca48a99e572e6611693ed5236#diff-5b42ddf3b07fc1249495bc04afe49f172d8494fd5d9347c988fe6e33990100f1)
**Problem**: `visit` -> `visitClass`
<img width="1774" alt="image (1)" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/12322f93-b2e1-4578-86f0-4c61e7d3524c">

**Comment by tsantalis** [comment]
@pouryafard75 fixed

![Screenshot from 2023-08-20 14-03-23](https://github.com/tsantalis/RefactoringMiner/assets/1483516/4b1ecee0-5202-44ad-8c01-3da243e0ba5c)
