### ISSUE TITLE
Incorrect Extract Variable from the assginment

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#510]
Commit: https://github.com/clojure/clojure/commit/309c03055b06525c275b278542c881019424760e
File: [Compiler.java](https://github.com/clojure/clojure/commit/309c03055b06525c275b278542c881019424760e#diff-acddf4ef15ed09e1bfb6c1c3efc03396bcc49fcd223c395b11f6eb765e52f22c)
**Problem**: Unnecessary Extract Variable Refactoring reported
**Note**: When we detect the extract variable refactoring from the assignment, the references must appear after the assignment

<img width="1436" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/5a113777-002f-4d71-b166-cc09a864bcea">
<img width="1147" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/c6ea96cf-13d8-49f8-822b-f69f5d801363">

**Comment by tsantalis** [comment]
@pouryafard75 
Extract Variable is no longer detected, but I think `getReturnType()` is matched during post-processing.
As we discussed, only complete statements should be matched, not sub-expressions.

![Screenshot from 2023-08-20 07-42-24](https://github.com/tsantalis/RefactoringMiner/assets/1483516/da4223e4-496d-4418-92d4-aa6d7402a0d4)
