### ISSUE TITLE
Missed one of two ExtractMethod Refactoring while the call sites have different scopes

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#511]
Commit: https://github.com/Activiti/Activiti/commit/a70ca1d9ad2ea07b19c5e1f9540c809d7a12d3fb
File: [DbSqlSession.java](https://github.com/Activiti/Activiti/commit/a70ca1d9ad2ea07b19c5e1f9540c809d7a12d3fb#diff-81d494068ed340f1018686c9d4828297e795beca68c69f698fdff9a36675a50b)
Problem: 1 of 2 Extract Method refactorings for `flushPersistentObjects` detected
<img width="1431" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/67ee03a5-3d6a-409e-9cd6-7e3c62a3765b">

**Comment by tsantalis** [comment]
@pouryafard75 
The missing Extract Method is detected now.
I will check if it is possible to have a Split Conditional for the first clone.

![Screenshot from 2023-08-16 18-26-17](https://github.com/tsantalis/RefactoringMiner/assets/1483516/78bc1832-9990-4f8d-a82e-7ec367e7af89)
