### ISSUE TITLE
Inaccurate mapping for the ```return``` statements

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#513]
Commit: https://github.com/VoltDB/voltdb/commit/cfc54e8afa7ee7d5376525a84559e90b21487ccf
File: [KafkaStreamImporter.java](https://github.com/VoltDB/voltdb/commit/cfc54e8afa7ee7d5376525a84559e90b21487ccf#diff-0ce452297026d80fe3416e0b6fa4dd440da74ed037d297ad68522049d0e97196)
Problem:  `return` statements in the `getLastOffset()` method looks problematic
<img width="1424" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/ecb1413a-d2bb-46f6-9e5c-eb75b0ba1949">

**Comment by tsantalis** [comment]
@pouryafard75 
I fixed the `return` statement mappings in `getLastOffset()`
