### ISSUE TITLE
Incorrect mapping within Identical Methods

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#517]
Commit: https://github.com/apache/camel/commit/ab1d1dd78fe53edb50c4ede447e4ac5a55ee2ac9
File: [JmsMessageHelper.java](https://github.com/apache/camel/commit/ab1d1dd78fe53edb50c4ede447e4ac5a55ee2ac9#diff-e9f1a6d061475bcf825301b8a3f130cc268735bfde73c0353ea4131645b9d61f)
Problem: Method `setJmsMessageHeaders` doesn't contain any changes but the mappings seem to be incorrect for the if-statement.
<img width="1421" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/28820932/6be48cfd-4b77-414d-b065-216aaa642412">

**Comment by tsantalis** [comment]
@pouryafard75 
This happened  because L246-257 and R261-272 have no statements in their body.
I will have to use the similarity in their comments to match them.

**Comment by tsantalis** [comment]
@pouryafard75 
I fixed it and I am running the tests.
But I noticed a wrong mapping in Javadoc. This must be matched on your side.

![Screenshot from 2023-08-09 21-32-18](https://github.com/tsantalis/RefactoringMiner/assets/1483516/453601da-4019-404a-887e-fb69333cdb3c)
