### ISSUE TITLE
Wrong Move Code Refactoring

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#522]
[Druid-da32e1a](https://github.com/apache/druid/commit/da32e1ae534a99c29ff60c5535f2d4cb0e344a73)
---

<img width="1075" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/11022419/834f1208-e8d7-43ad-82b6-586df90a12b2">

[Literal zero initialization of handoffConditionTimeout at line 259](https://github.com/apache/druid/commit/da32e1ae534a99c29ff60c5535f2d4cb0e344a73#diff-adf7a2fa3a63d2d9227c4a59932834cf819a7848dee39a0a2669a23b316a508bL259) is unmapped and [the same literal zero initialization of handoffConditionTimeout that moved to line 272](https://github.com/apache/druid/commit/da32e1ae534a99c29ff60c5535f2d4cb0e344a73#diff-adf7a2fa3a63d2d9227c4a59932834cf819a7848dee39a0a2669a23b316a508bR272) is mapped with [literal zero initialization of i at line 1309](https://github.com/apache/druid/commit/da32e1ae534a99c29ff60c5535f2d4cb0e344a73#diff-adf7a2fa3a63d2d9227c4a59932834cf819a7848dee39a0a2669a23b316a508bL1309)

That leads RefactoringMiner to mistakenly report a Move Code Refactoring as seen in the following screenshot:

<img width="1275" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/11022419/22ca7c63-9afe-4a00-bfdc-6577232a411e">

[Mapping HTML Druid-da32e1a.zip](https://github.com/victorgveloso/RefactoringMiner/files/12424151/RefactoringMiner-Druid-da32e1a.zip)

**Comment by tsantalis** [comment]
@victorgveloso 
Thanks for finding this issue. The fix applies a statement mapping optimization to discard the incorrect multi-mappings.

cc @pouryafard75 
After the fix only 4 Move Code refactorings are detected, which are correct.

Move Code from public tearDown() : void to public tearDownTest() : void in class io.druid.indexing.kafka.supervisor.KafkaSupervisorTest
Move Code from public setUp() : void to public setupClass() : void in class io.druid.indexing.kafka.supervisor.KafkaSupervisorTest

Move Code from public setUp() : void to public setupTest() : void in class io.druid.indexing.kafka.KafkaIndexTaskTest
Move Code from public tearDown() : void to public tearDownTest() : void in class io.druid.indexing.kafka.KafkaIndexTaskTest
