### ISSUE TITLE
Unrecognizable RenameAttributeRefactoring

### ISSUE THREAD

**Issue by Laughh** [tsantalis/RefactoringMiner#529]
Hi! I'm using RMiner to detect refactorings, but in my own test, I found that some rename refactorings of attribute cannot be recognized. 

 The left source code is previous version, and the right is the next one.

<img width="1185" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/88264468/bcfe93db-9a83-4c00-88c4-233d15791a20">

The results of output is following:
```
project.C --- project.C
Common Attributes
[]
Added Attributes
[public iList : List<Integer>]
Removed Attributes
[public list : List<Integer>]
```

**Comment by tsantalis** [comment]
Hi @Laughh 
RefactoringMiner detects Rename Variable/Attribute refactoring based on changes on the references of the variables.

If you add in your example some code in `test()` simply referencing the attribute, e.g., 
`iList.add(1);` -> `list.add(1);`
the refactoring will be detected.

Note that the references should change accordingly `iList` -> `list` for the refactoring to be detected.
RefactoringMiner checks that all references have been updated consistently to report the refactoring.
If some of the references are not updated consistently (e.g., `iList` -> `iList2`), then there is some ambiguity and no refactoring is reported.

**Comment by Laughh** [comment]
> Hi @Laughh RefactoringMiner detects Rename Variable/Attribute refactoring based on changes on the references of the variables.
> 
> If you add in your example some code in `test()` simply referencing the attribute, e.g., `iList.add(1);` -> `list.add(1);` the refactoring will be detected.
> 
> Note that the references should change accordingly `iList` -> `list` for the refactoring to be detected. RefactoringMiner checks that all references have been updated consistently to report the refactoring. If some of the references are not updated consistently (e.g., `iList` -> `iList2`), then there is some ambiguity and no refactoring is reported.
> 
> The consistency check is absolutely necessary, because if in your example you had more attributes, then there is no way to figure out the attribute mappings, without having references to the attributes in the code.

Thanks for you reply. BTW, is there any API to get reference for each attribute?

**Comment by tsantalis** [comment]
@Laughh 

The way to collect the references to a renamed attribute is as follows:
```java
RenameAttributeRefactoring ref;
for(CandidateAttributeRefactoring candidate : ref.getAttributeRenames()) {
    for(AbstractCodeMapping mapping : candidate.getReferences()) {
    }
}
```
Each mapping is a pair of statements referencing the renamed attribute.
Note that attribute references could also be located in different files than the file the attribute is declared in (e.g., public attributes).
