### ISSUE TITLE
How can I detect if commit + class combination has just refactorings

### ISSUE THREAD

**Issue by oguzhantortop** [tsantalis/RefactoringMiner#530]
Hi,
I am trying to calculate the effects of Refactorings on class metrics. However, I think that in commits there are not only refactorings but also there are some additions like bug fixings, new features etc. So I think I need to calculate metrics of classes of commits with only refactorings. I need to achieve this programmatically. Any ideas about how I can do that or basically is it possible?

**Comment by tsantalis** [comment]
Hi @oguzhantortop 

Your intuition is correct. Indeed, the refactorings reported by RefactoringMiner may have overlapping changes, such as bug fixes and new features.

You can use the following fork of RefactoringMiner
https://github.com/pedramnoori/RefactoringMiner
that implements `purity checker`, a tool that examines whether a refactoring is pure or not.
@pedramnoori can help you with any questions you may have.
