### ISSUE TITLE
Parameterize Test refactoring improvement

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/RefactoringMiner#534]
https://github.com/apache/camel/commit/b57b72d0e85f2340cb2d55be44d2175c0caa7cc1

This commit includes 9 tests parameterized to 3 tests,
but RefactoringMiner reports 9 to 1.

**Comment by victorgveloso** [comment]
https://github.com/apache/camel/commit/b57b72d0e85f2340cb2d55be44d2175c0caa7cc1 

Nine out of the nine Parameterize Test are detected. However, they are incorrectly reported as a nine-to-one method refactoring. That is, RMiner interprets it as nine methods merged into testLondonWithFileStream only.
<img width="1161" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/11022419/636f52ac-9b1c-4292-b770-87532962ff48">

In practice, they should be three three-to-one refactorings as the following table describes:

<table>
<tr>
<th>Parameter\Method</th>
<th>testLondonWithFileStream</th>
<th>testTampaWithFileStream</th>
<th>testLondonWithStringSourceAsObject</th>
<tr>
<th>
direct:object
</th>
<td>
testLondonWithFileStreamAsObject
</td>
<td>
testTampaWithFileStreamAsObject
</td>
<td>
testLondonWithStringSourceAsObject
</td>
</tr>
<tr>
<th>
direct:default
</th>
<td>
testLondonWithFileStreamAsDefault
</td>
<td>
testTampaWithFileStreamAsDefault
</td>
<td>
testLondonWithStringSourceAsDefault
</td>
</tr>
<tr>
<th>
direct:bytes
</th>
<td>
testLondonWithFileStreamAsBytes
</td>
<td>
testTampaWithFileStreamAsBytes
</td>
<td>
testLondonWithStringSourceAsBytes
</td>
</tr>
</tbody>
</table>

**Comment by tsantalis** [comment]
@victorgveloso @pouryafard75 
AST diff after the fix:

![Screenshot from 2023-10-28 05-16-54](https://github.com/tsantalis/RefactoringMiner/assets/1483516/4922b842-d389-4661-a593-e865f8b2a296)
![Screenshot from 2023-10-28 05-18-06](https://github.com/tsantalis/RefactoringMiner/assets/1483516/42bdbf11-49d8-4c52-b9bd-e0b49555deda)
![Screenshot from 2023-10-28 05-19-13](https://github.com/tsantalis/RefactoringMiner/assets/1483516/814cf3a3-7cf1-458b-b9bd-168ce7ade4f2)
