### ISSUE TITLE
Inline Attribute assigned in Setup (or Constructor)

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#538]
https://github.com/dropwizard/dropwizard/commit/9086577e29aba07058619a706701b6d07592aed9#diff-7db6549dedecb1a5b3e9d788f24fd61c11efaa7d7c0067a9630daabf952a0796L27

**Comment by victorgveloso** [comment]
In this same commit, Refactoring Miner missed a test method being merged into a parameterized test

<img width="1414" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/11022419/7e76d002-b51c-4dd1-90cf-e913e71726f4">

**Comment by tsantalis** [comment]
Diff after last commit:

![Screenshot from 2023-11-08 11-22-40](https://github.com/tsantalis/RefactoringMiner/assets/1483516/f1b8a6d1-43b0-4169-ba36-f76d5d95ccea)

**Comment by tsantalis** [comment]
![Screenshot from 2023-11-11 02-24-32](https://github.com/tsantalis/RefactoringMiner/assets/1483516/ef84d0da-290d-4f99-981f-7958644b1576)

**Comment by tsantalis** [comment]
After Inline Attribute detection:

![Screenshot from 2023-11-11 17-03-15](https://github.com/tsantalis/RefactoringMiner/assets/1483516/f5a87f3c-eff9-4fb8-8db1-1a1ec297191f)
