### ISSUE TITLE
Commit takes forever to be analyzed

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#539]
[06022b8fdc40e50eaac63758246353058e8cfa6d](https://github.com/apache/hadoop/commit/06022b8fdc40e50eaac63758246353058e8cfa6d)

**Comment by tsantalis** [comment]
The problem is in class
`hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/protocolPB/PBHelper.java`

**Comment by tsantalis** [comment]
@victorgveloso 
This commit takes less than 10 seconds to be process after the fix.
