### ISSUE TITLE
Classifier generate continous char sequence?

### ISSUE THREAD

**Issue by Laughh** [tsantalis/RefactoringMiner#557]
Hi! I'm using RMiner to do something, and in class `ExtendedOnlyRootsClassifier`, I have a question that each cluster generated by classifier is corresponding to a continous char sequence in the source code? And there is no overlap between cluser ? 

<img width="1403" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/88264468/cef578c2-e7de-44ff-a675-256cf0b1ccc2">
But in this picture, it seems that the actions of move and update are overlapped? I'm so confused, and it's important for me.

**Comment by tsantalis** [comment]
@Laughh 
It is possible to have a moved piece of code that part of it is modified too.
This is what the diff in the picture is showing.
There is one variable renamed `id` -> `srtId`
and one string literal updated.

I am not sure if I understood correctly your question. Please clarify.

**Comment by Laughh** [comment]
Yeah, that is exactly what I mean, so cluster generated by classifier is corresponding to a continous char sequence in the source code right, like update, delete and add ?

**Comment by tsantalis** [comment]
Yes, this is correct. The modified part is a sub-tree of the moved super-tree.
