### ISSUE TITLE
NPE Apache/Hive 48b201ee

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#570]
NPE thrown while analyzing https://github.com/apache/hive/commit/48b201ee163252b2127ce04fbf660df70312888a
```
168879310 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 48b201ee163252b2127ce04fbf660df70312888a
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
Caused by: java.lang.NullPointerException: null
```

**Comment by tsantalis** [comment]
@victorgveloso 
Unable to replicate. Commit processed without exception.

Refactorings at 48b201ee163252b2127ce04fbf660df70312888a
Move And Rename Method	public HiveHepPlannerContext(registry HiveRulesRegistry) from class org.apache.hadoop.hive.ql.optimizer.calcite.HiveHepPlannerContext to public HivePlannerContext(config HiveAlgorithmsConf, registry HiveRulesRegistry) from class org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Add Parameter	config : HiveAlgorithmsConf in method public HivePlannerContext(config HiveAlgorithmsConf, registry HiveRulesRegistry) from class org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Move Method	public unwrap(clazz Class<T>) : T from class org.apache.hadoop.hive.ql.optimizer.calcite.HiveHepPlannerContext to public unwrap(clazz Class<T>) : T from class org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Move Attribute	private registry : HiveRulesRegistry from class org.apache.hadoop.hive.ql.optimizer.calcite.HiveHepPlannerContext to private registry : HiveRulesRegistry from class org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Move And Rename Method	public HiveVolcanoPlannerContext(config HiveAlgorithmsConf) from class org.apache.hadoop.hive.ql.optimizer.calcite.HiveVolcanoPlannerContext to public HivePlannerContext(config HiveAlgorithmsConf, registry HiveRulesRegistry) from class org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Add Parameter	registry : HiveRulesRegistry in method public HivePlannerContext(config HiveAlgorithmsConf, registry HiveRulesRegistry) from class org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Move Method	public unwrap(clazz Class<T>) : T from class org.apache.hadoop.hive.ql.optimizer.calcite.HiveVolcanoPlannerContext to public unwrap(clazz Class<T>) : T from class org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Move Attribute	private config : HiveAlgorithmsConf from class org.apache.hadoop.hive.ql.optimizer.calcite.HiveVolcanoPlannerContext to private config : HiveAlgorithmsConf from class org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Merge Class	[org.apache.hadoop.hive.ql.optimizer.calcite.HiveHepPlannerContext, org.apache.hadoop.hive.ql.optimizer.calcite.HiveVolcanoPlannerContext] merged to org.apache.hadoop.hive.ql.optimizer.calcite.HivePlannerContext
Extract Method	public getPredsNotPushedAlready(predicatesToExclude Set<String>, inp RelNode, predsToPushDown List<RexNode>) : ImmutableList<RexNode> extracted from public getPredsNotPushedAlready(inp RelNode, predsToPushDown List<RexNode>) : ImmutableList<RexNode> in class org.apache.hadoop.hive.ql.optimizer.calcite.HiveCalciteUtil
Change Parameter Type	conf : HiveVolcanoPlannerContext to conf : HivePlannerContext in method public HiveVolcanoPlanner(conf HivePlannerContext) from class org.apache.hadoop.hive.ql.optimizer.calcite.cost.HiveVolcanoPlanner
Change Parameter Type	conf : HiveVolcanoPlannerContext to conf : HivePlannerContext in method public createPlanner(conf HivePlannerContext) : RelOptPlanner from class org.apache.hadoop.hive.ql.optimizer.calcite.cost.HiveVolcanoPlanner
Extract Variable	join : HiveJoin in method public copy(traitSet RelTraitSet, conditionExpr RexNode, left RelNode, right RelNode, joinType JoinRelType, semiJoinDone boolean) : HiveJoin from class org.apache.hadoop.hive.ql.optimizer.calcite.reloperators.HiveJoin
Extract Variable	semijoin : HiveSemiJoin in method public copy(traitSet RelTraitSet, condition RexNode, left RelNode, right RelNode, joinType JoinRelType, semiJoinDone boolean) : SemiJoin from class org.apache.hadoop.hive.ql.optimizer.calcite.reloperators.HiveSemiJoin
Add Method Annotation	@Override in method public implement(implementor Implementor) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.reloperators.HiveUnion
Inline Method	private createHiveFilterConjunctiveCondition(filterFactory FilterFactory, rexBuilder RexBuilder, input RelNode, conditions Collection<RexNode>) : RelNode inlined to public onMatch(call RelOptRuleCall) : void in class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Inline Method	private createHiveFilterConjunctiveCondition(filterFactory FilterFactory, rexBuilder RexBuilder, input RelNode, conditions Collection<RexNode>) : RelNode inlined to public onMatch(call RelOptRuleCall) : void in class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Remove Variable Modifier	final in variable newCondition : RexNode in method private createHiveFilterConjunctiveCondition(filterFactory FilterFactory, rexBuilder RexBuilder, input RelNode, conditions Collection<RexNode>) : RelNode from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Remove Variable Modifier	final in variable newCondition : RexNode in method private createHiveFilterConjunctiveCondition(filterFactory FilterFactory, rexBuilder RexBuilder, input RelNode, conditions Collection<RexNode>) : RelNode from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Rename Variable	newCondition : RexNode to newLeftPredicate : RexNode in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Rename Variable	newCondition : RexNode to newRightPredicate : RexNode in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Change Variable Type	newLeftConditions : Map<String,RexNode> to newLeftConditions : List<RexNode> in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Change Variable Type	newRightConditions : Map<String,RexNode> to newRightConditions : List<RexNode> in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Rename Variable	leftInput : RelNode to lChild : RelNode in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Rename Variable	rightInput : RelNode to rChild : RelNode in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Merge Variable	[leftInput : RelNode, rightInput : RelNode] to join : Join in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Change Parameter Type	filterFactory : FilterFactory to filterFactory : RelFactories.FilterFactory in method public HiveJoinAddNotNullRule(clazz Class<? extends Join>, filterFactory RelFactories.FilterFactory) from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Add Parameter	clazz : Class<? extends Join> in method public HiveJoinAddNotNullRule(clazz Class<? extends Join>, filterFactory RelFactories.FilterFactory) from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Change Variable Type	newConditions : Map<String,RexNode> to newConditions : List<RexNode> in method private getNotNullConditions(cluster RelOptCluster, rexBuilder RexBuilder, input RelNode, inputKeyPositions Set<Integer>, pushedPredicates Set<String>) : List<RexNode> from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Change Return Type	Map<String,RexNode> to List<RexNode> in method private getNotNullConditions(cluster RelOptCluster, rexBuilder RexBuilder, input RelNode, inputKeyPositions Set<Integer>, pushedPredicates Set<String>) : List<RexNode> from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Add Parameter	pushedPredicates : Set<String> in method private getNotNullConditions(cluster RelOptCluster, rexBuilder RexBuilder, input RelNode, inputKeyPositions Set<Integer>, pushedPredicates Set<String>) : List<RexNode> from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinAddNotNullRule
Change Attribute Type	filterFactory : RelFactories.FilterFactory to filterFactory : FilterFactory in class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinPushTransitivePredicatesRule
Extract Variable	newLeftPredicate : RexNode in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinPushTransitivePredicatesRule
Extract Variable	newRightPredicate : RexNode in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinPushTransitivePredicatesRule
Change Parameter Type	filterFactory : RelFactories.FilterFactory to filterFactory : FilterFactory in method public HiveJoinPushTransitivePredicatesRule(clazz Class<? extends Join>, filterFactory FilterFactory) from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinPushTransitivePredicatesRule
Rename Parameter	rn : RelNode to child : RelNode in method private getValidPreds(cluster RelOptCluster, child RelNode, predicatesToExclude Set<String>, rexs List<RexNode>, rType RelDataType) : ImmutableList<RexNode> from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinPushTransitivePredicatesRule
Add Parameter	predicatesToExclude : Set<String> in method private getValidPreds(cluster RelOptCluster, child RelNode, predicatesToExclude Set<String>, rexs List<RexNode>, rType RelDataType) : ImmutableList<RexNode> from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveJoinPushTransitivePredicatesRule
Extract Variable	newPredicate : RexNode in method public onMatch(call RelOptRuleCall) : void from class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HivePreFilteringRule
Rename Attribute	registry : SetMultimap<RelOptRule,RelNode> to registryVisited : SetMultimap<RelOptRule,RelNode> in class org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveRulesRegistry
Change Variable Type	confContext : HiveVolcanoPlannerContext to confContext : HivePlannerContext in method public apply(cluster RelOptCluster, relOptSchema RelOptSchema, rootSchema SchemaPlus) : RelNode from class org.apache.hadoop.hive.ql.parse.CalcitePlanner.CalcitePlannerAction
Change Variable Type	context : HiveHepPlannerContext to context : HivePlannerContext in method public testRuleFiredOnlyOnce() : void from class org.apache.hadoop.hive.ql.optimizer.calcite.TestCBORuleFiredOnlyOnce
