### ISSUE TITLE
StringIndexOutOfBounds swagger-api/swagger-codegen 3b780e

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#574]
Exception thrown while analyzing https://github.com/swagger-api/swagger-codegen/commit/3b780e30d81aeb8d9e6c4cdc172cde26c3d88ceb
```
48678463 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 3b780e30d81aeb8d9e6c4cdc172cde26c3d88ceb
java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: begin 69, end 66, length 82
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 69, end 66, length 82
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
	at java.base/java.lang.String.substring(String.java:2709)
	at gr.uom.java.xmi.decomposition.StringBasedHeuristics.commonConcat(StringBasedHeuristics.java:1516)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8454)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:451)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForOperationMoves(UMLModelDiff.java:3729)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForOperationMovesBetweenCommonClasses(UMLModelDiff.java:3477)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:2344)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:163)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.lambda$detect$3(GitHistoryRefactoringMinerImpl.java:760)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tsantalis** [comment]
@victorgveloso 
**FIXED**

Refactorings at 3b780e30d81aeb8d9e6c4cdc172cde26c3d88ceb
Move Source Folder	samples/client/petstore/java/default to samples/client/petstore/java/jersey1
Rename Variable	library : CliOption to libraryOption : CliOption in method public JavaClientCodegen() from class io.swagger.codegen.languages.JavaClientCodegen
Add Method Annotation	@SuppressWarnings("unchecked") in method public deserialize(response Response, returnType Type) : T from class io.swagger.client.ApiClient
Add Method Annotation	@SuppressWarnings("unchecked") in method public executeAsync(call Call, returnType Type, callback ApiCallback<T>) : void from class io.swagger.client.ApiClient
Add Method Annotation	@SuppressWarnings("unchecked") in method public deserialize(body String, returnType Type) : T from class io.swagger.client.JSON
Add Attribute Annotation	@SerializedName("map_property") in attribute private mapProperty : Map<String,String> from class io.swagger.client.model.AdditionalPropertiesClass
Remove Attribute Annotation	@JsonProperty("map_property") in attribute private mapProperty : Map<String,String> from class io.swagger.client.model.AdditionalPropertiesClass
Add Attribute Annotation	@SerializedName("map_of_map_property") in attribute private mapOfMapProperty : Map<String,Map<String,String>> from class io.swagger.client.model.AdditionalPropertiesClass
Remove Attribute Annotation	@JsonProperty("map_of_map_property") in attribute private mapOfMapProperty : Map<String,Map<String,String>> from class io.swagger.client.model.AdditionalPropertiesClass
Add Attribute Annotation	@SerializedName("className") in attribute private className : String from class io.swagger.client.model.Animal
Remove Attribute Annotation	@JsonProperty("className") in attribute private className : String from class io.swagger.client.model.Animal
Add Attribute Annotation	@SerializedName("color") in attribute private color : String from class io.swagger.client.model.Animal
Remove Attribute Annotation	@JsonProperty("color") in attribute private color : String from class io.swagger.client.model.Animal
Add Attribute Annotation	@SerializedName("ArrayArrayNumber") in attribute private arrayArrayNumber : List<List<BigDecimal>> from class io.swagger.client.model.ArrayOfArrayOfNumberOnly
Remove Attribute Annotation	@JsonProperty("ArrayArrayNumber") in attribute private arrayArrayNumber : List<List<BigDecimal>> from class io.swagger.client.model.ArrayOfArrayOfNumberOnly
Add Attribute Annotation	@SerializedName("ArrayNumber") in attribute private arrayNumber : List<BigDecimal> from class io.swagger.client.model.ArrayOfNumberOnly
Remove Attribute Annotation	@JsonProperty("ArrayNumber") in attribute private arrayNumber : List<BigDecimal> from class io.swagger.client.model.ArrayOfNumberOnly
Add Attribute Annotation	@SerializedName("array_of_string") in attribute private arrayOfString : List<String> from class io.swagger.client.model.ArrayTest
Remove Attribute Annotation	@JsonProperty("array_of_string") in attribute private arrayOfString : List<String> from class io.swagger.client.model.ArrayTest
Add Attribute Annotation	@SerializedName("array_array_of_integer") in attribute private arrayArrayOfInteger : List<List<Long>> from class io.swagger.client.model.ArrayTest
Remove Attribute Annotation	@JsonProperty("array_array_of_integer") in attribute private arrayArrayOfInteger : List<List<Long>> from class io.swagger.client.model.ArrayTest
Add Attribute Annotation	@SerializedName("array_array_of_model") in attribute private arrayArrayOfModel : List<List<ReadOnlyFirst>> from class io.swagger.client.model.ArrayTest
Remove Attribute Annotation	@JsonProperty("array_array_of_model") in attribute private arrayArrayOfModel : List<List<ReadOnlyFirst>> from class io.swagger.client.model.ArrayTest
Add Attribute Annotation	@SerializedName("className") in attribute private className : String from class io.swagger.client.model.Cat
Remove Attribute Annotation	@JsonProperty("className") in attribute private className : String from class io.swagger.client.model.Cat
Add Attribute Annotation	@SerializedName("color") in attribute private color : String from class io.swagger.client.model.Cat
Remove Attribute Annotation	@JsonProperty("color") in attribute private color : String from class io.swagger.client.model.Cat
Add Attribute Annotation	@SerializedName("declawed") in attribute private declawed : Boolean from class io.swagger.client.model.Cat
Remove Attribute Annotation	@JsonProperty("declawed") in attribute private declawed : Boolean from class io.swagger.client.model.Cat
Add Attribute Annotation	@SerializedName("id") in attribute private id : Long from class io.swagger.client.model.Category
Remove Attribute Annotation	@JsonProperty("id") in attribute private id : Long from class io.swagger.client.model.Category
Add Attribute Annotation	@SerializedName("name") in attribute private name : String from class io.swagger.client.model.Category
Remove Attribute Annotation	@JsonProperty("name") in attribute private name : String from class io.swagger.client.model.Category
Add Attribute Annotation	@SerializedName("className") in attribute private className : String from class io.swagger.client.model.Dog
Remove Attribute Annotation	@JsonProperty("className") in attribute private className : String from class io.swagger.client.model.Dog
Add Attribute Annotation	@SerializedName("color") in attribute private color : String from class io.swagger.client.model.Dog
Remove Attribute Annotation	@JsonProperty("color") in attribute private color : String from class io.swagger.client.model.Dog
Add Attribute Annotation	@SerializedName("breed") in attribute private breed : String from class io.swagger.client.model.Dog
Remove Attribute Annotation	@JsonProperty("breed") in attribute private breed : String from class io.swagger.client.model.Dog
Add Attribute Annotation	@SerializedName("_abc") in enum constant _ABC("_abc") from class io.swagger.client.model.EnumClass
Add Attribute Annotation	@SerializedName("-efg") in enum constant _EFG("-efg") from class io.swagger.client.model.EnumClass
Add Attribute Annotation	@SerializedName("(xyz)") in enum constant _XYZ_("(xyz)") from class io.swagger.client.model.EnumClass
Add Attribute Annotation	@SerializedName("enum_string") in attribute private enumString : EnumStringEnum from class io.swagger.client.model.EnumTest
Remove Attribute Annotation	@JsonProperty("enum_string") in attribute private enumString : EnumStringEnum from class io.swagger.client.model.EnumTest
Add Attribute Annotation	@SerializedName("enum_integer") in attribute private enumInteger : EnumIntegerEnum from class io.swagger.client.model.EnumTest
Remove Attribute Annotation	@JsonProperty("enum_integer") in attribute private enumInteger : EnumIntegerEnum from class io.swagger.client.model.EnumTest
Add Attribute Annotation	@SerializedName("enum_number") in attribute private enumNumber : EnumNumberEnum from class io.swagger.client.model.EnumTest
Remove Attribute Annotation	@JsonProperty("enum_number") in attribute private enumNumber : EnumNumberEnum from class io.swagger.client.model.EnumTest
Add Attribute Annotation	@SerializedName("integer") in attribute private integer : Integer from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("integer") in attribute private integer : Integer from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("int32") in attribute private int32 : Integer from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("int32") in attribute private int32 : Integer from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("int64") in attribute private int64 : Long from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("int64") in attribute private int64 : Long from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("number") in attribute private number : BigDecimal from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("number") in attribute private number : BigDecimal from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("float") in attribute private _float : Float from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("float") in attribute private _float : Float from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("double") in attribute private _double : Double from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("double") in attribute private _double : Double from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("string") in attribute private string : String from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("string") in attribute private string : String from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("byte") in attribute private _byte : byte[] from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("byte") in attribute private _byte : byte[] from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("binary") in attribute private binary : byte[] from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("binary") in attribute private binary : byte[] from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("date") in attribute private date : LocalDate from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("date") in attribute private date : LocalDate from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("dateTime") in attribute private dateTime : DateTime from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("dateTime") in attribute private dateTime : DateTime from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("uuid") in attribute private uuid : String from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("uuid") in attribute private uuid : String from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("password") in attribute private password : String from class io.swagger.client.model.FormatTest
Remove Attribute Annotation	@JsonProperty("password") in attribute private password : String from class io.swagger.client.model.FormatTest
Add Attribute Annotation	@SerializedName("bar") in attribute private bar : String from class io.swagger.client.model.HasOnlyReadOnly
Remove Attribute Annotation	@JsonProperty("bar") in attribute private bar : String from class io.swagger.client.model.HasOnlyReadOnly
Add Attribute Annotation	@SerializedName("foo") in attribute private foo : String from class io.swagger.client.model.HasOnlyReadOnly
Remove Attribute Annotation	@JsonProperty("foo") in attribute private foo : String from class io.swagger.client.model.HasOnlyReadOnly
Add Attribute Annotation	@SerializedName("map_map_of_string") in attribute private mapMapOfString : Map<String,Map<String,String>> from class io.swagger.client.model.MapTest
Remove Attribute Annotation	@JsonProperty("map_map_of_string") in attribute private mapMapOfString : Map<String,Map<String,String>> from class io.swagger.client.model.MapTest
Add Attribute Annotation	@SerializedName("map_of_enum_string") in attribute private mapOfEnumString : Map<String,InnerEnum> from class io.swagger.client.model.MapTest
Remove Attribute Annotation	@JsonProperty("map_of_enum_string") in attribute private mapOfEnumString : Map<String,InnerEnum> from class io.swagger.client.model.MapTest
Add Attribute Annotation	@SerializedName("uuid") in attribute private uuid : String from class io.swagger.client.model.MixedPropertiesAndAdditionalPropertiesClass
Remove Attribute Annotation	@JsonProperty("uuid") in attribute private uuid : String from class io.swagger.client.model.MixedPropertiesAndAdditionalPropertiesClass
Add Attribute Annotation	@SerializedName("dateTime") in attribute private dateTime : DateTime from class io.swagger.client.model.MixedPropertiesAndAdditionalPropertiesClass
Remove Attribute Annotation	@JsonProperty("dateTime") in attribute private dateTime : DateTime from class io.swagger.client.model.MixedPropertiesAndAdditionalPropertiesClass
Add Attribute Annotation	@SerializedName("map") in attribute private map : Map<String,Animal> from class io.swagger.client.model.MixedPropertiesAndAdditionalPropertiesClass
Remove Attribute Annotation	@JsonProperty("map") in attribute private map : Map<String,Animal> from class io.swagger.client.model.MixedPropertiesAndAdditionalPropertiesClass
Add Attribute Annotation	@SerializedName("name") in attribute private name : Integer from class io.swagger.client.model.Model200Response
Remove Attribute Annotation	@JsonProperty("name") in attribute private name : Integer from class io.swagger.client.model.Model200Response
Add Attribute Annotation	@SerializedName("class") in attribute private PropertyClass : String from class io.swagger.client.model.Model200Response
Remove Attribute Annotation	@JsonProperty("class") in attribute private PropertyClass : String from class io.swagger.client.model.Model200Response
Add Attribute Annotation	@SerializedName("code") in attribute private code : Integer from class io.swagger.client.model.ModelApiResponse
Remove Attribute Annotation	@JsonProperty("code") in attribute private code : Integer from class io.swagger.client.model.ModelApiResponse
Add Attribute Annotation	@SerializedName("type") in attribute private type : String from class io.swagger.client.model.ModelApiResponse
Remove Attribute Annotation	@JsonProperty("type") in attribute private type : String from class io.swagger.client.model.ModelApiResponse
Add Attribute Annotation	@SerializedName("message") in attribute private message : String from class io.swagger.client.model.ModelApiResponse
Remove Attribute Annotation	@JsonProperty("message") in attribute private message : String from class io.swagger.client.model.ModelApiResponse
Add Attribute Annotation	@SerializedName("return") in attribute private _return : Integer from class io.swagger.client.model.ModelReturn
Remove Attribute Annotation	@JsonProperty("return") in attribute private _return : Integer from class io.swagger.client.model.ModelReturn
Add Attribute Annotation	@SerializedName("name") in attribute private name : Integer from class io.swagger.client.model.Name
Remove Attribute Annotation	@JsonProperty("name") in attribute private name : Integer from class io.swagger.client.model.Name
Add Attribute Annotation	@SerializedName("snake_case") in attribute private snakeCase : Integer from class io.swagger.client.model.Name
Remove Attribute Annotation	@JsonProperty("snake_case") in attribute private snakeCase : Integer from class io.swagger.client.model.Name
Add Attribute Annotation	@SerializedName("property") in attribute private property : String from class io.swagger.client.model.Name
Remove Attribute Annotation	@JsonProperty("property") in attribute private property : String from class io.swagger.client.model.Name
Add Attribute Annotation	@SerializedName("123Number") in attribute private _123Number : Integer from class io.swagger.client.model.Name
Remove Attribute Annotation	@JsonProperty("123Number") in attribute private _123Number : Integer from class io.swagger.client.model.Name
Add Attribute Annotation	@SerializedName("JustNumber") in attribute private justNumber : BigDecimal from class io.swagger.client.model.NumberOnly
Remove Attribute Annotation	@JsonProperty("JustNumber") in attribute private justNumber : BigDecimal from class io.swagger.client.model.NumberOnly
Add Attribute Annotation	@SerializedName("id") in attribute private id : Long from class io.swagger.client.model.Order
Remove Attribute Annotation	@JsonProperty("id") in attribute private id : Long from class io.swagger.client.model.Order
Add Attribute Annotation	@SerializedName("petId") in attribute private petId : Long from class io.swagger.client.model.Order
Remove Attribute Annotation	@JsonProperty("petId") in attribute private petId : Long from class io.swagger.client.model.Order
Add Attribute Annotation	@SerializedName("quantity") in attribute private quantity : Integer from class io.swagger.client.model.Order
Remove Attribute Annotation	@JsonProperty("quantity") in attribute private quantity : Integer from class io.swagger.client.model.Order
Add Attribute Annotation	@SerializedName("shipDate") in attribute private shipDate : DateTime from class io.swagger.client.model.Order
Remove Attribute Annotation	@JsonProperty("shipDate") in attribute private shipDate : DateTime from class io.swagger.client.model.Order
Add Attribute Annotation	@SerializedName("status") in attribute private status : StatusEnum from class io.swagger.client.model.Order
Remove Attribute Annotation	@JsonProperty("status") in attribute private status : StatusEnum from class io.swagger.client.model.Order
Add Attribute Annotation	@SerializedName("complete") in attribute private complete : Boolean from class io.swagger.client.model.Order
Remove Attribute Annotation	@JsonProperty("complete") in attribute private complete : Boolean from class io.swagger.client.model.Order
Add Attribute Annotation	@SerializedName("id") in attribute private id : Long from class io.swagger.client.model.Pet
Remove Attribute Annotation	@JsonProperty("id") in attribute private id : Long from class io.swagger.client.model.Pet
Add Attribute Annotation	@SerializedName("category") in attribute private category : Category from class io.swagger.client.model.Pet
Remove Attribute Annotation	@JsonProperty("category") in attribute private category : Category from class io.swagger.client.model.Pet
Add Attribute Annotation	@SerializedName("name") in attribute private name : String from class io.swagger.client.model.Pet
Remove Attribute Annotation	@JsonProperty("name") in attribute private name : String from class io.swagger.client.model.Pet
Add Attribute Annotation	@SerializedName("photoUrls") in attribute private photoUrls : List<String> from class io.swagger.client.model.Pet
Remove Attribute Annotation	@JsonProperty("photoUrls") in attribute private photoUrls : List<String> from class io.swagger.client.model.Pet
Add Attribute Annotation	@SerializedName("tags") in attribute private tags : List<Tag> from class io.swagger.client.model.Pet
Remove Attribute Annotation	@JsonProperty("tags") in attribute private tags : List<Tag> from class io.swagger.client.model.Pet
Add Attribute Annotation	@SerializedName("status") in attribute private status : StatusEnum from class io.swagger.client.model.Pet
Remove Attribute Annotation	@JsonProperty("status") in attribute private status : StatusEnum from class io.swagger.client.model.Pet
Add Attribute Annotation	@SerializedName("bar") in attribute private bar : String from class io.swagger.client.model.ReadOnlyFirst
Remove Attribute Annotation	@JsonProperty("bar") in attribute private bar : String from class io.swagger.client.model.ReadOnlyFirst
Add Attribute Annotation	@SerializedName("baz") in attribute private baz : String from class io.swagger.client.model.ReadOnlyFirst
Remove Attribute Annotation	@JsonProperty("baz") in attribute private baz : String from class io.swagger.client.model.ReadOnlyFirst
Add Attribute Annotation	@SerializedName("$special[property.name]") in attribute private specialPropertyName : Long from class io.swagger.client.model.SpecialModelName
Remove Attribute Annotation	@JsonProperty("$special[property.name]") in attribute private specialPropertyName : Long from class io.swagger.client.model.SpecialModelName
Add Attribute Annotation	@SerializedName("id") in attribute private id : Long from class io.swagger.client.model.Tag
Remove Attribute Annotation	@JsonProperty("id") in attribute private id : Long from class io.swagger.client.model.Tag
Add Attribute Annotation	@SerializedName("name") in attribute private name : String from class io.swagger.client.model.Tag
Remove Attribute Annotation	@JsonProperty("name") in attribute private name : String from class io.swagger.client.model.Tag
Add Attribute Annotation	@SerializedName("id") in attribute private id : Long from class io.swagger.client.model.User
Remove Attribute Annotation	@JsonProperty("id") in attribute private id : Long from class io.swagger.client.model.User
Add Attribute Annotation	@SerializedName("username") in attribute private username : String from class io.swagger.client.model.User
Remove Attribute Annotation	@JsonProperty("username") in attribute private username : String from class io.swagger.client.model.User
Add Attribute Annotation	@SerializedName("firstName") in attribute private firstName : String from class io.swagger.client.model.User
Remove Attribute Annotation	@JsonProperty("firstName") in attribute private firstName : String from class io.swagger.client.model.User
Add Attribute Annotation	@SerializedName("lastName") in attribute private lastName : String from class io.swagger.client.model.User
Remove Attribute Annotation	@JsonProperty("lastName") in attribute private lastName : String from class io.swagger.client.model.User
Add Attribute Annotation	@SerializedName("email") in attribute private email : String from class io.swagger.client.model.User
Remove Attribute Annotation	@JsonProperty("email") in attribute private email : String from class io.swagger.client.model.User
Add Attribute Annotation	@SerializedName("password") in attribute private password : String from class io.swagger.client.model.User
Remove Attribute Annotation	@JsonProperty("password") in attribute private password : String from class io.swagger.client.model.User
Add Attribute Annotation	@SerializedName("phone") in attribute private phone : String from class io.swagger.client.model.User
Remove Attribute Annotation	@JsonProperty("phone") in attribute private phone : String from class io.swagger.client.model.User
Add Attribute Annotation	@SerializedName("userStatus") in attribute private userStatus : Integer from class io.swagger.client.model.User
Remove Attribute Annotation	@JsonProperty("userStatus") in attribute private userStatus : Integer from class io.swagger.client.model.User
Rename Method	public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T renamed to public handleResponse(response Response, returnType Type) : T in class io.swagger.client.ApiClient
Change Attribute Type	httpClient : Client to httpClient : OkHttpClient in class io.swagger.client.ApiClient
Inline Method	public rebuildHttpClient() : ApiClient inlined to public setDebugging(debugging boolean) : ApiClient in class io.swagger.client.ApiClient
Inline Method	public rebuildHttpClient() : ApiClient inlined to public setDebugging(debugging boolean) : ApiClient in class io.swagger.client.ApiClient
Extract Method	public formatDatetime(date Date) : String extracted from public parameterToString(param Object) : String in class io.swagger.client.ApiClient
Extract Method	public formatDatetime(date Date) : String extracted from public parameterToString(param Object) : String in class io.swagger.client.ApiClient
Change Return Type	Client to OkHttpClient in method public getHttpClient() : OkHttpClient from class io.swagger.client.ApiClient
Change Parameter Type	httpClient : Client to httpClient : OkHttpClient in method public setHttpClient(httpClient OkHttpClient) : ApiClient from class io.swagger.client.ApiClient
Change Variable Type	e : java.text.ParseException to e : ParseException in method public parseDate(str String) : Date from class io.swagger.client.ApiClient
Change Variable Type	valueCollection : Collection<?> to valueCollection : Collection in method public parameterToPairs(collectionFormat String, name String, value Object) : List<Pair> from class io.swagger.client.ApiClient
Change Method Access Modifier	private to public in method public buildUrl(path String, queryParams List<Pair>) : String from class io.swagger.client.ApiClient
Change Method Access Modifier	private to public in method public updateParamsForAuth(authNames String[], queryParams List<Pair>, headerParams Map<String,String>) : void from class io.swagger.client.ApiClient
Change Variable Type	e : RuntimeException to e : IOException in method public handleResponse(response Response, returnType Type) : T from class io.swagger.client.ApiClient
Parameterize Variable	response : ClientResponse to response : Response in method public handleResponse(response Response, returnType Type) : T from class io.swagger.client.ApiClient
Change Variable Type	response : ClientResponse to response : Response in method public handleResponse(response Response, returnType Type) : T from class io.swagger.client.ApiClient
Change Parameter Type	returnType : GenericType<T> to returnType : Type in method public handleResponse(response Response, returnType Type) : T from class io.swagger.client.ApiClient
Remove Parameter	path : String in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Remove Parameter	method : String in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Remove Parameter	queryParams : List<Pair> in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Remove Parameter	body : Object in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Remove Parameter	headerParams : Map<String,String> in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Remove Parameter	formParams : Map<String,Object> in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Remove Parameter	accept : String in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Remove Parameter	contentType : String in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Remove Parameter	authNames : String[] in method public invokeAPI(path String, method String, queryParams List<Pair>, body Object, headerParams Map<String,String>, formParams Map<String,Object>, accept String, contentType String, authNames String[], returnType GenericType<T>) : T from class io.swagger.client.ApiClient
Replace Variable With Attribute	jsonProvider : JacksonJsonProvider to loggingInterceptor : HttpLoggingInterceptor in method public setDebugging(debugging boolean) : ApiClient from class io.swagger.client.ApiClient
Change Variable Type	jsonProvider : JacksonJsonProvider to loggingInterceptor : HttpLoggingInterceptor in method public setDebugging(debugging boolean) : ApiClient from class io.swagger.client.ApiClient
Change Variable Type	date : Date to date : LocalDate in method public testEndpointParametersTest() : void from class io.swagger.client.api.FakeApiTest
Change Variable Type	dateTime : Date to dateTime : DateTime in method public testEndpointParametersTest() : void from class io.swagger.client.api.FakeApiTest
Add Attribute Annotation	@SerializedName("1") in enum constant NUMBER_1(1) from class io.swagger.client.model.EnumTest.EnumIntegerEnum
Add Attribute Annotation	@SerializedName("-1") in enum constant NUMBER_MINUS_1(-1) from class io.swagger.client.model.EnumTest.EnumIntegerEnum
Add Attribute Annotation	@SerializedName("1.1") in enum constant NUMBER_1_DOT_1(1.1) from class io.swagger.client.model.EnumTest.EnumNumberEnum
Add Attribute Annotation	@SerializedName("-1.2") in enum constant NUMBER_MINUS_1_DOT_2(-1.2) from class io.swagger.client.model.EnumTest.EnumNumberEnum
Add Attribute Annotation	@SerializedName("UPPER") in enum constant UPPER("UPPER") from class io.swagger.client.model.EnumTest.EnumStringEnum
Add Attribute Annotation	@SerializedName("lower") in enum constant LOWER("lower") from class io.swagger.client.model.EnumTest.EnumStringEnum
Add Attribute Annotation	@SerializedName("UPPER") in enum constant UPPER("UPPER") from class io.swagger.client.model.MapTest.InnerEnum
Add Attribute Annotation	@SerializedName("lower") in enum constant LOWER("lower") from class io.swagger.client.model.MapTest.InnerEnum
Add Attribute Annotation	@SerializedName("placed") in enum constant PLACED("placed") from class io.swagger.client.model.Order.StatusEnum
Add Attribute Annotation	@SerializedName("approved") in enum constant APPROVED("approved") from class io.swagger.client.model.Order.StatusEnum
Add Attribute Annotation	@SerializedName("delivered") in enum constant DELIVERED("delivered") from class io.swagger.client.model.Order.StatusEnum
Add Attribute Annotation	@SerializedName("available") in enum constant AVAILABLE("available") from class io.swagger.client.model.Pet.StatusEnum
Add Attribute Annotation	@SerializedName("pending") in enum constant PENDING("pending") from class io.swagger.client.model.Pet.StatusEnum
Add Attribute Annotation	@SerializedName("sold") in enum constant SOLD("sold") from class io.swagger.client.model.Pet.StatusEnum
Extract Class	io.swagger.client.JSON from class io.swagger.client.ApiClient
Remove Parameter	testCodeInjectEnd : String in method private testCodeInjectEndCall(testCodeInjectEnd String, progressListener ProgressResponseBody.ProgressListener, progressRequestListener ProgressRequestBody.ProgressRequestListener) : Call from class io.swagger.client.api.FakeApi
Move And Rename Method	private testCodeInjectEndCall(testCodeInjectEnd String, progressListener ProgressResponseBody.ProgressListener, progressRequestListener ProgressRequestBody.ProgressRequestListener) : Call from class io.swagger.client.api.FakeApi to private getInventoryCall(progressListener ProgressResponseBody.ProgressListener, progressRequestListener ProgressRequestBody.ProgressRequestListener) : Call from class io.swagger.client.api.StoreApi
Rename Parameter	testCodeInjectEnd : String to apiKey : String in method public deletePetAsync(petId Long, apiKey String, callback ApiCallback<Void>) : Call from class io.swagger.client.api.PetApi
Add Parameter	petId : Long in method public deletePetAsync(petId Long, apiKey String, callback ApiCallback<Void>) : Call from class io.swagger.client.api.PetApi
Move And Rename Method	public testCodeInjectEndAsync(testCodeInjectEnd String, callback ApiCallback<Void>) : Call from class io.swagger.client.api.FakeApi to public deletePetAsync(petId Long, apiKey String, callback ApiCallback<Void>) : Call from class io.swagger.client.api.PetApi
Add Attribute Modifier	final in attribute private statusCode : int from class io.swagger.client.ApiResponse
Move Attribute	private statusCode : int from class io.swagger.client.ApiClient to private statusCode : int from class io.swagger.client.ApiResponse
Move Source Folder	samples/client/petstore/java/default to samples/client/petstore/java/jersey1
