### ISSUE TITLE
Timeout Exception antlr/antlr4 08e9776

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#585]
https://github.com/antlr/antlr4/commit/08e9776a4ac507d931e8f3e282b2778cd7640af0 timed out
```
159654750 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 08e9776a4ac507d931e8f3e282b2778cd7640af0
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment]
@victorgveloso 
**FIXED**

Refactorings at 08e9776a4ac507d931e8f3e282b2778cd7640af0
Move Class	org.antlr.v4.test.runtime.csharp.BaseTest.StreamVacuum moved to org.antlr.v4.test.runtime.csharp.BaseCSharpTest.StreamVacuum
Move Class	org.antlr.v4.test.runtime.csharp.BaseTest.FilteringTokenStream moved to org.antlr.v4.test.runtime.csharp.BaseCSharpTest.FilteringTokenStream
Move Class	org.antlr.v4.test.runtime.go.BaseTest.StreamVacuum moved to org.antlr.v4.test.runtime.go.BaseGoTest.StreamVacuum
Move Class	org.antlr.v4.test.runtime.go.BaseTest.FilteringTokenStream moved to org.antlr.v4.test.runtime.go.BaseGoTest.FilteringTokenStream
Move Class	org.antlr.v4.test.runtime.go.BaseTest.IntTokenStream moved to org.antlr.v4.test.runtime.go.BaseGoTest.IntTokenStream
Move Class	org.antlr.v4.test.runtime.java.BaseTest.StreamVacuum moved to org.antlr.v4.test.runtime.java.BaseJavaTest.StreamVacuum
Move Class	org.antlr.v4.test.runtime.java.BaseTest.FilteringTokenStream moved to org.antlr.v4.test.runtime.java.BaseJavaTest.FilteringTokenStream
Move Class	org.antlr.v4.test.runtime.java.BaseTest.IntTokenStream moved to org.antlr.v4.test.runtime.java.BaseJavaTest.IntTokenStream
Move Class	org.antlr.v4.test.runtime.javascript.node.BaseTest.StreamVacuum moved to org.antlr.v4.test.runtime.javascript.node.BaseNodeTest.StreamVacuum
Move Class	org.antlr.v4.test.runtime.javascript.node.BaseTest.FilteringTokenStream moved to org.antlr.v4.test.runtime.javascript.node.BaseNodeTest.FilteringTokenStream
Move Class	org.antlr.v4.test.runtime.javascript.node.BaseTest.IntTokenStream moved to org.antlr.v4.test.runtime.javascript.node.BaseNodeTest.IntTokenStream
Move Class	org.antlr.v4.test.runtime.java.ErrorQueue moved to org.antlr.v4.test.runtime.ErrorQueue
Move And Rename Class	org.antlr.v4.test.runtime.csharp.BaseTest moved and renamed to org.antlr.v4.test.runtime.legacy.csharp.BaseCSharpTest
Move And Rename Class	org.antlr.v4.test.runtime.go.BaseTest moved and renamed to org.antlr.v4.test.runtime.legacy.go.BaseGoTest
Move And Rename Class	org.antlr.v4.test.runtime.java.BaseTest moved and renamed to org.antlr.v4.test.runtime.legacy.java.LegacyBaseJavaTest
Move And Rename Class	org.antlr.v4.test.runtime.javascript.node.BaseTest moved and renamed to org.antlr.v4.test.runtime.legacy.javascript.node.BaseNodeTest
Remove Class Modifier	abstract in class org.antlr.v4.test.runtime.cpp.BaseCppTest
Rename Method	public setUp() : void renamed to public testSetUp() : void in class org.antlr.v4.test.runtime.cpp.BaseCppTest
Inline Method	protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean, trace boolean) : String inlined to public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String in class org.antlr.v4.test.runtime.cpp.BaseCppTest
Rename Parameter	debug : boolean to showDiagnosticErrors : boolean in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Rename Parameter	debug : boolean to showDiagnosticErrors : boolean in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Extract Method	private runCommand(command String[], workPath String, description String) : String extracted from private buildRuntime() : boolean in class org.antlr.v4.test.runtime.cpp.BaseCppTest
Extract Method	private runCommand(command String[], workPath String, description String) : String extracted from private buildRuntime() : boolean in class org.antlr.v4.test.runtime.cpp.BaseCppTest
Extract Method	private runCommand(command String[], workPath String, description String) : String extracted from public execModule(fileName String) : String in class org.antlr.v4.test.runtime.cpp.BaseCppTest
Extract Method	private runCommand(command String[], workPath String, description String) : String extracted from public execModule(fileName String) : String in class org.antlr.v4.test.runtime.cpp.BaseCppTest
Parameterize Variable	runtimePath : String to workPath : String in method private runCommand(command String[], workPath String, description String) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Extract Variable	err : String in method private runProcess(builder ProcessBuilder, description String) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Change Variable Type	args : ArrayList<String> to command2 : List<String> in method public execModule(fileName String) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Change Variable Type	args : ArrayList<String> to command2 : List<String> in method public execModule(fileName String) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Rename Variable	args : ArrayList<String> to command2 : List<String> in method public execModule(fileName String) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Rename Variable	args : ArrayList<String> to command2 : List<String> in method public execModule(fileName String) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Add Method Annotation	@Override in method public execLexer(grammarFileName String, grammarStr String, lexerName String, input String, showDFA boolean) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Change Method Access Modifier	protected to public in method public execLexer(grammarFileName String, grammarStr String, lexerName String, input String, showDFA boolean) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Add Method Annotation	@Override in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Change Method Access Modifier	protected to public in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Add Method Annotation	@Override in method public eraseTempDir() : void from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Change Method Access Modifier	protected to public in method public eraseTempDir() : void from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Add Method Annotation	@Override in method public testSetUp() : void from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Remove Method Annotation	@Before in method public setUp() : void from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Parameterize Attribute	tmpdir : String to workPath : String in method private runCommand(command String[], workPath String, description String) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Rename Method	public setUp() : void renamed to public testSetUp() : void in class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Add Method Annotation	@Override in method public execLexer(grammarFileName String, grammarStr String, lexerName String, input String, showDFA boolean) : String from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Remove Thrown Exception Type	Exception in method protected execLexer(grammarFileName String, grammarStr String, lexerName String, input String, showDFA boolean) : String from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Change Method Access Modifier	protected to public in method public execLexer(grammarFileName String, grammarStr String, lexerName String, input String, showDFA boolean) : String from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Rename Parameter	debug : boolean to showDiagnosticErrors : boolean in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Add Method Annotation	@Override in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Remove Thrown Exception Type	Exception in method protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean) : String from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Change Method Access Modifier	protected to public in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Add Method Annotation	@Override in method public eraseTempDir() : void from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Change Method Access Modifier	protected to public in method public eraseTempDir() : void from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Add Method Annotation	@Override in method public testSetUp() : void from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Remove Method Annotation	@Before in method public setUp() : void from class org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest
Rename Method	public setUp() : void renamed to public testSetUp() : void in class org.antlr.v4.test.runtime.python.BasePythonTest
Rename Method	protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean, trace boolean) : String renamed to public execParser_(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean, trace boolean) : String in class org.antlr.v4.test.runtime.python.BasePythonTest
Add Method Annotation	@Override in method public execLexer(grammarFileName String, grammarStr String, lexerName String, input String, showDFA boolean) : String from class org.antlr.v4.test.runtime.python.BasePythonTest
Change Method Access Modifier	protected to public in method public execLexer(grammarFileName String, grammarStr String, lexerName String, input String, showDFA boolean) : String from class org.antlr.v4.test.runtime.python.BasePythonTest
Rename Parameter	debug : boolean to showDiagnosticErrors : boolean in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.python.BasePythonTest
Change Method Access Modifier	protected to public in method public execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, showDiagnosticErrors boolean) : String from class org.antlr.v4.test.runtime.python.BasePythonTest
Add Method Annotation	@Override in method public eraseTempDir() : void from class org.antlr.v4.test.runtime.python.BasePythonTest
Change Method Access Modifier	protected to public in method public eraseTempDir() : void from class org.antlr.v4.test.runtime.python.BasePythonTest
Add Method Annotation	@Override in method public testSetUp() : void from class org.antlr.v4.test.runtime.python.BasePythonTest
Remove Method Annotation	@Before in method public setUp() : void from class org.antlr.v4.test.runtime.python.BasePythonTest
Change Method Access Modifier	protected to public in method public execParser_(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean, trace boolean) : String from class org.antlr.v4.test.runtime.python.BasePythonTest
Remove Class Modifier	abstract in class org.antlr.v4.test.runtime.python2.BasePython2Test
Remove Class Modifier	abstract in class org.antlr.v4.test.runtime.python3.BasePython3Test
Rename Method	public setUp() : void renamed to public testSetUp() : void in class org.antlr.v4.test.tool.TestParserProfiler
Add Method Annotation	@Before in method public testSetUp() : void from class org.antlr.v4.test.tool.TestParserProfiler
Change Method Access Modifier	protected to public in method public eraseTempDir() : void from class org.antlr.v4.test.tool.TestPerformance
Add Parameter	listenerName : String in method protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean) : String from class org.antlr.v4.test.runtime.legacy.csharp.BaseCSharpTest
Add Parameter	visitorName : String in method protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean) : String from class org.antlr.v4.test.runtime.legacy.csharp.BaseCSharpTest
Rename Attribute	parserpkgdir : File to tmpdir : File in class org.antlr.v4.test.runtime.legacy.go.BaseGoTest
Rename Attribute	tmpdir : File to overall_tmpdir : File in class org.antlr.v4.test.runtime.legacy.go.BaseGoTest
Add Parameter	listenerName : String in method protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean) : String from class org.antlr.v4.test.runtime.legacy.java.LegacyBaseJavaTest
Add Parameter	visitorName : String in method protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean) : String from class org.antlr.v4.test.runtime.legacy.java.LegacyBaseJavaTest
Add Parameter	listenerName : String in method protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean, profile boolean) : String from class org.antlr.v4.test.runtime.legacy.java.LegacyBaseJavaTest
Add Parameter	visitorName : String in method protected execParser(grammarFileName String, grammarStr String, parserName String, lexerName String, listenerName String, visitorName String, startRuleName String, input String, debug boolean, profile boolean) : String from class org.antlr.v4.test.runtime.legacy.java.LegacyBaseJavaTest
Extract Interface	org.antlr.v4.test.runtime.SingleTest from classes [org.antlr.v4.test.runtime.cpp.BaseCppTest, org.antlr.v4.test.runtime.javascript.browser.BaseBrowserTest, org.antlr.v4.test.runtime.python.BasePythonTest]
Extract Superclass	org.antlr.v4.test.runtime.java.BaseJavaTest from classes [org.antlr.v4.test.tool.TestATNConstruction, org.antlr.v4.test.tool.TestATNDeserialization, org.antlr.v4.test.tool.TestATNInterpreter, org.antlr.v4.test.tool.TestATNLexerInterpreter, org.antlr.v4.test.tool.TestATNParserPrediction, org.antlr.v4.test.tool.TestATNSerialization, org.antlr.v4.test.tool.TestActionSplitter, org.antlr.v4.test.tool.TestActionTranslation, org.antlr.v4.test.tool.TestAttributeChecks, org.antlr.v4.test.tool.TestBasicSemanticErrors, org.antlr.v4.test.tool.TestBufferedTokenStream, org.antlr.v4.test.tool.TestCodeGeneration, org.antlr.v4.test.tool.TestCompositeGrammars, org.antlr.v4.test.tool.TestDollarParser, org.antlr.v4.test.tool.TestErrorSets, org.antlr.v4.test.tool.TestIntervalSet, org.antlr.v4.test.tool.TestLeftRecursionToolIssues, org.antlr.v4.test.tool.TestLexerActions, org.antlr.v4.test.tool.TestParseTreeMatcher, org.antlr.v4.test.tool.TestParserExec, org.antlr.v4.test.tool.TestParserInterpreter, org.antlr.v4.test.tool.TestParserProfiler, org.antlr.v4.test.tool.TestPerformance, org.antlr.v4.test.tool.TestScopeParsing, org.antlr.v4.test.tool.TestSymbolIssues, org.antlr.v4.test.tool.TestTokenPositionOptions, org.antlr.v4.test.tool.TestTokenStreamRewriter, org.antlr.v4.test.tool.TestTokenTypeAssignment, org.antlr.v4.test.tool.TestToolSyntaxErrors, org.antlr.v4.test.tool.TestTopologicalSort, org.antlr.v4.test.tool.TestUnbufferedCharStream, org.antlr.v4.test.tool.TestUnbufferedTokenStream, org.antlr.v4.test.tool.TestVocabulary, org.antlr.v4.test.tool.TestXPath]
Move Method	private locateTool(tool String) : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest to private locateTool(tool String) : String from class org.antlr.v4.test.runtime.legacy.cpp.BaseCppTest
Move Method	protected locateCompiler() : String from class org.antlr.v4.test.runtime.cpp.BaseCppTest to protected locateCompiler() : String from class org.antlr.v4.test.runtime.legacy.cpp.BaseCppTest
Move Attribute	public testWatcher : TestRule from class org.antlr.v4.test.runtime.cpp.BaseCppTest to public testWatcher : TestRule from class org.antlr.v4.test.runtime.legacy.cpp.BaseCppTest
Extract Class	org.antlr.v4.test.runtime.legacy.cpp.BaseCppTest from class org.antlr.v4.test.runtime.cpp.BaseCppTest
Add Method Annotation	@Override in method public getTarget() : String from class org.antlr.v4.test.runtime.BaseRuntimeTestDescriptor
Change Method Access Modifier	private to public in method public getTarget() : String from class org.antlr.v4.test.runtime.BaseRuntimeTestDescriptor
Move And Rename Method	private getTargetName() : String from class org.antlr.v4.testgen.TestGenerator to public getTarget() : String from class org.antlr.v4.test.runtime.BaseRuntimeTestDescriptor
Move Method	private importLanguageTemplates(testGroup STGroup, languageGroup STGroup) : void from class org.antlr.v4.testgen.TestGenerator to private importLanguageTemplates(testGroup STGroup, languageGroup STGroup) : void from class org.antlr.v4.testgen.DescrGenerator
Move Method	public writeFile(file File, content String) : void from class org.antlr.v4.testgen.TestGenerator to public writeFile(file File, content String) : void from class org.antlr.v4.testgen.DescrGenerator
Move Method	protected info(message String) : void from class org.antlr.v4.testgen.TestGenerator to protected info(message String) : void from class org.antlr.v4.testgen.DescrGenerator
Move Method	protected warn(message String) : void from class org.antlr.v4.testgen.TestGenerator to protected warn(message String) : void from class org.antlr.v4.testgen.DescrGenerator
Move Method	protected error(message String, throwable Throwable) : void from class org.antlr.v4.testgen.TestGenerator to protected error(message String, throwable Throwable) : void from class org.antlr.v4.testgen.DescrGenerator
Extract And Move Method	public testSetUp() : void extracted from public setUp() : void in class org.antlr.v4.test.tool.TestParserProfiler & moved to class org.antlr.v4.test.tool.TestATNConstruction
Extract And Move Method	public testSetUp() : void extracted from public setUp() : void in class org.antlr.v4.test.tool.TestParserProfiler & moved to class org.antlr.v4.test.tool.TestATNDeserialization
Move Source Folder	runtime-testsuite to runtime-testsuite-legacy
