### ISSUE TITLE
Problem in method statementWithoutAnonymous() with nested anonymous class declarations

### ISSUE THREAD

**Issue by djaekim** [tsantalis/RefactoringMiner#64]
StackTrace:

![image](https://user-images.githubusercontent.com/26092570/66882338-05a0c300-ef98-11e9-98dd-38c41215673c.png)

Reproduce:
- detectAtCommit(Flink, commit: 942d6c0439eb43231885bf389279d9e22794e0cc)

**Comment by tsantalis** [comment]
There is no NullPointerException
2019-10-16 15:00:00 INFO  Processing tmp1/flink 453109de5a608d19b8700d6059d6ae4332c48835 ...
2019-10-16 15:00:01 INFO  Processing tmp1/flink 942d6c0439eb43231885bf389279d9e22794e0cc ...
Commits: 1  Errors: 0
Total  TP:  0  FP: 62  FN:  0  TN:  0  Unk.:  0  Prec.: 0.000  Recall: NaN
MA     TP:  0  FP:  2  FN:  0  TN:  0  Unk.:  0  Prec.: 0.000  Recall: NaN
RM     TP:  0  FP:  1  FN:  0  TN:  0  Unk.:  0  Prec.: 0.000  Recall: NaN
MM     TP:  0  FP: 52  FN:  0  TN:  0  Unk.:  0  Prec.: 0.000  Recall: NaN
RP     TP:  0  FP:  1  FN:  0  TN:  0  Unk.:  0  Prec.: 0.000  Recall: NaN
MA     TP:  0  FP:  1  FN:  0  TN:  0  Unk.:  0  Prec.: 0.000  Recall: NaN
CPT    TP:  0  FP:  4  FN:  0  TN:  0  Unk.:  0  Prec.: 0.000  Recall: NaN
CAT    TP:  0  FP:  1  FN:  0  TN:  0  Unk.:  0  Prec.: 0.000  Recall: NaN
at https://github.com/apache/flink/commit/942d6c0439eb43231885bf389279d9e22794e0cc

 

>  Move Method public setString(fieldNumber int, str String) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setString(fieldNumber int, str String) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getTupleInto(tuple Tuple) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getTupleInto(tuple Tuple) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setDouble(fieldNumber int, d Double) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setDouble(fieldNumber int, d Double) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getField(fieldNumber int) : Object from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getField(fieldNumber int) : Object from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getByte(tupleNumber int, fieldNumber int) : Byte from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getByte(tupleNumber int, fieldNumber int) : Byte from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method package tupleTypesToByteArray(tuple Tuple) : byte[] from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to package tupleTypesToByteArray(tuple Tuple) : byte[] from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getCharacter(fieldNumber int) : Character from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getCharacter(fieldNumber int) : Character from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setCharacter(tupleNumber int, fieldNumber int, c Character) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setCharacter(tupleNumber int, fieldNumber int, c Character) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public Clear() : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public Clear() : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setLong(tupleNumber int, fieldNumber int, l Long) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setLong(tupleNumber int, fieldNumber int, l Long) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setShort(tupleNumber int, fieldNumber int, s Short) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setShort(tupleNumber int, fieldNumber int, s Short) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getField(tupleNumber int, fieldNumber int) : Object from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getField(tupleNumber int, fieldNumber int) : Object from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public removeTuple(index int) : Tuple from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public removeTuple(index int) : Tuple from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getDouble(tupleNumber int, fieldNumber int) : Double from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getDouble(tupleNumber int, fieldNumber int) : Double from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setField(tupleNumber int, fieldNumber int, o Object) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setField(tupleNumber int, fieldNumber int, o Object) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setBoolean(fieldNumber int, b Boolean) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setBoolean(fieldNumber int, b Boolean) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Change Attribute Type wordCounts : MutableTableState<String,Integer> to wordCounts : Map<String,Integer> in class eu.stratosphere.streaming.examples.wordcount.WordCountCounter
>   Move Method public getByte(fieldNumber int) : Byte from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getByte(fieldNumber int) : Byte from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public appendRecord(record StreamRecord) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public appendRecord(record StreamRecordGeneric<T>) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setByte(tupleNumber int, fieldNumber int, b Byte) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setByte(tupleNumber int, fieldNumber int, b Byte) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public addTuple(tuple Tuple) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public addTuple(tuple T) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Attribute private numOfTuples : int from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to private numOfTuples : int from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setInteger(fieldNumber int, i Integer) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setInteger(fieldNumber int, i Integer) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Change Parameter Type tuple : Tuple to tuple : T in method public setTuple(tuple T) : void in class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Rename Parameter numOfFields : int to batchsize : int in method public StreamRecord(batchsize int) in class eu.stratosphere.streaming.api.streamrecord.StreamRecord
>   Move Method public getBoolean(tupleNumber int, fieldNumber int) : Boolean from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getBoolean(tupleNumber int, fieldNumber int) : Boolean from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setTuple(tuple Tuple) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setTuple(tuple T) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getDouble(fieldNumber int) : Double from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getDouble(fieldNumber int) : Double from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setByte(fieldNumber int, b Byte) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setByte(fieldNumber int, b Byte) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setFloat(tupleNumber int, fieldNumber int, f Float) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setFloat(tupleNumber int, fieldNumber int, f Float) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getInteger(fieldNumber int) : Integer from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getInteger(fieldNumber int) : Integer from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getFloat(tupleNumber int, fieldNumber int) : Float from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getFloat(tupleNumber int, fieldNumber int) : Float from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public addTuple(index int, tuple Tuple) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public addTuple(index int, tuple T) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setField(fieldNumber int, o Object) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setField(fieldNumber int, o Object) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setFloat(fieldNumber int, f Float) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setFloat(fieldNumber int, f Float) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getShort(fieldNumber int) : Short from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getShort(fieldNumber int) : Short from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Change Parameter Type record : StreamRecord to record : StreamRecordGeneric<T> in method public appendRecord(record StreamRecordGeneric<T>) : void in class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getLong(fieldNumber int) : Long from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getLong(fieldNumber int) : Long from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setCharacter(fieldNumber int, c Character) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setCharacter(fieldNumber int, c Character) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setInteger(tupleNumber int, fieldNumber int, i Integer) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setInteger(tupleNumber int, fieldNumber int, i Integer) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getCharacter(tupleNumber int, fieldNumber int) : Character from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getCharacter(tupleNumber int, fieldNumber int) : Character from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getShort(tupleNumber int, fieldNumber int) : Short from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getShort(tupleNumber int, fieldNumber int) : Short from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getFloat(fieldNumber int) : Float from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getFloat(fieldNumber int) : Float from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setShort(fieldNumber int, s Short) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setShort(fieldNumber int, s Short) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Change Parameter Type tuple : Tuple to tuple : T in method public addTuple(index int, tuple T) : void in class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setDouble(tupleNumber int, fieldNumber int, d Double) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setDouble(tupleNumber int, fieldNumber int, d Double) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Attribute private numOfFields : int from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to private numOfFields : int from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setBoolean(tupleNumber int, fieldNumber int, b Boolean) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setBoolean(tupleNumber int, fieldNumber int, b Boolean) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method package tupleTypesFromByteArray(representation byte[]) : TypeInformation[] from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to package tupleTypesFromByteArray(representation byte[]) : TypeInformation[] from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getLong(tupleNumber int, fieldNumber int) : Long from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getLong(tupleNumber int, fieldNumber int) : Long from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getString(tupleNumber int, fieldNumber int) : String from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getString(tupleNumber int, fieldNumber int) : String from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public isEmpty() : boolean from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public isEmpty() : boolean from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getNumOfTuples() : int from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getNumOfTuples() : int from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getString(fieldNumber int) : String from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getString(fieldNumber int) : String from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Rename Method public getNumOfFields() : int renamed to public getBatchSize() : int in class eu.stratosphere.streaming.api.streamrecord.StreamRecord
>   Move Method public getBoolean(fieldNumber int) : Boolean from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getBoolean(fieldNumber int) : Boolean from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setLong(fieldNumber int, l Long) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setLong(fieldNumber int, l Long) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Merge Attribute [numOfFields : int, numOfTuples : int] to batchSize : int in class eu.stratosphere.streaming.api.streamrecord.StreamRecord
>   Move Method public getInteger(tupleNumber int, fieldNumber int) : Integer from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getInteger(tupleNumber int, fieldNumber int) : Integer from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public setString(tupleNumber int, fieldNumber int, str String) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public setString(tupleNumber int, fieldNumber int, str String) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Change Parameter Type tuple : Tuple to tuple : T in method public addTuple(tuple T) : void in class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>   Move Method public getTupleInto(tupleNumber int, tuple Tuple) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecord to public getTupleInto(tupleNumber int, tuple Tuple) : void from class eu.stratosphere.streaming.api.streamrecord.StreamRecordGeneric
>

**Comment by djaekim** [comment]
* Another NPE

* Stack Trace:

![image](https://user-images.githubusercontent.com/26092570/66953276-2d416b00-f02c-11e9-8ca0-40e94a7afb38.png)

* Reproduce: 

detectAtCommit("kafka", 56623efd73ec77e68cf35021d18d630b27062e82)

**Comment by tsantalis** [comment]
Same problem in commit
https://github.com/apache/flink/commit/3561222c5d6c7cee79f8c5872f32227632135c48

**Comment by djaekim** [comment]
thank you!
