### ISSUE TITLE
Diff between two commits

### ISSUE THREAD

**Issue by jzheng2017** [tsantalis/RefactoringMiner#650]
Hi,

Is there a way to get a diff between two commits and not just at a single commit level? So for instance between commit `x` and commit `y` the method `x` has changed to `x_2` and then `x_3` and to ... `x_n`. Is there a way to find this relation between method `x` to method `x_n`? Or do I have to manually compute it using the list of refactorings?

**Comment by tsantalis** [comment]
Hi @jzheng2017 

You basically have two options:
1. Use the `detectBetweenCommits` API that will find all refactorings between the two commits. Then you need to group the refactorings related to the program element (method `x` in your case) and infer that `x` changed to `x_n`.
2. Use our project [CodeTracker](https://github.com/jodavimehran/code-tracker) based on RefactoringMiner. 
https://github.com/jodavimehran/code-tracker?tab=readme-ov-file#how-to-track-methods
This will give all commits where method `x` changed somehow.
The paper explaining how it work is available at https://doi.org/10.1145/3540250.3549079
or https://users.encs.concordia.ca/~nikolaos/publications/FSE_2022.pdf
