### ISSUE TITLE
Dockerfile should be split up in build and distribution

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#669]
The dockerfile https://github.com/tsantalis/RefactoringMiner/blob/master/Dockerfile uses a full-blown JDK to build.

It should switch to a [multi stage build](https://docs.docker.com/build/building/multi-stage/) to reduce image size.

IMHO simply up to line 10 is build and from line 11 its the run image.

https://github.com/tsantalis/RefactoringMiner/blob/master/Dockerfile

**Comment by tsantalis** [comment]
@pouryafard75 
Could you please take care of this issue reported by @koppor ?
Thank you

**Comment by tsantalis** [comment]
@koppor 
@pouryafard75 reduced the image size significantly to 300 MB.
