### ISSUE TITLE
Chances of any other JVM lanugages support?

### ISSUE THREAD

**Issue by svitkovsergey** [tsantalis/RefactoringMiner#67]
Hi!
Thanks for creation and maintaining of RefactoringMiner.
As I know, currently it could find refactorings only in Java projects. Therefore, my question is: are there any chances of supporting other JVM languages, such as Scala and Kotlin?
I don't know much about Eclipse AST representation, but if it possible, I could try to help with it, if you will provide any additional information about it.
Best regards! :)

**Comment by tsantalis** [comment]
@likeanowl I believe it is possible to support statically typed languages, but it will be more challenging for dynamically typed languages.
Research-wise it has more value to extend the tool for supporting dynamically typed languages, such as JavaScript and Python.
