### ISSUE TITLE
More redable color contrast at number of changed files.

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#670]
IMHO a similar information should be encoded the same way. In the concrete case, the number of changes.

This is "somehow" the case. Example:

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/7d405c8c-530d-4b42-a41b-51cad2d9be4e)

However, I cannot read the "2" because white in lightgray is not that readable (Background: https://colorusage.arc.nasa.gov/luminance_cont.php). Another encoding should be chosen. GitHub uses a sub background to have all numbers appear the same way:

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/2ccb1afb-4979-4b2f-88f4-42e9e5d52486)

Maybe, that idea can be used here?

If you also have time to change the colors, you could choose some more light colors. The current red signales "danger", which is IMHO too strong for just deleted files. In my case, there was no deleted file - and the "danger" signalling is still there.

Maybe just choose a "random" color palette from the net

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/43b5c0c0-90cc-4023-bff3-ad8829a597d2)

(I found that one at https://www.shutterstock.com/de/blog/farbpaletten-ideen-website)

**Comment by tsantalis** [comment]
@koppor 
Number color changed to black. Thank you for your suggestions.

![image](https://github.com/tsantalis/RefactoringMiner/assets/1483516/41339fa7-b8c0-44ec-be42-94b7882982f6)

**Comment by koppor** [comment]
Just for reference: Check https://ctan.org/pkg/colorblind

![Image](https://github.com/user-attachments/assets/f81d4c80-7894-48cd-817b-6b06c705381a)

**Comment by koppor** [comment]
From README.md:

![Image](https://github.com/user-attachments/assets/39fd07fe-23ac-45ef-9326-7a2b660d0228)

I think, these colors are OK (and close to the Pale Highlight color palette). Moreover, there is finally the arrow showing relations :) (Even if I think that this arrow was added manually)

**Comment by koppor** [comment]
The current colors are very-very much the same

![Image](https://github.com/user-attachments/assets/adf9960c-219b-4ce0-8930-24a88b0079ff)
