### ISSUE TITLE
More user guidance "ManocoDiff" and "ClassicDiff"

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#671]
I am new to AST-based diffs, and I do not know the terms "MonacoDiff" and "ClassicDiff". In the tool, I did not find any hints on their meanings pros and cons (refs https://adr.github.io/madr/).

Following proposals:

- Tooltip at the main screen when hovering on these labels
- Heading in the diff page which diff is chosen (currenlty only readable in the url "vanilla-diff" and "monaco-diff".
- If possible: Change URL part `vanialla-diff` to `classic-diff` so that the URL part is consistent to the naming to the end suer.

---

Context: 

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/becf5fce-4100-4146-8281-6aedbc34a652)

**Comment by tsantalis** [comment]
@koppor 
"MonacoDiff" comes from the name of the [editor](https://microsoft.github.io/monaco-editor/) used to visualize the source code.

Thank you for your comments.
@pouryafard75 and I will work on them.

**Comment by koppor** [comment]
@tsantalis IMHO, these two buttons get much too much user attention in the UI. As user, I want to see the diffs and not decide at each diff viewing which mode I want. The two renderings are IMHO too similar to provide value when switching back and forth. 

Can you do a global setting which diff mode to use? Storing in a cookie is OK for me.
