### ISSUE TITLE
Extracted assertion method is mapped to test method

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#673]
## Detected changed
Test method [get_property_should_support_records](https://github.com/apache/logging-log4j2/commit/c624e01cc433cc36f23167c8f39ab40873ecc6ec#diff-37b3a24b58fbb623e30794eed14e6f88352ee77cd1a0fa2b204c4bdefd4c77e2L62) is mapped to an extracted assertion method [assertMapConvertsTo](https://github.com/apache/logging-log4j2/commit/c624e01cc433cc36f23167c8f39ab40873ecc6ec#diff-37b3a24b58fbb623e30794eed14e6f88352ee77cd1a0fa2b204c4bdefd4c77e2R200-R200)
<img width="1439" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/11022419/d682414c-d76b-48ee-b54a-de3d0bbd9052">

## Expected change
method [get_property_should_support_records](https://github.com/apache/logging-log4j2/commit/c624e01cc433cc36f23167c8f39ab40873ecc6ec#diff-37b3a24b58fbb623e30794eed14e6f88352ee77cd1a0fa2b204c4bdefd4c77e2L62) should be mapped to [should_support_nested_records](https://github.com/apache/logging-log4j2/commit/c624e01cc433cc36f23167c8f39ab40873ecc6ec#diff-37b3a24b58fbb623e30794eed14e6f88352ee77cd1a0fa2b204c4bdefd4c77e2R200-R200) that invokes extract assertion method [assertMapConvertsTo](https://github.com/apache/logging-log4j2/commit/c624e01cc433cc36f23167c8f39ab40873ecc6ec#diff-37b3a24b58fbb623e30794eed14e6f88352ee77cd1a0fa2b204c4bdefd4c77e2R200-R200)

**Comment by tsantalis** [comment]
@victorgveloso 
I checked this case and it is extremely challenging.

First I am not sure why method [get_property_should_support_records](https://github.com/apache/logging-log4j2/commit/c624e01cc433cc36f23167c8f39ab40873ecc6ec#diff-37b3a24b58fbb623e30794eed14e6f88352ee77cd1a0fa2b204c4bdefd4c77e2L62) should be mapped to [should_support_nested_records](https://github.com/apache/logging-log4j2/commit/c624e01cc433cc36f23167c8f39ab40873ecc6ec#diff-37b3a24b58fbb623e30794eed14e6f88352ee77cd1a0fa2b204c4bdefd4c77e2R200-R200)
because there is no common code, between these two methods.

```java
@Test
void get_property_should_support_records() {
    final TestListLogger logger = new TestListLogger(BasicPropertyEnvironmentTest.class.getName());
    final PropertyEnvironment env = new TestPropertyEnvironment(TEST_PROPS, logger);
    final ComponentProperties expected = new ComponentProperties(
            true,
            123,
            123456L,
            StandardCharsets.UTF_8,
            Duration.ofHours(8),
            "Hello child!",
            PropertyEnvironment.class,
            StandardLevel.INFO,
            new SubComponentProperties("Hello parent!"));
    assertThat(env.getProperty(ComponentProperties.class)).isEqualTo(expected);
    assertThat(logger.getMessages()).isEmpty();
}
```
```java
@Test
void should_support_nested_records() {
    assertMapConvertsTo(Map.of(), new Component(null, new SubComponent(null)));
    assertMapConvertsTo(COMPONENT_PROPS, new Component("COMPONENT", new SubComponent("SUBCOMPONENT")));
}
```
What is the common thing that could justify their match? Maybe `should_support_nested_records()` is actually a new test.

**Comment by victorgveloso** [comment]
Hi Nikos,

The test method isn't new because there is a test method with a similar
name which invokes the utility method that has much in common with the
original test method.

Usually, I'd agree with RMiner's mapping if the mapped methods weren't of
different "types". Notice that is a rather tricky and conceptual problem.
Hence it requires thinking in the original test case and the utility method
it relies on as separate "types of method". That is, a test case cannot
evolve into an assertion. They should never match with each other.

**Comment by tsantalis** [comment]
To detect the Rename Method we should be able to match something.
We have a heuristic that checks if part of the method has been extracted, but still the algorithm expects to have at least one statement that can be matched in the bodies of the renamed methods.

**Comment by victorgveloso** [comment]
Ok, you convinced me they shouldn't match. However, don't you agree that matching the old test method with the new assertion method is a False Positive?

**Comment by tsantalis** [comment]
@victorgveloso 
If you look at the two methods 4 statements are in common and the new statement
`final Object actual = env.getProperty(expected.getClass());`
is actually an Extract Variable refactoring.

So, all 5 statements in method [assertMapConvertsTo](https://github.com/apache/logging-log4j2/commit/c624e01cc433cc36f23167c8f39ab40873ecc6ec#diff-37b3a24b58fbb623e30794eed14e6f88352ee77cd1a0fa2b204c4bdefd4c77e2R200-R200) in a way exist in the original method.

`assertMapConvertsTo` essentially parameterizes the `map` which used to be `TEST_PROPS` and
the `expected` which used to be of `ComponentProperties` and now is `Object`

The diff perfectly reflects these changes.
So, to me it seems they took a test, they made it into a reusable method,
and then added some new tests that reuse `assertMapConvertsTo`

These new tests are:
`should_support_basic_values()`
`should_support_boxed_values()`
`should_support_scalar_values()`
`should_support_arrays_of_scalars()`
`should_support_nested_records()`
