### ISSUE TITLE
Inline variable can’t be detected in some cases

### ISSUE THREAD

**Issue by simpt5** [tsantalis/RefactoringMiner#678]
## Tested tools and version:
Refactoring Aware Commit Review Chrome Extension (Version: 2.0.4).
RefactoringMiner (Version 3.0.4) maven dependency.

## Description:
During the usage of RefactoringMiner, I found a few inline variable refactoring cases that can’t be detected. Do you have any idea why this happens and how to resolve this problem?

Commit URL: 
https://github.com/discoStar711/job-finder/pull/10/commits/4559aa19ca2228a0ebb7242636751c5be4ba42e3

The following inline variable refactoring in the above commit can’t be detected.
 
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/e97e308b-40f7-4c1f-8082-b7dc7adc7579)
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/b6253d13-58fb-48d0-92f5-af418462cb2f)

 

The same situation also happens in the following commit:
https://github.com/RefactoringGuru/design-patterns-java/pull/15/commits/74514fe2180a00990516d9c47096553f92f86989

The inline variable refactoring following can’t be detected too:
 
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/ff497383-3ea3-4efd-87df-48320ea6ff88)

**Comment by tsantalis** [comment]
Related to issue #154

**Comment by tsantalis** [comment]
@simpt5 
Thank you for reporting all these issues. We greatly appreciate this.
This issue has been fixed. The Inline Variable refactorings are now detected in both commits.
