### ISSUE TITLE
A case where merge conditional refactoring can’t be detected

### ISSUE THREAD

**Issue by simpt5** [tsantalis/RefactoringMiner#680]
## Tested tools and version:
Refactoring Aware Commit Review Chrome Extension (Version: 2.0.4).
RefactoringMiner (Version 3.0.4) maven dependency.

## Description:
During the usage of RefactoringMiner, I found a few merge conditional refactoring cases that can’t be detected. Do you have any idea why this happens and how to resolve this problem?

Commit URL: https://github.com/Multibit-Legacy/multibit-hd/pull/900/commits/bae6ebfb3baea282a949b2389c5a766a67510869

File URL: https://github.com/Multibit-Legacy/multibit-hd/pull/900/commits/bae6ebfb3baea282a949b2389c5a766a67510869#diff-313a1504fb912a4b2ce5bf840fe3b39f96f3efd9d3a499bfcfd581e2be17961f

The following merge conditional refactoring in the above commit can’t be detected.
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/36266a2c-400e-497a-873a-8211d721e269)

 

Do you have any idea about the reason, and how to fix it?

**Comment by tsantalis** [comment]
@simpt5 
Refactoring is detected as follows:
Merge Conditional	[return false;, if((os.contains("sunos")) || (os.contains("linux"))), if(isMac() && (System.getProperty("os.version","").startsWith("10.")))] to return (os.contains("sunos")) || (os.contains("linux")) || isMac() && (System.getProperty("os.version","").startsWith("10.")); in method public isUnix() : boolean from class org.multibit.hd.core.utils.OSUtils
