### ISSUE TITLE
Lack of support for refactoring related with diamond operator

### ISSUE THREAD

**Issue by simpt5** [tsantalis/RefactoringMiner#682]
## Issue content:
Currently, refactoring using diamond operator is not supported by RefactoringMiner. So, could it possibly be supported in the future considering the prevalent usage for this Java language feature.

## Tested tools and version:
Refactoring Aware Commit Review Chrome Extension (Version: 2.0.4).
RefactoringMiner (Version 3.0.4) maven dependency.

## Description
The following is a refactoring using diamond operator which can’t be detected by RefactoringMiner by far:
Diamond operator:
Commit URL: https://github.com/netty/netty/pull/12341/commits/efbdc36bed55023b684c6f80f8fca6b4447d2d67

File URL: https://github.com/netty/netty/pull/12341/commits/efbdc36bed55023b684c6f80f8fca6b4447d2d67#diff-1c54bb58f97cc96026f7b4c7b8b14422eec526228adb17522e5dc0749e82d629

Screenshot:
 
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/8456100c-f2a7-4abe-8ae7-5a7027df411e)

**Comment by tsantalis** [comment]
Statements are properly matched:

![Screenshot from 2024-03-16 20-33-26](https://github.com/tsantalis/RefactoringMiner/assets/1483516/d58cab62-9b08-4c3f-b38b-0c8adcaff7f7)

**Comment by simpt5** [comment]
**Very thanks for your reply.** 
Yes, statements are matched, those diamond operator operations are refactoring, but when applying the RefactoringMiner to detect them, they can't be detected as refactoring for now (as in the following screenshot). I am wondering could it be theoretically or possibly supported by RefactoringMiner to detect this kind of refactoring? This operation may seems very "slight" and "obvious", but it is very prevalent when developer maintain their codebase.
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/1acf2d86-3e3e-48f9-8884-88eac2235d8b)

**Comment by tsantalis** [comment]
@simpt5 
Yes, this one is very easy to detect and report. I will add it as a feature request.
What would be the name of this refactoring type?
`Replace Generics with Diamond Operator`

**Comment by tsantalis** [comment]
@simpt5 
The refactoring is officially supported `Replace Generic with Diamond`
62 instances of this refactoring were found in our Refactoring oracle.
