### ISSUE TITLE
Lack of support for the refactoring using Foreach loop

### ISSUE THREAD

**Issue by simpt5** [tsantalis/RefactoringMiner#683]
## Issue content:
Currently, the detection for refactoring using Foreach loop is currently not supported by RefactoringMiner. So, Could it possibly be supported in the future considering the prevalent usage for this Java language feature.

## Tested tools and version:
Refactoring Aware Commit Review Chrome Extension (Version: 2.0.4).
RefactoringMiner (Version 3.0.4) maven dependency.

## Description
Following are some refactoring using Foreach loop which can’t be detected by RefactoringMiner by far:
1. Commit URL: https://github.com/TakahikoKawasaki/nv-websocket-client/pull/185/commits/b38e5714e754382136fe7db22b0c7c29da9a8825

File URL: https://github.com/TakahikoKawasaki/nv-websocket-client/pull/185/commits/b38e5714e754382136fe7db22b0c7c29da9a8825#diff-3988986baa164e2e7bff8990843f6f522f1e311fa11009ea18deef8ea29b8273

Screenshot:
 
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/9f9e9c6c-5755-4385-8e96-1ae97143d2e4)

2. Commit URL: https://github.com/apache/camel-kafka-connector/pull/678/commits/3d7a0b8f2ae04d7857397fc5ed4d4bb5e857d34c

File URL: https://github.com/apache/camel-kafka-connector/pull/678/commits/3d7a0b8f2ae04d7857397fc5ed4d4bb5e857d34c#diff-92fac77733338b050bef1c026e76eaa018d0800bcf75255278e0c9713222868c

Screenshot:
 
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/0d0f6920-52f7-4e53-b951-c665dfd01119)

**Comment by tsantalis** [comment]
@simpt5 @pouryafard75 

The `for` statements are actually matched by RefactoringMiner, despite having a different AST type.
Below you can see how the AST diff looks like.

![Screenshot from 2024-03-25 10-06-53](https://github.com/tsantalis/RefactoringMiner/assets/1483516/26a76a2a-4cc1-4f71-9cd0-3ef2273fe3e2)

![Screenshot from 2024-03-25 10-00-12](https://github.com/tsantalis/RefactoringMiner/assets/1483516/7b7fb7fc-cc48-4db9-8a46-e13ba694a6f1)
