### ISSUE TITLE
Call for support about refactoring using ternary conditional operator

### ISSUE THREAD

**Issue by simpt5** [tsantalis/RefactoringMiner#684]
## Issue content:
Refactoring using ternary conditional operator is not supported by RefactoringMiner currently. So, could it possibly be supported in the future considering the prevalent usage for this kind of Java language feature.

## Tested tools and version:
Refactoring Aware Commit Review Chrome Extension (Version: 2.0.4).
RefactoringMiner (Version 3.0.4) maven dependency.

## Description
The following are some refactoring using ternary conditional operator which can’t be detected by RefactoringMiner for now:
1.	Ternary conditional operator
1.1 Commit URL: https://github.com/Frann0/fravaer/pull/25/commits/79131373dc3ec8be59228fe8882afd6e94b01e42

File URL:
https://github.com/Frann0/fravaer/pull/25/commits/79131373dc3ec8be59228fe8882afd6e94b01e42#diff-5173c891f817e5ccc12daff9403fbac1bf9c26a18fe8b5b919819fd856ce52a2

Screenshot:
 
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/e17e1d0d-61d0-482b-8258-5aa41357fa0c)

1.2	Commit URL: https://github.com/JetBrains/android/pull/1/commits/f09ab2f26685aece483e74fdbf31275bc34b9f3d

File URL:
https://github.com/JetBrains/android/pull/1/commits/f09ab2f26685aece483e74fdbf31275bc34b9f3d#diff-23beeb3fb180735103f464d3f20129857e5ec738f647bc367ae24b439b074273

Screenshot:
 
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/d6ca6a07-5766-4a27-b78e-7eb60a628755)

**Comment by tsantalis** [comment]
@simpt5

The mappings of sub-expressions has been improved in the AST diff, as shown in the screenshots.
It would be possible to report a `Replace Conditional with Ternary` refactoring

![Screenshot from 2024-03-29 17-30-39](https://github.com/tsantalis/RefactoringMiner/assets/1483516/ff707b95-2ab1-4776-8e7a-6d3708cb731c)

![Screenshot from 2024-03-29 17-31-49](https://github.com/tsantalis/RefactoringMiner/assets/1483516/6187aa0d-b33e-4d57-83b7-41bfd24498dc)
