### ISSUE TITLE
Call for support about refactoring based on Try-with-resources

### ISSUE THREAD

**Issue by simpt5** [tsantalis/RefactoringMiner#685]
## Issue content:
Currently, refactoring using Try-with-resources in Java is not supported by RefactoringMiner. Could it possibly be supported in the future considering the prevalent usage for this Java language feature.

## Tested tools and version:
Refactoring Aware Commit Review Chrome Extension (Version: 2.0.4).
RefactoringMiner (Version 3.0.4) maven dependency.

## Description
The following is a refactoring using Try-with-resources which can’t be detected by RefactoringMiner:
1.	Try-with-resources
Commit URL: https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/259/commits/777fab8c6a202d7682c3e702e4fb87e974092b29

File URL: https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/259/commits/777fab8c6a202d7682c3e702e4fb87e974092b29#diff-43eff33928dd116bcc512facf912524a8c1a900c1d65ad15fec4599e2c326e6b

Screenshot:
 
![image](https://github.com/tsantalis/RefactoringMiner/assets/163680970/7389930d-e533-4d4b-ae5a-978329efa9cd)

**Comment by tsantalis** [comment]
@simpt5
The corresponding `try` blocks are actually getting matched as shown in the screenshot.

![Screenshot from 2024-04-01 09-09-08](https://github.com/tsantalis/RefactoringMiner/assets/1483516/d42b7fb8-f610-46de-83f9-654b9278c73a)
