### ISSUE TITLE
Detected method extraction is reported twice

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#686]
http://lab:4000/refactoring/260/15388201

http://lab:4000/refactoring/260/15388200

<img width="1414" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/11022419/138420be-4110-4574-9c06-ea95e1d352d3">

The method at
https://github.com/hazelcast/hazelcast/commit/ffa1d33cd2b4dcacbc48b752aaead7eb3a956276#diff-6c2709c8310d1fad31023d77c616ab752614814b7d811abb8151eebbcb254374R178-R182
has two associated extract method refactoring.
The first is mapped to the invocation at:
https://github.com/hazelcast/hazelcast/commit/ffa1d33cd2b4dcacbc48b752aaead7eb3a956276#diff-6c2709c8310d1fad31023d77c616ab752614814b7d811abb8151eebbcb254374R172-R172
The second is mapped to the invocation at:
https://github.com/hazelcast/hazelcast/commit/ffa1d33cd2b4dcacbc48b752aaead7eb3a956276#diff-6c2709c8310d1fad31023d77c616ab752614814b7d811abb8151eebbcb254374R124-R124

**Comment by tsantalis** [comment]
@victorgveloso 
I checked all refactorings and they are correct.
The same method `createMessageTask` is extracted from multiple different tests.

@pouryafard75 
`new` is not getting matched

![image](https://github.com/tsantalis/RefactoringMiner/assets/1483516/0ba89eb8-83c2-461f-bb37-34b30583f871)

**Comment by victorgveloso** [comment]
@pouryafard75 just explained me that RMiner reports one extracted method refactoring for each method invocation and that is the intended behaviour. 

I don't know if that changed recently, but getExtractedOperationInvocations returns an ArrayList hence why I assumed that array could contain multiple values. Instead it always contain a single invocation as the refactoring is split by invocation.
