### ISSUE TITLE
Merge Commits

### ISSUE THREAD

**Issue by oguzhantortop** [tsantalis/RefactoringMiner#693]
hi,
In refactoring Miner read.me for detectBetweenCommits it is written that:

"You can also analyze between commits using detectBetweenCommits or between tags using detectBetweenTags. RefactoringMiner will iterate through all non-merge commits from start commit/tag to end commit/tag."

I have some questions regarding this:
1) Same non-merge commit constraint applies for detectAll method? I have noticed that while calling handle(String commitId, List<Refactoring> refactorings) methods Refactoring Miner skips some of the commits. But also commits with empty Refactoring List is also supplied to this callback.
2) The reason that why we can't have refactorings for merge commits in my opinion might be merge commits has multiple parent commits. Is that why we can't have refactorings in merge commits?

Thank you.

**Comment by tsantalis** [comment]
Hi @oguzhantortop

The reason merge commits are excluded is explained in our CASCON 2013 [paper](https://users.encs.concordia.ca/~nikolaos/publications/CASCON_2013.pdf) under Section 3.2.
Analyzing the complete commit history including merge commits would result in duplicate refactorings being reported (i.e., the same refactorings reported twice, once in the commit they actually occurred and once in the merge commit merging the actual commit on the main branch).

In the current implementation, all `GitServiceImpl` APIs exclude merge commits
[createRevsWalkBetweenTags](https://github.com/tsantalis/RefactoringMiner/blob/master/src/main/java/org/refactoringminer/util/GitServiceImpl.java#L235)
[createRevsWalkBetweenCommits](https://github.com/tsantalis/RefactoringMiner/blob/master/src/main/java/org/refactoringminer/util/GitServiceImpl.java#L257)
[DefaultCommitsFilter used by createAllRevsWalk](https://github.com/tsantalis/RefactoringMiner/blob/master/src/main/java/org/refactoringminer/util/GitServiceImpl.java#L271)

These three methods are used by the `detectBetweenTags`, `detectBetweenCommits`, and `detectAll` APIs, respectively.
