### ISSUE TITLE
Missed Move Methods

### ISSUE THREAD

**Issue by MatinMan** [tsantalis/RefactoringMiner#7]
Project Name: argoUML
Source: https://github.com/danilofes/argouml-refactorings.git
Commit hash: f7daed39b7096a537d138c60b7429affaec368d6
Branch: master
Test Case: https://github.com/MatinMan/Refactoring/blob/master/Reporting/argoUML/argouml_mm.md#tools-evaluation

Refactoring Miner1 missed the following case:
canEdit: Moved from FigInclude to SelectionActor 

Project Name: aTunes
Source: https://github.com/danilofes/atunes-refactorings.git
Commit hash: d2bcdb51d88f25a35e37342389ba09bcc52ddba9
Branch: master
Test Case: https://github.com/MatinMan/Refactoring/blob/master/Reporting/aTunes/aTunes_mm.md#tools-evaluation

Refactoring Miner1 missed the following case:
isSongFavorite(final IFavorites favorites, final String artist, final String title): moved from FavoritesSongsManager to FavoritesObjectDataStore

Test cases already exist in the TestRecal class

**Comment by tsantalis** [comment]
The second case is detected as
Extract And Move Method `public isSongFavorite(favorites IFavorites, artist String, title String) : boolean` extracted from `public isSongFavorite(favorites IFavorites, artist String, title String) : boolean` in class `net.sourceforge.atunes.kernel.modules.favorites.FavoritesSongsManager` & moved to class `net.sourceforge.atunes.kernel.modules.favorites.FavoritesObjectDataStore`
