### ISSUE TITLE
Sort files in a tree / similar to GitHub

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#702]
My case: https://github.com/JabRef/jabref/pull/11180/files

I want to add review comments on files. Since there are 30 files, it is hard to find the other file if the ordering of files does not match. I would like to see the same ordering in RFM and in GitHub

GitHub:

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/d8288915-9996-4779-a95f-53b359b76423)

RFM:

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/599196ac-b89c-4534-beca-bca27b9f21da)

I think, the GitHub ordering is good, because it orders first as folders, then as file names. Maybe, RFM can adapt that ordering, too?

**Comment by tsantalis** [comment]
@koppor
This is how the updated UI looks like. We are still working on it to make it more functional and user-friendly.

![Screenshot from 2024-04-15 19-42-03](https://github.com/tsantalis/RefactoringMiner/assets/1483516/9f9a57e3-ab1d-4b54-85e1-fba9df6491a5)

**Comment by koppor** [comment]
@tsantalis Nice! - The indent could be less, then the white space could be used to display additional information. Maybe a next step could be to be more similar to github and show the diff on the right side of the tree.

Maybe interesting link: Feedback to the GitHub tree is collected at https://github.com/orgs/community/discussions/12341.

**Comment by tsantalis** [comment]
@koppor

Tree file view updates:
- [X] The folders can be expanded and collapsed
- [X] The files are decorated with icons showing if the file is `modified` or `moved/renamed`

![Screenshot from 2024-04-20 02-36-03](https://github.com/tsantalis/RefactoringMiner/assets/1483516/f823736d-6850-4224-afb2-fe4ef1b7d573)

![Screenshot from 2024-04-20 02-37-50](https://github.com/tsantalis/RefactoringMiner/assets/1483516/64019817-fc34-427b-8020-c9e18a1bbf2c)

**Comment by tsantalis** [comment]
- [X] Add vertical lines to show clearly the nesting of folders

![image](https://github.com/tsantalis/RefactoringMiner/assets/1483516/35b8d969-6137-47a9-900f-a209f0238c7b)

**Comment by koppor** [comment]
Looks nice!

Intuitively, I clicked on the file name and nothing happens. I was expecting that the MonacoDiff shows up.

**Comment by tsantalis** [comment]
@koppor 
This is the way we would like eventually to do it. Clicking on the file name should open the diff.
And also have the file tree as a left-side panel, so that the diff loads directly on the right side.

I will try as a temporary solution to open the monaco diff when clicking on the name.

**Comment by tsantalis** [comment]
@koppor 
Added hypelink on the file name opening the monaco diff by default.

![Screenshot from 2024-04-25 21-38-33](https://github.com/tsantalis/RefactoringMiner/assets/1483516/21efeff5-ce1c-4097-9f89-ece1f85a9c6e)

**Comment by koppor** [comment]
@tsantalis Thank you for the quick action taken. I always need to wait until Mondays for a new Docker build to try out. 😅

**Comment by tsantalis** [comment]
@koppor 
I also updated the way the renamed files are displayed. I will push a new Docker images in a few minutes

![Screenshot from 2024-04-26 05-25-32](https://github.com/tsantalis/RefactoringMiner/assets/1483516/d8c69432-2f8a-41cf-9a52-facc9e89e744)

**Comment by koppor** [comment]
To keep the number of issues low, I close this.

The current solution works good. The "endless scrolling" requirement is outlined at https://github.com/tsantalis/RefactoringMiner/issues/672#issuecomment-2075100158 and will behandled there.
