### ISSUE TITLE
CLI option for PR review

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#704]
It would be nice if RM could directly support PR view. Checking https://github.com/tsantalis/RefactoringMiner?tab=readme-ov-file#running-refactoringminer-from-the-command-line, it currently does not.

Wish: CLI option: `diff --pr 11158`

Then, RM checks the default remote for finding the pr `11158`. When found, fetch the commits. Set the target branch as src and the PR source branch as dst. I made good experiences with https://github-api.kohsuke.org/, maybe this is a quick win. (Side note: I used that API at https://github.com/koppor/github-contributors-list/tree/main).

**Comment by tsantalis** [comment]
@koppor

These are the diff command line options

> ./RefactoringMiner diff -h
> You can run the diff with the following options:
>     --url <commit-url>                           		      Run the diff with a GitHub commit url
>     --url <pr-url>                               		      Run the diff with a GitHub PullRequest url
>     --src <folder1> --dst <folder2>            		              Run the diff with two local directories
>     --repo <repo-folder-path> --commit <commitID>  		      Run the diff with a locally cloned GitHub repo
> 
> To export the mappings/actions, add --export to the end of the command.

For a PR, you can run it as
./RefactoringMiner diff --url https://github.com/JabRef/jabref/pull/11180

You will need to create a file named `github-oauth.properties`, which includes a single line starting as
`OAuthToken=`
followed by your own GitHub OAuth token

**Comment by tsantalis** [comment]
@koppor

I updated the documentation with the AST diff command line options
https://github.com/tsantalis/RefactoringMiner?tab=readme-ov-file#ast-diff-command-line-options

**Comment by koppor** [comment]
Thank you for the support @tsantalis 

> You will need to create a file named `github-oauth.properties`, which includes a single line starting as `OAuthToken=` followed by your own GitHub OAuth token

Would it also be possible that RM uses ~/.github and `oauth=` as source? This is the format the [GitHub API for Java](https://github-api.kohsuke.org/) uses when not configured (in Java) at all. See https://github.com/koppor/github-contributors-list/blob/d83bc2670ad01abfd53cd80b9cc2f8c707dcea54/gcl.java#L145 for an example.

OK, doesn't help here with docker, because I would need to route my home directory.

However, the `ENV` `GITHUB_OAUTH` should work.

OK, this works, if `github-oauth.properties` exists in `/diff` and contains something invalid 🤣.

```
C:\Users\koppor\rmc>docker run -p 6789:6789 -v c:\users\koppor\rmc:/diff tsantalis/refactoringminer diff --url https://github.com/JabRef/jabref/pull/11180
java.io.IOException: Failed to resolve credentials from ~/.github or the environment.
        at org.kohsuke.github.GitHubBuilder.fromCredentials(GitHubBuilder.java:78)
```

(`c:\users\koppor\rmc` contains the file)


> For a PR, you can run it as
> 
> > ./RefactoringMiner diff --url [JabRef/jabref#11180](https://github.com/JabRef/jabref/pull/11180)

Nice! Thank you for the hint!

**Comment by pouryafard75** [comment]
@koppor Just to clarify, `OAuthToken` as env variable should work always. Let me know if the issue hasnt been resolved.

**Comment by koppor** [comment]
@pouryafard75 you are right. My bad.

Following command line worked

    docker run -p 6789:6789  --env OAuthToken=ghp_xxx tsantalis/refactoringminer diff --url https://github.com/openjdk/jfx/commit/974bf468c8261c61f8087aa6132824993ae89afd
