### ISSUE TITLE
Keyboard shortcuts should be disabled if find mode is on

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#705]
Browser: Firefox

I am used to press <kbd>Ctrl</kbd>+<kbd>F </kbd>to find something.

1.  diff --url https://github.com/JabRef/jabref/pull/11180
2. Select `src/main/java/org/jabref/gui/JabRefFrame.java`
3. Press <kbd>Ctrl</kbd>+<kbd>F </kbd>
4. Type `c`
5. Result: (OK)
    ![grafik](https://github.com/tsantalis/RefactoringMiner/assets/1366654/b82a5392-ae7b-40dd-bfa4-e0d17adda9d5)
6. Type `l`
7. Search closes and the file overview is shown

Expected result: Search continues.

Workaround: Press back in the browser, continue typing in the search popup.

**Comment by tsantalis** [comment]
@koppor
This issue has been fixed
