### ISSUE TITLE
constant change

### ISSUE THREAD

**Issue by wangsiqidahaoren** [tsantalis/RefactoringMiner#718]
If an extract method refactoring occurs with an inner constant change. Does RefactoringMiner2.0 considered this as a refactoring operation? @tsantalis

**Comment by tsantalis** [comment]
@wangsiqidahaoren
Do you have a commit where such a change happened?
RefactoringMiner could detect such a refactoring, but I am not sure if the extract method detection is running for constant initializers. I need to check this. If you have a commit, it would help a lot.

**Comment by wangsiqidahaoren** [comment]
Sorry I dn't have such a commit, I am just interest of this kind of situation

**Comment by tsantalis** [comment]
This is fine. Can you please at least provide an artificial example within the issue with some code, so that I can understand better the change scenario?

**Comment by tsantalis** [comment]
@wangsiqidahaoren 
I am closing the issue due to missing input.
