### ISSUE TITLE
Proper handling of newlines when parsing comments

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#725]
I am investigating another "interesting" PR (https://github.com/koppor/jabref/pull/687)

I noticed that comments are now handled. Thank you for that!

It would be great if RefactoringMinor could handle newlines. Currently, if "only" line breaks change, it is determined as deleted/new - not as moved:

![grafik](https://github.com/tsantalis/RefactoringMiner/assets/1366654/8f902f1b-10b6-4fc4-b5cb-69177695c481)

**Comment by tsantalis** [comment]
Move code from `main` to `initLogging`

![Screenshot from 2024-05-27 15-21-00](https://github.com/tsantalis/RefactoringMiner/assets/1483516/3cc3a58e-926d-4621-9527-86ef75592e27)

**Comment by tsantalis** [comment]
@koppor 

It's really cool the tool finds that `routeLoggingToSlf4J` and `addLogToDisk` have been merged to `initLogging`
On top of that `initializeLogger` has been inlined to `initLogging`.

This is a challenging case, but our tool did pretty well !!

**Comment by tsantalis** [comment]
Diff after supporting move code from `main` to `initLogging`
![Screenshot from 2024-05-28 05-54-05](https://github.com/tsantalis/RefactoringMiner/assets/1483516/dd9a191f-a2eb-4021-a09f-3755a4423ae3)

**Comment by tsantalis** [comment]
@koppor @pouryafard75 
The javadoc is matched as follows:

![Screenshot from 2024-05-28 20-03-14](https://github.com/tsantalis/RefactoringMiner/assets/1483516/cffff696-aa65-401f-be9d-2641fc938aa7)

![Screenshot from 2024-05-28 20-05-56](https://github.com/tsantalis/RefactoringMiner/assets/1483516/b0283d4f-8774-466b-abde-59b63a6c34fb)

**Comment by tsantalis** [comment]
@koppor @pouryafard75 

![image](https://github.com/tsantalis/RefactoringMiner/assets/1483516/c72e2027-55cd-4875-a25a-3e0a627184c7)

This issue has been fixed to perfection!
Thanks Pouria for your nice implementation.
