### ISSUE TITLE
Click on non-touched lines should also scroll

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#726]
Currently, when clicking on deleted and inserted, the views sync.

When clicking on non-touched lines, nothing happens.

Wish: Clicking on non-touched lines, the other view should scroll to that position.

(This is a workaround for https://github.com/tsantalis/RefactoringMiner/issues/672)

**Comment by tsantalis** [comment]
@koppor 

**Double-clicking** on non-touched lines auto-scrolls and aligns the editors.

**Comment by koppor** [comment]
> @koppor 
> 
> **Double-clicking** on non-touched lines auto-scrolls and aligns the editors.

Oh, and for the touched ones a single click? Why this UI difference? 😅
