### ISSUE TITLE
Proper handling of "default"

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#746]
I got another "interesting" pull request: https://github.com/JabRef/jabref/pull/11282.

I think, RefactoringMiner does not properly handle "default". Without any change in the letters, it is marked as removed and added:

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/d617bf4d-a4a9-4ecb-a37a-277337a85f03)

---

Side note (not related to the issue itself, but to the linked pull request): In general, my wish is "endless scrolling" and not only synchronized scrolling as requested at https://github.com/tsantalis/RefactoringMiner/issues/672

**Comment by tsantalis** [comment]
@koppor 
Thank you for reporting the issue.

@pouryafard75 
It seems we do not process the `default` keyword.

**Comment by tsantalis** [comment]
@koppor 
We are currently working on the feature to hide the unchanged parts of the code, similar to GitHub.

The endless scrolling feature will be the next one to implement.

**Comment by tsantalis** [comment]
@koppor 

We also improved the diff of formatting changes in Javadoc.

![image](https://github.com/tsantalis/RefactoringMiner/assets/1483516/26404dc3-b92b-4c3a-8739-68fab9badd6e)
