### ISSUE TITLE
"Next" should be dislabed if the last file is reached

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#751]
Up for discussion.

In my view, "Prev" and "Next" imply some order. A list. If the end of the list is reached, I would expect that there is no "Next". Thus, the button should be disabled. - Similar on GitHub with endless scrolling. At the real end of the changes, there is no wrap around to the beginning.

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/a9c8cee1-d0d9-4f63-92b9-145f72ad78fb)

---

It would be nice to show the number of upcoming files in braces - or as tooltip "10 file(s) left"

**Comment by tsantalis** [comment]
@koppor 

`Prev` and `Next` buttons are disabled, and also show how many diffs remain to be inspected. Thanks @pouryafard75 

![image](https://github.com/tsantalis/RefactoringMiner/assets/1483516/6971dc70-40ad-4eb3-b6f5-48e7880ba52b)

![image](https://github.com/tsantalis/RefactoringMiner/assets/1483516/6b458701-b38d-46e5-8372-e2568a3172f5)

![image](https://github.com/tsantalis/RefactoringMiner/assets/1483516/548003fe-84ea-400b-b148-b8eecc98aa69)

**Comment by koppor** [comment]
Thank you all for the action taken! 👍
