### ISSUE TITLE
Repository Can not Resolve

### ISSUE THREAD

**Issue by Farhat47** [tsantalis/RefactoringMiner#78]
Hello 

After I added RefactoringMiner-1.0.jar to my project I got this error that "Can not Resolve symbol Repository"
Has someone any idea how could this problem solved?

Thanks in advance

**Comment by tsantalis** [comment]
Try adding it as a Maven dependency
https://github.com/tsantalis/RefactoringMiner#how-to-use-refactoringminer-as-a-maven-dependency
