### ISSUE TITLE
Support inline comment diff

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/RefactoringMiner#785]
In commit
https://github.com/junit-team/junit4/commit/8226e3e64a7d4ace29eb08ab6c9fc9d4055f20c9#diff-4eb3b874a09430f86c048deff28238d9e68ace7807efb6769604379d5790bd78

`src/org/junit/experimental/theories/internal/AllMembersSupplier.java` ->
‎`src/main/java/org/junit/experimental/theories/internal/AllMembersSupplier.java`

there is a single comment added, but our diff is empty.

![image](https://github.com/user-attachments/assets/f6603ab5-1229-4062-969b-79ec1f51864a)

@pouryafard75 
Let's add our own build of GumTree 4, and implement the comment diff.

**Comment by tsantalis** [comment]
@pouryafard75 
The comment is added in method `getValueSources()`
so you should get the commentListDiff from the bodyMapper for this method.

![image](https://github.com/user-attachments/assets/ed58a0fe-a2a9-4d6a-82ed-27807e4267f7)

`classDiff.getCommentListDiff()` returns comment diffs for comments directly within the class body (not inside methods).

Also the bodyMappers of Extract Method and Inline Method refactorings may have comment mappings. These are comments that are extracted/inlined along with code.

**Comment by pouryafard75** [comment]
Ok understood.
https://github.com/Alluxio/alluxio/commit/0ba343846f21649e29ffc600f30a7f3e463fb24c

Is this one also reported? If yes, where?
<img width="1118" alt="image" src="https://github.com/user-attachments/assets/054176b0-9d26-491f-9dde-6f126f84344a">

**Comment by pouryafard75** [comment]
You can merge the [PR](https://github.com/tsantalis/RefactoringMiner/pull/786l).

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/66c0ea09-e091-4bb4-bb80-f9f1f43fac79">

**Comment by tsantalis** [comment]
@pouryafard75 
A classDiff may have packageDeclaration JavadocDiff and commentListDiff
`private Optional<UMLJavadocDiff> packageDeclarationJavadocDiff;`
`private UMLCommentListDiff packageDeclarationCommentListDiff;`

This is for whatever exists before the package declaration.
However the case you have is a whitespace change. I am not sure if we skip whitespace changes.

**Comment by pouryafard75** [comment]
Please merge the PR after the tests. We can continue working on that.

**Comment by tsantalis** [comment]
@pouryafard75 
We have a problem with this commit, which has only comment changes. The diff is empty.
https://github.com/apache/commons-lang/commit/835085d91

**Comment by tsantalis** [comment]
@pouryafard75 

You should just call `classDiff.getPackageDeclarationCommentListDiff()` and it gets generated on demand.

```
public UMLCommentListDiff getPackageDeclarationCommentListDiff() {
	if(packageDeclarationCommentListDiff == null)
		packageDeclarationCommentListDiff = new UMLCommentListDiff(getOriginalClass().getPackageDeclarationComments(), getNextClass().getPackageDeclarationComments());
	return packageDeclarationCommentListDiff;
}
```

**Comment by tsantalis** [comment]
@koppor @pouryafard75 
I can confirm that we match accurately comments extracted to new methods

![image](https://github.com/user-attachments/assets/b5ec1c2a-8334-4b6e-84fc-f89a55bcc7af)

![image](https://github.com/user-attachments/assets/708e1a8e-b6ee-4778-9c65-eb86571f6dbd)

And also comments moved due to control flow restructuring

![image](https://github.com/user-attachments/assets/b5c0b06d-f6d3-4700-94ae-7e3e8acb2f44)

**Comment by tsantalis** [comment]
@koppor @pouryafard75 
We also support comment multi-mappings when duplicated code is merged into a single copy.

![image](https://github.com/user-attachments/assets/569c0218-7070-493a-873e-581faa86785f)
