### ISSUE TITLE
Enable search for diff

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#787]
I am currently reviewing https://github.com/JabRef/jabref/pull/11831

I have the langauge diff

```diff
+Parser\ choice\:=Parser choice:
```

I want to know where the string is used.

I would like to have a search in the text of the dispalyed diff in refactoring miner. (Because the browser html search is not htat usable)

OK, it might that this string is in the `fxml` files, which Refactoring Miner does not support. Nevertheless, a search would be nice.

**Comment by tsantalis** [comment]
@koppor 
You can open the browser search by clicking somewhere out of the diff windows and then CTRL + F

![image](https://github.com/user-attachments/assets/1ad85324-591d-457a-8292-a38b47217e9d)

**Comment by koppor** [comment]
> @koppor 
> You can open the browser search by clicking somewhere out of the diff windows and then CTRL + F
> 

I tried. Not that usable. I tried to express with „(Because the browser html search is not htat usable“.

Will try to refine the issue with a better description of short comings and wishes. 

Until then, I close to keep the number of issues low.

**Comment by tsantalis** [comment]
Support Stream API pipeline split into two methods

Move And Rename Method	`public performSearch(searchQuery String) : List<BibEntry>` from class `org.jabref.logic.importer.fetcher.GrobidCitationFetcher` to `public parseSeveralPlainCitations(text String) : List<BibEntry>` from class `org.jabref.logic.importer.plaincitation.SeveralPlainCitationParser`

Extract Method	`public splitCitations(text String) : Stream<String>` extracted from `public performSearch(searchQuery String) : List<BibEntry>` in class `org.jabref.logic.importer.plaincitation.SeveralPlainCitationParser`

Rename Parameter	`searchQuery : String` to `text : String` in method `public parseSeveralPlainCitations(text String) : List<BibEntry>` from class `org.jabref.logic.importer.plaincitation.SeveralPlainCitationParser`

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/33ba5ba6-9fcf-4002-b0b6-d9444e715c7e" />
