### ISSUE TITLE
Change Variable Type reported incorrectly

### ISSUE THREAD

**Issue by ameyaKetkar** [tsantalis/RefactoringMiner#79]
For the [commit](https://github.com/speedment/speedment/commit/e4128e95053a333a1a2bf8db03ca5e0f5b0b836f), RMiner reports Change Variable type - speedment : Speedment to dbmsHandlerComponent : dbmsHandlerComponent. 
My diagnosis: 
*  [speedment : Speedment](https://github.com/speedment/speedment/commit/e4128e95053a333a1a2bf8db03ca5e0f5b0b836f#diff-19b24c83c1b92d31975ef2dbed747373L161) is a parameter of the method readFromResultSet(Speedment, Column, AtomicInteger
* [dbmsHandlerComponent : dbmsHandlerComponent] is  new added field in the same class.
* This could be a **Replace Variable With Attribute** + **Change Type**

**Comment by tsantalis** [comment]
It is reported as Replace Variable With Attribute + Change Variable Type refactorings.
@ameyaKetkar Do you mean it should be reported as a single refactoring?
