### ISSUE TITLE
Avoid coloring leading whitespace

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/RefactoringMiner#794]
Request by @dmazinanian 

![image](https://github.com/user-attachments/assets/28a5cec7-060f-4ce2-84e8-237f52cb23b2)

![image](https://github.com/user-attachments/assets/3d9ffcf1-3b40-4b59-8b19-da08874569a2)

**Comment by tsantalis** [comment]
@dmazinanian 
leading whitespace is no longer colored. Thank you @pouryafard75 

![image](https://github.com/user-attachments/assets/4000d37b-bb1a-4262-9861-7fb5bdefc033)

**Comment by dmazinanian** [comment]
This is great, thanks for the quick turnaround!
