### ISSUE TITLE
nonMappedLeavesT1/nonMappedLeavesT2 lists present mapped elements.

### ISSUE THREAD

**Issue by xuyisen** [tsantalis/RefactoringMiner#798]
### Commit link
* https://github.com/google/gson/commit/08174e201980698a89f5f5996e10617d89ff09e1
### Problem
Professor Nikalaos,
   When I used the latest version of **RefactoringMiner** to detect pure refactoring of `gson` project, I found that several attributes of `bodyMapper` may conflict. `nonMappedLeavesT1` and `nonMappedLeavesT2` should store statements without mapping relationship, but I found that `mappings `already have three leave statements, which appeared again in `nonMappedLeavesT1` and `nonMappedLeavesT2`. This caused problems when I analyzed pure operation. Is this a problem?
![QQ_1731099963981](https://github.com/user-attachments/assets/faa2add9-8d26-477b-b12b-77c037464a6d)
![QQ_1731100036171](https://github.com/user-attachments/assets/f80c79c8-8f6e-4802-9316-d7718ea1d744)

Yisen Xu from course SOEN6491

**Comment by tsantalis** [comment]
@xuyisen 
These are nested lambda expressions, within matched statements.

**Comment by xuyisen** [comment]
Thank you, Professor. I got it. Is it possible to map these lambda expressions as well, i.e. move them to the mappings property? Because they do look the same in terms of expression.

**Comment by tsantalis** [comment]
@xuyisen 
I fixed it with my last commit. You should not have nonMappedLeaves now. Please confirm.

**Comment by xuyisen** [comment]
Thank you, Professor. I pulled the latest code, re-ran the program on this commit, and now it works fine.
