### ISSUE TITLE
RefactoringMiner 3.0 stuck on a commit in xstream open-source library.

### ISSUE THREAD

**Issue by waheed-sep** [tsantalis/RefactoringMiner#802]
I am running RefactoringMiner 3.0 on xstream (https://github.com/x-stream/xstream). First I download the repo to my computer, then I ran the RefactoringMiner as:
```RefactoringMiner -a . master -json refs.json``` on the above local repo.

The tool stucks at a specific commit. I don't know is there any way to skip that commit from analysis or set a timeout for all commits to be processed in that specific timeout.

I am using the tool on Windows 11.

**Comment by tsantalis** [comment]
@waheed-sep 

The commit it gets stuck seems to be
https://github.com/x-stream/xstream/commit/78601ea146c871127df5aacc5d1610832b236655

It is a bit strange, because the commit is no so large.
But it has some very weird classes `A50InnerClasses`, `A50StaticInnerClasses`

**Comment by tsantalis** [comment]
@waheed-sep 
The issue has been fixed.

**Total count: [Commits: 2893, Errors: 0, Refactorings: 15289]**

I managed to run the tool for all commits of the projects. 
It finishes in a couple of minutes. 
The resulting JSON file is 25 MB.

**Comment by waheed-sep** [comment]
Thank you so much @tsantalis for fixing the issue, now the tool is running smooth on the repo.
