### ISSUE TITLE
PurityChecker can't detect these pure refactorings.

### ISSUE THREAD

**Issue by xuyisen** [tsantalis/RefactoringMiner#805]
### Commit:
https://github.com/xuyisen/test-refactoringMiner/commit/105d58a6622d1a32bce48bca5a31cf5c07dbdbdf

### Description
Hi Professor,

I used PurityChecker to verify the purity of the LLM-generated refactoring. While I believe the refactoring is pure, PurityChecker seems to produce an incorrect result.
    
![image](https://github.com/user-attachments/assets/3793d82f-5de8-4803-bd70-9d8de50573b9)

![image](https://github.com/user-attachments/assets/bcd4e3ba-b563-473d-b8e9-ded2af687be1)

**Comment by tsantalis** [comment]
@xuyisen 

There was actually one remaining replacement that the tool could not tolerate, which is the change of method invocation
`isTrue` or `isFalse` to `isEqualTo`, as the tool does not know about equivalent/alternative APIs.

All other replacements (overlapping extract variable, rename of `f` to `field`, parameterize of `true` or `false` to `serialize` and `expected`, respectively) were already handled by the tool.

So, I hard-coded this specific equivalent/alternative API knowledge to report these refactorings as pure.
