### ISSUE TITLE
Reporting deletion/addition for the unchenged tokens

### ISSUE THREAD

**Issue by maorethians** [tsantalis/RefactoringMiner#806]
During extracting additions from [this commit](https://github.com/bazelbuild/bazel/commit/2d4c8eb79ea7d373127889e5e289ff0a99fd59c4), RM reports deletion and addition for exactly the same _modifier_ and _simpleName_ while it could match their surroundings.

![image](https://github.com/user-attachments/assets/f5a3b80c-49b1-436a-9918-0444fde500f8)

**Comment by tsantalis** [comment]
@pouryafard75 
It seems we don't support `sealed` and `permits`.

**Comment by pouryafard75** [comment]
@tsantalis The issue is on the core actually, I update diff wrappers accordingly after you introduce the API for classDiff.

**Comment by tsantalis** [comment]
@maorethians @pouryafard75 

The issue has been fixed

![image](https://github.com/user-attachments/assets/3bb5c25f-3cdf-4110-8708-b88240a2915c)
