### ISSUE TITLE
Reporting deletion/addition for comments of the matched elements

### ISSUE THREAD

**Issue by maorethians** [tsantalis/RefactoringMiner#807]
For both `ImmutableSortedMap.java` of [This Commit](https://github.com/google/guava/commit/8a1c90e7b34765d720b3711d4180526dde24c124), while RM mapped code elements and annotations, it could not map the exact same comments and reported them as deletion/addition:
![image](https://github.com/user-attachments/assets/d1f8e419-f768-4d90-aa0e-d8384141fa75)

**Comment by tsantalis** [comment]
@maorethians 
This issue has been fixed
