### ISSUE TITLE
Reporting deletion/addition for "}" with INITIALIZER type

### ISSUE THREAD

**Issue by maorethians** [tsantalis/RefactoringMiner#808]
In [This Commit](https://github.com/bazelbuild/bazel/commit/91673a2c11d64b1ec21bf1edfe35a242a7daa569):
![image](https://github.com/user-attachments/assets/57fb674d-c0a0-4a2b-9706-244d972fc77c)

**Comment by tsantalis** [comment]
@pouryafard75 
This looks like AST diff related, because the record declaration is matched.
