### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by danielogen** [tsantalis/RefactoringMiner#810]
Repo: [apache/flink](https://github.com/apache/flink)
Commit: [27287a1](https://api.github.com/repos/apache/flink/commits/27287a1)

Refactoring Miner Version: 3.0.9
Java Version: openjdk64-17.0.12

> java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.UMLType.matchWithParentClassTypeParameterChange(gr.uom.java.xmi.UMLType, java.util.Set)" because the return value of "gr.uom.java.xmi.decomposition.VariableDeclaration.getType()" is null
> 	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.equalType(VariableReplacementAnalysis.java:502)
> 	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.findVariableMerges(VariableReplacementAnalysis.java:1585)
> 	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.<init>(VariableReplacementAnalysis.java:159)
> 	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.computeRefactoringsWithinBody(UMLOperationBodyMapper.java:3084)
> 	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getRefactorings(UMLOperationBodyMapper.java:3034)
> 	at gr.uom.java.xmi.decomposition.ReplacementAlgorithm.processLambdas(ReplacementAlgorithm.java:4737)
> 	at gr.uom.java.xmi.decomposition.ReplacementAlgorithm.processAnonymousAndLambdas(ReplacementAlgorithm.java:4655)
> 	at gr.uom.java.xmi.decomposition.ReplacementAlgorithm.findReplacementsWithExactMatching(ReplacementAlgorithm.java:1425)
> 	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:5616)
> 	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:1237)
> 	at gr.uom.java.xmi.diff.UMLAttributeDiff.init(UMLAttributeDiff.java:137)
> 	at gr.uom.java.xmi.diff.UMLAttributeDiff.<init>(UMLAttributeDiff.java:53)
> 	at gr.uom.java.xmi.diff.UMLClassDiff.processAttributes(UMLClassDiff.java:26)
> 	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:165)
> 	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)

**Comment by tsantalis** [comment]
Hi @danielogen 

It seems the issue has been fixed after version 3.0.9.
This is the diff I just generated for https://github.com/apache/flink/commit/27287a1
You can either build RefactoringMiner from the latest commit, or wait for the new release, which will include the bug fix.

![image](https://github.com/user-attachments/assets/ab81acf0-d98d-4768-baf0-c401e83c410c)

**Comment by danielogen** [comment]
Got it! Thank you @tsantalis
