### ISSUE TITLE
false positive in statementsInScopeUsingVariable

### ISSUE THREAD

**Issue by maorethians** [tsantalis/RefactoringMiner#822]
In the newly introduced `JksSslStoreBundle` method in `JksSslStoreBundle.java` file of [This Commit](https://github.com/spring-projects/spring-boot/commit/499672184c7bcb4e7932663985d3f4ae928ed59e), RefactoringMiner reports `Assert.notNull(resourceLoader,...)` as a usage of newly declared `resourceLoader` field while it is the usage of the method parameter with the same name:
![image](https://github.com/user-attachments/assets/c3e71013-ba52-4d07-8ef8-75efe6a13949)

**Comment by tsantalis** [comment]
@maorethians 
Yes, you are right.
If it is not `this.resourceLoader` and there is a parameter with the name `resourceLoader`, then we have a parameter access

**Comment by tsantalis** [comment]
@maorethians 
Can you please check if my fix works in some other cases too? I tested it only in the case you mention above.
