### ISSUE TITLE
false positive in findInvocationsInChildModel

### ISSUE THREAD

**Issue by maorethians** [tsantalis/RefactoringMiner#824]
In `PropertiesSslBundle.java` file of [This Commit](https://github.com/spring-projects/spring-boot/commit/499672184c7bcb4e7932663985d3f4ae928ed59e), there are two pairs of `get` methods, one working with `PemSslBundleProperties` and the other one is working with `JksSslBundleProperties`. However, the usage hierarchy reported by RefactoringMiner is as below:
![image](https://github.com/user-attachments/assets/41888501-47e5-45f6-a799-586f9e044a05)
Essentially, it does not consider the type of the provided parameters and reported the usage of the `get` method with `PemSslBundleProperties` parameter for `JksSslBundleProperties` method declaration and vice versa.

It is also the case for inter-class method invocations:
![image](https://github.com/user-attachments/assets/4b68de8f-3280-4882-ad4b-43943fa2cfeb)
While `properties` is of type `PemSslBundleProperties`, it reported `PropertiesSslBundle.get(...)` as an invocation of both `PemSslBundleProperties` and `JksSslBundleProperties` method declarations.

**Comment by tsantalis** [comment]
@maorethians 
I am very confused with the way you report the issue.

There are two `get` method declarations in [PropertiesSslBundle.java](https://github.com/spring-projects/spring-boot/commit/499672184c7bcb4e7932663985d3f4ae928ed59e#diff-d76d8c6ae728a7f8c886725ec85f5597140e17ec3c7ce3b9a2ccd935b19c87e5)

`public static SslBundle get(PemSslBundleProperties properties, ResourceLoader resourceLoader)`

`public static SslBundle get(JksSslBundleProperties properties, ResourceLoader resourceLoader)`

You are saying that these two are mixed up, when matching their calls.

**Comment by tsantalis** [comment]
I see there are two `Extract Method` refactorings happening in the file and one of them is misidentified.
