### ISSUE TITLE
AST diff not showing moved methods in case of Split Class

### ISSUE THREAD

**Issue by tsantalis** [tsantalis/RefactoringMiner#828]
https://github.com/checkstyle/checkstyle/commit/00769882831961af98ce009d82b435b118b7ca61
https://github.com/checkstyle/checkstyle/commit/cdf3e56bacd3895262af8a1df9ca5c81f4071970

The commits above have Split Class scenarios.
However, the moved methods are not shown properly.

![image](https://github.com/user-attachments/assets/59934678-bf17-4464-b6cc-174394aff1a8)
![image](https://github.com/user-attachments/assets/46d86ff2-c280-4a48-9690-f28adf3bb39b)

![image](https://github.com/user-attachments/assets/ae270a77-1d8f-41d2-b234-45a65a622709)

**Comment by tsantalis** [comment]
@pouryafard75 
Strangely, it only works well for the first method being moved between the two file.

**Comment by pouryafard75** [comment]
@tsantalis The first method is processed due to the rename method refactoring.

**Comment by tsantalis** [comment]
@pouryafard75 
The parameters are not getting matched!!

![image](https://github.com/user-attachments/assets/05bc8f6e-7762-4f3a-a2cb-fd8bcee4963c)
