### ISSUE TITLE
There exist a refactoring that can't be detected by RefactoringMiner

### ISSUE THREAD

**Issue by xuyisen** [tsantalis/RefactoringMiner#831]
## Commit
https://github.com/xuyisen/test-refactoringMiner/commit/f90e91de1dd1535cb70c76ed77c58bb35298206d

## Description
This refactoring is generated by LLM, but it can't be detected by RefactoringMiner.
![image](https://github.com/user-attachments/assets/e93e2c34-84fb-4abe-ab69-bae76118bf1f)

**Comment by tsantalis** [comment]
@xuyisen 
Thank you for reporting this problem. It has been fixed.
I will need to update the RefactoringMiner server to see this refactoring with the Chrome extension,
but it can be detected with the latest commit.
