### ISSUE TITLE
Reporting method invocations multiple times

### ISSUE THREAD

**Issue by maorethians** [tsantalis/RefactoringMiner#833]
In [This Commit](https://github.com/dbeaver/dbeaver/commit/fc4174608e241b8f05a3a5be555a9078565dcae6), RM used to report the invocations properly. However, right now for some of the methods, it reports the same invocations multiple times which results in situations like below:
![image](https://github.com/user-attachments/assets/ae28a656-9209-4f32-8b13-128ae348e289)

I think that I remember we didn't have such a problem before recent changes for the same commit.

You can use the specific method declaration and one of its reported invocations below to track the issue:
![image](https://github.com/user-attachments/assets/58dd6f66-95f9-4391-a419-033da52fe8ec)
Note that the id of each node is shown as a white label above it which contains the location info of the corresponding change.

**Comment by tsantalis** [comment]
@maorethians 
You know that I cannot copy paste information from figures.
Next time give me in text form these IDs you report.

**Comment by tsantalis** [comment]
For this method, there are 9 results, none of them is a duplicate:

1. `getRequestOffset()`  line range:99-99	`plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/semantics/completion/SQLQueryCompletionContext.java`
2. `getRequestOffset()`  line range:135-135	`plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/semantics/completion/SQLQueryCompletionContext.java`
3. `getRequestOffset()`  line range:137-137	`plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/semantics/completion/SQLQueryCompletionContext.java`
4. `getRequestOffset()`  line range:161-161	`plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/semantics/completion/SQLQueryCompletionContext.java`
5. `getRequestOffset()`  line range:267-267	`plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/semantics/completion/SQLQueryCompletionContext.java`
6. `getRequestOffset()`  line range:100-100	`plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/semantics/SQLQueryCompletionAnalyzer.java`
7. `getRequestOffset()`  line range:111-111	`plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/semantics/SQLQueryCompletionAnalyzer.java`
8. `getRequestOffset()`  line range:143-143	`plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/semantics/SQLQueryCompletionAnalyzer.java`
9. `getRequestOffset()`  line range:229-229	`plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/semantics/SQLQueryCompletionProposal.java`

**Comment by tsantalis** [comment]
@maorethians 
Your research has become art. Beautiful visualization!

**Comment by tsantalis** [comment]
@maorethians 
The only calls I found as duplicated are method references, such as `analyzer::getProposals`

**Comment by maorethians** [comment]
I tested `findInvocationsInChildModel` multiple times and its result is not consistent. I checked its output for `getRequestOffset` operation in `org.jkiss.dbeaver.model.sql.semantics.completion.SQLQueryCompletionContext` class and it returns different number of invocations:
![image](https://github.com/user-attachments/assets/0f2f23a9-b372-4e63-a453-54a8fc39e228)
![image](https://github.com/user-attachments/assets/6f380372-a920-4ab7-8af0-adb452e706a4)
![image](https://github.com/user-attachments/assets/750af2a3-a2bb-460b-8f13-f4c632c0a645)

**Comment by tsantalis** [comment]
@maorethians @pouryafard75 

This is the code I use to replicate, and it always returns the same **9 results**.
Can you try to run it?

```java
String url = "https://github.com/dbeaver/dbeaver/commit/fc4174608e241b8f05a3a5be555a9078565dcae6";
String repo = URLHelper.getRepo(url);
String commit = URLHelper.getCommit(url);
ProjectASTDiff projectASTDiff = new GitHistoryRefactoringMinerImpl().diffAtCommit(repo, commit, 10000);
        
UMLModelDiff modelDiff = projectASTDiff.getModelDiff();
for(UMLClassDiff classDiff : modelDiff.getCommonClassDiffList()) {
 if(classDiff.getOriginalClassName().endsWith(".SQLQueryCompletionContext")) {
  for(UMLOperation op : classDiff.getAddedOperations()) {
   if(op.getName().equals("getRequestOffset")) {
    List<AbstractCall> calls = modelDiff.findInvocationsInChildModel(op);
    System.out.println(calls.size());
   }
  }
 }
}
```

**Comment by pouryafard75** [comment]
@tsantalis I ran it multiple times and got 9 results consistently.

**Comment by maorethians** [comment]
I confirm that your code is always returning 9 for me too. I checked that I provide the same exact operation to `findInvocationsInChildModel`. So there may be a modeldiff manipulation by mistake which resulted in this behavior on my side. I'll try to track it down.
Thank you for your efforts and tests @tsantalis @pouryafard75.
I close this issue.
