### ISSUE TITLE
Some API usage examples are outdated  in README.md

### ISSUE THREAD

**Issue by Tbabm** [tsantalis/RefactoringMiner#85]
Hi!

I try to run RefactoringMiner using the example code: [With two directories containing Java source code](https://github.com/tsantalis/RefactoringMiner#with-two-directories-containing-java-source-code), but it seems that the constructor of `UMLModelASTReader` has been changed. The example code in README.md does not work now. 
Could you please update the usage example?

By the way, I am trying to identify `rename` and `type change` refactorings between two Java methods. I wonder whether there are any APIs that can be used to identify refactorings between two Java methods instead of two commits? 

Thank you~

**Comment by tsantalis** [comment]
I did some internal changes to avoid the need to pass a third argument to the constructor of `UMLModelASTReader`
You can now use the API as shown in the current documentation.

Regarding your request to compare directly two Java methods,
can you give me some insight about why your input is so restricted and you cannot provide commits?
I am trying to understand better your problem.

**Comment by Tbabm** [comment]
Thank you for your help!

In fact, I can provide commits to get the refactorings between two methods. But I have more than 50k Java method pairs to analyze, which have already been extracted from commits, and only a few method pairs in each commit should be analyzed. So it may save some time if I can directly compare Java methods instead of their corresponding commits.

If there is no direct API, I think I can do this by constructing a fake commit for each method pairs. : )

**Comment by tsantalis** [comment]
I have some concerns about providing the ability to compare directly two method declarations.
The first has to do with `Eclipse JDT ASTParser`, which is currently configured to accept `CompilationUnit` as input (i.e., Java file). I know it can be configure to parse statements, but haven't tried it with statement configuration.
The second has to do with missing context. What if you compare a pair of methods from which a code fragment was extracted to a third method. Providing only the pair of methods as input compromises the ability of RefactoringMiner to match all statements, including the extracted ones. Some of the type changes and renames you are looking for could be done within the body of the extracted method.
I think the minimum input you can provide for RefactoringMiner to work properly is a pair of CompilationUnits, and the ideal input is the entire commit.

**Comment by Tbabm** [comment]
Hi @tsantalis, 
I agree with your concerns and totally understand that RefactoringMiner does not provide such APIs. Currently, I work around by constructing fake commits and RefactoringMiner works well for me.

Thank you for your kind help!
