### ISSUE TITLE
Bug in "involved classes before refactoring" in Move and Inline refactorings

### ISSUE THREAD

**Issue by mauricioaniche** [tsantalis/RefactoringMiner#87]
When calling the `getInvolvedClassesBeforeRefactoring()` method in a `InlineOperationRefactoring` (i.e., a _Move and Inline Method_ refactoring), I am getting the class where the code was moved _to_, and not the class it was moved _from_.

See the following commit https://github.com/AsyncHttpClient/async-http-client/commit/1838b924c3c19b516f1e51040521d0038c4961a8:

The Refactoring object that I get has the following toString(): `Move And Inline Method	package setFuture(rf FutureImpl<V>) : void moved from class com.ning.http.client.providers.NettyAsyncResponse to class com.ning.http.client.providers.NettyResponseFuture & inlined to public NettyResponseFuture(url Url, request Request, asyncHandler AsyncHandler<V>, nettyRequest HttpRequest, responseTimeoutInMs int)`

The origin class is `com.ning.http.client.providers.NettyAsyncResponse`. However, `getInvolvedClassesBeforeRefactoring()` returns `com.ning.http.client.providers.NettyResponseFuture`.

Looking at the implementation of the `getInvolvedClassesBeforeRefactoring()`, I see that it uses `getTargetOperationBeforeInline()` to get the target before. However, the `toString()`, which prints things correctly, uses attribute `inlinedOperation`. 

Maybe the `getInvolvedClassesBeforeRefactoring` needs some extra logic to handle all the inline cases?

(This is happening in other similar cases too)

**Comment by tsantalis** [comment]
I will update the code as follows:
```java
pairs.add(new ImmutablePair<String, String>(getInlinedOperation().getLocationInfo().getFilePath(), getInlinedOperation().getClassName()));
pairs.add(new ImmutablePair<String, String>(getTargetOperationBeforeInline().getLocationInfo().getFilePath(), getTargetOperationBeforeInline().getClassName()));
```
If the refactoring is an `Inline Method`, `pairs` will contain one pair only.
If the refactoring is a `Move & Inline Method`, `pairs` will contain two pairs.
Can you please test it?

**Comment by mauricioaniche** [comment]
It works now!

Can we define a contract for these refactorings? Like, the first one will always be the 'origin' and the second one will always be the 'destination'? This is important to me as, right now, I care a lot about where the 'original method' was (and a bit less about where it goes, for now).

**Comment by tsantalis** [comment]
In general, I try to avoid such contracts that cannot be enforced somehow in the API.
I think it's easy to use the refactoring description for `Move & Inline Method` and `Extract & Move Method` to figure out the `origin` and `destination`, as the class names used in the refactoring description have the same value with `pair.getRight()`

**Comment by mauricioaniche** [comment]
Ok, I can do some string parsing from my side. Thanks for fixing it so fast!

**Comment by mauricioaniche** [comment]
There won't be a way to know which one is the origin and which one is the destination (see final comments in https://github.com/tsantalis/RefactoringMiner/issues/87). 

We should implement a way to do this, maybe by parsing the refactoring description.

TBH, right now, as we try both files, one of them will fail because the origin method doesn't exist in the destination method. So, we collect the data we want, but we have some noise in the logs, which is not nice. Fix it? Let it go? Suggestions?

**Comment by mauricioaniche** [comment]
(Sorry, last comment was in the wrong project)
