### ISSUE TITLE
Constants that are never used

### ISSUE THREAD

**Issue by mauricioaniche** [tsantalis/RefactoringMiner#88]
Just to double check: in `RefactoringType`, it seems that `MERGE_OPERATION` and `CHANGE_METHOD_SIGNATURE` are never really used.

Maybe it was before, and it's not anymore?

**Comment by tsantalis** [comment]
`CHANGE_METHOD_SIGNATURE` is deprecated. We currently have more fine-grained refactorings, such as
1. Change Return Type
2. Rename Method
3. Change Parameter Type
4. Rename Parameter
5. Merge Parameter
6. Split Parameter

The plan is to add support for Add/Remove Parameter in the future
Regarding MERGE_OPERATION or even SPLIT_OPERATION, we also plan to support them in the future.
