### ISSUE TITLE
Pull up Method

### ISSUE THREAD

**Issue by MatinMan** [tsantalis/RefactoringMiner#9]
Project Name: argoUML
Source: https://github.com/danilofes/argouml-refactorings.git
Commit hash: 8c2be520e01a83ee893158aa6cb90ee2d64f6a63
Branch: master
Test Case: https://github.com/MatinMan/Refactoring/blob/master/Reporting/argoUML/argouml_pum.md#tools-evaluation

-----

Project Name: aTunes
Source: https://github.com/danilofes/atunes-refactorings.git
Commit hash: 566cbfcc517e5d7e7372b893bb5ea779b7397ffd
Branch: master
Test Case: https://github.com/MatinMan/Refactoring/blob/master/Reporting/aTunes/aTunes_pum.md#tools-evaluation

----

- These methods are not in the removed operation list in the move operation detection process. They are either deleted in identifying the _"operation signature change"_ process or _"move from removed to added operation"_.

Test cases already exist in the TestRecal class

**Comment by tsantalis** [comment]
Both cases are properly detected in the current version of the tool.
