### ISSUE TITLE
API for retrieving the changes for a given refactoring

### ISSUE THREAD

**Issue by liuhuigmail** [tsantalis/RefactoringMiner#99]
Hi tsantalis,

Nice work on uncovering of refactorings!

I just wonder if there is any way by the tool to retrieve the changes (token level, like diff of two versions) caused by a given refactoring that is uncovered by the tool. Or even better, we an undo the refactoring via the tool instead  of refactoring tools. 

Thanks.

Hui Liu
liuhui08@bit.edu.cn

**Comment by tsantalis** [comment]
Hi @liuhuigmail 
Do you need something more than what is already provided by the Java API?
https://github.com/tsantalis/RefactoringMiner#statement-matching-information-for-the-detected-refactorings

There is no functionality to undo refactoring operations.

**Comment by liuhuigmail** [comment]
Thanks for the quick response.
If possible, we do want to retrieve all of the changes (token level, like diff of two versions) caused by a given refactoring that is uncovered by the tool.

**Comment by tsantalis** [comment]
RefactoringMiner provides a hierarchy of Diff objects, but for the moment this API is not publicly exposed.
You can write some small code to obtain this information.
https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L140
Extract local variable `modelDiff` from `refactoringsAtRevision = parentUMLModel.diff(currentUMLModel, renamedFilesHint).getRefactorings();` as shown below:

`UMLModelDiff modelDiff = parentUMLModel.diff(currentUMLModel, renamedFilesHint);`
From `modelDiff` you can access the following lists of `UMLClassBaseDiff` objects:
```java
private List<UMLClassDiff> commonClassDiffList;
private List<UMLClassMoveDiff> classMoveDiffList;
private List<UMLClassMoveDiff> innerClassMoveDiffList;
private List<UMLClassRenameDiff> classRenameDiffList;
```
`commonClassDiffList` includes the Diff objects for classes with the same file path (i..e, classes not moved/renamed)
`classMoveDiffList` includes the Diff objects for moved classes.
`innerclassMoveDiffList` includes the Diff objects for moved inner classes.
`classRenameDiffList` includes the Diff objects for renamed classes.

From each `UMLClassBaseDiff` object, you can obtain `List<UMLOperationBodyMapper> operationBodyMapperList`.
Each `UMLOperationBodyMapper` represents a pair of matched methods.
From this point you can continue with your code as shown in the README
https://github.com/tsantalis/RefactoringMiner#statement-matching-information-for-the-detected-refactorings
In this way, you can get a complete diff for all modified/added/deleted files in a commit.

**Comment by liuhuigmail** [comment]
Appologize for late reply.
We are still figuring out what we can retrieve from the tool. 
Thank you for the help.
